package publicapi

import (
	"context"
	"net/http/httptest"
	"regexp"
	"testing"
	"time"

	"github.com/DATA-DOG/go-sqlmock"
	"github.com/google/uuid"

	dbmodels "github.com/publira/publira/server/internal/db"
	"github.com/publira/publira/server/internal/storage"
)

const (
	getTenantByIDQuery                            = "-- name: GetTenantByID :one\nSELECT id, public_id, domain, name, default_reading_period_hours, created_at, status, admin_domain, timezone\nFROM tenants\nWHERE id = $1\nLIMIT 1\n"
	listActiveSeriesIDsByPublishedAtDescQuery     = "-- name: ListActiveSeriesIDsByPublishedAtDesc :many\nSELECT s.id\nFROM series s\nWHERE s.tenant_id = $1\n    AND s.is_published = true\n    AND s.published_at IS NOT NULL\n    AND s.published_at <= NOW()\n    AND (\n        $2::uuid IS NULL\n        OR (\n            $3::boolean\n            AND (s.published_at, s.id) <= (\n                $4::timestamptz,\n                $2::uuid\n            )\n        )\n        OR (\n            NOT $3::boolean\n            AND (s.published_at, s.id) < (\n                $4::timestamptz,\n                $2::uuid\n            )\n        )\n    )\nORDER BY s.published_at DESC,\n    s.id DESC\nLIMIT $5\n"
	listActiveSeriesIDsByPublishedAtAscQuery      = "-- name: ListActiveSeriesIDsByPublishedAtAsc :many\nSELECT s.id\nFROM series s\nWHERE s.tenant_id = $1\n    AND s.is_published = true\n    AND s.published_at IS NOT NULL\n    AND s.published_at <= NOW()\n    AND (\n        $2::uuid IS NULL\n        OR (\n            $3::boolean\n            AND (s.published_at, s.id) >= (\n                $4::timestamptz,\n                $2::uuid\n            )\n        )\n        OR (\n            NOT $3::boolean\n            AND (s.published_at, s.id) > (\n                $4::timestamptz,\n                $2::uuid\n            )\n        )\n    )\nORDER BY s.published_at ASC,\n    s.id ASC\nLIMIT $5\n"
	listActiveSeriesIDsByTitleAscQuery            = "-- name: ListActiveSeriesIDsByTitleAsc :many\nSELECT s.id\nFROM series s\nWHERE s.tenant_id = $1\n    AND s.is_published = true\n    AND s.published_at IS NOT NULL\n    AND s.published_at <= NOW()\n    AND (\n        $2::uuid IS NULL\n        OR (\n            $3::boolean\n            AND (s.title, s.id) >= (\n                $4::text,\n                $2::uuid\n            )\n        )\n        OR (\n            NOT $3::boolean\n            AND (s.title, s.id) > (\n                $4::text,\n                $2::uuid\n            )\n        )\n    )\nORDER BY s.title ASC,\n    s.id ASC\nLIMIT $5\n"
	listActiveSeriesIDsByTitleDescQuery           = "-- name: ListActiveSeriesIDsByTitleDesc :many\nSELECT s.id\nFROM series s\nWHERE s.tenant_id = $1\n    AND s.is_published = true\n    AND s.published_at IS NOT NULL\n    AND s.published_at <= NOW()\n    AND (\n        $2::uuid IS NULL\n        OR (\n            $3::boolean\n            AND (s.title, s.id) <= (\n                $4::text,\n                $2::uuid\n            )\n        )\n        OR (\n            NOT $3::boolean\n            AND (s.title, s.id) < (\n                $4::text,\n                $2::uuid\n            )\n        )\n    )\nORDER BY s.title DESC,\n    s.id DESC\nLIMIT $5\n"
	listActiveSeriesByIDsQuery                    = "-- name: ListActiveSeriesByIDs :many\nSELECT s.id,\n    s.public_id,\n    s.title,\n    sl.synopsis,\n    s.published_at,\n    s.eye_catch_image_id,\n    NULL::timestamp AS eye_catch_image_updated_at,\n    COALESCE(\n        json_agg(\n            json_build_object(\n                'public_id',\n                c.public_id,\n                'name',\n                c.name,\n                'role',\n                sc.role,\n                'profile_text',\n                c.profile_text,\n                'icon_image_url',\n                CASE\n                    WHEN c.icon_image_id IS NOT NULL THEN '/images/creators/' || c.icon_image_id::text\n                    ELSE ''\n                END,\n                'icon_image_file_size_bytes',\n                0,\n                'icon_image_updated_at',\n                COALESCE(ci.updated_at::TEXT, '')\n            )\n            ORDER BY sc.display_order ASC\n        ) FILTER (\n            WHERE c.id IS NOT NULL\n        ),\n        '[]'\n    )::jsonb AS creators,\n    CASE\n        WHEN l.public_id IS NOT NULL THEN json_build_object(\n            'public_id',\n            l.public_id,\n            'name',\n            l.name\n        )\n        ELSE '{}'::json\n    END::jsonb AS label_info\nFROM series s\n    LEFT JOIN series_listings sl ON sl.series_id = s.id\n    LEFT JOIN labels l ON s.label_id = l.id\n    LEFT JOIN series_creators sc ON s.id = sc.series_id\n    LEFT JOIN creators c ON sc.creator_id = c.id\n    LEFT JOIN creator_images ci ON ci.id = c.icon_image_id\nWHERE s.tenant_id = $1\n    AND s.id = ANY($2::uuid [])\n    AND s.is_published = true\n    AND s.published_at IS NOT NULL\n    AND s.published_at <= NOW()\nGROUP BY s.id,\n    sl.series_id,\n    sl.synopsis,\n    l.public_id,\n    l.name\n"
	getSeriesDetailQuery                          = "-- name: GetSeriesDetail :one\nSELECT s.id,\n    s.public_id,\n    s.title,\n    l.public_id AS label_public_id,\n    l.name AS label_name,\n    s.eye_catch_image_id,\n    NULL::timestamp AS eye_catch_image_updated_at,\n    sl.synopsis,\n    s.is_published,\n    s.published_at,\n    -- 複数の著者情報をJSON配列として1カラムにまとめる\n    COALESCE(\n        json_agg(\n            json_build_object(\n                    'public_id',\n                    c.public_id,\n                'name',\n                c.name,\n                    'role',\n                    sc.role,\n                    'profile_text',\n                    c.profile_text,\n                    'icon_image_url',\n                    CASE\n                        WHEN c.icon_image_id IS NOT NULL THEN '/images/creators/' || c.icon_image_id::text\n                        ELSE ''\n                    END,\n                    'icon_image_file_size_bytes',\n                    0,\n                    'icon_image_updated_at',\n                    COALESCE(ci.updated_at::TEXT, '')\n            )\n            ORDER BY sc.display_order ASC\n        ) FILTER (\n            WHERE c.id IS NOT NULL\n        ),\n        '[]'\n    )::jsonb AS creators,\n    COALESCE(\n        (\n            SELECT json_agg(\n                    json_build_object(\n                        'public_id',\n                        e.public_id,\n                        'title',\n                        e.title,\n                        'order_index',\n                        e.order_index,\n                        'price',\n                        el.price,\n                        'reading_period_hours',\n                        el.reading_period_hours,\n                        'status',\n                        el.status,\n                        'scheduled_at',\n                        el.scheduled_at,\n                        'published_at',\n                        el.published_at\n                    )\n                    ORDER BY e.order_index ASC\n                )\n            FROM episodes e\n                JOIN episode_listings el ON el.episode_id = e.id\n            WHERE e.series_id = s.id\n                AND el.status = 'published'\n                AND el.published_at IS NOT NULL\n                AND el.published_at <= NOW()\n        ),\n        '[]'\n    )::jsonb AS episodes\nFROM series s\n    LEFT JOIN series_listings sl ON sl.series_id = s.id\n    LEFT JOIN labels l ON s.label_id = l.id\n    LEFT JOIN series_creators sc ON s.id = sc.series_id\n    LEFT JOIN creators c ON sc.creator_id = c.id\n    LEFT JOIN creator_images ci ON ci.id = c.icon_image_id\nWHERE s.public_id = $1\n    AND s.tenant_id = $2\nGROUP BY s.id,\n    l.id,\n    sl.series_id,\n    sl.synopsis\n"
	listSeriesImageVariantsByImageIDsQuery        = "-- name: ListSeriesImageVariantsByImageIDs :many\nSELECT series_image_id,\n    variant_type,\n    label,\n    content_type,\n    file_size_bytes,\n    width,\n    height\nFROM series_image_variants\nWHERE series_image_id = ANY($1::uuid[])\nORDER BY series_image_id,\n    variant_type,\n    width\n"
	getPublishedEpisodeByPublicIDQuery            = "-- name: GetPublishedEpisodeByPublicIDForTenant :one\nSELECT e.id,\n    e.public_id,\n    e.title,\n    e.order_index,\n    el.price,\n    el.reading_period_hours,\n    el.status,\n    el.scheduled_at,\n    el.published_at,\n    s.public_id AS series_public_id,\n    s.title AS series_title\nFROM episodes e\n    JOIN series s ON s.id = e.series_id\n    JOIN episode_listings el ON el.episode_id = e.id\nWHERE s.tenant_id = $1\n    AND e.public_id = $2\n    AND s.is_published = true\n    AND s.published_at IS NOT NULL\n    AND s.published_at <= NOW()\n    AND el.status = 'published'\n    AND el.published_at IS NOT NULL\n    AND el.published_at <= NOW()\nLIMIT 1\n"
	listPublishedPagesForTenantQuery              = "-- name: ListPublishedPagesForTenant :many\nSELECT p.id, p.tenant_id, p.slug, p.title, p.published_version_id, p.display_in_footer, p.created_at, p.updated_at\nFROM pages p\n\tJOIN page_versions pv ON pv.id = p.published_version_id\nWHERE p.tenant_id = $1\n\tAND p.display_in_footer = true\n\tAND pv.status = 'published'\n\tAND pv.published_at IS NOT NULL\n\tAND pv.published_at <= NOW()\nORDER BY p.created_at ASC\n"
	getPublishedPageBySlugQuery                   = "-- name: GetPublishedPageBySlugForTenant :one\nSELECT p.id,\n\tp.tenant_id,\n\tp.slug,\n\tp.title,\n\tp.published_version_id,\n\tp.display_in_footer,\n\tp.created_at,\n\tp.updated_at,\n\tpv.id AS version_id,\n\tpv.page_id,\n\tpv.version_number,\n\tpv.content_markdown,\n\tpv.author_user_id,\n\tpv.status,\n\tpv.publish_at,\n\tpv.created_at AS version_created_at,\n\tpv.published_at\nFROM pages p\n\tJOIN page_versions pv ON pv.id = p.published_version_id\nWHERE p.tenant_id = $1\n\tAND p.slug = $2\n\tAND pv.status = 'published'\n\tAND pv.published_at IS NOT NULL\n\tAND pv.published_at <= NOW()\nLIMIT 1\n"
	listEpisodeImagesByEpisodeIDQuery             = "-- name: ListEpisodeImagesByEpisodeID :many\nSELECT\n    ei.id,\n    ei.tenant_id,\n    ei.episode_id,\n    ei.display_order,\n    ei.created_at,\n    eiv.content_type,\n    eiv.file_size_bytes,\n    eiv.width,\n    eiv.height\nFROM episode_images ei\nJOIN LATERAL (\n    SELECT content_type, file_size_bytes, width, height\n    FROM episode_image_variants\n    WHERE episode_image_id = ei.id\n    ORDER BY width DESC\n    LIMIT 1\n) eiv ON true\nWHERE ei.episode_id = $1\nORDER BY ei.display_order ASC,\n    ei.created_at ASC\n"
	userHasEpisodeContentAccessQuery              = "-- name: UserHasEpisodeContentAccess :one\nSELECT (\n        EXISTS (\n            SELECT 1\n            FROM purchases p\n            WHERE p.tenant_id = $1\n                AND p.user_id = $2\n                AND p.episode_id = $3\n                AND (\n                    p.expires_at IS NULL\n                    OR p.expires_at > NOW()\n                )\n        )\n        OR EXISTS (\n            SELECT 1\n            FROM access_tickets at\n            WHERE at.tenant_id = $1\n                AND at.user_id = $2\n                AND at.episode_id = $3\n                AND at.revoked_at IS NULL\n                AND (\n                    at.expires_at IS NULL\n                    OR at.expires_at > NOW()\n                )\n        )\n    ) AS has_access\n"
	listPublishedAuthorIDsByNameAscQuery          = "-- name: ListPublishedAuthorIDsByNameAsc :many\nSELECT c.id\nFROM creators c\nWHERE c.tenant_id = $1\n    AND EXISTS (\n        SELECT 1\n        FROM series_creators sc\n            JOIN series s ON s.id = sc.series_id\n        WHERE sc.creator_id = c.id\n            AND s.tenant_id = c.tenant_id\n            AND s.is_published = true\n            AND s.published_at IS NOT NULL\n            AND s.published_at <= NOW()\n    )\n    AND (\n        $2::uuid IS NULL\n        OR (\n            $3::boolean\n            AND (c.name, c.id) >= (\n                $4::text,\n                $2::uuid\n            )\n        )\n        OR (\n            NOT $3::boolean\n            AND (c.name, c.id) > (\n                $4::text,\n                $2::uuid\n            )\n        )\n    )\nORDER BY c.name ASC,\n    c.id ASC\nLIMIT $5\n"
	listPublishedAuthorIDsByNameDescQuery         = "-- name: ListPublishedAuthorIDsByNameDesc :many\nSELECT c.id\nFROM creators c\nWHERE c.tenant_id = $1\n    AND EXISTS (\n        SELECT 1\n        FROM series_creators sc\n            JOIN series s ON s.id = sc.series_id\n        WHERE sc.creator_id = c.id\n            AND s.tenant_id = c.tenant_id\n            AND s.is_published = true\n            AND s.published_at IS NOT NULL\n            AND s.published_at <= NOW()\n    )\n    AND (\n        $2::uuid IS NULL\n        OR (\n            $3::boolean\n            AND (c.name, c.id) <= (\n                $4::text,\n                $2::uuid\n            )\n        )\n        OR (\n            NOT $3::boolean\n            AND (c.name, c.id) < (\n                $4::text,\n                $2::uuid\n            )\n        )\n    )\nORDER BY c.name DESC,\n    c.id DESC\nLIMIT $5\n"
	listPublishedAuthorsByIDsQuery                = "-- name: ListPublishedAuthorsByIDs :many\nSELECT c.id,\n    c.public_id,\n    c.name,\n    c.profile_text,\n    c.icon_image_id,\n    ci.updated_at AS icon_image_updated_at,\n    COALESCE(civ.file_size_bytes, 0)::bigint AS icon_image_file_size_bytes,\n    (\n        SELECT COUNT(*)::int4\n        FROM series_creators sc\n            JOIN series s ON s.id = sc.series_id\n        WHERE sc.creator_id = c.id\n            AND s.tenant_id = c.tenant_id\n            AND s.is_published = true\n            AND s.published_at IS NOT NULL\n            AND s.published_at <= NOW()\n    ) AS published_series_count\nFROM creators c\n    LEFT JOIN creator_images ci ON ci.id = c.icon_image_id\n    LEFT JOIN LATERAL (\n        SELECT file_size_bytes\n        FROM creator_image_variants\n        WHERE creator_image_id = ci.id\n        ORDER BY width DESC\n        LIMIT 1\n    ) civ ON true\nWHERE c.tenant_id = $1\n    AND c.id = ANY($2::uuid [])\n"
	getPublishedAuthorByPublicIDQuery             = "-- name: GetPublishedAuthorByPublicID :one\nSELECT c.id,\n    c.public_id,\n    c.name,\n    c.profile_text,\n    c.icon_image_id,\n    ci.updated_at AS icon_image_updated_at,\n    COALESCE(civ.file_size_bytes, 0)::bigint AS icon_image_file_size_bytes,\n    (\n        SELECT COUNT(*)::int4\n        FROM series_creators sc\n            JOIN series s ON s.id = sc.series_id\n        WHERE sc.creator_id = c.id\n            AND s.tenant_id = c.tenant_id\n            AND s.is_published = true\n            AND s.published_at IS NOT NULL\n            AND s.published_at <= NOW()\n    ) AS published_series_count\nFROM creators c\n    LEFT JOIN creator_images ci ON ci.id = c.icon_image_id\n    LEFT JOIN LATERAL (\n        SELECT file_size_bytes\n        FROM creator_image_variants\n        WHERE creator_image_id = ci.id\n        ORDER BY width DESC\n        LIMIT 1\n    ) civ ON true\nWHERE c.tenant_id = $1\n    AND c.public_id = $2\n    AND EXISTS (\n        SELECT 1\n        FROM series_creators sc\n            JOIN series s ON s.id = sc.series_id\n        WHERE sc.creator_id = c.id\n            AND s.tenant_id = c.tenant_id\n            AND s.is_published = true\n            AND s.published_at IS NOT NULL\n            AND s.published_at <= NOW()\n    )\nLIMIT 1\n"
	listPublishedSeriesIDsByCreatorTitleAscQuery  = "-- name: ListPublishedSeriesIDsByCreatorTitleAsc :many\nSELECT s.id\nFROM series s\n    JOIN series_creators sc ON sc.series_id = s.id\nWHERE sc.creator_id = $1\n    AND s.tenant_id = $2\n    AND s.is_published = true\n    AND s.published_at IS NOT NULL\n    AND s.published_at <= NOW()\n    AND (\n        $3::uuid IS NULL\n        OR (\n            $4::boolean\n            AND (s.title, s.id) >= (\n                $5::text,\n                $3::uuid\n            )\n        )\n        OR (\n            NOT $4::boolean\n            AND (s.title, s.id) > (\n                $5::text,\n                $3::uuid\n            )\n        )\n    )\nORDER BY s.title ASC,\n    s.id ASC\nLIMIT $6\n"
	listPublishedSeriesIDsByCreatorTitleDescQuery = "-- name: ListPublishedSeriesIDsByCreatorTitleDesc :many\nSELECT s.id\nFROM series s\n    JOIN series_creators sc ON sc.series_id = s.id\nWHERE sc.creator_id = $1\n    AND s.tenant_id = $2\n    AND s.is_published = true\n    AND s.published_at IS NOT NULL\n    AND s.published_at <= NOW()\n    AND (\n        $3::uuid IS NULL\n        OR (\n            $4::boolean\n            AND (s.title, s.id) <= (\n                $5::text,\n                $3::uuid\n            )\n        )\n        OR (\n            NOT $4::boolean\n            AND (s.title, s.id) < (\n                $5::text,\n                $3::uuid\n            )\n        )\n    )\nORDER BY s.title DESC,\n    s.id DESC\nLIMIT $6\n"
)

func newTestPublicServer(t *testing.T) (*httptest.Server, sqlmock.Sqlmock) {
	t.Helper()
	db, mock, err := sqlmock.New()
	if err != nil {
		t.Fatalf("sqlmock.New: %v", err)
	}
	t.Cleanup(func() {
		_ = db.Close()
	})
	server := httptest.NewServer(NewHandler(db, dbmodels.New(db), &testStorageProvider{}, nil, nil))
	t.Cleanup(server.Close)
	return server, mock
}

type testStorageProvider struct{}

func (p *testStorageProvider) Upload(_ context.Context, req storage.UploadRequest) (storage.UploadResult, error) {
	return storage.UploadResult{
		Provider:  "local",
		ObjectKey: req.ObjectKey,
		URL:       "local://" + req.ObjectKey,
		SizeBytes: int64(len(req.Data)),
	}, nil
}

func expectTenantLookup(mock sqlmock.Sqlmock, tenantID uuid.UUID, publicID string, now time.Time) {
	expectTenantLookupWithTimezone(mock, tenantID, publicID, now, "Asia/Tokyo")
}

func expectTenantLookupWithTimezone(mock sqlmock.Sqlmock, tenantID uuid.UUID, publicID string, now time.Time, timezone string) {
	mock.ExpectQuery(regexp.QuoteMeta(getTenantByIDQuery)).
		WithArgs(tenantID).
		WillReturnRows(sqlmock.NewRows([]string{"id", "public_id", "domain", "name", "default_reading_period_hours", "created_at", "status", "admin_domain", "timezone"}).
			AddRow(tenantID, publicID, "tenant.example", "Tenant", nil, now, "active", nil, timezone))
}

func assertPublicExpectations(t *testing.T, mock sqlmock.Sqlmock) {
	t.Helper()
	if err := mock.ExpectationsWereMet(); err != nil {
		t.Fatalf("unmet SQL expectations: %v", err)
	}
}
