-- The (tenant_id, id) key that the composite foreign key from
-- episode_image_variants names. PostgreSQL accepts a reference only against a
-- unique key on exactly those columns, and this table's primary key is id
-- alone.
--
-- Alone in its file, and concurrent, because episode_images holds one row per
-- page of every episode and the upload path writes to it. A plain CREATE INDEX
-- would block those writes for the length of the build.
--
-- It stays a bare index rather than being promoted to a UNIQUE constraint the
-- way the smaller parents in this sweep carry one: a reference is satisfied by
-- either, but a constraint owns its index, so dropping the constraint on the
-- way back down would take the index with it and leave the rollback rebuilding
-- it — blocking, on the table this migration exists to avoid blocking.
CREATE UNIQUE INDEX CONCURRENTLY episode_images_tenant_id_id_key ON episode_images USING btree (tenant_id, id);
