ALTER TABLE tenant_themes
DROP COLUMN info_foreground_color,
DROP COLUMN info_color,
DROP COLUMN destructive_foreground_color,
DROP COLUMN destructive_color,
DROP COLUMN warning_foreground_color,
DROP COLUMN warning_color,
DROP COLUMN success_foreground_color,
DROP COLUMN success_color,
DROP COLUMN ring_color,
DROP COLUMN input_color,
DROP COLUMN border_color,
DROP COLUMN muted_foreground_color,
DROP COLUMN muted_color,
DROP COLUMN accent_foreground_color,
DROP COLUMN secondary_foreground_color,
DROP COLUMN primary_foreground_color,
DROP COLUMN popover_foreground_color,
DROP COLUMN popover_color,
DROP COLUMN card_foreground_color,
DROP COLUMN card_color,
DROP COLUMN surface_foreground_color,
DROP COLUMN surface_color,
DROP COLUMN foreground_color,
DROP COLUMN background_color;

ALTER TABLE tenant_themes
ALTER COLUMN primary_color DROP DEFAULT,
ALTER COLUMN secondary_color DROP DEFAULT,
ALTER COLUMN accent_color DROP DEFAULT;
