UPDATE tenant_themes
SET background_color = '#f6f2e9',
    foreground_color = '#1e2b38',
    surface_color = '#fbf8f2',
    surface_foreground_color = '#1e2b38',
    card_color = '#fffdf8',
    card_foreground_color = '#1e2b38',
    popover_color = '#fffdf8',
    popover_foreground_color = '#1e2b38',
    primary_color = '#0f7c82',
    primary_foreground_color = '#f4fbfb',
    secondary_color = '#b35235',
    secondary_foreground_color = '#fff6f1',
    accent_color = '#7aae90',
    accent_foreground_color = '#0f2a1f',
    muted_color = '#e9e1d3',
    muted_foreground_color = '#56616e',
    border_color = '#d7ccba',
    input_color = '#e3d8c7',
    ring_color = '#2d8d93',
    success_color = '#247542',
    success_foreground_color = '#f3fcf7',
    warning_color = '#9b6217',
    warning_foreground_color = '#fff8ea',
    destructive_color = '#b54444',
    destructive_foreground_color = '#fff4f4',
    info_color = '#2b5e9f',
    info_foreground_color = '#f3f8ff'
WHERE (
        background_color,
        foreground_color,
        surface_color,
        surface_foreground_color,
        card_color,
        card_foreground_color,
        popover_color,
        popover_foreground_color,
        primary_color,
        primary_foreground_color,
        secondary_color,
        secondary_foreground_color,
        accent_color,
        accent_foreground_color,
        muted_color,
        muted_foreground_color,
        border_color,
        input_color,
        ring_color,
        success_color,
        success_foreground_color,
        warning_color,
        warning_foreground_color,
        destructive_color,
        destructive_foreground_color,
        info_color,
        info_foreground_color
    ) = (
        '#f5f5f2',
        '#1f1d1a',
        '#fafaf8',
        '#1f1d1a',
        '#ffffff',
        '#1f1d1a',
        '#ffffff',
        '#1f1d1a',
        '#2b4c8c',
        '#ffffff',
        '#c63d17',
        '#ffffff',
        '#e3e9f5',
        '#22407a',
        '#e8e8e3',
        '#5f5e59',
        '#d6d6d0',
        '#cfcfc8',
        '#2b4c8c',
        '#2a6b3f',
        '#ffffff',
        '#8a5a0b',
        '#ffffff',
        '#8f1d1d',
        '#ffffff',
        '#2f5d8a',
        '#ffffff'
    );

ALTER TABLE ONLY tenant_themes
    ALTER COLUMN background_color SET DEFAULT '#f6f2e9'::character varying,
    ALTER COLUMN foreground_color SET DEFAULT '#1e2b38'::character varying,
    ALTER COLUMN surface_color SET DEFAULT '#fbf8f2'::character varying,
    ALTER COLUMN surface_foreground_color SET DEFAULT '#1e2b38'::character varying,
    ALTER COLUMN card_color SET DEFAULT '#fffdf8'::character varying,
    ALTER COLUMN card_foreground_color SET DEFAULT '#1e2b38'::character varying,
    ALTER COLUMN popover_color SET DEFAULT '#fffdf8'::character varying,
    ALTER COLUMN popover_foreground_color SET DEFAULT '#1e2b38'::character varying,
    ALTER COLUMN primary_color SET DEFAULT '#0f7c82'::character varying,
    ALTER COLUMN primary_foreground_color SET DEFAULT '#f4fbfb'::character varying,
    ALTER COLUMN secondary_color SET DEFAULT '#b35235'::character varying,
    ALTER COLUMN secondary_foreground_color SET DEFAULT '#fff6f1'::character varying,
    ALTER COLUMN accent_color SET DEFAULT '#7aae90'::character varying,
    ALTER COLUMN accent_foreground_color SET DEFAULT '#0f2a1f'::character varying,
    ALTER COLUMN muted_color SET DEFAULT '#e9e1d3'::character varying,
    ALTER COLUMN muted_foreground_color SET DEFAULT '#56616e'::character varying,
    ALTER COLUMN border_color SET DEFAULT '#d7ccba'::character varying,
    ALTER COLUMN input_color SET DEFAULT '#e3d8c7'::character varying,
    ALTER COLUMN ring_color SET DEFAULT '#2d8d93'::character varying,
    ALTER COLUMN success_color SET DEFAULT '#247542'::character varying,
    ALTER COLUMN success_foreground_color SET DEFAULT '#f3fcf7'::character varying,
    ALTER COLUMN warning_color SET DEFAULT '#9b6217'::character varying,
    ALTER COLUMN warning_foreground_color SET DEFAULT '#fff8ea'::character varying,
    ALTER COLUMN destructive_color SET DEFAULT '#b54444'::character varying,
    ALTER COLUMN destructive_foreground_color SET DEFAULT '#fff4f4'::character varying,
    ALTER COLUMN info_color SET DEFAULT '#2b5e9f'::character varying,
    ALTER COLUMN info_foreground_color SET DEFAULT '#f3f8ff'::character varying;
