-- Move the tenant theme defaults from the cream-and-terracotta palette to
-- paper, sumi, ai, and shu.
--
-- The color columns are NOT NULL with a column default, and a theme row is
-- created without colors whenever a tenant uploads an icon or a logo before it
-- has saved one. Such a row stores the palette that was default at the time,
-- so changing the defaults alone would leave those tenants on the old cream
-- while a tenant with no row at all moves to the new palette.
--
-- The UPDATE therefore repaints the rows that still carry every one of the old
-- defaults. Comparing all 27 columns at once is what separates "never chose a
-- theme" from "chose these colors": a tenant that edited even one token keeps
-- its whole palette untouched.
ALTER TABLE ONLY tenant_themes
    ALTER COLUMN background_color SET DEFAULT '#f5f5f2'::character varying,
    ALTER COLUMN foreground_color SET DEFAULT '#1f1d1a'::character varying,
    ALTER COLUMN surface_color SET DEFAULT '#fafaf8'::character varying,
    ALTER COLUMN surface_foreground_color SET DEFAULT '#1f1d1a'::character varying,
    ALTER COLUMN card_color SET DEFAULT '#ffffff'::character varying,
    ALTER COLUMN card_foreground_color SET DEFAULT '#1f1d1a'::character varying,
    ALTER COLUMN popover_color SET DEFAULT '#ffffff'::character varying,
    ALTER COLUMN popover_foreground_color SET DEFAULT '#1f1d1a'::character varying,
    ALTER COLUMN primary_color SET DEFAULT '#2b4c8c'::character varying,
    ALTER COLUMN primary_foreground_color SET DEFAULT '#ffffff'::character varying,
    ALTER COLUMN secondary_color SET DEFAULT '#c63d17'::character varying,
    ALTER COLUMN secondary_foreground_color SET DEFAULT '#ffffff'::character varying,
    ALTER COLUMN accent_color SET DEFAULT '#e3e9f5'::character varying,
    ALTER COLUMN accent_foreground_color SET DEFAULT '#22407a'::character varying,
    ALTER COLUMN muted_color SET DEFAULT '#e8e8e3'::character varying,
    ALTER COLUMN muted_foreground_color SET DEFAULT '#5f5e59'::character varying,
    ALTER COLUMN border_color SET DEFAULT '#d6d6d0'::character varying,
    ALTER COLUMN input_color SET DEFAULT '#cfcfc8'::character varying,
    ALTER COLUMN ring_color SET DEFAULT '#2b4c8c'::character varying,
    ALTER COLUMN success_color SET DEFAULT '#2a6b3f'::character varying,
    ALTER COLUMN success_foreground_color SET DEFAULT '#ffffff'::character varying,
    ALTER COLUMN warning_color SET DEFAULT '#8a5a0b'::character varying,
    ALTER COLUMN warning_foreground_color SET DEFAULT '#ffffff'::character varying,
    ALTER COLUMN destructive_color SET DEFAULT '#8f1d1d'::character varying,
    ALTER COLUMN destructive_foreground_color SET DEFAULT '#ffffff'::character varying,
    ALTER COLUMN info_color SET DEFAULT '#2f5d8a'::character varying,
    ALTER COLUMN info_foreground_color SET DEFAULT '#ffffff'::character varying;

UPDATE tenant_themes
SET background_color = '#f5f5f2',
    foreground_color = '#1f1d1a',
    surface_color = '#fafaf8',
    surface_foreground_color = '#1f1d1a',
    card_color = '#ffffff',
    card_foreground_color = '#1f1d1a',
    popover_color = '#ffffff',
    popover_foreground_color = '#1f1d1a',
    primary_color = '#2b4c8c',
    primary_foreground_color = '#ffffff',
    secondary_color = '#c63d17',
    secondary_foreground_color = '#ffffff',
    accent_color = '#e3e9f5',
    accent_foreground_color = '#22407a',
    muted_color = '#e8e8e3',
    muted_foreground_color = '#5f5e59',
    border_color = '#d6d6d0',
    input_color = '#cfcfc8',
    ring_color = '#2b4c8c',
    success_color = '#2a6b3f',
    success_foreground_color = '#ffffff',
    warning_color = '#8a5a0b',
    warning_foreground_color = '#ffffff',
    destructive_color = '#8f1d1d',
    destructive_foreground_color = '#ffffff',
    info_color = '#2f5d8a',
    info_foreground_color = '#ffffff'
WHERE (
        background_color,
        foreground_color,
        surface_color,
        surface_foreground_color,
        card_color,
        card_foreground_color,
        popover_color,
        popover_foreground_color,
        primary_color,
        primary_foreground_color,
        secondary_color,
        secondary_foreground_color,
        accent_color,
        accent_foreground_color,
        muted_color,
        muted_foreground_color,
        border_color,
        input_color,
        ring_color,
        success_color,
        success_foreground_color,
        warning_color,
        warning_foreground_color,
        destructive_color,
        destructive_foreground_color,
        info_color,
        info_foreground_color
    ) = (
        '#f6f2e9',
        '#1e2b38',
        '#fbf8f2',
        '#1e2b38',
        '#fffdf8',
        '#1e2b38',
        '#fffdf8',
        '#1e2b38',
        '#0f7c82',
        '#f4fbfb',
        '#b35235',
        '#fff6f1',
        '#7aae90',
        '#0f2a1f',
        '#e9e1d3',
        '#56616e',
        '#d7ccba',
        '#e3d8c7',
        '#2d8d93',
        '#247542',
        '#f3fcf7',
        '#9b6217',
        '#fff8ea',
        '#b54444',
        '#fff4f4',
        '#2b5e9f',
        '#f3f8ff'
    );
