ALTER TABLE tenant_themes
ADD COLUMN background_color VARCHAR(32) NOT NULL DEFAULT '#f6f2e9',
ADD COLUMN foreground_color VARCHAR(32) NOT NULL DEFAULT '#1e2b38',
ADD COLUMN surface_color VARCHAR(32) NOT NULL DEFAULT '#fbf8f2',
ADD COLUMN surface_foreground_color VARCHAR(32) NOT NULL DEFAULT '#1e2b38',
ADD COLUMN card_color VARCHAR(32) NOT NULL DEFAULT '#fffdf8',
ADD COLUMN card_foreground_color VARCHAR(32) NOT NULL DEFAULT '#1e2b38',
ADD COLUMN popover_color VARCHAR(32) NOT NULL DEFAULT '#fffdf8',
ADD COLUMN popover_foreground_color VARCHAR(32) NOT NULL DEFAULT '#1e2b38',
ADD COLUMN primary_foreground_color VARCHAR(32) NOT NULL DEFAULT '#f4fbfb',
ADD COLUMN secondary_foreground_color VARCHAR(32) NOT NULL DEFAULT '#fff6f1',
ADD COLUMN accent_foreground_color VARCHAR(32) NOT NULL DEFAULT '#0f2a1f',
ADD COLUMN muted_color VARCHAR(32) NOT NULL DEFAULT '#e9e1d3',
ADD COLUMN muted_foreground_color VARCHAR(32) NOT NULL DEFAULT '#5c6773',
ADD COLUMN border_color VARCHAR(32) NOT NULL DEFAULT '#d7ccba',
ADD COLUMN input_color VARCHAR(32) NOT NULL DEFAULT '#e3d8c7',
ADD COLUMN ring_color VARCHAR(32) NOT NULL DEFAULT '#2d8d93',
ADD COLUMN success_color VARCHAR(32) NOT NULL DEFAULT '#2f8f5b',
ADD COLUMN success_foreground_color VARCHAR(32) NOT NULL DEFAULT '#f3fcf7',
ADD COLUMN warning_color VARCHAR(32) NOT NULL DEFAULT '#c4872a',
ADD COLUMN warning_foreground_color VARCHAR(32) NOT NULL DEFAULT '#fff8ea',
ADD COLUMN destructive_color VARCHAR(32) NOT NULL DEFAULT '#b54444',
ADD COLUMN destructive_foreground_color VARCHAR(32) NOT NULL DEFAULT '#fff4f4',
ADD COLUMN info_color VARCHAR(32) NOT NULL DEFAULT '#3c78c2',
ADD COLUMN info_foreground_color VARCHAR(32) NOT NULL DEFAULT '#f3f8ff';

ALTER TABLE tenant_themes
ALTER COLUMN primary_color SET DEFAULT '#0f7c82',
ALTER COLUMN secondary_color SET DEFAULT '#d96f4a',
ALTER COLUMN accent_color SET DEFAULT '#7aae90';
