import { afterEach, describe, expect, it } from "vitest";

import { profileCookieName } from "./cookie-name";

const originalSuffix = process.env.PUBLIRA_COOKIE_SUFFIX;

afterEach(() => {
  if (originalSuffix === undefined) {
    delete process.env.PUBLIRA_COOKIE_SUFFIX;
    return;
  }
  process.env.PUBLIRA_COOKIE_SUFFIX = originalSuffix;
});

describe("profileCookieName", () => {
  it("keeps established names outside a development profile", () => {
    delete process.env.PUBLIRA_COOKIE_SUFFIX;

    expect(profileCookieName("publira_web_host_auth")).toBe(
      "publira_web_host_auth"
    );
  });

  it("namespaces a profile's Cookie", () => {
    process.env.PUBLIRA_COOKIE_SUFFIX = "-issue-1178";

    expect(profileCookieName("publira_web_host_auth")).toBe(
      "publira_web_host_auth-issue-1178"
    );
  });

  it("rejects a suffix that cannot be generated by a profile", () => {
    process.env.PUBLIRA_COOKIE_SUFFIX = "-UPPER";

    expect(() => profileCookieName("publira_web_host_auth")).toThrow(
      /PUBLIRA_COOKIE_SUFFIX/u
    );
  });
});
