syntax = "proto3";

package publira.platform.v1;

option go_package = "github.com/publira/publira/server/gen/publira/platform/v1;publirasplatformv1";

import "publira/types/v1/types.proto";

message PlatformAuthServiceCreateSessionRequest {
  string email = 1;
  string password = 2;
}

message PlatformAuthServiceCreateSessionResponse {
  publira.types.v1.User user = 1;
  publira.types.v1.Session session = 2;
}

message PlatformAuthServiceDeleteSessionRequest {}

message PlatformAuthServiceDeleteSessionResponse {}

message PlatformAuthServiceGetMeRequest {}

message PlatformAuthServiceGetMeResponse {
  publira.types.v1.User user = 1;
}

service PlatformAuthService {
  rpc CreateSession(PlatformAuthServiceCreateSessionRequest) returns (PlatformAuthServiceCreateSessionResponse) {}
  rpc DeleteSession(PlatformAuthServiceDeleteSessionRequest) returns (PlatformAuthServiceDeleteSessionResponse) {}
  rpc GetMe(PlatformAuthServiceGetMeRequest) returns (PlatformAuthServiceGetMeResponse) {}
}
