import assert from "node:assert/strict";
import { describe, it } from "node:test";

import {
  dartIdentifier,
  dartParameter,
  dartStringLiteral,
  renderDartMessages,
} from "./dart-messages.ts";

const locales = [
  { code: "ja", intl: "ja-JP" },
  { code: "en", intl: "en-US" },
];

const catalogs = (
  ja: Record<string, unknown>,
  en: Record<string, unknown>
): Map<string, unknown> =>
  new Map<string, unknown>([
    ["ja", { errors: { validation: "確認してください。" }, mobile: ja }],
    ["en", { errors: { validation: "Check your input." }, mobile: en }],
  ]);

describe("dartIdentifier", () => {
  it("drops the app's own namespace and camel-cases the rest", () => {
    assert.equal(
      dartIdentifier("mobile.series.episode_count"),
      "seriesEpisodeCount"
    );
    assert.equal(dartIdentifier("mobile.common.retry"), "commonRetry");
  });

  it("keeps a shared namespace in the identifier", () => {
    assert.equal(dartIdentifier("errors.rpc.not-found"), "errorsRpcNotFound");
  });

  it("refuses a key that would shadow the class's own members or a reserved word", () => {
    assert.throws(() => dartIdentifier("mobile.of"), /cannot declare/u);
    assert.throws(() => dartIdentifier("mobile.class"), /cannot declare/u);
    assert.throws(
      () => dartIdentifier("mobile.intl_locale"),
      /cannot declare/u
    );
  });

  it("refuses a key that is not made of identifier characters", () => {
    assert.throws(() => dartIdentifier("mobile.sign in"), /cannot become/u);
    assert.throws(() => dartIdentifier("mobile.2fa"), /cannot become/u);
  });
});

describe("dartParameter", () => {
  it("camel-cases a placeholder name", () => {
    assert.equal(dartParameter("count"), "count");
    assert.equal(dartParameter("series_title"), "seriesTitle");
  });

  it("refuses a placeholder that cannot be a parameter", () => {
    assert.throws(() => dartParameter("default"), /cannot become/u);
  });
});

const parameterOf = (variable: string) => dartParameter(variable);

/**
 * A namespace built from entries, so the object keeps an order the generator
 * must not depend on.
 */
const unsorted = () =>
  Object.fromEntries([
    [
      "b",
      Object.fromEntries([
        ["z", "1"],
        ["a", "2"],
      ]),
    ],
    ["a", { y: "3" }],
  ]);

describe("dartStringLiteral", () => {
  it("interpolates a placeholder without braces where the text allows it", () => {
    assert.equal(
      dartStringLiteral(
        ["Page ", { variable: "page" }, " of ", { variable: "total" }],
        parameterOf
      ),
      "'Page $page of $total'"
    );
    assert.equal(
      dartStringLiteral([{ variable: "count" }, " 話"], parameterOf),
      "'$count 話'"
    );
  });

  it("braces a placeholder the following text would otherwise extend", () => {
    // Assembled in pieces so the Dart interpolation is not read as a
    // TypeScript template placeholder.
    assert.equal(
      dartStringLiteral([{ variable: "count" }, "px"], parameterOf),
      ["'$", "{count}px'"].join("")
    );
    assert.equal(
      dartStringLiteral([{ variable: "n" }, "_th"], parameterOf),
      ["'$", "{n}_th'"].join("")
    );
  });

  it("escapes what a single-quoted Dart literal needs escaped", () => {
    assert.equal(
      dartStringLiteral(["it's $5 and C:\\Users\nnext"], parameterOf),
      "'it\\'s \\$5 and C:\\\\Users\\nnext'"
    );
  });
});

describe("renderDartMessages", () => {
  const ja = {
    series: { episode_count: "{$count} 話", title: "シリーズ" },
    viewer: { page_status: "{$page} / {$total}" },
  };
  const en = {
    series: { episode_count: "{$count} episodes", title: "Series" },
    viewer: { page_status: "{$page} / {$total}" },
  };

  it("declares one member per key and one subclass per locale", () => {
    const output = renderDartMessages(locales, catalogs(ja, en));

    assert.match(
      output,
      /^\/\/ Code generated by scripts\/generate-locale-registry\.ts; DO NOT EDIT\.\n/u
    );
    assert.ok(output.includes("abstract class AppMessages {"));
    assert.ok(
      output.includes(
        "  static const supportedLocales = <Locale>[Locale('ja'), Locale('en')];"
      )
    );
    assert.ok(
      output.includes(
        "      'ja' => const _AppMessagesJa(),\n      'en' => const _AppMessagesEn(),\n      _ => null,"
      )
    );
    assert.ok(
      output.includes(
        "  /// `errors.validation`\n  String get errorsValidation;"
      )
    );
    assert.ok(
      output.includes(
        "  /// `mobile.series.episode_count`\n  String seriesEpisodeCount({required String count});"
      )
    );
    assert.ok(
      output.includes(
        "  String viewerPageStatus({required String page, required String total});"
      )
    );
    assert.ok(
      output.includes(
        "class _AppMessagesJa extends AppMessages {\n  const _AppMessagesJa();\n\n  @override\n  String get intlLocale {\n    return 'ja-JP';\n  }"
      )
    );
    assert.ok(
      output.includes(
        "  @override\n  String seriesEpisodeCount({required String count}) {\n    return '$count 話';\n  }"
      )
    );
    assert.ok(
      output.includes(
        "  @override\n  String seriesEpisodeCount({required String count}) {\n    return '$count episodes';\n  }"
      )
    );
    assert.ok(output.includes("    return '$page / $total';"));
  });

  it("derives the script a language, and each region, is written in", () => {
    const chinese = [
      { code: "en", intl: "en-US" },
      { code: "zh-Hans", intl: "zh-Hans-CN" },
      { code: "zh-Hant", intl: "zh-Hant-TW" },
    ];
    const catalog = {
      errors: { validation: "Check your input." },
      mobile: { series: { title: "Series" } },
    };
    const output = renderDartMessages(
      chinese,
      new Map(chinese.map(({ code }) => [code, catalog]))
    );

    assert.ok(
      output.includes("  static const likelyScripts = <String, String>{\n")
    );
    assert.ok(output.includes("    'en': 'Latn',\n"));
    assert.ok(output.includes("    'zh': 'Hans',\n"));
    assert.ok(output.includes("    'zh-TW': 'Hant',\n"));
    assert.ok(output.includes("    'zh-HK': 'Hant',\n"));
    // A region written in the language's own script is left out, and a
    // language two catalogs share is still named once.
    assert.ok(!output.includes("'zh-CN'"));
    assert.equal(output.match(/'zh': /gu)?.length, 1);
  });

  it("orders members by key, whatever order the catalog lists them in", () => {
    const output = renderDartMessages(
      locales,
      catalogs(unsorted(), unsorted())
    );
    const members = [...output.matchAll(/String get (?<member>\w+);/gu)].map(
      (match) => match.groups?.member
    );

    assert.deepEqual(members, [
      "intlLocale",
      "errorsValidation",
      "aY",
      "bA",
      "bZ",
    ]);
  });

  it("splits a parameter list the formatter would not fit on one line", () => {
    const output = renderDartMessages(
      locales,
      catalogs(
        {
          a: { long_message: "{$first_value} {$second_value} {$third_value}" },
        },
        { a: { long_message: "{$first_value} {$second_value} {$third_value}" } }
      )
    );

    assert.ok(
      output.includes(
        "  String aLongMessage({\n    required String firstValue,\n    required String secondValue,\n    required String thirdValue,\n  });"
      )
    );
    assert.ok(
      output.includes(
        "  String aLongMessage({\n    required String firstValue,\n    required String secondValue,\n    required String thirdValue,\n  }) {\n    return '$firstValue $secondValue $thirdValue';\n  }"
      )
    );
  });

  it("gives a method the union of the placeholders its locales use", () => {
    const output = renderDartMessages(
      locales,
      catalogs({ a: { m: "{$name} さん" } }, { a: { m: "Hello" } })
    );

    assert.ok(output.includes("  String aM({required String name});"));
    assert.ok(
      output.includes(
        "  String aM({required String name}) {\n    return 'Hello';\n  }"
      )
    );
  });

  it("fails when the locales do not hold the same keys", () => {
    assert.throws(
      () =>
        renderDartMessages(
          locales,
          catalogs({ a: { x: "1" } }, { a: { y: "1" } })
        ),
      /does not match/u
    );
  });

  it("fails when two keys compile into the same member", () => {
    assert.throws(
      () =>
        renderDartMessages(
          locales,
          catalogs(
            { a: { "b-c": "2", b_c: "1" } },
            { a: { "b-c": "2", b_c: "1" } }
          )
        ),
      /both compile into aBC/u
    );
  });

  it("fails on a message outside the catalog's subset", () => {
    assert.throws(
      () =>
        renderDartMessages(
          locales,
          catalogs({ a: { n: "{$n :number}" } }, { a: { n: "{$n :number}" } })
        ),
      /functions/u
    );
  });

  it("fails when a namespace the app compiles is missing", () => {
    assert.throws(
      () =>
        renderDartMessages(
          locales,
          new Map<string, unknown>([
            ["ja", { errors: {} }],
            ["en", { errors: {} }],
          ])
        ),
      /has no mobile namespace/u
    );
  });
});
