import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const indexPath = path.resolve(root, "locales/index.json");
const newline = "\n";
const check = process.argv.at(2) === "--check";

const fail = (message: string): never => {
  throw new Error(`Invalid locales/index.json: ${message}`);
};

const index: unknown = JSON.parse(readFileSync(indexPath, "utf-8"));
if (
  typeof index !== "object" ||
  index === null ||
  !("locales" in index) ||
  !Array.isArray(index.locales) ||
  index.locales.length === 0
) {
  fail("locales must be a non-empty array");
}

const localeCode = /^[a-z]{2,3}(?:-[A-Za-z0-9]{2,8})*$/u;
const locales = index.locales.map(
  (locale): { code: string; intl: string; label: string } => {
    if (
      typeof locale !== "object" ||
      locale === null ||
      !("code" in locale) ||
      !("intl" in locale) ||
      !("label" in locale) ||
      typeof locale.code !== "string" ||
      !localeCode.test(locale.code) ||
      typeof locale.intl !== "string" ||
      !locale.intl ||
      typeof locale.label !== "string" ||
      !locale.label
    ) {
      return fail("each locale needs a valid code, intl value, and label");
    }

    return locale;
  }
);

const codes = new Set<string>();
for (const locale of locales) {
  if (codes.has(locale.code)) {
    fail(`locale code ${JSON.stringify(locale.code)} is duplicated`);
  }
  codes.add(locale.code);
  if (!existsSync(path.resolve(root, `locales/${locale.code}.json`))) {
    fail(`catalog locales/${locale.code}.json does not exist`);
  }
}

const source = "ja";
if (!codes.has(source)) {
  fail("locales must include ja as the catalog key source");
}

const catalogCodes = new Set(
  readdirSync(path.resolve(root, "locales"), { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith(".json"))
    .map((entry) => entry.name.slice(0, -".json".length))
    .filter((code) => code !== "index")
);
for (const code of codes) {
  catalogCodes.delete(code);
}
if (catalogCodes.size > 0) {
  fail(`catalogs missing from locales: ${[...catalogCodes].join(", ")}`);
}

const quote = (value: string) => JSON.stringify(value);
const imports = locales
  .map(
    ({ code }) =>
      `import ${code} from "../../../../locales/${code}.json" with { type: "json" };`
  )
  .join(newline);
const dynamicImports = locales
  .map(
    ({ code }) =>
      `  ${code}: () => import("../../../../locales/${code}.json", { with: { type: "json" } }),`
  )
  .join(newline);
const codesLiteral = locales.map(({ code }) => quote(code)).join(", ");
const localeDetails = locales
  .map(
    ({ code, intl, label }) =>
      `  ${code}: { intl: ${quote(intl)}, label: ${quote(label)} },`
  )
  .join(newline);
const catalogEntries = locales
  .map(({ code }) =>
    code === source ? `  ${code},` : `  ${code}: ${code}MatchesSource,`
  )
  .join(newline);
const exactCatalogs = locales
  .filter(({ code }) => code !== source)
  .map(
    ({ code }) =>
      `const ${code}MatchesSource: ExactCatalog<typeof ${code}, LocaleMessages> = ${code};`
  )
  .join(newline);
const goCodes = locales.map(({ code }) => quote(code)).join(", ");
const generatedHeader =
  "// Code generated by scripts/generate-locale-registry.ts; DO NOT EDIT.";

const files = new Map([
  [
    "packages/i18n/src/gen/locale-registry.ts",
    `${generatedHeader}${newline}${newline}const localeCodes = [${codesLiteral}] as const;${newline}${newline}export type Locale = (typeof localeCodes)[number];${newline}${newline}export const getLocales = (): readonly [Locale, ...Locale[]] =>${newline}  [...localeCodes] as [Locale, ...Locale[]];${newline}${newline}const localeDetails = {${newline}${localeDetails}${newline}} as const satisfies Record<Locale, { intl: string; label: string }>;${newline}${newline}export const getIntlLocale = (locale: Locale): string =>${newline}  localeDetails[locale].intl;${newline}${newline}export const getLocaleLabel = (locale: Locale): string =>${newline}  localeDetails[locale].label;${newline}`,
  ],
  [
    "packages/i18n/src/gen/locale-catalogs.ts",
    `${generatedHeader}${newline}${newline}${imports}${newline}${newline}import type { ExactCatalog } from "../i18n";${newline}import type { Locale } from "./locale-registry";${newline}${newline}export type LocaleMessages = typeof ${source};${newline}${newline}${exactCatalogs}${newline}${newline}export const CATALOGS = {${newline}${catalogEntries}${newline}} as const satisfies Record<Locale, LocaleMessages>;${newline}`,
  ],
  [
    "packages/i18n/src/gen/locale-messages.ts",
    `${generatedHeader}${newline}${newline}import { loadMessages } from "../i18n";${newline}import type {${newline}  Locale,${newline}  LocaleCatalogImporters,${newline}  MessageTree,${newline}} from "../i18n";${newline}import type { LocaleMessages } from "./locale-catalogs";${newline}${newline}const importers = {${newline}${dynamicImports}${newline}} satisfies LocaleCatalogImporters<LocaleMessages>;${newline}${newline}export const loadLocaleMessages = (${newline}  locale: Locale | string${newline}): Promise<MessageTree> =>${newline}  loadMessages(locale, importers);${newline}`,
  ],
  [
    "server/internal/locale/gen/locales.go",
    `${generatedHeader}${newline}${newline}package gen${newline}${newline}var Supported = []string{${goCodes}}${newline}`,
  ],
]);

for (const [outputPath, content] of files) {
  const absolutePath = path.resolve(root, outputPath);
  if (check) {
    if (
      !existsSync(absolutePath) ||
      readFileSync(absolutePath, "utf-8") !== content
    ) {
      fail(`${outputPath} is out of date; run pnpm locales:generate`);
    }
    continue;
  }

  mkdirSync(path.dirname(absolutePath), { recursive: true });
  writeFileSync(absolutePath, content);
}
