import assert from "node:assert/strict";
import { describe, it } from "node:test";

import { renderGoMessages } from "./go-messages.ts";
import { goString } from "./go-source.ts";

const locales = [
  { code: "ja", intl: "ja-JP" },
  { code: "en", intl: "en-US" },
];

const catalogs = (
  japanese: Record<string, unknown>,
  english: Record<string, unknown>
): Map<string, unknown> =>
  new Map<string, unknown>([
    ["ja", { email: japanese }],
    ["en", { email: english }],
  ]);

describe("goString", () => {
  it("escapes what a Go literal cannot carry as it stands", () => {
    assert.equal(goString('say "no"'), '"say \\"no\\""');
    assert.equal(goString("C:\\Users"), '"C:\\\\Users"');
    assert.equal(goString("one\ntwo"), '"one\\ntwo"');
  });

  it("escapes a space a reader could not tell from an ordinary one", () => {
    // U+202F, which Intl writes before an English AM/PM.
    assert.equal(goString("9:00\u202FPM"), '"9:00\\u202fPM"');
    assert.equal(goString("9:00 PM"), '"9:00 PM"');
  });

  it("leaves the copy of a language that is written in it alone", () => {
    assert.equal(goString("パスワードの再設定"), '"パスワードの再設定"');
  });
});

describe("renderGoMessages", () => {
  it("compiles a message into its text and the variables it reads", () => {
    const output = renderGoMessages(
      locales,
      catalogs(
        { layout: { footer: "{$brand} から送信されています。" } },
        { layout: { footer: "Sent by {$brand}." } }
      )
    );

    assert.match(output, /^\/\/ Code generated by /u);
    assert.match(
      output,
      /"email\.layout\.footer": \{\n\t\t\t\{Text: "Sent by "\},\n\t\t\t\{Variable: "brand"\},\n\t\t\t\{Text: "\."\},\n\t\t\},/u
    );
  });

  it("refuses catalogs that do not carry the same keys", () => {
    assert.throws(
      () =>
        renderGoMessages(
          locales,
          catalogs(
            { layout: { footer: "送信されています。" } },
            { layout: { brand: "Publira", footer: "Sent." } }
          )
        ),
      /does not match/u
    );
  });
});
