import assert from "node:assert/strict";
import { describe, it } from "node:test";

import { renderGoMessages } from "./go-messages.ts";
import { goLocaleEntries, goString } from "./go-source.ts";

const locales = [
  { code: "ja", intl: "ja-JP" },
  { code: "en", intl: "en-US" },
];

const catalogs = (
  japanese: Record<string, unknown>,
  english: Record<string, unknown>
): Map<string, unknown> =>
  new Map<string, unknown>([
    ["ja", { email: japanese }],
    ["en", { email: english }],
  ]);

describe("goString", () => {
  it("escapes what a Go literal cannot carry as it stands", () => {
    assert.equal(goString('say "no"'), '"say \\"no\\""');
    assert.equal(goString("C:\\Users"), '"C:\\\\Users"');
    assert.equal(goString("one\ntwo"), '"one\\ntwo"');
  });

  it("escapes a space a reader could not tell from an ordinary one", () => {
    // U+202F, which Intl writes before an English AM/PM.
    assert.equal(goString("9:00\u202FPM"), '"9:00\\u202fPM"');
    assert.equal(goString("9:00 PM"), '"9:00 PM"');
  });

  it("leaves the copy of a language that is written in it alone", () => {
    assert.equal(goString("パスワードの再設定"), '"パスワードの再設定"');
  });
});

describe("goLocaleEntries", () => {
  it("pads the keys into the column gofmt aligns them to", () => {
    assert.deepEqual(
      goLocaleEntries(
        [
          ["ja", '"ja-JP"'],
          ["zh-Hans", '"zh-Hans-CN"'],
        ],
        "\t"
      ),
      ['\t"ja":      "ja-JP",', '\t"zh-Hans": "zh-Hans-CN",']
    );
  });
});

describe("renderGoMessages", () => {
  it("carries each locale's MessageFormat 2 source as it stands", () => {
    const output = renderGoMessages(
      locales,
      catalogs(
        { layout: { footer: "From {$brand}." } },
        { layout: { footer: "Sent by {$brand}. \\{ \\}" } }
      )
    );

    assert.match(output, /^\/\/ Code generated by /u);
    assert.ok(
      output.includes(
        [
          '\t"email.layout.footer": {',
          '\t\t"ja": "From {$brand}.",',
          '\t\t"en": "Sent by {$brand}. \\\\{ \\\\}",',
          "\t},",
        ].join("\n")
      )
    );
  });

  it("refuses catalogs that do not carry the same keys", () => {
    assert.throws(
      () =>
        renderGoMessages(
          locales,
          catalogs(
            { layout: { footer: "Sent." } },
            { layout: { brand: "Publira", footer: "Sent." } }
          )
        ),
      /does not match/u
    );
  });
});
