/** Writing Go source the generators of `locales/` share. */

export interface GoLocale {
  readonly code: string;
  readonly intl: string;
}

export const GENERATED_HEADER =
  "// Code generated by scripts/generate-locale-registry.ts; DO NOT EDIT.";

/**
 * A character a reader of the generated file could not see, or could not tell
 * from an ordinary space: every format character, and every space separator
 * other than U+0020. `Intl` puts U+202F before an English AM/PM, so one of
 * these does reach the output.
 */
const INVISIBLE = /[\p{Cf}\p{Zs}]/u;

/** `value` as an interpreted Go string literal. */
export const goString = (value: string): string => {
  let literal = '"';
  for (const character of value) {
    const code = character.codePointAt(0) ?? 0;
    if (character === '"' || character === "\\") {
      literal += `\\${character}`;
    } else if (character === "\n") {
      literal += "\\n";
    } else if (character === "\r") {
      literal += "\\r";
    } else if (character === "\t") {
      literal += "\\t";
    } else if (code < 0x20 || code === 0x7f) {
      literal += `\\x${code.toString(16).padStart(2, "0")}`;
    } else if (character !== " " && INVISIBLE.test(character)) {
      literal += `\\u${code.toString(16).padStart(4, "0")}`;
    } else {
      literal += character;
    }
  }

  return `${literal}"`;
};

/**
 * The elements of a Go map literal keyed by locale code, one per line, with
 * each value already written as Go source. `gofmt` pads the keys of such a
 * block into a column, and stops doing so only past a key length no locale
 * code comes near, so the column is as wide as the longest code.
 */
export const goLocaleEntries = (
  entries: readonly (readonly [code: string, value: string])[],
  indent: string
): string[] => {
  const keyed = entries.map(([code, value]) => ({
    key: `${goString(code)}:`,
    value,
  }));
  const width = Math.max(...keyed.map(({ key }) => key.length));

  return keyed.map(
    ({ key, value }) => `${indent}${key.padEnd(width)} ${value},`
  );
};
