// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package dbmodels

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const insertAdminAuditLog = `-- name: InsertAdminAuditLog :exec
INSERT INTO admin_audit_logs (
    id,
    actor_user_public_id,
    actor_role,
    tenant_public_id,
    action,
    target_type,
    target_id,
    outcome,
    reason,
    client_ip
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertAdminAuditLogParams struct {
	ID                uuid.UUID      `json:"id"`
	ActorUserPublicID string         `json:"actor_user_public_id"`
	ActorRole         string         `json:"actor_role"`
	TenantPublicID    sql.NullString `json:"tenant_public_id"`
	Action            string         `json:"action"`
	TargetType        sql.NullString `json:"target_type"`
	TargetID          sql.NullString `json:"target_id"`
	Outcome           string         `json:"outcome"`
	Reason            sql.NullString `json:"reason"`
	ClientIp          sql.NullString `json:"client_ip"`
}

// 管理操作監査ログを記録する
func (q *Queries) InsertAdminAuditLog(ctx context.Context, arg InsertAdminAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAdminAuditLog,
		arg.ID,
		arg.ActorUserPublicID,
		arg.ActorRole,
		arg.TenantPublicID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Outcome,
		arg.Reason,
		arg.ClientIp,
	)
	return err
}

const listAdminAuditLogs = `-- name: ListAdminAuditLogs :many
SELECT id, actor_user_public_id, actor_role, tenant_public_id, action, target_type, target_id, outcome, reason, client_ip, created_at
FROM admin_audit_logs
WHERE ($1::text IS NULL OR actor_user_public_id = $1::text)
  AND ($2::text IS NULL OR tenant_public_id = $2::text)
  AND ($3::text IS NULL OR action = $3::text)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListAdminAuditLogsParams struct {
	FilterActorUserPublicID sql.NullString `json:"filter_actor_user_public_id"`
	FilterTenantPublicID    sql.NullString `json:"filter_tenant_public_id"`
	FilterAction            sql.NullString `json:"filter_action"`
	Offset                  int32          `json:"offset"`
	Limit                   int32          `json:"limit"`
}

// 管理操作監査ログ一覧取得（フィルタ対応）
func (q *Queries) ListAdminAuditLogs(ctx context.Context, arg ListAdminAuditLogsParams) ([]AdminAuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAdminAuditLogs,
		arg.FilterActorUserPublicID,
		arg.FilterTenantPublicID,
		arg.FilterAction,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminAuditLog
	for rows.Next() {
		var i AdminAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserPublicID,
			&i.ActorRole,
			&i.TenantPublicID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Outcome,
			&i.Reason,
			&i.ClientIp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
