// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comment.sql

package dbmodels

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const approveEpisodeCommentByPublicIDForTenant = `-- name: ApproveEpisodeCommentByPublicIDForTenant :one
UPDATE episode_comments
SET status = 'published',
    published_at = NOW(),
    approved_by = $1::uuid,
    updated_at = NOW()
WHERE tenant_id = $2
    AND public_id = $3
    AND status = 'pending'
RETURNING id, tenant_id, public_id, episode_id, user_id, body, status, approved_by, hidden_by, hidden_reason, created_at, updated_at, published_at, hidden_at, withdrawn_at
`

type ApproveEpisodeCommentByPublicIDForTenantParams struct {
	ApprovedBy uuid.UUID `json:"approved_by"`
	TenantID   uuid.UUID `json:"tenant_id"`
	PublicID   string    `json:"public_id"`
}

// Approval is what publishes a comment posted under approval_required, so it is
// also where published_at is first written.
func (q *Queries) ApproveEpisodeCommentByPublicIDForTenant(ctx context.Context, arg ApproveEpisodeCommentByPublicIDForTenantParams) (EpisodeComment, error) {
	row := q.db.QueryRowContext(ctx, approveEpisodeCommentByPublicIDForTenant, arg.ApprovedBy, arg.TenantID, arg.PublicID)
	var i EpisodeComment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PublicID,
		&i.EpisodeID,
		&i.UserID,
		&i.Body,
		&i.Status,
		&i.ApprovedBy,
		&i.HiddenBy,
		&i.HiddenReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.HiddenAt,
		&i.WithdrawnAt,
	)
	return i, err
}

const createEpisodeComment = `-- name: CreateEpisodeComment :one

INSERT INTO episode_comments (
    id,
    tenant_id,
    public_id,
    episode_id,
    user_id,
    body,
    status,
    published_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, tenant_id, public_id, episode_id, user_id, body, status, approved_by, hidden_by, hidden_reason, created_at, updated_at, published_at, hidden_at, withdrawn_at
`

type CreateEpisodeCommentParams struct {
	ID          uuid.UUID    `json:"id"`
	TenantID    uuid.UUID    `json:"tenant_id"`
	PublicID    string       `json:"public_id"`
	EpisodeID   uuid.UUID    `json:"episode_id"`
	UserID      uuid.UUID    `json:"user_id"`
	Body        string       `json:"body"`
	Status      string       `json:"status"`
	PublishedAt sql.NullTime `json:"published_at"`
}

// Reader comments on published episodes.
//
// Every state transition is an UPDATE on the single episode_comments row, so
// the WHERE clause of each one names the status it is allowed to move from and
// the query returns no row when the comment was already moved by someone else.
// The caller tells "not found" from "already handled" by that.
//
// Expected plans:
//
//	ListPublishedEpisodeCommentsByCreatedAt*
//	  -> idx_episode_comments_tenant_episode_status_created_at
//	ListUserEpisodeCommentsByCreatedAt*
//	  -> idx_episode_comments_tenant_user_created_at
//	ListEpisodeCommentsByStatusCreatedAt*
//	  -> idx_episode_comments_tenant_status_created_at
//	PurgeWithdrawnEpisodeComments
//	  -> idx_episode_comments_tenant_withdrawn_at
//
// status and published_at come from the tenant's comment_mode: 'published' with
// a timestamp under immediate, 'pending' with NULL under approval_required.
func (q *Queries) CreateEpisodeComment(ctx context.Context, arg CreateEpisodeCommentParams) (EpisodeComment, error) {
	row := q.db.QueryRowContext(ctx, createEpisodeComment,
		arg.ID,
		arg.TenantID,
		arg.PublicID,
		arg.EpisodeID,
		arg.UserID,
		arg.Body,
		arg.Status,
		arg.PublishedAt,
	)
	var i EpisodeComment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PublicID,
		&i.EpisodeID,
		&i.UserID,
		&i.Body,
		&i.Status,
		&i.ApprovedBy,
		&i.HiddenBy,
		&i.HiddenReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.HiddenAt,
		&i.WithdrawnAt,
	)
	return i, err
}

const hideEpisodeCommentByPublicIDForTenant = `-- name: HideEpisodeCommentByPublicIDForTenant :one
UPDATE episode_comments
SET status = 'hidden',
    hidden_at = NOW(),
    hidden_by = $1,
    hidden_reason = $2::text,
    updated_at = NOW()
WHERE tenant_id = $3
    AND public_id = $4
    AND status IN ('pending', 'published')
RETURNING id, tenant_id, public_id, episode_id, user_id, body, status, approved_by, hidden_by, hidden_reason, created_at, updated_at, published_at, hidden_at, withdrawn_at
`

type HideEpisodeCommentByPublicIDForTenantParams struct {
	HiddenBy     uuid.NullUUID `json:"hidden_by"`
	HiddenReason string        `json:"hidden_reason"`
	TenantID     uuid.UUID     `json:"tenant_id"`
	PublicID     string        `json:"public_id"`
}

// hidden_by is NULL when hidden_reason is 'auto_reports': the report threshold
// has no staff actor to name.
func (q *Queries) HideEpisodeCommentByPublicIDForTenant(ctx context.Context, arg HideEpisodeCommentByPublicIDForTenantParams) (EpisodeComment, error) {
	row := q.db.QueryRowContext(ctx, hideEpisodeCommentByPublicIDForTenant,
		arg.HiddenBy,
		arg.HiddenReason,
		arg.TenantID,
		arg.PublicID,
	)
	var i EpisodeComment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PublicID,
		&i.EpisodeID,
		&i.UserID,
		&i.Body,
		&i.Status,
		&i.ApprovedBy,
		&i.HiddenBy,
		&i.HiddenReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.HiddenAt,
		&i.WithdrawnAt,
	)
	return i, err
}

const listEpisodeCommentsByStatusCreatedAtAsc = `-- name: ListEpisodeCommentsByStatusCreatedAtAsc :many
SELECT id, tenant_id, public_id, episode_id, user_id, body, status, approved_by, hidden_by, hidden_reason, created_at, updated_at, published_at, hidden_at, withdrawn_at
FROM episode_comments
WHERE tenant_id = $1
    AND status = $2
    AND (
        $3::timestamptz IS NULL
        OR (
            $4::boolean
            AND (created_at, id) >= (
                $3::timestamptz,
                $5::uuid
            )
        )
        OR (
            NOT $4::boolean
            AND (created_at, id) > (
                $3::timestamptz,
                $5::uuid
            )
        )
    )
ORDER BY created_at ASC,
    id ASC
LIMIT $6
`

type ListEpisodeCommentsByStatusCreatedAtAscParams struct {
	TenantID        uuid.UUID     `json:"tenant_id"`
	Status          string        `json:"status"`
	CursorCreatedAt sql.NullTime  `json:"cursor_created_at"`
	CursorInclusive bool          `json:"cursor_inclusive"`
	CursorID        uuid.NullUUID `json:"cursor_id"`
	Limit           int32         `json:"limit"`
}

// The previous-page half of ListEpisodeCommentsByStatusCreatedAtDesc.
func (q *Queries) ListEpisodeCommentsByStatusCreatedAtAsc(ctx context.Context, arg ListEpisodeCommentsByStatusCreatedAtAscParams) ([]EpisodeComment, error) {
	rows, err := q.db.QueryContext(ctx, listEpisodeCommentsByStatusCreatedAtAsc,
		arg.TenantID,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorInclusive,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EpisodeComment
	for rows.Next() {
		var i EpisodeComment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PublicID,
			&i.EpisodeID,
			&i.UserID,
			&i.Body,
			&i.Status,
			&i.ApprovedBy,
			&i.HiddenBy,
			&i.HiddenReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.HiddenAt,
			&i.WithdrawnAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodeCommentsByStatusCreatedAtDesc = `-- name: ListEpisodeCommentsByStatusCreatedAtDesc :many
SELECT id, tenant_id, public_id, episode_id, user_id, body, status, approved_by, hidden_by, hidden_reason, created_at, updated_at, published_at, hidden_at, withdrawn_at
FROM episode_comments
WHERE tenant_id = $1
    AND status = $2
    AND (
        $3::timestamptz IS NULL
        OR (
            $4::boolean
            AND (created_at, id) <= (
                $3::timestamptz,
                $5::uuid
            )
        )
        OR (
            NOT $4::boolean
            AND (created_at, id) < (
                $3::timestamptz,
                $5::uuid
            )
        )
    )
ORDER BY created_at DESC,
    id DESC
LIMIT $6
`

type ListEpisodeCommentsByStatusCreatedAtDescParams struct {
	TenantID        uuid.UUID     `json:"tenant_id"`
	Status          string        `json:"status"`
	CursorCreatedAt sql.NullTime  `json:"cursor_created_at"`
	CursorInclusive bool          `json:"cursor_inclusive"`
	CursorID        uuid.NullUUID `json:"cursor_id"`
	Limit           int32         `json:"limit"`
}

// The console queues: 'pending' is the approval queue, 'hidden' the removed
// comments staff can restore, 'withdrawn' what an author deleted and the
// retention window still keeps. One tenant-wide list per status, so a moderator
// does not have to open an episode to find work.
func (q *Queries) ListEpisodeCommentsByStatusCreatedAtDesc(ctx context.Context, arg ListEpisodeCommentsByStatusCreatedAtDescParams) ([]EpisodeComment, error) {
	rows, err := q.db.QueryContext(ctx, listEpisodeCommentsByStatusCreatedAtDesc,
		arg.TenantID,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorInclusive,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EpisodeComment
	for rows.Next() {
		var i EpisodeComment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PublicID,
			&i.EpisodeID,
			&i.UserID,
			&i.Body,
			&i.Status,
			&i.ApprovedBy,
			&i.HiddenBy,
			&i.HiddenReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.HiddenAt,
			&i.WithdrawnAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedEpisodeCommentsByCreatedAtAsc = `-- name: ListPublishedEpisodeCommentsByCreatedAtAsc :many
SELECT c.id,
    c.public_id,
    c.body,
    c.created_at,
    c.user_id,
    u.public_id AS author_public_id,
    u.name AS author_name
FROM episode_comments c
    JOIN users u ON u.tenant_id = c.tenant_id
        AND u.id = c.user_id
WHERE c.tenant_id = $1
    AND c.episode_id = $2
    AND c.status = 'published'
    AND (
        $3::timestamptz IS NULL
        OR (
            $4::boolean
            AND (c.created_at, c.id) >= (
                $3::timestamptz,
                $5::uuid
            )
        )
        OR (
            NOT $4::boolean
            AND (c.created_at, c.id) > (
                $3::timestamptz,
                $5::uuid
            )
        )
    )
ORDER BY c.created_at ASC,
    c.id ASC
LIMIT $6
`

type ListPublishedEpisodeCommentsByCreatedAtAscParams struct {
	TenantID        uuid.UUID     `json:"tenant_id"`
	EpisodeID       uuid.UUID     `json:"episode_id"`
	CursorCreatedAt sql.NullTime  `json:"cursor_created_at"`
	CursorInclusive bool          `json:"cursor_inclusive"`
	CursorID        uuid.NullUUID `json:"cursor_id"`
	Limit           int32         `json:"limit"`
}

type ListPublishedEpisodeCommentsByCreatedAtAscRow struct {
	ID             uuid.UUID `json:"id"`
	PublicID       string    `json:"public_id"`
	Body           string    `json:"body"`
	CreatedAt      time.Time `json:"created_at"`
	UserID         uuid.UUID `json:"user_id"`
	AuthorPublicID string    `json:"author_public_id"`
	AuthorName     string    `json:"author_name"`
}

// The previous-page half of ListPublishedEpisodeCommentsByCreatedAtDesc. The
// handler reverses the returned rows to preserve the newest-first display order.
func (q *Queries) ListPublishedEpisodeCommentsByCreatedAtAsc(ctx context.Context, arg ListPublishedEpisodeCommentsByCreatedAtAscParams) ([]ListPublishedEpisodeCommentsByCreatedAtAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedEpisodeCommentsByCreatedAtAsc,
		arg.TenantID,
		arg.EpisodeID,
		arg.CursorCreatedAt,
		arg.CursorInclusive,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedEpisodeCommentsByCreatedAtAscRow
	for rows.Next() {
		var i ListPublishedEpisodeCommentsByCreatedAtAscRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Body,
			&i.CreatedAt,
			&i.UserID,
			&i.AuthorPublicID,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedEpisodeCommentsByCreatedAtDesc = `-- name: ListPublishedEpisodeCommentsByCreatedAtDesc :many
SELECT c.id,
    c.public_id,
    c.body,
    c.created_at,
    c.user_id,
    u.public_id AS author_public_id,
    u.name AS author_name
FROM episode_comments c
    JOIN users u ON u.tenant_id = c.tenant_id
        AND u.id = c.user_id
WHERE c.tenant_id = $1
    AND c.episode_id = $2
    AND c.status = 'published'
    AND (
        $3::timestamptz IS NULL
        OR (
            $4::boolean
            AND (c.created_at, c.id) <= (
                $3::timestamptz,
                $5::uuid
            )
        )
        OR (
            NOT $4::boolean
            AND (c.created_at, c.id) < (
                $3::timestamptz,
                $5::uuid
            )
        )
    )
ORDER BY c.created_at DESC,
    c.id DESC
LIMIT $6
`

type ListPublishedEpisodeCommentsByCreatedAtDescParams struct {
	TenantID        uuid.UUID     `json:"tenant_id"`
	EpisodeID       uuid.UUID     `json:"episode_id"`
	CursorCreatedAt sql.NullTime  `json:"cursor_created_at"`
	CursorInclusive bool          `json:"cursor_inclusive"`
	CursorID        uuid.NullUUID `json:"cursor_id"`
	Limit           int32         `json:"limit"`
}

type ListPublishedEpisodeCommentsByCreatedAtDescRow struct {
	ID             uuid.UUID `json:"id"`
	PublicID       string    `json:"public_id"`
	Body           string    `json:"body"`
	CreatedAt      time.Time `json:"created_at"`
	UserID         uuid.UUID `json:"user_id"`
	AuthorPublicID string    `json:"author_public_id"`
	AuthorName     string    `json:"author_name"`
}

// The public list of one episode. Only 'published' rows appear here, so a
// pending, removed, or withdrawn comment is absent for every reader; the author
// sees their own through ListUserEpisodeCommentsByCreatedAt*.
func (q *Queries) ListPublishedEpisodeCommentsByCreatedAtDesc(ctx context.Context, arg ListPublishedEpisodeCommentsByCreatedAtDescParams) ([]ListPublishedEpisodeCommentsByCreatedAtDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedEpisodeCommentsByCreatedAtDesc,
		arg.TenantID,
		arg.EpisodeID,
		arg.CursorCreatedAt,
		arg.CursorInclusive,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedEpisodeCommentsByCreatedAtDescRow
	for rows.Next() {
		var i ListPublishedEpisodeCommentsByCreatedAtDescRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Body,
			&i.CreatedAt,
			&i.UserID,
			&i.AuthorPublicID,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserEpisodeCommentsByCreatedAtAsc = `-- name: ListUserEpisodeCommentsByCreatedAtAsc :many
SELECT id,
    public_id,
    episode_id,
    body,
    status,
    created_at,
    published_at
FROM episode_comments
WHERE tenant_id = $1
    AND user_id = $2
    AND status <> 'withdrawn'
    AND (
        $3::timestamptz IS NULL
        OR (
            $4::boolean
            AND (created_at, id) >= (
                $3::timestamptz,
                $5::uuid
            )
        )
        OR (
            NOT $4::boolean
            AND (created_at, id) > (
                $3::timestamptz,
                $5::uuid
            )
        )
    )
ORDER BY created_at ASC,
    id ASC
LIMIT $6
`

type ListUserEpisodeCommentsByCreatedAtAscParams struct {
	TenantID        uuid.UUID     `json:"tenant_id"`
	UserID          uuid.UUID     `json:"user_id"`
	CursorCreatedAt sql.NullTime  `json:"cursor_created_at"`
	CursorInclusive bool          `json:"cursor_inclusive"`
	CursorID        uuid.NullUUID `json:"cursor_id"`
	Limit           int32         `json:"limit"`
}

type ListUserEpisodeCommentsByCreatedAtAscRow struct {
	ID          uuid.UUID    `json:"id"`
	PublicID    string       `json:"public_id"`
	EpisodeID   uuid.UUID    `json:"episode_id"`
	Body        string       `json:"body"`
	Status      string       `json:"status"`
	CreatedAt   time.Time    `json:"created_at"`
	PublishedAt sql.NullTime `json:"published_at"`
}

// The previous-page half of ListUserEpisodeCommentsByCreatedAtDesc.
func (q *Queries) ListUserEpisodeCommentsByCreatedAtAsc(ctx context.Context, arg ListUserEpisodeCommentsByCreatedAtAscParams) ([]ListUserEpisodeCommentsByCreatedAtAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserEpisodeCommentsByCreatedAtAsc,
		arg.TenantID,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorInclusive,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserEpisodeCommentsByCreatedAtAscRow
	for rows.Next() {
		var i ListUserEpisodeCommentsByCreatedAtAscRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.EpisodeID,
			&i.Body,
			&i.Status,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserEpisodeCommentsByCreatedAtDesc = `-- name: ListUserEpisodeCommentsByCreatedAtDesc :many
SELECT id,
    public_id,
    episode_id,
    body,
    status,
    created_at,
    published_at
FROM episode_comments
WHERE tenant_id = $1
    AND user_id = $2
    AND status <> 'withdrawn'
    AND (
        $3::timestamptz IS NULL
        OR (
            $4::boolean
            AND (created_at, id) <= (
                $3::timestamptz,
                $5::uuid
            )
        )
        OR (
            NOT $4::boolean
            AND (created_at, id) < (
                $3::timestamptz,
                $5::uuid
            )
        )
    )
ORDER BY created_at DESC,
    id DESC
LIMIT $6
`

type ListUserEpisodeCommentsByCreatedAtDescParams struct {
	TenantID        uuid.UUID     `json:"tenant_id"`
	UserID          uuid.UUID     `json:"user_id"`
	CursorCreatedAt sql.NullTime  `json:"cursor_created_at"`
	CursorInclusive bool          `json:"cursor_inclusive"`
	CursorID        uuid.NullUUID `json:"cursor_id"`
	Limit           int32         `json:"limit"`
}

type ListUserEpisodeCommentsByCreatedAtDescRow struct {
	ID          uuid.UUID    `json:"id"`
	PublicID    string       `json:"public_id"`
	EpisodeID   uuid.UUID    `json:"episode_id"`
	Body        string       `json:"body"`
	Status      string       `json:"status"`
	CreatedAt   time.Time    `json:"created_at"`
	PublishedAt sql.NullTime `json:"published_at"`
}

// The viewer's own comments. A comment removed by staff or by the report
// threshold stays in this list exactly as it was, because the removal is
// silent; only the author's own withdrawal takes it away from them.
func (q *Queries) ListUserEpisodeCommentsByCreatedAtDesc(ctx context.Context, arg ListUserEpisodeCommentsByCreatedAtDescParams) ([]ListUserEpisodeCommentsByCreatedAtDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserEpisodeCommentsByCreatedAtDesc,
		arg.TenantID,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorInclusive,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserEpisodeCommentsByCreatedAtDescRow
	for rows.Next() {
		var i ListUserEpisodeCommentsByCreatedAtDescRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.EpisodeID,
			&i.Body,
			&i.Status,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeWithdrawnEpisodeComments = `-- name: PurgeWithdrawnEpisodeComments :execrows
DELETE FROM episode_comments
WHERE id IN (
    SELECT expired.id
    FROM episode_comments expired
    WHERE expired.tenant_id = $1
        AND expired.status = 'withdrawn'
        AND expired.withdrawn_at < $2::timestamptz
    ORDER BY expired.withdrawn_at
    LIMIT $3
)
`

type PurgeWithdrawnEpisodeCommentsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Cutoff   time.Time `json:"cutoff"`
	Limit    int32     `json:"limit"`
}

// The end of the retention window for a comment its author deleted. The inner
// select bounds one chunk, so a tenant with a long backlog is drained over
// several statements instead of one long-running delete.
func (q *Queries) PurgeWithdrawnEpisodeComments(ctx context.Context, arg PurgeWithdrawnEpisodeCommentsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeWithdrawnEpisodeComments, arg.TenantID, arg.Cutoff, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const restoreEpisodeCommentByPublicIDForTenant = `-- name: RestoreEpisodeCommentByPublicIDForTenant :one
UPDATE episode_comments
SET status = CASE WHEN published_at IS NULL THEN 'pending' ELSE 'published' END,
    hidden_at = NULL,
    hidden_by = NULL,
    hidden_reason = NULL,
    updated_at = NOW()
WHERE tenant_id = $1
    AND public_id = $2
    AND status = 'hidden'
RETURNING id, tenant_id, public_id, episode_id, user_id, body, status, approved_by, hidden_by, hidden_reason, created_at, updated_at, published_at, hidden_at, withdrawn_at
`

type RestoreEpisodeCommentByPublicIDForTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	PublicID string    `json:"public_id"`
}

// A restored comment returns to the state the removal interrupted, which
// published_at records: one that was already public becomes public again, and
// one removed while still awaiting approval goes back into that queue.
func (q *Queries) RestoreEpisodeCommentByPublicIDForTenant(ctx context.Context, arg RestoreEpisodeCommentByPublicIDForTenantParams) (EpisodeComment, error) {
	row := q.db.QueryRowContext(ctx, restoreEpisodeCommentByPublicIDForTenant, arg.TenantID, arg.PublicID)
	var i EpisodeComment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PublicID,
		&i.EpisodeID,
		&i.UserID,
		&i.Body,
		&i.Status,
		&i.ApprovedBy,
		&i.HiddenBy,
		&i.HiddenReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.HiddenAt,
		&i.WithdrawnAt,
	)
	return i, err
}

const withdrawEpisodeCommentByPublicIDForUser = `-- name: WithdrawEpisodeCommentByPublicIDForUser :one
UPDATE episode_comments
SET status = 'withdrawn',
    withdrawn_at = NOW(),
    hidden_at = NULL,
    hidden_by = NULL,
    hidden_reason = NULL,
    updated_at = NOW()
WHERE tenant_id = $1
    AND user_id = $2
    AND public_id = $3
    AND status <> 'withdrawn'
RETURNING id, tenant_id, public_id, episode_id, user_id, body, status, approved_by, hidden_by, hidden_reason, created_at, updated_at, published_at, hidden_at, withdrawn_at
`

type WithdrawEpisodeCommentByPublicIDForUserParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
	PublicID string    `json:"public_id"`
}

// The author's own deletion. It applies to a comment staff had removed too,
// since the author was never told about that removal and still sees the
// comment. The removal columns are cleared because no removal is in force on a
// withdrawn row any more; audit_logs keeps what staff did and why.
func (q *Queries) WithdrawEpisodeCommentByPublicIDForUser(ctx context.Context, arg WithdrawEpisodeCommentByPublicIDForUserParams) (EpisodeComment, error) {
	row := q.db.QueryRowContext(ctx, withdrawEpisodeCommentByPublicIDForUser, arg.TenantID, arg.UserID, arg.PublicID)
	var i EpisodeComment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PublicID,
		&i.EpisodeID,
		&i.UserID,
		&i.Body,
		&i.Status,
		&i.ApprovedBy,
		&i.HiddenBy,
		&i.HiddenReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.HiddenAt,
		&i.WithdrawnAt,
	)
	return i, err
}
