// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: engagement.sql

package dbmodels

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getContentDailyStatsByEntity = `-- name: GetContentDailyStatsByEntity :one
SELECT id, tenant_id, stat_date, entity_type, entity_id, view_count, unique_viewer_count, member_view_count, purchase_count, complete_count, rating_count, rating_sum, favorite_count, updated_at
FROM content_daily_stats
WHERE tenant_id = $1
    AND stat_date = $2
    AND entity_type = $3
    AND entity_id = $4
`

type GetContentDailyStatsByEntityParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	StatDate   time.Time `json:"stat_date"`
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
}

func (q *Queries) GetContentDailyStatsByEntity(ctx context.Context, arg GetContentDailyStatsByEntityParams) (ContentDailyStat, error) {
	row := q.db.QueryRowContext(ctx, getContentDailyStatsByEntity,
		arg.TenantID,
		arg.StatDate,
		arg.EntityType,
		arg.EntityID,
	)
	var i ContentDailyStat
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StatDate,
		&i.EntityType,
		&i.EntityID,
		&i.ViewCount,
		&i.UniqueViewerCount,
		&i.MemberViewCount,
		&i.PurchaseCount,
		&i.CompleteCount,
		&i.RatingCount,
		&i.RatingSum,
		&i.FavoriteCount,
		&i.UpdatedAt,
	)
	return i, err
}

const getContentEventByID = `-- name: GetContentEventByID :one
SELECT id, tenant_id, event_type, user_id, anonymous_id, actor_key, series_id, episode_id, debounce_bucket, rating_score, source_table, source_id, payload, occurred_at, created_at
FROM content_events
WHERE id = $1
`

func (q *Queries) GetContentEventByID(ctx context.Context, id uuid.UUID) (ContentEvent, error) {
	row := q.db.QueryRowContext(ctx, getContentEventByID, id)
	var i ContentEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.UserID,
		&i.AnonymousID,
		&i.ActorKey,
		&i.SeriesID,
		&i.EpisodeID,
		&i.DebounceBucket,
		&i.RatingScore,
		&i.SourceTable,
		&i.SourceID,
		&i.Payload,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getContentRankingSnapshot = `-- name: GetContentRankingSnapshot :one
SELECT id, tenant_id, ranking_key, period_start, period_end, entity_type, items, algorithm_version, computed_at
FROM content_ranking_snapshots
WHERE tenant_id = $1
    AND ranking_key = $2
    AND period_start = $3
    AND period_end = $4
    AND entity_type = $5
    AND algorithm_version = $6
`

type GetContentRankingSnapshotParams struct {
	TenantID         uuid.UUID `json:"tenant_id"`
	RankingKey       string    `json:"ranking_key"`
	PeriodStart      time.Time `json:"period_start"`
	PeriodEnd        time.Time `json:"period_end"`
	EntityType       string    `json:"entity_type"`
	AlgorithmVersion int32     `json:"algorithm_version"`
}

func (q *Queries) GetContentRankingSnapshot(ctx context.Context, arg GetContentRankingSnapshotParams) (ContentRankingSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getContentRankingSnapshot,
		arg.TenantID,
		arg.RankingKey,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.EntityType,
		arg.AlgorithmVersion,
	)
	var i ContentRankingSnapshot
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RankingKey,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.EntityType,
		&i.Items,
		&i.AlgorithmVersion,
		&i.ComputedAt,
	)
	return i, err
}

const getEpisodeReadThroughTotals = `-- name: GetEpisodeReadThroughTotals :one
SELECT COALESCE(sum(complete_count), 0)::bigint AS complete_count,
    COALESCE(sum(member_view_count), 0)::bigint AS member_view_count
FROM content_daily_stats
WHERE tenant_id = $1
    AND entity_type = 'episode'
    AND stat_date >= $2
    AND stat_date <= $3
`

type GetEpisodeReadThroughTotalsParams struct {
	TenantID    uuid.UUID `json:"tenant_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
}

type GetEpisodeReadThroughTotalsRow struct {
	CompleteCount   int64 `json:"complete_count"`
	MemberViewCount int64 `json:"member_view_count"`
}

// The tenant-wide numerator and denominator for the same window. This is the
// headline metric rather than a page count, so it does not fall under the "no
// total for a cursor list" rule: it stays the same value on every page, and a
// rate assembled from one page's rows would describe that page instead of the
// period.
func (q *Queries) GetEpisodeReadThroughTotals(ctx context.Context, arg GetEpisodeReadThroughTotalsParams) (GetEpisodeReadThroughTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, getEpisodeReadThroughTotals, arg.TenantID, arg.PeriodStart, arg.PeriodEnd)
	var i GetEpisodeReadThroughTotalsRow
	err := row.Scan(&i.CompleteCount, &i.MemberViewCount)
	return i, err
}

const getItemRecommendFeatures = `-- name: GetItemRecommendFeatures :one
SELECT tenant_id, entity_type, entity_id, features, feature_version, computed_at
FROM item_recommend_features
WHERE tenant_id = $1
    AND entity_type = $2
    AND entity_id = $3
`

type GetItemRecommendFeaturesParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
}

func (q *Queries) GetItemRecommendFeatures(ctx context.Context, arg GetItemRecommendFeaturesParams) (ItemRecommendFeature, error) {
	row := q.db.QueryRowContext(ctx, getItemRecommendFeatures, arg.TenantID, arg.EntityType, arg.EntityID)
	var i ItemRecommendFeature
	err := row.Scan(
		&i.TenantID,
		&i.EntityType,
		&i.EntityID,
		&i.Features,
		&i.FeatureVersion,
		&i.ComputedAt,
	)
	return i, err
}

const getLatestContentRankingSnapshot = `-- name: GetLatestContentRankingSnapshot :one
SELECT id, tenant_id, ranking_key, period_start, period_end, entity_type, items, algorithm_version, computed_at
FROM content_ranking_snapshots
WHERE tenant_id = $1
    AND ranking_key = $2
    AND entity_type = $3
ORDER BY computed_at DESC
LIMIT 1
`

type GetLatestContentRankingSnapshotParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	RankingKey string    `json:"ranking_key"`
	EntityType string    `json:"entity_type"`
}

// The newest snapshot for one ranking key and entity type, whichever period
// and algorithm version produced it. A reader on a request path cannot know
// which day the last batch run covered, so it asks for the most recently
// computed row instead of naming period bounds. A bumped algorithm_version
// files its snapshots beside the old ones rather than replacing them, and wins
// here because it was computed later.
func (q *Queries) GetLatestContentRankingSnapshot(ctx context.Context, arg GetLatestContentRankingSnapshotParams) (ContentRankingSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getLatestContentRankingSnapshot, arg.TenantID, arg.RankingKey, arg.EntityType)
	var i ContentRankingSnapshot
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RankingKey,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.EntityType,
		&i.Items,
		&i.AlgorithmVersion,
		&i.ComputedAt,
	)
	return i, err
}

const getUserRecommendFeatures = `-- name: GetUserRecommendFeatures :one
SELECT tenant_id, user_id, features, feature_version, computed_at
FROM user_recommend_features
WHERE tenant_id = $1
    AND user_id = $2
`

type GetUserRecommendFeaturesParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) GetUserRecommendFeatures(ctx context.Context, arg GetUserRecommendFeaturesParams) (UserRecommendFeature, error) {
	row := q.db.QueryRowContext(ctx, getUserRecommendFeatures, arg.TenantID, arg.UserID)
	var i UserRecommendFeature
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Features,
		&i.FeatureVersion,
		&i.ComputedAt,
	)
	return i, err
}

const insertContentEvent = `-- name: InsertContentEvent :one

INSERT INTO content_events (
    id,
    tenant_id,
    event_type,
    user_id,
    anonymous_id,
    series_id,
    episode_id,
    debounce_bucket,
    rating_score,
    source_table,
    source_id,
    payload,
    occurred_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
RETURNING id, tenant_id, event_type, user_id, anonymous_id, actor_key, series_id, episode_id, debounce_bucket, rating_score, source_table, source_id, payload, occurred_at, created_at
`

type InsertContentEventParams struct {
	ID             uuid.UUID       `json:"id"`
	TenantID       uuid.UUID       `json:"tenant_id"`
	EventType      string          `json:"event_type"`
	UserID         uuid.NullUUID   `json:"user_id"`
	AnonymousID    uuid.NullUUID   `json:"anonymous_id"`
	SeriesID       uuid.NullUUID   `json:"series_id"`
	EpisodeID      uuid.NullUUID   `json:"episode_id"`
	DebounceBucket sql.NullInt64   `json:"debounce_bucket"`
	RatingScore    sql.NullInt16   `json:"rating_score"`
	SourceTable    sql.NullString  `json:"source_table"`
	SourceID       uuid.NullUUID   `json:"source_id"`
	Payload        json.RawMessage `json:"payload"`
	OccurredAt     time.Time       `json:"occurred_at"`
}

// Engagement / recommend query skeleton.
// Later issues fill handlers and batches; these queries pin the index-backed
// shapes so sqlc generates now and EXPLAIN stays checkable.
//
// Expected plans (empty table may still seq-scan; SET enable_seqscan = off
// in the integration test to confirm the index is eligible):
//
//	ListContentEventsByTenantOccurredAt
//	  -> idx_content_events_tenant_occurred_at
//	ListContentEventsByTenantTypeOccurredAt
//	  -> idx_content_events_tenant_type_occurred_at
//	GetContentDailyStatsByEntity
//	  -> idx_content_daily_stats_unique / idx_content_daily_stats_tenant_entity
//	GetContentRankingSnapshot
//	  -> idx_content_ranking_snapshots_unique
//	GetLatestContentRankingSnapshot
//	  -> idx_content_ranking_snapshots_tenant_key_computed
//	InsertDebouncedEpisodeViewEvent
//	  -> idx_content_events_episode_view_debounce
//	InsertProjectedSourceEvent
//	  -> idx_content_events_source_unique
//	ListLatestContentRatingsByEntity
//	  -> idx_content_events_tenant_series_occurred_at
//	ListRecommendedSeriesIDs / ListRecommendedSeriesIDsReversed
//	  -> no index; sorts one tenant's published series (see the note there)
//	ListEpisodeReadThroughDesc / ListEpisodeReadThroughAsc
//	  -> idx_content_daily_stats_tenant_date for the window, then a sort on the
//	     aggregate it groups (see the note there)
func (q *Queries) InsertContentEvent(ctx context.Context, arg InsertContentEventParams) (ContentEvent, error) {
	row := q.db.QueryRowContext(ctx, insertContentEvent,
		arg.ID,
		arg.TenantID,
		arg.EventType,
		arg.UserID,
		arg.AnonymousID,
		arg.SeriesID,
		arg.EpisodeID,
		arg.DebounceBucket,
		arg.RatingScore,
		arg.SourceTable,
		arg.SourceID,
		arg.Payload,
		arg.OccurredAt,
	)
	var i ContentEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.UserID,
		&i.AnonymousID,
		&i.ActorKey,
		&i.SeriesID,
		&i.EpisodeID,
		&i.DebounceBucket,
		&i.RatingScore,
		&i.SourceTable,
		&i.SourceID,
		&i.Payload,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertDebouncedEpisodeViewEvent = `-- name: InsertDebouncedEpisodeViewEvent :one
INSERT INTO content_events (
    id,
    tenant_id,
    event_type,
    user_id,
    anonymous_id,
    series_id,
    episode_id,
    debounce_bucket,
    payload,
    occurred_at
) VALUES (
    $1,
    $2,
    'episode_view',
    $3,
    $4,
    $5::uuid,
    $6::uuid,
    $7::bigint,
    $8,
    $9
)
ON CONFLICT (tenant_id, event_type, episode_id, actor_key, debounce_bucket)
WHERE event_type = 'episode_view'
DO NOTHING
RETURNING id, tenant_id, event_type, user_id, anonymous_id, actor_key, series_id, episode_id, debounce_bucket, rating_score, source_table, source_id, payload, occurred_at, created_at
`

type InsertDebouncedEpisodeViewEventParams struct {
	ID             uuid.UUID       `json:"id"`
	TenantID       uuid.UUID       `json:"tenant_id"`
	UserID         uuid.NullUUID   `json:"user_id"`
	AnonymousID    uuid.NullUUID   `json:"anonymous_id"`
	SeriesID       uuid.UUID       `json:"series_id"`
	EpisodeID      uuid.UUID       `json:"episode_id"`
	DebounceBucket int64           `json:"debounce_bucket"`
	Payload        json.RawMessage `json:"payload"`
	OccurredAt     time.Time       `json:"occurred_at"`
}

// Fixed 30-minute epoch bucket. Same actor + episode + bucket is a no-op.
// :one returns no rows on conflict (same as CreateNotification).
func (q *Queries) InsertDebouncedEpisodeViewEvent(ctx context.Context, arg InsertDebouncedEpisodeViewEventParams) (ContentEvent, error) {
	row := q.db.QueryRowContext(ctx, insertDebouncedEpisodeViewEvent,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.AnonymousID,
		arg.SeriesID,
		arg.EpisodeID,
		arg.DebounceBucket,
		arg.Payload,
		arg.OccurredAt,
	)
	var i ContentEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.UserID,
		&i.AnonymousID,
		&i.ActorKey,
		&i.SeriesID,
		&i.EpisodeID,
		&i.DebounceBucket,
		&i.RatingScore,
		&i.SourceTable,
		&i.SourceID,
		&i.Payload,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertDebouncedSeriesViewEvent = `-- name: InsertDebouncedSeriesViewEvent :one
INSERT INTO content_events (
    id,
    tenant_id,
    event_type,
    user_id,
    anonymous_id,
    series_id,
    debounce_bucket,
    payload,
    occurred_at
) VALUES (
    $1,
    $2,
    'series_view',
    $3,
    $4,
    $5::uuid,
    $6::bigint,
    $7,
    $8
)
ON CONFLICT (tenant_id, event_type, series_id, actor_key, debounce_bucket)
WHERE event_type = 'series_view'
DO NOTHING
RETURNING id, tenant_id, event_type, user_id, anonymous_id, actor_key, series_id, episode_id, debounce_bucket, rating_score, source_table, source_id, payload, occurred_at, created_at
`

type InsertDebouncedSeriesViewEventParams struct {
	ID             uuid.UUID       `json:"id"`
	TenantID       uuid.UUID       `json:"tenant_id"`
	UserID         uuid.NullUUID   `json:"user_id"`
	AnonymousID    uuid.NullUUID   `json:"anonymous_id"`
	SeriesID       uuid.UUID       `json:"series_id"`
	DebounceBucket int64           `json:"debounce_bucket"`
	Payload        json.RawMessage `json:"payload"`
	OccurredAt     time.Time       `json:"occurred_at"`
}

func (q *Queries) InsertDebouncedSeriesViewEvent(ctx context.Context, arg InsertDebouncedSeriesViewEventParams) (ContentEvent, error) {
	row := q.db.QueryRowContext(ctx, insertDebouncedSeriesViewEvent,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.AnonymousID,
		arg.SeriesID,
		arg.DebounceBucket,
		arg.Payload,
		arg.OccurredAt,
	)
	var i ContentEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.UserID,
		&i.AnonymousID,
		&i.ActorKey,
		&i.SeriesID,
		&i.EpisodeID,
		&i.DebounceBucket,
		&i.RatingScore,
		&i.SourceTable,
		&i.SourceID,
		&i.Payload,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertProjectedSourceEvent = `-- name: InsertProjectedSourceEvent :one
INSERT INTO content_events (
    id,
    tenant_id,
    event_type,
    user_id,
    series_id,
    episode_id,
    source_table,
    source_id,
    payload,
    occurred_at
) VALUES (
    $1,
    $2,
    $3,
    $4::uuid,
    $5::uuid,
    $6::uuid,
    $7::text,
    $8::uuid,
    $9,
    $10
)
ON CONFLICT (tenant_id, source_table, source_id)
WHERE source_id IS NOT NULL
DO NOTHING
RETURNING id, tenant_id, event_type, user_id, anonymous_id, actor_key, series_id, episode_id, debounce_bucket, rating_score, source_table, source_id, payload, occurred_at, created_at
`

type InsertProjectedSourceEventParams struct {
	ID          uuid.UUID       `json:"id"`
	TenantID    uuid.UUID       `json:"tenant_id"`
	EventType   string          `json:"event_type"`
	UserID      uuid.UUID       `json:"user_id"`
	SeriesID    uuid.UUID       `json:"series_id"`
	EpisodeID   uuid.UUID       `json:"episode_id"`
	SourceTable string          `json:"source_table"`
	SourceID    uuid.UUID       `json:"source_id"`
	Payload     json.RawMessage `json:"payload"`
	OccurredAt  time.Time       `json:"occurred_at"`
}

// Idempotent projection from a SoT row (purchases.id, access_tickets.id).
func (q *Queries) InsertProjectedSourceEvent(ctx context.Context, arg InsertProjectedSourceEventParams) (ContentEvent, error) {
	row := q.db.QueryRowContext(ctx, insertProjectedSourceEvent,
		arg.ID,
		arg.TenantID,
		arg.EventType,
		arg.UserID,
		arg.SeriesID,
		arg.EpisodeID,
		arg.SourceTable,
		arg.SourceID,
		arg.Payload,
		arg.OccurredAt,
	)
	var i ContentEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.UserID,
		&i.AnonymousID,
		&i.ActorKey,
		&i.SeriesID,
		&i.EpisodeID,
		&i.DebounceBucket,
		&i.RatingScore,
		&i.SourceTable,
		&i.SourceID,
		&i.Payload,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertRatingEvent = `-- name: InsertRatingEvent :one
INSERT INTO content_events (
    id,
    tenant_id,
    event_type,
    user_id,
    series_id,
    episode_id,
    rating_score,
    occurred_at
) VALUES (
    $1,
    $2,
    'rating',
    $3::uuid,
    $4::uuid,
    $5,
    $6::smallint,
    $7
)
RETURNING id, tenant_id, event_type, user_id, anonymous_id, actor_key, series_id, episode_id, debounce_bucket, rating_score, source_table, source_id, payload, occurred_at, created_at
`

type InsertRatingEventParams struct {
	ID          uuid.UUID     `json:"id"`
	TenantID    uuid.UUID     `json:"tenant_id"`
	UserID      uuid.UUID     `json:"user_id"`
	SeriesID    uuid.UUID     `json:"series_id"`
	EpisodeID   uuid.NullUUID `json:"episode_id"`
	RatingScore int16         `json:"rating_score"`
	OccurredAt  time.Time     `json:"occurred_at"`
}

// Ratings are append-only, like every other content_events row: a member who
// changes their score inserts another event instead of updating the previous
// one, so the history stays reconstructable and nothing has to be deleted.
// Which score "counts" is therefore a read-side decision, not a write-side one
// (see ListLatestContentRatingsByEntity). There is deliberately no debounce
// bucket here: a rating is an explicit act, not a page load.
//
// episode_id NULL rates the series itself; set, it rates that episode, and
// series_id must still be the episode's own series. Both are resolved by the
// server from the catalog row, never taken from client input.
func (q *Queries) InsertRatingEvent(ctx context.Context, arg InsertRatingEventParams) (ContentEvent, error) {
	row := q.db.QueryRowContext(ctx, insertRatingEvent,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.SeriesID,
		arg.EpisodeID,
		arg.RatingScore,
		arg.OccurredAt,
	)
	var i ContentEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.UserID,
		&i.AnonymousID,
		&i.ActorKey,
		&i.SeriesID,
		&i.EpisodeID,
		&i.DebounceBucket,
		&i.RatingScore,
		&i.SourceTable,
		&i.SourceID,
		&i.Payload,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listContentDailyStatsByTenantDate = `-- name: ListContentDailyStatsByTenantDate :many
SELECT id, tenant_id, stat_date, entity_type, entity_id, view_count, unique_viewer_count, member_view_count, purchase_count, complete_count, rating_count, rating_sum, favorite_count, updated_at
FROM content_daily_stats
WHERE tenant_id = $1
    AND stat_date = $2
ORDER BY entity_type, entity_id
`

type ListContentDailyStatsByTenantDateParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	StatDate time.Time `json:"stat_date"`
}

func (q *Queries) ListContentDailyStatsByTenantDate(ctx context.Context, arg ListContentDailyStatsByTenantDateParams) ([]ContentDailyStat, error) {
	rows, err := q.db.QueryContext(ctx, listContentDailyStatsByTenantDate, arg.TenantID, arg.StatDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentDailyStat
	for rows.Next() {
		var i ContentDailyStat
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StatDate,
			&i.EntityType,
			&i.EntityID,
			&i.ViewCount,
			&i.UniqueViewerCount,
			&i.MemberViewCount,
			&i.PurchaseCount,
			&i.CompleteCount,
			&i.RatingCount,
			&i.RatingSum,
			&i.FavoriteCount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentEventsByTenantOccurredAt = `-- name: ListContentEventsByTenantOccurredAt :many
SELECT id, tenant_id, event_type, user_id, anonymous_id, actor_key, series_id, episode_id, debounce_bucket, rating_score, source_table, source_id, payload, occurred_at, created_at
FROM content_events
WHERE tenant_id = $1
ORDER BY occurred_at DESC
LIMIT $2
`

type ListContentEventsByTenantOccurredAtParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
}

// Representative tenant timeline. EXPLAIN: idx_content_events_tenant_occurred_at.
func (q *Queries) ListContentEventsByTenantOccurredAt(ctx context.Context, arg ListContentEventsByTenantOccurredAtParams) ([]ContentEvent, error) {
	rows, err := q.db.QueryContext(ctx, listContentEventsByTenantOccurredAt, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentEvent
	for rows.Next() {
		var i ContentEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventType,
			&i.UserID,
			&i.AnonymousID,
			&i.ActorKey,
			&i.SeriesID,
			&i.EpisodeID,
			&i.DebounceBucket,
			&i.RatingScore,
			&i.SourceTable,
			&i.SourceID,
			&i.Payload,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentEventsByTenantTypeOccurredAt = `-- name: ListContentEventsByTenantTypeOccurredAt :many
SELECT id, tenant_id, event_type, user_id, anonymous_id, actor_key, series_id, episode_id, debounce_bucket, rating_score, source_table, source_id, payload, occurred_at, created_at
FROM content_events
WHERE tenant_id = $1
    AND event_type = $2
ORDER BY occurred_at DESC
LIMIT $3
`

type ListContentEventsByTenantTypeOccurredAtParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	EventType string    `json:"event_type"`
	Limit     int32     `json:"limit"`
}

// Representative type-filtered timeline. EXPLAIN: idx_content_events_tenant_type_occurred_at.
func (q *Queries) ListContentEventsByTenantTypeOccurredAt(ctx context.Context, arg ListContentEventsByTenantTypeOccurredAtParams) ([]ContentEvent, error) {
	rows, err := q.db.QueryContext(ctx, listContentEventsByTenantTypeOccurredAt, arg.TenantID, arg.EventType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentEvent
	for rows.Next() {
		var i ContentEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventType,
			&i.UserID,
			&i.AnonymousID,
			&i.ActorKey,
			&i.SeriesID,
			&i.EpisodeID,
			&i.DebounceBucket,
			&i.RatingScore,
			&i.SourceTable,
			&i.SourceID,
			&i.Payload,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodeReadThroughAsc = `-- name: ListEpisodeReadThroughAsc :many
WITH totals AS (
    SELECT s.entity_id,
        sum(s.complete_count)::bigint AS complete_count,
        sum(s.member_view_count)::bigint AS member_view_count
    FROM content_daily_stats s
    WHERE s.tenant_id = $1
        AND s.entity_type = 'episode'
        AND s.stat_date >= $6
        AND s.stat_date <= $7
    GROUP BY s.entity_id
    HAVING sum(s.complete_count) > 0 OR sum(s.member_view_count) > 0
)
SELECT t.entity_id AS episode_id,
    t.complete_count,
    t.member_view_count,
    e.public_id AS episode_public_id,
    e.title AS episode_title,
    sr.public_id AS series_public_id,
    sr.title AS series_title
FROM totals t
    JOIN episodes e ON e.tenant_id = $1 AND e.id = t.entity_id
    JOIN series sr ON sr.tenant_id = e.tenant_id AND sr.id = e.series_id
WHERE (
        $2::uuid IS NULL
        OR (
            $3::boolean
            AND (t.complete_count, t.entity_id) >= (
                $4::bigint,
                $2::uuid
            )
        )
        OR (
            NOT $3::boolean
            AND (t.complete_count, t.entity_id) > (
                $4::bigint,
                $2::uuid
            )
        )
    )
ORDER BY t.complete_count ASC, t.entity_id ASC
LIMIT $5
`

type ListEpisodeReadThroughAscParams struct {
	TenantID            uuid.UUID     `json:"tenant_id"`
	CursorEntityID      uuid.NullUUID `json:"cursor_entity_id"`
	CursorInclusive     bool          `json:"cursor_inclusive"`
	CursorCompleteCount sql.NullInt64 `json:"cursor_complete_count"`
	Limit               int32         `json:"limit"`
	PeriodStart         time.Time     `json:"period_start"`
	PeriodEnd           time.Time     `json:"period_end"`
}

type ListEpisodeReadThroughAscRow struct {
	EpisodeID       uuid.UUID `json:"episode_id"`
	CompleteCount   int64     `json:"complete_count"`
	MemberViewCount int64     `json:"member_view_count"`
	EpisodePublicID string    `json:"episode_public_id"`
	EpisodeTitle    string    `json:"episode_title"`
	SeriesPublicID  string    `json:"series_public_id"`
	SeriesTitle     string    `json:"series_title"`
}

// ListEpisodeReadThroughDesc walked the other way, to build a previous page.
// The order it describes is the same one.
func (q *Queries) ListEpisodeReadThroughAsc(ctx context.Context, arg ListEpisodeReadThroughAscParams) ([]ListEpisodeReadThroughAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listEpisodeReadThroughAsc,
		arg.TenantID,
		arg.CursorEntityID,
		arg.CursorInclusive,
		arg.CursorCompleteCount,
		arg.Limit,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEpisodeReadThroughAscRow
	for rows.Next() {
		var i ListEpisodeReadThroughAscRow
		if err := rows.Scan(
			&i.EpisodeID,
			&i.CompleteCount,
			&i.MemberViewCount,
			&i.EpisodePublicID,
			&i.EpisodeTitle,
			&i.SeriesPublicID,
			&i.SeriesTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodeReadThroughDesc = `-- name: ListEpisodeReadThroughDesc :many
WITH totals AS (
    SELECT s.entity_id,
        sum(s.complete_count)::bigint AS complete_count,
        sum(s.member_view_count)::bigint AS member_view_count
    FROM content_daily_stats s
    WHERE s.tenant_id = $1
        AND s.entity_type = 'episode'
        AND s.stat_date >= $6
        AND s.stat_date <= $7
    GROUP BY s.entity_id
    HAVING sum(s.complete_count) > 0 OR sum(s.member_view_count) > 0
)
SELECT t.entity_id AS episode_id,
    t.complete_count,
    t.member_view_count,
    e.public_id AS episode_public_id,
    e.title AS episode_title,
    sr.public_id AS series_public_id,
    sr.title AS series_title
FROM totals t
    JOIN episodes e ON e.tenant_id = $1 AND e.id = t.entity_id
    JOIN series sr ON sr.tenant_id = e.tenant_id AND sr.id = e.series_id
WHERE (
        $2::uuid IS NULL
        OR (
            $3::boolean
            AND (t.complete_count, t.entity_id) <= (
                $4::bigint,
                $2::uuid
            )
        )
        OR (
            NOT $3::boolean
            AND (t.complete_count, t.entity_id) < (
                $4::bigint,
                $2::uuid
            )
        )
    )
ORDER BY t.complete_count DESC, t.entity_id DESC
LIMIT $5
`

type ListEpisodeReadThroughDescParams struct {
	TenantID            uuid.UUID     `json:"tenant_id"`
	CursorEntityID      uuid.NullUUID `json:"cursor_entity_id"`
	CursorInclusive     bool          `json:"cursor_inclusive"`
	CursorCompleteCount sql.NullInt64 `json:"cursor_complete_count"`
	Limit               int32         `json:"limit"`
	PeriodStart         time.Time     `json:"period_start"`
	PeriodEnd           time.Time     `json:"period_end"`
}

type ListEpisodeReadThroughDescRow struct {
	EpisodeID       uuid.UUID `json:"episode_id"`
	CompleteCount   int64     `json:"complete_count"`
	MemberViewCount int64     `json:"member_view_count"`
	EpisodePublicID string    `json:"episode_public_id"`
	EpisodeTitle    string    `json:"episode_title"`
	SeriesPublicID  string    `json:"series_public_id"`
	SeriesTitle     string    `json:"series_title"`
}

// The read-through report the console shows, over a closed range of UTC stat
// dates. Both halves of the rate come from the same cohort: complete_count is
// the members who finished the episode in the range, member_view_count the
// views those same signed-in members opened it with. view_count is not usable
// here — it counts anonymous readers, who cannot produce a completion at all.
//
// No index can serve this scan: the sort key is an aggregate of the rows the
// query itself groups, the way ListRecommendedSeriesIDs sorts by a rank its own
// JSON supplies. It stays bounded by one tenant's episode rows inside the
// report window, which idx_content_daily_stats_tenant_date narrows first.
//
// (complete_count, entity_id) is unique because entity_id alone is, so the
// keyset scan can neither skip nor repeat episodes that tie on completions.
func (q *Queries) ListEpisodeReadThroughDesc(ctx context.Context, arg ListEpisodeReadThroughDescParams) ([]ListEpisodeReadThroughDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listEpisodeReadThroughDesc,
		arg.TenantID,
		arg.CursorEntityID,
		arg.CursorInclusive,
		arg.CursorCompleteCount,
		arg.Limit,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEpisodeReadThroughDescRow
	for rows.Next() {
		var i ListEpisodeReadThroughDescRow
		if err := rows.Scan(
			&i.EpisodeID,
			&i.CompleteCount,
			&i.MemberViewCount,
			&i.EpisodePublicID,
			&i.EpisodeTitle,
			&i.SeriesPublicID,
			&i.SeriesTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestContentRatingsByEntity = `-- name: ListLatestContentRatingsByEntity :many
SELECT DISTINCT ON (actor_key) actor_key,
    rating_score,
    occurred_at
FROM content_events
WHERE tenant_id = $1
    AND event_type = 'rating'
    AND series_id = $2::uuid
    AND episode_id IS NOT DISTINCT FROM $3::uuid
ORDER BY actor_key, occurred_at DESC, id DESC
`

type ListLatestContentRatingsByEntityParams struct {
	TenantID  uuid.UUID     `json:"tenant_id"`
	SeriesID  uuid.UUID     `json:"series_id"`
	EpisodeID uuid.NullUUID `json:"episode_id"`
}

type ListLatestContentRatingsByEntityRow struct {
	ActorKey    uuid.NullUUID `json:"actor_key"`
	RatingScore sql.NullInt16 `json:"rating_score"`
	OccurredAt  time.Time     `json:"occurred_at"`
}

// The latest rating each actor currently stands by for one entity: the stock
// view of an append-only log. `content_daily_stats.rating_count` /
// `rating_sum` are the *flow* of a single day and cannot answer this,
// because a member who rated 1 on Monday and 5 on Tuesday contributes to both
// days. A stock average has to come from this DISTINCT ON, over the full
// retained history, until a materialised current-rating table exists.
//
// The tie-break runs past occurred_at because two events from one actor can
// share a timestamp; id is UUIDv7, so the later insert wins.
func (q *Queries) ListLatestContentRatingsByEntity(ctx context.Context, arg ListLatestContentRatingsByEntityParams) ([]ListLatestContentRatingsByEntityRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestContentRatingsByEntity, arg.TenantID, arg.SeriesID, arg.EpisodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestContentRatingsByEntityRow
	for rows.Next() {
		var i ListLatestContentRatingsByEntityRow
		if err := rows.Scan(&i.ActorKey, &i.RatingScore, &i.OccurredAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendedSeriesIDs = `-- name: ListRecommendedSeriesIDs :many
WITH ranked AS (
    SELECT (item->>'entity_id')::uuid AS entity_id,
        min((item->>'rank')::int) AS rank
    FROM jsonb_array_elements($6::jsonb) AS item
    GROUP BY (item->>'entity_id')::uuid
),
candidate AS (
    SELECT s.id,
        s.published_at,
        COALESCE(r.rank, 2147483647)::int AS sort_rank
    FROM series s
        LEFT JOIN ranked r ON r.entity_id = s.id
    WHERE s.tenant_id = $7
        AND s.is_published = true
        AND s.published_at IS NOT NULL
        AND s.published_at <= NOW()
)
SELECT id, sort_rank
FROM candidate
WHERE (
        $1::uuid IS NULL
        OR sort_rank > $2::int
        OR (
            sort_rank = $2::int
            AND (
                (
                    $3::boolean
                    AND (published_at, id) <= (
                        $4::timestamptz,
                        $1::uuid
                    )
                )
                OR (
                    NOT $3::boolean
                    AND (published_at, id) < (
                        $4::timestamptz,
                        $1::uuid
                    )
                )
            )
        )
    )
ORDER BY sort_rank ASC,
    published_at DESC,
    id DESC
LIMIT $5
`

type ListRecommendedSeriesIDsParams struct {
	CursorID          uuid.NullUUID   `json:"cursor_id"`
	CursorRank        sql.NullInt32   `json:"cursor_rank"`
	CursorInclusive   bool            `json:"cursor_inclusive"`
	CursorPublishedAt sql.NullTime    `json:"cursor_published_at"`
	Limit             int32           `json:"limit"`
	RankingItems      json.RawMessage `json:"ranking_items"`
	TenantID          uuid.UUID       `json:"tenant_id"`
}

type ListRecommendedSeriesIDsRow struct {
	ID       uuid.UUID `json:"id"`
	SortRank int32     `json:"sort_rank"`
}

// The keyset scan behind the storefront recommendation list. It takes one
// ranking snapshot's items as they are stored and puts the ranked series first,
// then every other published series newest first.
//
// The sort key is (sort_rank, published_at, id). A series the snapshot does not
// name borrows int4's maximum and sorts last; every rank a snapshot can hold is
// below it. Ties are impossible: a rank is unique within a snapshot, and the
// unranked share one sort_rank that id breaks.
//
// sort_rank comes back with each row because the cursor is built from it. A
// caller that recomputed the rank from the same JSON would have to fold
// duplicates and missing ranks exactly the way min() and COALESCE do here, and
// a token built on a value this query never sorted by points at the wrong page.
//
// This is the one list query here that no index can serve. Its first sort key
// comes from the snapshot's JSONB rather than from a column of series, so the
// scan reads the tenant's published series and sorts them. That is bounded by
// one tenant's catalogue, and ranking_items is one snapshot (50 items by
// default), folded per entity_id so the LEFT JOIN cannot multiply rows.
func (q *Queries) ListRecommendedSeriesIDs(ctx context.Context, arg ListRecommendedSeriesIDsParams) ([]ListRecommendedSeriesIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecommendedSeriesIDs,
		arg.CursorID,
		arg.CursorRank,
		arg.CursorInclusive,
		arg.CursorPublishedAt,
		arg.Limit,
		arg.RankingItems,
		arg.TenantID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecommendedSeriesIDsRow
	for rows.Next() {
		var i ListRecommendedSeriesIDsRow
		if err := rows.Scan(&i.ID, &i.SortRank); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecommendedSeriesIDsReversed = `-- name: ListRecommendedSeriesIDsReversed :many
WITH ranked AS (
    SELECT (item->>'entity_id')::uuid AS entity_id,
        min((item->>'rank')::int) AS rank
    FROM jsonb_array_elements($6::jsonb) AS item
    GROUP BY (item->>'entity_id')::uuid
),
candidate AS (
    SELECT s.id,
        s.published_at,
        COALESCE(r.rank, 2147483647)::int AS sort_rank
    FROM series s
        LEFT JOIN ranked r ON r.entity_id = s.id
    WHERE s.tenant_id = $7
        AND s.is_published = true
        AND s.published_at IS NOT NULL
        AND s.published_at <= NOW()
)
SELECT id, sort_rank
FROM candidate
WHERE (
        $1::uuid IS NULL
        OR sort_rank < $2::int
        OR (
            sort_rank = $2::int
            AND (
                (
                    $3::boolean
                    AND (published_at, id) >= (
                        $4::timestamptz,
                        $1::uuid
                    )
                )
                OR (
                    NOT $3::boolean
                    AND (published_at, id) > (
                        $4::timestamptz,
                        $1::uuid
                    )
                )
            )
        )
    )
ORDER BY sort_rank DESC,
    published_at ASC,
    id ASC
LIMIT $5
`

type ListRecommendedSeriesIDsReversedParams struct {
	CursorID          uuid.NullUUID   `json:"cursor_id"`
	CursorRank        sql.NullInt32   `json:"cursor_rank"`
	CursorInclusive   bool            `json:"cursor_inclusive"`
	CursorPublishedAt sql.NullTime    `json:"cursor_published_at"`
	Limit             int32           `json:"limit"`
	RankingItems      json.RawMessage `json:"ranking_items"`
	TenantID          uuid.UUID       `json:"tenant_id"`
}

type ListRecommendedSeriesIDsReversedRow struct {
	ID       uuid.UUID `json:"id"`
	SortRank int32     `json:"sort_rank"`
}

// ListRecommendedSeriesIDs walked the other way. It exists only to build a
// previous page; the order it describes is the same one.
func (q *Queries) ListRecommendedSeriesIDsReversed(ctx context.Context, arg ListRecommendedSeriesIDsReversedParams) ([]ListRecommendedSeriesIDsReversedRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecommendedSeriesIDsReversed,
		arg.CursorID,
		arg.CursorRank,
		arg.CursorInclusive,
		arg.CursorPublishedAt,
		arg.Limit,
		arg.RankingItems,
		arg.TenantID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecommendedSeriesIDsReversedRow
	for rows.Next() {
		var i ListRecommendedSeriesIDsReversedRow
		if err := rows.Scan(&i.ID, &i.SortRank); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectEpisodeCompleteEvent = `-- name: ProjectEpisodeCompleteEvent :one
INSERT INTO content_events (
    id,
    tenant_id,
    event_type,
    user_id,
    series_id,
    episode_id,
    source_table,
    source_id,
    payload,
    occurred_at
)
SELECT
    $1,
    r.tenant_id,
    'episode_complete',
    r.user_id,
    e.series_id,
    r.episode_id,
    'episode_reads',
    r.id,
    '{}'::jsonb,
    r.read_at
FROM episode_reads r
JOIN episodes e
    ON e.tenant_id = r.tenant_id
    AND e.id = r.episode_id
WHERE r.tenant_id = $2
    AND r.user_id = $3
    AND r.episode_id = $4
ON CONFLICT (tenant_id, source_table, source_id)
WHERE source_id IS NOT NULL
DO NOTHING
RETURNING id, tenant_id, event_type, user_id, anonymous_id, actor_key, series_id, episode_id, debounce_bucket, rating_score, source_table, source_id, payload, occurred_at, created_at
`

type ProjectEpisodeCompleteEventParams struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	UserID    uuid.UUID `json:"user_id"`
	EpisodeID uuid.UUID `json:"episode_id"`
}

// Projects one member's first completed read as the analytics event for that
// read. episode_reads stays the source of truth for the business state: its
// user, episode, and first read time are copied, and the owning series is
// resolved from the catalog rather than taken from the caller.
//
// The pair (source_table, source_id) is what makes this replayable. A repeated
// notification returns the same episode_reads row, so the projection lands on
// the same source key and the unique index turns the second attempt into a
// no-op. Nothing here depends on knowing whether the read row was new.
func (q *Queries) ProjectEpisodeCompleteEvent(ctx context.Context, arg ProjectEpisodeCompleteEventParams) (ContentEvent, error) {
	row := q.db.QueryRowContext(ctx, projectEpisodeCompleteEvent,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.EpisodeID,
	)
	var i ContentEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.UserID,
		&i.AnonymousID,
		&i.ActorKey,
		&i.SeriesID,
		&i.EpisodeID,
		&i.DebounceBucket,
		&i.RatingScore,
		&i.SourceTable,
		&i.SourceID,
		&i.Payload,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const projectPendingEpisodeCompleteEvents = `-- name: ProjectPendingEpisodeCompleteEvents :one
WITH candidates AS (
    SELECT r.id,
        r.tenant_id,
        r.user_id,
        r.episode_id,
        r.read_at,
        e.series_id
    FROM episode_reads r
    JOIN episodes e
        ON e.tenant_id = r.tenant_id
        AND e.id = r.episode_id
    WHERE NOT EXISTS (
            SELECT 1
            FROM content_events ce
            WHERE ce.tenant_id = r.tenant_id
                AND ce.source_table = 'episode_reads'
                AND ce.source_id = r.id
        )
    ORDER BY r.read_at, r.id
    LIMIT $1
), inserted AS (
    INSERT INTO content_events (
        id,
        tenant_id,
        event_type,
        user_id,
        series_id,
        episode_id,
        source_table,
        source_id,
        payload,
        occurred_at
    )
    SELECT
        uuidv7(),
        c.tenant_id,
        'episode_complete',
        c.user_id,
        c.series_id,
        c.episode_id,
        'episode_reads',
        c.id,
        '{}'::jsonb,
        c.read_at
    FROM candidates c
    ON CONFLICT (tenant_id, source_table, source_id)
    WHERE source_id IS NOT NULL
    DO NOTHING
    RETURNING 1
)
SELECT (SELECT count(*) FROM candidates)::bigint AS candidate_count,
    (SELECT count(*) FROM inserted)::bigint AS inserted_count
`

type ProjectPendingEpisodeCompleteEventsRow struct {
	CandidateCount int64 `json:"candidate_count"`
	InsertedCount  int64 `json:"inserted_count"`
}

// Reconciles episode_reads rows whose projection never landed, across every
// tenant. The request path writes the event outside the transaction that
// stored the read and swallows its failure, so a completion can outlive its
// event; this is how that gap closes.
//
// The anti-join and the unique index answer the same question at different
// times, and both are needed: the anti-join keeps the statement from proposing
// rows that already exist, and ON CONFLICT keeps a concurrent request-path
// write from turning this run into a duplicate key error. Ordering by read_at
// makes a run resumable — every batch takes the oldest unprojected reads — so
// repeated runs converge instead of revisiting the same window.
//
// Both counts come back because they answer different questions and can differ.
// candidate_count is how many unprojected reads this batch claimed, and is what
// tells the caller whether the backlog is exhausted; inserted_count is how many
// events were actually written. A request-path write that lands between this
// statement's select and its insert makes the second smaller than the first, so
// a caller that looped on inserted_count would stop with reads still pending.
//
// id is uuidv7() rather than a value passed in because the statement inserts a
// whole batch; content_events ids are UUIDv7 so that events sharing an
// occurred_at still order by when they were recorded.
func (q *Queries) ProjectPendingEpisodeCompleteEvents(ctx context.Context, limit int32) (ProjectPendingEpisodeCompleteEventsRow, error) {
	row := q.db.QueryRowContext(ctx, projectPendingEpisodeCompleteEvents, limit)
	var i ProjectPendingEpisodeCompleteEventsRow
	err := row.Scan(&i.CandidateCount, &i.InsertedCount)
	return i, err
}

const projectPurchaseContentEvent = `-- name: ProjectPurchaseContentEvent :one
INSERT INTO content_events (
    id,
    tenant_id,
    event_type,
    user_id,
    series_id,
    episode_id,
    source_table,
    source_id,
    payload,
    occurred_at
)
SELECT
    $1,
    p.tenant_id,
    'purchase',
    p.user_id,
    e.series_id,
    p.episode_id,
    'purchases',
    p.id,
    '{}'::jsonb,
    p.purchased_at
FROM purchases p
JOIN episodes e
    ON e.tenant_id = p.tenant_id
    AND e.id = p.episode_id
WHERE p.tenant_id = $2
    AND p.stripe_checkout_session_id = $3::text
ON CONFLICT (tenant_id, source_table, source_id)
WHERE source_id IS NOT NULL
DO NOTHING
RETURNING id, tenant_id, event_type, user_id, anonymous_id, actor_key, series_id, episode_id, debounce_bucket, rating_score, source_table, source_id, payload, occurred_at, created_at
`

type ProjectPurchaseContentEventParams struct {
	ID                      uuid.UUID `json:"id"`
	TenantID                uuid.UUID `json:"tenant_id"`
	StripeCheckoutSessionID string    `json:"stripe_checkout_session_id"`
}

// Projects the Stripe-confirmed purchase without trusting webhook metadata for
// the actor or content target. purchases stays the source of truth: its user
// is copied directly and the episode resolves its owning series. A retry is a
// no-op after the source unique index has accepted the first event.
//
// The Phase 0 daily purchase aggregate reads purchases directly. Do not mix
// this projection into that aggregate until its source contract moves to
// content_events, or purchases will be counted twice.
func (q *Queries) ProjectPurchaseContentEvent(ctx context.Context, arg ProjectPurchaseContentEventParams) (ContentEvent, error) {
	row := q.db.QueryRowContext(ctx, projectPurchaseContentEvent, arg.ID, arg.TenantID, arg.StripeCheckoutSessionID)
	var i ContentEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.UserID,
		&i.AnonymousID,
		&i.ActorKey,
		&i.SeriesID,
		&i.EpisodeID,
		&i.DebounceBucket,
		&i.RatingScore,
		&i.SourceTable,
		&i.SourceID,
		&i.Payload,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertContentDailyStats = `-- name: UpsertContentDailyStats :one
INSERT INTO content_daily_stats (
    id,
    tenant_id,
    stat_date,
    entity_type,
    entity_id,
    view_count,
    unique_viewer_count,
    member_view_count,
    purchase_count,
    complete_count,
    rating_count,
    rating_sum,
    favorite_count
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
ON CONFLICT (tenant_id, stat_date, entity_type, entity_id) DO UPDATE
SET view_count = EXCLUDED.view_count,
    unique_viewer_count = EXCLUDED.unique_viewer_count,
    member_view_count = EXCLUDED.member_view_count,
    purchase_count = EXCLUDED.purchase_count,
    complete_count = EXCLUDED.complete_count,
    rating_count = EXCLUDED.rating_count,
    rating_sum = EXCLUDED.rating_sum,
    favorite_count = EXCLUDED.favorite_count,
    updated_at = NOW()
RETURNING id, tenant_id, stat_date, entity_type, entity_id, view_count, unique_viewer_count, member_view_count, purchase_count, complete_count, rating_count, rating_sum, favorite_count, updated_at
`

type UpsertContentDailyStatsParams struct {
	ID                uuid.UUID `json:"id"`
	TenantID          uuid.UUID `json:"tenant_id"`
	StatDate          time.Time `json:"stat_date"`
	EntityType        string    `json:"entity_type"`
	EntityID          uuid.UUID `json:"entity_id"`
	ViewCount         int64     `json:"view_count"`
	UniqueViewerCount int64     `json:"unique_viewer_count"`
	MemberViewCount   int64     `json:"member_view_count"`
	PurchaseCount     int64     `json:"purchase_count"`
	CompleteCount     int64     `json:"complete_count"`
	RatingCount       int64     `json:"rating_count"`
	RatingSum         int64     `json:"rating_sum"`
	FavoriteCount     int64     `json:"favorite_count"`
}

// Daily stats are full-day replacements. Upsert keeps a single row per
// (tenant, date, entity). rating_count / rating_sum are that day's flow — the
// rating events that occurred on stat_date — and not a stock average: a member
// who re-rates is counted on both days, and a member who never re-rates is
// counted on neither day after the first. Summing rating_sum / rating_count
// across a date range therefore averages ratings *given* in that range, not
// the ratings an item currently holds (ListLatestContentRatingsByEntity).
func (q *Queries) UpsertContentDailyStats(ctx context.Context, arg UpsertContentDailyStatsParams) (ContentDailyStat, error) {
	row := q.db.QueryRowContext(ctx, upsertContentDailyStats,
		arg.ID,
		arg.TenantID,
		arg.StatDate,
		arg.EntityType,
		arg.EntityID,
		arg.ViewCount,
		arg.UniqueViewerCount,
		arg.MemberViewCount,
		arg.PurchaseCount,
		arg.CompleteCount,
		arg.RatingCount,
		arg.RatingSum,
		arg.FavoriteCount,
	)
	var i ContentDailyStat
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StatDate,
		&i.EntityType,
		&i.EntityID,
		&i.ViewCount,
		&i.UniqueViewerCount,
		&i.MemberViewCount,
		&i.PurchaseCount,
		&i.CompleteCount,
		&i.RatingCount,
		&i.RatingSum,
		&i.FavoriteCount,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertContentRankingSnapshot = `-- name: UpsertContentRankingSnapshot :one
INSERT INTO content_ranking_snapshots (
    id,
    tenant_id,
    ranking_key,
    period_start,
    period_end,
    entity_type,
    items,
    algorithm_version,
    computed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
ON CONFLICT (tenant_id, ranking_key, period_start, period_end, entity_type, algorithm_version) DO UPDATE
SET items = EXCLUDED.items,
    computed_at = EXCLUDED.computed_at
RETURNING id, tenant_id, ranking_key, period_start, period_end, entity_type, items, algorithm_version, computed_at
`

type UpsertContentRankingSnapshotParams struct {
	ID               uuid.UUID       `json:"id"`
	TenantID         uuid.UUID       `json:"tenant_id"`
	RankingKey       string          `json:"ranking_key"`
	PeriodStart      time.Time       `json:"period_start"`
	PeriodEnd        time.Time       `json:"period_end"`
	EntityType       string          `json:"entity_type"`
	Items            json.RawMessage `json:"items"`
	AlgorithmVersion int32           `json:"algorithm_version"`
	ComputedAt       time.Time       `json:"computed_at"`
}

func (q *Queries) UpsertContentRankingSnapshot(ctx context.Context, arg UpsertContentRankingSnapshotParams) (ContentRankingSnapshot, error) {
	row := q.db.QueryRowContext(ctx, upsertContentRankingSnapshot,
		arg.ID,
		arg.TenantID,
		arg.RankingKey,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.EntityType,
		arg.Items,
		arg.AlgorithmVersion,
		arg.ComputedAt,
	)
	var i ContentRankingSnapshot
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RankingKey,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.EntityType,
		&i.Items,
		&i.AlgorithmVersion,
		&i.ComputedAt,
	)
	return i, err
}

const upsertItemRecommendFeatures = `-- name: UpsertItemRecommendFeatures :one
INSERT INTO item_recommend_features (
    tenant_id,
    entity_type,
    entity_id,
    features,
    feature_version,
    computed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (tenant_id, entity_type, entity_id) DO UPDATE
SET features = EXCLUDED.features,
    feature_version = EXCLUDED.feature_version,
    computed_at = EXCLUDED.computed_at
RETURNING tenant_id, entity_type, entity_id, features, feature_version, computed_at
`

type UpsertItemRecommendFeaturesParams struct {
	TenantID       uuid.UUID       `json:"tenant_id"`
	EntityType     string          `json:"entity_type"`
	EntityID       uuid.UUID       `json:"entity_id"`
	Features       json.RawMessage `json:"features"`
	FeatureVersion int32           `json:"feature_version"`
	ComputedAt     time.Time       `json:"computed_at"`
}

func (q *Queries) UpsertItemRecommendFeatures(ctx context.Context, arg UpsertItemRecommendFeaturesParams) (ItemRecommendFeature, error) {
	row := q.db.QueryRowContext(ctx, upsertItemRecommendFeatures,
		arg.TenantID,
		arg.EntityType,
		arg.EntityID,
		arg.Features,
		arg.FeatureVersion,
		arg.ComputedAt,
	)
	var i ItemRecommendFeature
	err := row.Scan(
		&i.TenantID,
		&i.EntityType,
		&i.EntityID,
		&i.Features,
		&i.FeatureVersion,
		&i.ComputedAt,
	)
	return i, err
}

const upsertUserRecommendFeatures = `-- name: UpsertUserRecommendFeatures :one
INSERT INTO user_recommend_features (
    tenant_id,
    user_id,
    features,
    feature_version,
    computed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (tenant_id, user_id) DO UPDATE
SET features = EXCLUDED.features,
    feature_version = EXCLUDED.feature_version,
    computed_at = EXCLUDED.computed_at
RETURNING tenant_id, user_id, features, feature_version, computed_at
`

type UpsertUserRecommendFeaturesParams struct {
	TenantID       uuid.UUID       `json:"tenant_id"`
	UserID         uuid.UUID       `json:"user_id"`
	Features       json.RawMessage `json:"features"`
	FeatureVersion int32           `json:"feature_version"`
	ComputedAt     time.Time       `json:"computed_at"`
}

func (q *Queries) UpsertUserRecommendFeatures(ctx context.Context, arg UpsertUserRecommendFeaturesParams) (UserRecommendFeature, error) {
	row := q.db.QueryRowContext(ctx, upsertUserRecommendFeatures,
		arg.TenantID,
		arg.UserID,
		arg.Features,
		arg.FeatureVersion,
		arg.ComputedAt,
	)
	var i UserRecommendFeature
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Features,
		&i.FeatureVersion,
		&i.ComputedAt,
	)
	return i, err
}
