// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: engagement.sql

package dbmodels

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getContentDailyStatsByEntity = `-- name: GetContentDailyStatsByEntity :one
SELECT id, tenant_id, stat_date, entity_type, entity_id, view_count, unique_viewer_count, purchase_count, rating_count, rating_sum, favorite_count, updated_at
FROM content_daily_stats
WHERE tenant_id = $1
    AND stat_date = $2
    AND entity_type = $3
    AND entity_id = $4
`

type GetContentDailyStatsByEntityParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	StatDate   time.Time `json:"stat_date"`
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
}

func (q *Queries) GetContentDailyStatsByEntity(ctx context.Context, arg GetContentDailyStatsByEntityParams) (ContentDailyStat, error) {
	row := q.db.QueryRowContext(ctx, getContentDailyStatsByEntity,
		arg.TenantID,
		arg.StatDate,
		arg.EntityType,
		arg.EntityID,
	)
	var i ContentDailyStat
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StatDate,
		&i.EntityType,
		&i.EntityID,
		&i.ViewCount,
		&i.UniqueViewerCount,
		&i.PurchaseCount,
		&i.RatingCount,
		&i.RatingSum,
		&i.FavoriteCount,
		&i.UpdatedAt,
	)
	return i, err
}

const getContentEventByID = `-- name: GetContentEventByID :one
SELECT id, tenant_id, event_type, user_id, anonymous_id, actor_key, series_id, episode_id, debounce_bucket, rating_score, source_table, source_id, payload, occurred_at, created_at
FROM content_events
WHERE id = $1
`

func (q *Queries) GetContentEventByID(ctx context.Context, id uuid.UUID) (ContentEvent, error) {
	row := q.db.QueryRowContext(ctx, getContentEventByID, id)
	var i ContentEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.UserID,
		&i.AnonymousID,
		&i.ActorKey,
		&i.SeriesID,
		&i.EpisodeID,
		&i.DebounceBucket,
		&i.RatingScore,
		&i.SourceTable,
		&i.SourceID,
		&i.Payload,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getContentRankingSnapshot = `-- name: GetContentRankingSnapshot :one
SELECT id, tenant_id, ranking_key, period_start, period_end, entity_type, items, algorithm_version, computed_at
FROM content_ranking_snapshots
WHERE tenant_id = $1
    AND ranking_key = $2
    AND period_start = $3
    AND period_end = $4
    AND entity_type = $5
    AND algorithm_version = $6
`

type GetContentRankingSnapshotParams struct {
	TenantID         uuid.UUID `json:"tenant_id"`
	RankingKey       string    `json:"ranking_key"`
	PeriodStart      time.Time `json:"period_start"`
	PeriodEnd        time.Time `json:"period_end"`
	EntityType       string    `json:"entity_type"`
	AlgorithmVersion int32     `json:"algorithm_version"`
}

func (q *Queries) GetContentRankingSnapshot(ctx context.Context, arg GetContentRankingSnapshotParams) (ContentRankingSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getContentRankingSnapshot,
		arg.TenantID,
		arg.RankingKey,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.EntityType,
		arg.AlgorithmVersion,
	)
	var i ContentRankingSnapshot
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RankingKey,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.EntityType,
		&i.Items,
		&i.AlgorithmVersion,
		&i.ComputedAt,
	)
	return i, err
}

const getItemRecommendFeatures = `-- name: GetItemRecommendFeatures :one
SELECT tenant_id, entity_type, entity_id, features, feature_version, computed_at
FROM item_recommend_features
WHERE tenant_id = $1
    AND entity_type = $2
    AND entity_id = $3
`

type GetItemRecommendFeaturesParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
}

func (q *Queries) GetItemRecommendFeatures(ctx context.Context, arg GetItemRecommendFeaturesParams) (ItemRecommendFeature, error) {
	row := q.db.QueryRowContext(ctx, getItemRecommendFeatures, arg.TenantID, arg.EntityType, arg.EntityID)
	var i ItemRecommendFeature
	err := row.Scan(
		&i.TenantID,
		&i.EntityType,
		&i.EntityID,
		&i.Features,
		&i.FeatureVersion,
		&i.ComputedAt,
	)
	return i, err
}

const getUserRecommendFeatures = `-- name: GetUserRecommendFeatures :one
SELECT tenant_id, user_id, features, feature_version, computed_at
FROM user_recommend_features
WHERE tenant_id = $1
    AND user_id = $2
`

type GetUserRecommendFeaturesParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) GetUserRecommendFeatures(ctx context.Context, arg GetUserRecommendFeaturesParams) (UserRecommendFeature, error) {
	row := q.db.QueryRowContext(ctx, getUserRecommendFeatures, arg.TenantID, arg.UserID)
	var i UserRecommendFeature
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Features,
		&i.FeatureVersion,
		&i.ComputedAt,
	)
	return i, err
}

const insertContentEvent = `-- name: InsertContentEvent :one

INSERT INTO content_events (
    id,
    tenant_id,
    event_type,
    user_id,
    anonymous_id,
    series_id,
    episode_id,
    debounce_bucket,
    rating_score,
    source_table,
    source_id,
    payload,
    occurred_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
RETURNING id, tenant_id, event_type, user_id, anonymous_id, actor_key, series_id, episode_id, debounce_bucket, rating_score, source_table, source_id, payload, occurred_at, created_at
`

type InsertContentEventParams struct {
	ID             uuid.UUID       `json:"id"`
	TenantID       uuid.UUID       `json:"tenant_id"`
	EventType      string          `json:"event_type"`
	UserID         uuid.NullUUID   `json:"user_id"`
	AnonymousID    uuid.NullUUID   `json:"anonymous_id"`
	SeriesID       uuid.NullUUID   `json:"series_id"`
	EpisodeID      uuid.NullUUID   `json:"episode_id"`
	DebounceBucket sql.NullInt64   `json:"debounce_bucket"`
	RatingScore    sql.NullInt16   `json:"rating_score"`
	SourceTable    sql.NullString  `json:"source_table"`
	SourceID       uuid.NullUUID   `json:"source_id"`
	Payload        json.RawMessage `json:"payload"`
	OccurredAt     time.Time       `json:"occurred_at"`
}

// Engagement / recommend query skeleton (#589).
// Later issues fill handlers and batches; these queries pin the index-backed
// shapes so sqlc generates now and EXPLAIN stays checkable.
//
// Expected plans (empty table may still seq-scan; SET enable_seqscan = off
// in the integration test to confirm the index is eligible):
//
//	ListContentEventsByTenantOccurredAt
//	  -> idx_content_events_tenant_occurred_at
//	ListContentEventsByTenantTypeOccurredAt
//	  -> idx_content_events_tenant_type_occurred_at
//	GetContentDailyStatsByEntity
//	  -> idx_content_daily_stats_unique / idx_content_daily_stats_tenant_entity
//	GetContentRankingSnapshot
//	  -> idx_content_ranking_snapshots_unique
//	InsertDebouncedEpisodeViewEvent
//	  -> idx_content_events_episode_view_debounce
//	InsertProjectedSourceEvent
//	  -> idx_content_events_source_unique
//	ListLatestContentRatingsByEntity
//	  -> idx_content_events_tenant_series_occurred_at
func (q *Queries) InsertContentEvent(ctx context.Context, arg InsertContentEventParams) (ContentEvent, error) {
	row := q.db.QueryRowContext(ctx, insertContentEvent,
		arg.ID,
		arg.TenantID,
		arg.EventType,
		arg.UserID,
		arg.AnonymousID,
		arg.SeriesID,
		arg.EpisodeID,
		arg.DebounceBucket,
		arg.RatingScore,
		arg.SourceTable,
		arg.SourceID,
		arg.Payload,
		arg.OccurredAt,
	)
	var i ContentEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.UserID,
		&i.AnonymousID,
		&i.ActorKey,
		&i.SeriesID,
		&i.EpisodeID,
		&i.DebounceBucket,
		&i.RatingScore,
		&i.SourceTable,
		&i.SourceID,
		&i.Payload,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertDebouncedEpisodeViewEvent = `-- name: InsertDebouncedEpisodeViewEvent :one
INSERT INTO content_events (
    id,
    tenant_id,
    event_type,
    user_id,
    anonymous_id,
    series_id,
    episode_id,
    debounce_bucket,
    payload,
    occurred_at
) VALUES (
    $1,
    $2,
    'episode_view',
    $3,
    $4,
    $5::uuid,
    $6::uuid,
    $7::bigint,
    $8,
    $9
)
ON CONFLICT (tenant_id, event_type, episode_id, actor_key, debounce_bucket)
WHERE event_type = 'episode_view'
DO NOTHING
RETURNING id, tenant_id, event_type, user_id, anonymous_id, actor_key, series_id, episode_id, debounce_bucket, rating_score, source_table, source_id, payload, occurred_at, created_at
`

type InsertDebouncedEpisodeViewEventParams struct {
	ID             uuid.UUID       `json:"id"`
	TenantID       uuid.UUID       `json:"tenant_id"`
	UserID         uuid.NullUUID   `json:"user_id"`
	AnonymousID    uuid.NullUUID   `json:"anonymous_id"`
	SeriesID       uuid.UUID       `json:"series_id"`
	EpisodeID      uuid.UUID       `json:"episode_id"`
	DebounceBucket int64           `json:"debounce_bucket"`
	Payload        json.RawMessage `json:"payload"`
	OccurredAt     time.Time       `json:"occurred_at"`
}

// Fixed 30-minute epoch bucket. Same actor + episode + bucket is a no-op.
// :one returns no rows on conflict (same as CreateNotification).
func (q *Queries) InsertDebouncedEpisodeViewEvent(ctx context.Context, arg InsertDebouncedEpisodeViewEventParams) (ContentEvent, error) {
	row := q.db.QueryRowContext(ctx, insertDebouncedEpisodeViewEvent,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.AnonymousID,
		arg.SeriesID,
		arg.EpisodeID,
		arg.DebounceBucket,
		arg.Payload,
		arg.OccurredAt,
	)
	var i ContentEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.UserID,
		&i.AnonymousID,
		&i.ActorKey,
		&i.SeriesID,
		&i.EpisodeID,
		&i.DebounceBucket,
		&i.RatingScore,
		&i.SourceTable,
		&i.SourceID,
		&i.Payload,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertDebouncedSeriesViewEvent = `-- name: InsertDebouncedSeriesViewEvent :one
INSERT INTO content_events (
    id,
    tenant_id,
    event_type,
    user_id,
    anonymous_id,
    series_id,
    debounce_bucket,
    payload,
    occurred_at
) VALUES (
    $1,
    $2,
    'series_view',
    $3,
    $4,
    $5::uuid,
    $6::bigint,
    $7,
    $8
)
ON CONFLICT (tenant_id, event_type, series_id, actor_key, debounce_bucket)
WHERE event_type = 'series_view'
DO NOTHING
RETURNING id, tenant_id, event_type, user_id, anonymous_id, actor_key, series_id, episode_id, debounce_bucket, rating_score, source_table, source_id, payload, occurred_at, created_at
`

type InsertDebouncedSeriesViewEventParams struct {
	ID             uuid.UUID       `json:"id"`
	TenantID       uuid.UUID       `json:"tenant_id"`
	UserID         uuid.NullUUID   `json:"user_id"`
	AnonymousID    uuid.NullUUID   `json:"anonymous_id"`
	SeriesID       uuid.UUID       `json:"series_id"`
	DebounceBucket int64           `json:"debounce_bucket"`
	Payload        json.RawMessage `json:"payload"`
	OccurredAt     time.Time       `json:"occurred_at"`
}

func (q *Queries) InsertDebouncedSeriesViewEvent(ctx context.Context, arg InsertDebouncedSeriesViewEventParams) (ContentEvent, error) {
	row := q.db.QueryRowContext(ctx, insertDebouncedSeriesViewEvent,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.AnonymousID,
		arg.SeriesID,
		arg.DebounceBucket,
		arg.Payload,
		arg.OccurredAt,
	)
	var i ContentEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.UserID,
		&i.AnonymousID,
		&i.ActorKey,
		&i.SeriesID,
		&i.EpisodeID,
		&i.DebounceBucket,
		&i.RatingScore,
		&i.SourceTable,
		&i.SourceID,
		&i.Payload,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertProjectedSourceEvent = `-- name: InsertProjectedSourceEvent :one
INSERT INTO content_events (
    id,
    tenant_id,
    event_type,
    user_id,
    series_id,
    episode_id,
    source_table,
    source_id,
    payload,
    occurred_at
) VALUES (
    $1,
    $2,
    $3,
    $4::uuid,
    $5::uuid,
    $6::uuid,
    $7::text,
    $8::uuid,
    $9,
    $10
)
ON CONFLICT (tenant_id, source_table, source_id)
WHERE source_id IS NOT NULL
DO NOTHING
RETURNING id, tenant_id, event_type, user_id, anonymous_id, actor_key, series_id, episode_id, debounce_bucket, rating_score, source_table, source_id, payload, occurred_at, created_at
`

type InsertProjectedSourceEventParams struct {
	ID          uuid.UUID       `json:"id"`
	TenantID    uuid.UUID       `json:"tenant_id"`
	EventType   string          `json:"event_type"`
	UserID      uuid.UUID       `json:"user_id"`
	SeriesID    uuid.UUID       `json:"series_id"`
	EpisodeID   uuid.UUID       `json:"episode_id"`
	SourceTable string          `json:"source_table"`
	SourceID    uuid.UUID       `json:"source_id"`
	Payload     json.RawMessage `json:"payload"`
	OccurredAt  time.Time       `json:"occurred_at"`
}

// Idempotent projection from a SoT row (purchases.id, access_tickets.id).
func (q *Queries) InsertProjectedSourceEvent(ctx context.Context, arg InsertProjectedSourceEventParams) (ContentEvent, error) {
	row := q.db.QueryRowContext(ctx, insertProjectedSourceEvent,
		arg.ID,
		arg.TenantID,
		arg.EventType,
		arg.UserID,
		arg.SeriesID,
		arg.EpisodeID,
		arg.SourceTable,
		arg.SourceID,
		arg.Payload,
		arg.OccurredAt,
	)
	var i ContentEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.UserID,
		&i.AnonymousID,
		&i.ActorKey,
		&i.SeriesID,
		&i.EpisodeID,
		&i.DebounceBucket,
		&i.RatingScore,
		&i.SourceTable,
		&i.SourceID,
		&i.Payload,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertRatingEvent = `-- name: InsertRatingEvent :one
INSERT INTO content_events (
    id,
    tenant_id,
    event_type,
    user_id,
    series_id,
    episode_id,
    rating_score,
    occurred_at
) VALUES (
    $1,
    $2,
    'rating',
    $3::uuid,
    $4::uuid,
    $5,
    $6::smallint,
    $7
)
RETURNING id, tenant_id, event_type, user_id, anonymous_id, actor_key, series_id, episode_id, debounce_bucket, rating_score, source_table, source_id, payload, occurred_at, created_at
`

type InsertRatingEventParams struct {
	ID          uuid.UUID     `json:"id"`
	TenantID    uuid.UUID     `json:"tenant_id"`
	UserID      uuid.UUID     `json:"user_id"`
	SeriesID    uuid.UUID     `json:"series_id"`
	EpisodeID   uuid.NullUUID `json:"episode_id"`
	RatingScore int16         `json:"rating_score"`
	OccurredAt  time.Time     `json:"occurred_at"`
}

// Ratings are append-only, like every other content_events row: a member who
// changes their score inserts another event instead of updating the previous
// one, so the history stays reconstructable and nothing has to be deleted.
// Which score "counts" is therefore a read-side decision, not a write-side one
// (see ListLatestContentRatingsByEntity). There is deliberately no debounce
// bucket here: a rating is an explicit act, not a page load.
//
// episode_id NULL rates the series itself; set, it rates that episode, and
// series_id must still be the episode's own series. Both are resolved by the
// server from the catalog row, never taken from client input.
func (q *Queries) InsertRatingEvent(ctx context.Context, arg InsertRatingEventParams) (ContentEvent, error) {
	row := q.db.QueryRowContext(ctx, insertRatingEvent,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.SeriesID,
		arg.EpisodeID,
		arg.RatingScore,
		arg.OccurredAt,
	)
	var i ContentEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.UserID,
		&i.AnonymousID,
		&i.ActorKey,
		&i.SeriesID,
		&i.EpisodeID,
		&i.DebounceBucket,
		&i.RatingScore,
		&i.SourceTable,
		&i.SourceID,
		&i.Payload,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listContentDailyStatsByTenantDate = `-- name: ListContentDailyStatsByTenantDate :many
SELECT id, tenant_id, stat_date, entity_type, entity_id, view_count, unique_viewer_count, purchase_count, rating_count, rating_sum, favorite_count, updated_at
FROM content_daily_stats
WHERE tenant_id = $1
    AND stat_date = $2
ORDER BY entity_type, entity_id
`

type ListContentDailyStatsByTenantDateParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	StatDate time.Time `json:"stat_date"`
}

func (q *Queries) ListContentDailyStatsByTenantDate(ctx context.Context, arg ListContentDailyStatsByTenantDateParams) ([]ContentDailyStat, error) {
	rows, err := q.db.QueryContext(ctx, listContentDailyStatsByTenantDate, arg.TenantID, arg.StatDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentDailyStat
	for rows.Next() {
		var i ContentDailyStat
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StatDate,
			&i.EntityType,
			&i.EntityID,
			&i.ViewCount,
			&i.UniqueViewerCount,
			&i.PurchaseCount,
			&i.RatingCount,
			&i.RatingSum,
			&i.FavoriteCount,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentEventsByTenantOccurredAt = `-- name: ListContentEventsByTenantOccurredAt :many
SELECT id, tenant_id, event_type, user_id, anonymous_id, actor_key, series_id, episode_id, debounce_bucket, rating_score, source_table, source_id, payload, occurred_at, created_at
FROM content_events
WHERE tenant_id = $1
ORDER BY occurred_at DESC
LIMIT $2
`

type ListContentEventsByTenantOccurredAtParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
}

// Representative tenant timeline. EXPLAIN: idx_content_events_tenant_occurred_at.
func (q *Queries) ListContentEventsByTenantOccurredAt(ctx context.Context, arg ListContentEventsByTenantOccurredAtParams) ([]ContentEvent, error) {
	rows, err := q.db.QueryContext(ctx, listContentEventsByTenantOccurredAt, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentEvent
	for rows.Next() {
		var i ContentEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventType,
			&i.UserID,
			&i.AnonymousID,
			&i.ActorKey,
			&i.SeriesID,
			&i.EpisodeID,
			&i.DebounceBucket,
			&i.RatingScore,
			&i.SourceTable,
			&i.SourceID,
			&i.Payload,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentEventsByTenantTypeOccurredAt = `-- name: ListContentEventsByTenantTypeOccurredAt :many
SELECT id, tenant_id, event_type, user_id, anonymous_id, actor_key, series_id, episode_id, debounce_bucket, rating_score, source_table, source_id, payload, occurred_at, created_at
FROM content_events
WHERE tenant_id = $1
    AND event_type = $2
ORDER BY occurred_at DESC
LIMIT $3
`

type ListContentEventsByTenantTypeOccurredAtParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	EventType string    `json:"event_type"`
	Limit     int32     `json:"limit"`
}

// Representative type-filtered timeline. EXPLAIN: idx_content_events_tenant_type_occurred_at.
func (q *Queries) ListContentEventsByTenantTypeOccurredAt(ctx context.Context, arg ListContentEventsByTenantTypeOccurredAtParams) ([]ContentEvent, error) {
	rows, err := q.db.QueryContext(ctx, listContentEventsByTenantTypeOccurredAt, arg.TenantID, arg.EventType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentEvent
	for rows.Next() {
		var i ContentEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventType,
			&i.UserID,
			&i.AnonymousID,
			&i.ActorKey,
			&i.SeriesID,
			&i.EpisodeID,
			&i.DebounceBucket,
			&i.RatingScore,
			&i.SourceTable,
			&i.SourceID,
			&i.Payload,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestContentRatingsByEntity = `-- name: ListLatestContentRatingsByEntity :many
SELECT DISTINCT ON (actor_key) actor_key,
    rating_score,
    occurred_at
FROM content_events
WHERE tenant_id = $1
    AND event_type = 'rating'
    AND series_id = $2::uuid
    AND episode_id IS NOT DISTINCT FROM $3::uuid
ORDER BY actor_key, occurred_at DESC, id DESC
`

type ListLatestContentRatingsByEntityParams struct {
	TenantID  uuid.UUID     `json:"tenant_id"`
	SeriesID  uuid.UUID     `json:"series_id"`
	EpisodeID uuid.NullUUID `json:"episode_id"`
}

type ListLatestContentRatingsByEntityRow struct {
	ActorKey    uuid.NullUUID `json:"actor_key"`
	RatingScore sql.NullInt16 `json:"rating_score"`
	OccurredAt  time.Time     `json:"occurred_at"`
}

// The latest rating each actor currently stands by for one entity: the stock
// view of an append-only log. `content_daily_stats.rating_count` /
// `rating_sum` (#593) are the *flow* of a single day and cannot answer this,
// because a member who rated 1 on Monday and 5 on Tuesday contributes to both
// days. A stock average has to come from this DISTINCT ON, over the full
// retained history, until a materialised current-rating table exists.
//
// The tie-break runs past occurred_at because two events from one actor can
// share a timestamp; id is UUIDv7, so the later insert wins.
func (q *Queries) ListLatestContentRatingsByEntity(ctx context.Context, arg ListLatestContentRatingsByEntityParams) ([]ListLatestContentRatingsByEntityRow, error) {
	rows, err := q.db.QueryContext(ctx, listLatestContentRatingsByEntity, arg.TenantID, arg.SeriesID, arg.EpisodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestContentRatingsByEntityRow
	for rows.Next() {
		var i ListLatestContentRatingsByEntityRow
		if err := rows.Scan(&i.ActorKey, &i.RatingScore, &i.OccurredAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectPurchaseContentEvent = `-- name: ProjectPurchaseContentEvent :one
INSERT INTO content_events (
    id,
    tenant_id,
    event_type,
    user_id,
    series_id,
    episode_id,
    source_table,
    source_id,
    payload,
    occurred_at
)
SELECT
    $1,
    p.tenant_id,
    'purchase',
    p.user_id,
    e.series_id,
    p.episode_id,
    'purchases',
    p.id,
    '{}'::jsonb,
    p.purchased_at
FROM purchases p
JOIN episodes e
    ON e.tenant_id = p.tenant_id
    AND e.id = p.episode_id
WHERE p.tenant_id = $2
    AND p.stripe_checkout_session_id = $3::text
ON CONFLICT (tenant_id, source_table, source_id)
WHERE source_id IS NOT NULL
DO NOTHING
RETURNING id, tenant_id, event_type, user_id, anonymous_id, actor_key, series_id, episode_id, debounce_bucket, rating_score, source_table, source_id, payload, occurred_at, created_at
`

type ProjectPurchaseContentEventParams struct {
	ID                      uuid.UUID `json:"id"`
	TenantID                uuid.UUID `json:"tenant_id"`
	StripeCheckoutSessionID string    `json:"stripe_checkout_session_id"`
}

// Projects the Stripe-confirmed purchase without trusting webhook metadata for
// the actor or content target. purchases stays the source of truth: its user
// is copied directly and the episode resolves its owning series. A retry is a
// no-op after the source unique index has accepted the first event.
//
// The Phase 0 daily purchase aggregate reads purchases directly. Do not mix
// this projection into that aggregate until its source contract moves to
// content_events, or purchases will be counted twice.
func (q *Queries) ProjectPurchaseContentEvent(ctx context.Context, arg ProjectPurchaseContentEventParams) (ContentEvent, error) {
	row := q.db.QueryRowContext(ctx, projectPurchaseContentEvent, arg.ID, arg.TenantID, arg.StripeCheckoutSessionID)
	var i ContentEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.UserID,
		&i.AnonymousID,
		&i.ActorKey,
		&i.SeriesID,
		&i.EpisodeID,
		&i.DebounceBucket,
		&i.RatingScore,
		&i.SourceTable,
		&i.SourceID,
		&i.Payload,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertContentDailyStats = `-- name: UpsertContentDailyStats :one
INSERT INTO content_daily_stats (
    id,
    tenant_id,
    stat_date,
    entity_type,
    entity_id,
    view_count,
    unique_viewer_count,
    purchase_count,
    rating_count,
    rating_sum,
    favorite_count
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
ON CONFLICT (tenant_id, stat_date, entity_type, entity_id) DO UPDATE
SET view_count = EXCLUDED.view_count,
    unique_viewer_count = EXCLUDED.unique_viewer_count,
    purchase_count = EXCLUDED.purchase_count,
    rating_count = EXCLUDED.rating_count,
    rating_sum = EXCLUDED.rating_sum,
    favorite_count = EXCLUDED.favorite_count,
    updated_at = NOW()
RETURNING id, tenant_id, stat_date, entity_type, entity_id, view_count, unique_viewer_count, purchase_count, rating_count, rating_sum, favorite_count, updated_at
`

type UpsertContentDailyStatsParams struct {
	ID                uuid.UUID `json:"id"`
	TenantID          uuid.UUID `json:"tenant_id"`
	StatDate          time.Time `json:"stat_date"`
	EntityType        string    `json:"entity_type"`
	EntityID          uuid.UUID `json:"entity_id"`
	ViewCount         int64     `json:"view_count"`
	UniqueViewerCount int64     `json:"unique_viewer_count"`
	PurchaseCount     int64     `json:"purchase_count"`
	RatingCount       int64     `json:"rating_count"`
	RatingSum         int64     `json:"rating_sum"`
	FavoriteCount     int64     `json:"favorite_count"`
}

// Daily stats are full-day replacements (#593). Upsert keeps a single row per
// (tenant, date, entity). rating_count / rating_sum are that day's flow — the
// rating events that occurred on stat_date — and not a stock average: a member
// who re-rates is counted on both days, and a member who never re-rates is
// counted on neither day after the first. Summing rating_sum / rating_count
// across a date range therefore averages ratings *given* in that range, not
// the ratings an item currently holds (ListLatestContentRatingsByEntity).
func (q *Queries) UpsertContentDailyStats(ctx context.Context, arg UpsertContentDailyStatsParams) (ContentDailyStat, error) {
	row := q.db.QueryRowContext(ctx, upsertContentDailyStats,
		arg.ID,
		arg.TenantID,
		arg.StatDate,
		arg.EntityType,
		arg.EntityID,
		arg.ViewCount,
		arg.UniqueViewerCount,
		arg.PurchaseCount,
		arg.RatingCount,
		arg.RatingSum,
		arg.FavoriteCount,
	)
	var i ContentDailyStat
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StatDate,
		&i.EntityType,
		&i.EntityID,
		&i.ViewCount,
		&i.UniqueViewerCount,
		&i.PurchaseCount,
		&i.RatingCount,
		&i.RatingSum,
		&i.FavoriteCount,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertContentRankingSnapshot = `-- name: UpsertContentRankingSnapshot :one
INSERT INTO content_ranking_snapshots (
    id,
    tenant_id,
    ranking_key,
    period_start,
    period_end,
    entity_type,
    items,
    algorithm_version,
    computed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
ON CONFLICT (tenant_id, ranking_key, period_start, period_end, entity_type, algorithm_version) DO UPDATE
SET items = EXCLUDED.items,
    computed_at = EXCLUDED.computed_at
RETURNING id, tenant_id, ranking_key, period_start, period_end, entity_type, items, algorithm_version, computed_at
`

type UpsertContentRankingSnapshotParams struct {
	ID               uuid.UUID       `json:"id"`
	TenantID         uuid.UUID       `json:"tenant_id"`
	RankingKey       string          `json:"ranking_key"`
	PeriodStart      time.Time       `json:"period_start"`
	PeriodEnd        time.Time       `json:"period_end"`
	EntityType       string          `json:"entity_type"`
	Items            json.RawMessage `json:"items"`
	AlgorithmVersion int32           `json:"algorithm_version"`
	ComputedAt       time.Time       `json:"computed_at"`
}

func (q *Queries) UpsertContentRankingSnapshot(ctx context.Context, arg UpsertContentRankingSnapshotParams) (ContentRankingSnapshot, error) {
	row := q.db.QueryRowContext(ctx, upsertContentRankingSnapshot,
		arg.ID,
		arg.TenantID,
		arg.RankingKey,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.EntityType,
		arg.Items,
		arg.AlgorithmVersion,
		arg.ComputedAt,
	)
	var i ContentRankingSnapshot
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RankingKey,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.EntityType,
		&i.Items,
		&i.AlgorithmVersion,
		&i.ComputedAt,
	)
	return i, err
}

const upsertItemRecommendFeatures = `-- name: UpsertItemRecommendFeatures :one
INSERT INTO item_recommend_features (
    tenant_id,
    entity_type,
    entity_id,
    features,
    feature_version,
    computed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (tenant_id, entity_type, entity_id) DO UPDATE
SET features = EXCLUDED.features,
    feature_version = EXCLUDED.feature_version,
    computed_at = EXCLUDED.computed_at
RETURNING tenant_id, entity_type, entity_id, features, feature_version, computed_at
`

type UpsertItemRecommendFeaturesParams struct {
	TenantID       uuid.UUID       `json:"tenant_id"`
	EntityType     string          `json:"entity_type"`
	EntityID       uuid.UUID       `json:"entity_id"`
	Features       json.RawMessage `json:"features"`
	FeatureVersion int32           `json:"feature_version"`
	ComputedAt     time.Time       `json:"computed_at"`
}

func (q *Queries) UpsertItemRecommendFeatures(ctx context.Context, arg UpsertItemRecommendFeaturesParams) (ItemRecommendFeature, error) {
	row := q.db.QueryRowContext(ctx, upsertItemRecommendFeatures,
		arg.TenantID,
		arg.EntityType,
		arg.EntityID,
		arg.Features,
		arg.FeatureVersion,
		arg.ComputedAt,
	)
	var i ItemRecommendFeature
	err := row.Scan(
		&i.TenantID,
		&i.EntityType,
		&i.EntityID,
		&i.Features,
		&i.FeatureVersion,
		&i.ComputedAt,
	)
	return i, err
}

const upsertUserRecommendFeatures = `-- name: UpsertUserRecommendFeatures :one
INSERT INTO user_recommend_features (
    tenant_id,
    user_id,
    features,
    feature_version,
    computed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (tenant_id, user_id) DO UPDATE
SET features = EXCLUDED.features,
    feature_version = EXCLUDED.feature_version,
    computed_at = EXCLUDED.computed_at
RETURNING tenant_id, user_id, features, feature_version, computed_at
`

type UpsertUserRecommendFeaturesParams struct {
	TenantID       uuid.UUID       `json:"tenant_id"`
	UserID         uuid.UUID       `json:"user_id"`
	Features       json.RawMessage `json:"features"`
	FeatureVersion int32           `json:"feature_version"`
	ComputedAt     time.Time       `json:"computed_at"`
}

func (q *Queries) UpsertUserRecommendFeatures(ctx context.Context, arg UpsertUserRecommendFeaturesParams) (UserRecommendFeature, error) {
	row := q.db.QueryRowContext(ctx, upsertUserRecommendFeatures,
		arg.TenantID,
		arg.UserID,
		arg.Features,
		arg.FeatureVersion,
		arg.ComputedAt,
	)
	var i UserRecommendFeature
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Features,
		&i.FeatureVersion,
		&i.ComputedAt,
	)
	return i, err
}
