// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: follow.sql

package dbmodels

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createCreatorFollow = `-- name: CreateCreatorFollow :one
INSERT INTO creator_follows (tenant_id, user_id, creator_id)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (tenant_id, user_id, creator_id) DO NOTHING
RETURNING tenant_id, user_id, creator_id, created_at
`

type CreateCreatorFollowParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatorID uuid.UUID `json:"creator_id"`
}

func (q *Queries) CreateCreatorFollow(ctx context.Context, arg CreateCreatorFollowParams) (CreatorFollow, error) {
	row := q.db.QueryRowContext(ctx, createCreatorFollow, arg.TenantID, arg.UserID, arg.CreatorID)
	var i CreatorFollow
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.CreatorID,
		&i.CreatedAt,
	)
	return i, err
}

const createEpisodeFollow = `-- name: CreateEpisodeFollow :one

INSERT INTO episode_follows (tenant_id, user_id, episode_id)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (tenant_id, user_id, episode_id) DO NOTHING
RETURNING tenant_id, user_id, episode_id, created_at
`

type CreateEpisodeFollowParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	UserID    uuid.UUID `json:"user_id"`
	EpisodeID uuid.UUID `json:"episode_id"`
}

// Durable member follows (#1128). Episode and creator follows have distinct
// source tables; content_events must not be used to model either relation.
func (q *Queries) CreateEpisodeFollow(ctx context.Context, arg CreateEpisodeFollowParams) (EpisodeFollow, error) {
	row := q.db.QueryRowContext(ctx, createEpisodeFollow, arg.TenantID, arg.UserID, arg.EpisodeID)
	var i EpisodeFollow
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.EpisodeID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCreatorFollow = `-- name: DeleteCreatorFollow :execrows
DELETE FROM creator_follows
WHERE tenant_id = $1
    AND user_id = $2
    AND creator_id = $3
`

type DeleteCreatorFollowParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatorID uuid.UUID `json:"creator_id"`
}

func (q *Queries) DeleteCreatorFollow(ctx context.Context, arg DeleteCreatorFollowParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCreatorFollow, arg.TenantID, arg.UserID, arg.CreatorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteEpisodeFollow = `-- name: DeleteEpisodeFollow :execrows
DELETE FROM episode_follows
WHERE tenant_id = $1
    AND user_id = $2
    AND episode_id = $3
`

type DeleteEpisodeFollowParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	UserID    uuid.UUID `json:"user_id"`
	EpisodeID uuid.UUID `json:"episode_id"`
}

func (q *Queries) DeleteEpisodeFollow(ctx context.Context, arg DeleteEpisodeFollowParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEpisodeFollow, arg.TenantID, arg.UserID, arg.EpisodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listPublishedCreatorFollowTargetPublicIDsByIDs = `-- name: ListPublishedCreatorFollowTargetPublicIDsByIDs :many
SELECT c.id,
    c.public_id
FROM creators c
WHERE c.tenant_id = $1
    AND c.id = ANY($2::uuid [])
    AND EXISTS (
        SELECT 1
        FROM series_creators sc
            JOIN series s ON s.id = sc.series_id
        WHERE sc.tenant_id = c.tenant_id
            AND sc.creator_id = c.id
            AND s.tenant_id = c.tenant_id
            AND s.is_published = true
            AND s.published_at IS NOT NULL
            AND s.published_at <= NOW()
    )
`

type ListPublishedCreatorFollowTargetPublicIDsByIDsParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Ids      []uuid.UUID `json:"ids"`
}

type ListPublishedCreatorFollowTargetPublicIDsByIDsRow struct {
	ID       uuid.UUID `json:"id"`
	PublicID string    `json:"public_id"`
}

func (q *Queries) ListPublishedCreatorFollowTargetPublicIDsByIDs(ctx context.Context, arg ListPublishedCreatorFollowTargetPublicIDsByIDsParams) ([]ListPublishedCreatorFollowTargetPublicIDsByIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedCreatorFollowTargetPublicIDsByIDs, arg.TenantID, pq.Array(arg.Ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedCreatorFollowTargetPublicIDsByIDsRow
	for rows.Next() {
		var i ListPublishedCreatorFollowTargetPublicIDsByIDsRow
		if err := rows.Scan(&i.ID, &i.PublicID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedEpisodeFollowTargetPublicIDsByIDs = `-- name: ListPublishedEpisodeFollowTargetPublicIDsByIDs :many
SELECT e.id,
    e.public_id
FROM episodes e
    JOIN series s ON s.tenant_id = e.tenant_id
        AND s.id = e.series_id
    JOIN episode_listings el ON el.tenant_id = e.tenant_id
        AND el.episode_id = e.id
WHERE e.tenant_id = $1
    AND e.id = ANY($2::uuid [])
    AND s.is_published = true
    AND s.published_at IS NOT NULL
    AND s.published_at <= NOW()
    AND el.status = 'published'
    AND el.published_at IS NOT NULL
    AND el.published_at <= NOW()
`

type ListPublishedEpisodeFollowTargetPublicIDsByIDsParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Ids      []uuid.UUID `json:"ids"`
}

type ListPublishedEpisodeFollowTargetPublicIDsByIDsRow struct {
	ID       uuid.UUID `json:"id"`
	PublicID string    `json:"public_id"`
}

// These projections are used only while constructing the public Follow API
// response. The follow relations and their cursor queries remain UUID-only.
func (q *Queries) ListPublishedEpisodeFollowTargetPublicIDsByIDs(ctx context.Context, arg ListPublishedEpisodeFollowTargetPublicIDsByIDsParams) ([]ListPublishedEpisodeFollowTargetPublicIDsByIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedEpisodeFollowTargetPublicIDsByIDs, arg.TenantID, pq.Array(arg.Ids))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedEpisodeFollowTargetPublicIDsByIDsRow
	for rows.Next() {
		var i ListPublishedEpisodeFollowTargetPublicIDsByIDsRow
		if err := rows.Scan(&i.ID, &i.PublicID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserFollowsByCreatedAtAsc = `-- name: ListUserFollowsByCreatedAtAsc :many
SELECT target_type,
    target_id,
    created_at
FROM (
    SELECT 'episode'::text AS target_type,
        ef.episode_id AS target_id,
        ef.created_at
    FROM episode_follows ef
        JOIN episodes e ON e.tenant_id = ef.tenant_id
            AND e.id = ef.episode_id
        JOIN series s ON s.tenant_id = e.tenant_id
            AND s.id = e.series_id
        JOIN episode_listings el ON el.tenant_id = e.tenant_id
            AND el.episode_id = e.id
    WHERE ef.tenant_id = $1
        AND ef.user_id = $2
        AND s.is_published = true
        AND s.published_at IS NOT NULL
        AND s.published_at <= NOW()
        AND el.status = 'published'
        AND el.published_at IS NOT NULL
        AND el.published_at <= NOW()
    UNION ALL
    SELECT 'creator'::text AS target_type,
        cf.creator_id AS target_id,
        cf.created_at
    FROM creator_follows cf
        JOIN creators c ON c.tenant_id = cf.tenant_id
            AND c.id = cf.creator_id
    WHERE cf.tenant_id = $1
        AND cf.user_id = $2
        AND EXISTS (
            SELECT 1
            FROM series_creators sc
                JOIN series s ON s.id = sc.series_id
            WHERE sc.tenant_id = c.tenant_id
                AND sc.creator_id = c.id
                AND s.tenant_id = c.tenant_id
                AND s.is_published = true
                AND s.published_at IS NOT NULL
                AND s.published_at <= NOW()
        )
) AS follows
WHERE $3::timestamptz IS NULL
    OR (
        $4::boolean
        AND (created_at, target_type, target_id) >= (
            $3::timestamptz,
            $5::text,
            $6::uuid
        )
    )
    OR (
        NOT $4::boolean
        AND (created_at, target_type, target_id) > (
            $3::timestamptz,
            $5::text,
            $6::uuid
        )
    )
ORDER BY created_at ASC,
    target_type DESC,
    target_id DESC
LIMIT $7
`

type ListUserFollowsByCreatedAtAscParams struct {
	TenantID         uuid.UUID      `json:"tenant_id"`
	UserID           uuid.UUID      `json:"user_id"`
	CursorCreatedAt  sql.NullTime   `json:"cursor_created_at"`
	CursorInclusive  bool           `json:"cursor_inclusive"`
	CursorTargetType sql.NullString `json:"cursor_target_type"`
	CursorTargetID   uuid.NullUUID  `json:"cursor_target_id"`
	Limit            int32          `json:"limit"`
}

type ListUserFollowsByCreatedAtAscRow struct {
	TargetType string    `json:"target_type"`
	TargetID   uuid.UUID `json:"target_id"`
	CreatedAt  time.Time `json:"created_at"`
}

// The previous-page half of ListUserFollowsByCreatedAtDesc. The handler reverses
// the returned rows to preserve the public newest-first display order.
func (q *Queries) ListUserFollowsByCreatedAtAsc(ctx context.Context, arg ListUserFollowsByCreatedAtAscParams) ([]ListUserFollowsByCreatedAtAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserFollowsByCreatedAtAsc,
		arg.TenantID,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorInclusive,
		arg.CursorTargetType,
		arg.CursorTargetID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserFollowsByCreatedAtAscRow
	for rows.Next() {
		var i ListUserFollowsByCreatedAtAscRow
		if err := rows.Scan(&i.TargetType, &i.TargetID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserFollowsByCreatedAtDesc = `-- name: ListUserFollowsByCreatedAtDesc :many
SELECT target_type,
    target_id,
    created_at
FROM (
    SELECT 'episode'::text AS target_type,
        ef.episode_id AS target_id,
        ef.created_at
    FROM episode_follows ef
        JOIN episodes e ON e.tenant_id = ef.tenant_id
            AND e.id = ef.episode_id
        JOIN series s ON s.tenant_id = e.tenant_id
            AND s.id = e.series_id
        JOIN episode_listings el ON el.tenant_id = e.tenant_id
            AND el.episode_id = e.id
    WHERE ef.tenant_id = $1
        AND ef.user_id = $2
        AND s.is_published = true
        AND s.published_at IS NOT NULL
        AND s.published_at <= NOW()
        AND el.status = 'published'
        AND el.published_at IS NOT NULL
        AND el.published_at <= NOW()
    UNION ALL
    SELECT 'creator'::text AS target_type,
        cf.creator_id AS target_id,
        cf.created_at
    FROM creator_follows cf
        JOIN creators c ON c.tenant_id = cf.tenant_id
            AND c.id = cf.creator_id
    WHERE cf.tenant_id = $1
        AND cf.user_id = $2
        AND EXISTS (
            SELECT 1
            FROM series_creators sc
                JOIN series s ON s.id = sc.series_id
            WHERE sc.tenant_id = c.tenant_id
                AND sc.creator_id = c.id
                AND s.tenant_id = c.tenant_id
                AND s.is_published = true
                AND s.published_at IS NOT NULL
                AND s.published_at <= NOW()
        )
) AS follows
WHERE $3::timestamptz IS NULL
    OR (
        $4::boolean
        AND (created_at, target_type, target_id) <= (
            $3::timestamptz,
            $5::text,
            $6::uuid
        )
    )
    OR (
        NOT $4::boolean
        AND (created_at, target_type, target_id) < (
            $3::timestamptz,
            $5::text,
            $6::uuid
        )
    )
ORDER BY created_at DESC,
    target_type ASC,
    target_id ASC
LIMIT $7
`

type ListUserFollowsByCreatedAtDescParams struct {
	TenantID         uuid.UUID      `json:"tenant_id"`
	UserID           uuid.UUID      `json:"user_id"`
	CursorCreatedAt  sql.NullTime   `json:"cursor_created_at"`
	CursorInclusive  bool           `json:"cursor_inclusive"`
	CursorTargetType sql.NullString `json:"cursor_target_type"`
	CursorTargetID   uuid.NullUUID  `json:"cursor_target_id"`
	Limit            int32          `json:"limit"`
}

type ListUserFollowsByCreatedAtDescRow struct {
	TargetType string    `json:"target_type"`
	TargetID   uuid.UUID `json:"target_id"`
	CreatedAt  time.Time `json:"created_at"`
}

// The API can expose one timeline while keeping each relationship's storage
// and future aggregates independent. Public joins make a target that is no
// longer visible disappear from this member's list without revealing why.
func (q *Queries) ListUserFollowsByCreatedAtDesc(ctx context.Context, arg ListUserFollowsByCreatedAtDescParams) ([]ListUserFollowsByCreatedAtDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserFollowsByCreatedAtDesc,
		arg.TenantID,
		arg.UserID,
		arg.CursorCreatedAt,
		arg.CursorInclusive,
		arg.CursorTargetType,
		arg.CursorTargetID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserFollowsByCreatedAtDescRow
	for rows.Next() {
		var i ListUserFollowsByCreatedAtDescRow
		if err := rows.Scan(&i.TargetType, &i.TargetID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userFollowsPublishedCreator = `-- name: UserFollowsPublishedCreator :one
SELECT EXISTS (
    SELECT 1
    FROM creator_follows cf
        JOIN creators c ON c.tenant_id = cf.tenant_id
            AND c.id = cf.creator_id
    WHERE cf.tenant_id = $1
        AND cf.user_id = $2
        AND cf.creator_id = $3
        AND EXISTS (
            SELECT 1
            FROM series_creators sc
                JOIN series s ON s.id = sc.series_id
            WHERE sc.tenant_id = c.tenant_id
                AND sc.creator_id = c.id
                AND s.tenant_id = c.tenant_id
                AND s.is_published = true
                AND s.published_at IS NOT NULL
                AND s.published_at <= NOW()
        )
) AS follows_published_creator
`

type UserFollowsPublishedCreatorParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatorID uuid.UUID `json:"creator_id"`
}

// Creators are public when they have at least one active series, matching
// GetPublishedAuthorByPublicID.
func (q *Queries) UserFollowsPublishedCreator(ctx context.Context, arg UserFollowsPublishedCreatorParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userFollowsPublishedCreator, arg.TenantID, arg.UserID, arg.CreatorID)
	var follows_published_creator bool
	err := row.Scan(&follows_published_creator)
	return follows_published_creator, err
}

const userFollowsPublishedEpisode = `-- name: UserFollowsPublishedEpisode :one
SELECT EXISTS (
    SELECT 1
    FROM episode_follows ef
        JOIN episodes e ON e.tenant_id = ef.tenant_id
            AND e.id = ef.episode_id
        JOIN series s ON s.tenant_id = e.tenant_id
            AND s.id = e.series_id
        JOIN episode_listings el ON el.tenant_id = e.tenant_id
            AND el.episode_id = e.id
    WHERE ef.tenant_id = $1
        AND ef.user_id = $2
        AND ef.episode_id = $3
        AND s.is_published = true
        AND s.published_at IS NOT NULL
        AND s.published_at <= NOW()
        AND el.status = 'published'
        AND el.published_at IS NOT NULL
        AND el.published_at <= NOW()
) AS follows_published_episode
`

type UserFollowsPublishedEpisodeParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	UserID    uuid.UUID `json:"user_id"`
	EpisodeID uuid.UUID `json:"episode_id"`
}

// Matches GetPublishedEpisodeByPublicIDForTenant, so a draft, scheduled, or
// otherwise non-public episode is indistinguishable from an unfollowed one.
func (q *Queries) UserFollowsPublishedEpisode(ctx context.Context, arg UserFollowsPublishedEpisodeParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userFollowsPublishedEpisode, arg.TenantID, arg.UserID, arg.EpisodeID)
	var follows_published_episode bool
	err := row.Scan(&follows_published_episode)
	return follows_published_episode, err
}
