// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: follow.sql

package dbmodels

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCreatorFollow = `-- name: CreateCreatorFollow :one
INSERT INTO creator_follows (tenant_id, user_id, creator_id)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (tenant_id, user_id, creator_id) DO NOTHING
RETURNING tenant_id, user_id, creator_id, created_at
`

type CreateCreatorFollowParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatorID uuid.UUID `json:"creator_id"`
}

func (q *Queries) CreateCreatorFollow(ctx context.Context, arg CreateCreatorFollowParams) (CreatorFollow, error) {
	row := q.db.QueryRowContext(ctx, createCreatorFollow, arg.TenantID, arg.UserID, arg.CreatorID)
	var i CreatorFollow
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.CreatorID,
		&i.CreatedAt,
	)
	return i, err
}

const createEpisodeFollow = `-- name: CreateEpisodeFollow :one

INSERT INTO episode_follows (tenant_id, user_id, episode_id)
VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (tenant_id, user_id, episode_id) DO NOTHING
RETURNING tenant_id, user_id, episode_id, created_at
`

type CreateEpisodeFollowParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	UserID    uuid.UUID `json:"user_id"`
	EpisodeID uuid.UUID `json:"episode_id"`
}

// Durable member follows (#1128). Episode and creator follows have distinct
// source tables; content_events must not be used to model either relation.
func (q *Queries) CreateEpisodeFollow(ctx context.Context, arg CreateEpisodeFollowParams) (EpisodeFollow, error) {
	row := q.db.QueryRowContext(ctx, createEpisodeFollow, arg.TenantID, arg.UserID, arg.EpisodeID)
	var i EpisodeFollow
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.EpisodeID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCreatorFollow = `-- name: DeleteCreatorFollow :execrows
DELETE FROM creator_follows
WHERE tenant_id = $1
    AND user_id = $2
    AND creator_id = $3
`

type DeleteCreatorFollowParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatorID uuid.UUID `json:"creator_id"`
}

func (q *Queries) DeleteCreatorFollow(ctx context.Context, arg DeleteCreatorFollowParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCreatorFollow, arg.TenantID, arg.UserID, arg.CreatorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteEpisodeFollow = `-- name: DeleteEpisodeFollow :execrows
DELETE FROM episode_follows
WHERE tenant_id = $1
    AND user_id = $2
    AND episode_id = $3
`

type DeleteEpisodeFollowParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	UserID    uuid.UUID `json:"user_id"`
	EpisodeID uuid.UUID `json:"episode_id"`
}

func (q *Queries) DeleteEpisodeFollow(ctx context.Context, arg DeleteEpisodeFollowParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEpisodeFollow, arg.TenantID, arg.UserID, arg.EpisodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listUserFollowsByCreatedAtDesc = `-- name: ListUserFollowsByCreatedAtDesc :many
SELECT target_type,
    target_id,
    created_at
FROM (
    SELECT 'episode'::text AS target_type,
        episode_id AS target_id,
        created_at
    FROM episode_follows ef
    WHERE ef.tenant_id = $1
        AND ef.user_id = $2
    UNION ALL
    SELECT 'creator'::text AS target_type,
        creator_id AS target_id,
        created_at
    FROM creator_follows cf
    WHERE cf.tenant_id = $1
        AND cf.user_id = $2
) follows
ORDER BY created_at DESC,
    target_type ASC,
    target_id ASC
LIMIT $3
`

type ListUserFollowsByCreatedAtDescParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
	Limit    int32     `json:"limit"`
}

type ListUserFollowsByCreatedAtDescRow struct {
	TargetType string    `json:"target_type"`
	TargetID   uuid.UUID `json:"target_id"`
	CreatedAt  time.Time `json:"created_at"`
}

// The API can expose one timeline while keeping each relationship's storage
// and future aggregates independent. The full sort key is stable for cursors.
func (q *Queries) ListUserFollowsByCreatedAtDesc(ctx context.Context, arg ListUserFollowsByCreatedAtDescParams) ([]ListUserFollowsByCreatedAtDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserFollowsByCreatedAtDesc, arg.TenantID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserFollowsByCreatedAtDescRow
	for rows.Next() {
		var i ListUserFollowsByCreatedAtDescRow
		if err := rows.Scan(&i.TargetType, &i.TargetID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userFollowsPublishedCreator = `-- name: UserFollowsPublishedCreator :one
SELECT EXISTS (
    SELECT 1
    FROM creator_follows cf
        JOIN creators c ON c.tenant_id = cf.tenant_id
            AND c.id = cf.creator_id
    WHERE cf.tenant_id = $1
        AND cf.user_id = $2
        AND cf.creator_id = $3
        AND EXISTS (
            SELECT 1
            FROM series_creators sc
                JOIN series s ON s.id = sc.series_id
            WHERE sc.tenant_id = c.tenant_id
                AND sc.creator_id = c.id
                AND s.tenant_id = c.tenant_id
                AND s.is_published = true
                AND s.published_at IS NOT NULL
                AND s.published_at <= NOW()
        )
) AS follows_published_creator
`

type UserFollowsPublishedCreatorParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatorID uuid.UUID `json:"creator_id"`
}

// Creators are public when they have at least one active series, matching
// GetPublishedAuthorByPublicID.
func (q *Queries) UserFollowsPublishedCreator(ctx context.Context, arg UserFollowsPublishedCreatorParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userFollowsPublishedCreator, arg.TenantID, arg.UserID, arg.CreatorID)
	var follows_published_creator bool
	err := row.Scan(&follows_published_creator)
	return follows_published_creator, err
}

const userFollowsPublishedEpisode = `-- name: UserFollowsPublishedEpisode :one
SELECT EXISTS (
    SELECT 1
    FROM episode_follows ef
        JOIN episodes e ON e.tenant_id = ef.tenant_id
            AND e.id = ef.episode_id
        JOIN series s ON s.tenant_id = e.tenant_id
            AND s.id = e.series_id
        JOIN episode_listings el ON el.tenant_id = e.tenant_id
            AND el.episode_id = e.id
    WHERE ef.tenant_id = $1
        AND ef.user_id = $2
        AND ef.episode_id = $3
        AND s.is_published = true
        AND s.published_at IS NOT NULL
        AND s.published_at <= NOW()
        AND el.status = 'published'
        AND el.published_at IS NOT NULL
        AND el.published_at <= NOW()
) AS follows_published_episode
`

type UserFollowsPublishedEpisodeParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	UserID    uuid.UUID `json:"user_id"`
	EpisodeID uuid.UUID `json:"episode_id"`
}

// Matches GetPublishedEpisodeByPublicIDForTenant, so a draft, scheduled, or
// otherwise non-public episode is indistinguishable from an unfollowed one.
func (q *Queries) UserFollowsPublishedEpisode(ctx context.Context, arg UserFollowsPublishedEpisodeParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userFollowsPublishedEpisode, arg.TenantID, arg.UserID, arg.EpisodeID)
	var follows_published_episode bool
	err := row.Scan(&follows_published_episode)
	return follows_published_episode, err
}
