// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mfa.sql

package dbmodels

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countUnusedUserMfaRecoveryCodes = `-- name: CountUnusedUserMfaRecoveryCodes :one
SELECT count(*)
FROM user_mfa_recovery_codes
WHERE user_id = $1
    AND used_at IS NULL
`

func (q *Queries) CountUnusedUserMfaRecoveryCodes(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnusedUserMfaRecoveryCodes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserMfaRecoveryCode = `-- name: CreateUserMfaRecoveryCode :exec
INSERT INTO user_mfa_recovery_codes (id, tenant_id, user_id, code_hash)
VALUES ($1, $2, $3, $4)
`

type CreateUserMfaRecoveryCodeParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
	CodeHash string    `json:"code_hash"`
}

func (q *Queries) CreateUserMfaRecoveryCode(ctx context.Context, arg CreateUserMfaRecoveryCodeParams) error {
	_, err := q.db.ExecContext(ctx, createUserMfaRecoveryCode,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.CodeHash,
	)
	return err
}

const deleteUserMfaRecoveryCodesByUserID = `-- name: DeleteUserMfaRecoveryCodesByUserID :exec
DELETE FROM user_mfa_recovery_codes
WHERE user_id = $1
`

func (q *Queries) DeleteUserMfaRecoveryCodesByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserMfaRecoveryCodesByUserID, userID)
	return err
}

const deleteUserMfaTotpByUserID = `-- name: DeleteUserMfaTotpByUserID :exec
DELETE FROM user_mfa_totp
WHERE user_id = $1
`

func (q *Queries) DeleteUserMfaTotpByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserMfaTotpByUserID, userID)
	return err
}

const enableUserMfaTotp = `-- name: EnableUserMfaTotp :one
UPDATE user_mfa_totp
SET enabled_at = now(),
    failed_attempts = 0,
    locked_until = NULL,
    updated_at = now()
WHERE user_id = $1
RETURNING user_id, tenant_id, secret_encrypted, enabled_at, last_verified_step, failed_attempts, locked_until, created_at, updated_at
`

// last_verified_step is left alone: the code that confirmed the enrollment
// was accepted through the same path a login code is, which stored it.
func (q *Queries) EnableUserMfaTotp(ctx context.Context, userID uuid.UUID) (UserMfaTotp, error) {
	row := q.db.QueryRowContext(ctx, enableUserMfaTotp, userID)
	var i UserMfaTotp
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.SecretEncrypted,
		&i.EnabledAt,
		&i.LastVerifiedStep,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserMfaTotpByUserID = `-- name: GetUserMfaTotpByUserID :one

SELECT user_id, tenant_id, secret_encrypted, enabled_at, last_verified_step, failed_attempts, locked_until, created_at, updated_at
FROM user_mfa_totp
WHERE user_id = $1
`

// Admin MFA. Every statement is keyed by user_id alone: the row-level
// security policies on both tables already confine them to the tenant the
// connection is scoped to.
func (q *Queries) GetUserMfaTotpByUserID(ctx context.Context, userID uuid.UUID) (UserMfaTotp, error) {
	row := q.db.QueryRowContext(ctx, getUserMfaTotpByUserID, userID)
	var i UserMfaTotp
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.SecretEncrypted,
		&i.EnabledAt,
		&i.LastVerifiedStep,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUnusedUserMfaRecoveryCodes = `-- name: ListUnusedUserMfaRecoveryCodes :many
SELECT id, code_hash
FROM user_mfa_recovery_codes
WHERE user_id = $1
    AND used_at IS NULL
ORDER BY created_at, id
`

type ListUnusedUserMfaRecoveryCodesRow struct {
	ID       uuid.UUID `json:"id"`
	CodeHash string    `json:"code_hash"`
}

func (q *Queries) ListUnusedUserMfaRecoveryCodes(ctx context.Context, userID uuid.UUID) ([]ListUnusedUserMfaRecoveryCodesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnusedUserMfaRecoveryCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnusedUserMfaRecoveryCodesRow
	for rows.Next() {
		var i ListUnusedUserMfaRecoveryCodesRow
		if err := rows.Scan(&i.ID, &i.CodeHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserMfaRecoveryCodeUsed = `-- name: MarkUserMfaRecoveryCodeUsed :execrows
UPDATE user_mfa_recovery_codes
SET used_at = now()
WHERE id = $1
    AND used_at IS NULL
`

func (q *Queries) MarkUserMfaRecoveryCodeUsed(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, markUserMfaRecoveryCodeUsed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markUserMfaTotpVerified = `-- name: MarkUserMfaTotpVerified :exec
UPDATE user_mfa_totp
SET last_verified_step = $1,
    failed_attempts = 0,
    locked_until = NULL,
    updated_at = now()
WHERE user_id = $2
`

type MarkUserMfaTotpVerifiedParams struct {
	LastVerifiedStep sql.NullInt64 `json:"last_verified_step"`
	UserID           uuid.UUID     `json:"user_id"`
}

func (q *Queries) MarkUserMfaTotpVerified(ctx context.Context, arg MarkUserMfaTotpVerifiedParams) error {
	_, err := q.db.ExecContext(ctx, markUserMfaTotpVerified, arg.LastVerifiedStep, arg.UserID)
	return err
}

const recordUserMfaTotpFailure = `-- name: RecordUserMfaTotpFailure :one
UPDATE user_mfa_totp
SET failed_attempts = CASE
        WHEN failed_attempts + 1 >= $1::int THEN 0
        ELSE failed_attempts + 1
    END,
    locked_until = CASE
        WHEN failed_attempts + 1 >= $1::int THEN $2::timestamptz
        ELSE locked_until
    END,
    updated_at = now()
WHERE user_id = $3
RETURNING user_id, tenant_id, secret_encrypted, enabled_at, last_verified_step, failed_attempts, locked_until, created_at, updated_at
`

type RecordUserMfaTotpFailureParams struct {
	MaxFailedAttempts int32     `json:"max_failed_attempts"`
	LockedUntil       time.Time `json:"locked_until"`
	UserID            uuid.UUID `json:"user_id"`
}

// Reaching the threshold starts the lock and puts the counter back to zero,
// so the attempt after a lock expires is not immediately the fifth again.
func (q *Queries) RecordUserMfaTotpFailure(ctx context.Context, arg RecordUserMfaTotpFailureParams) (UserMfaTotp, error) {
	row := q.db.QueryRowContext(ctx, recordUserMfaTotpFailure, arg.MaxFailedAttempts, arg.LockedUntil, arg.UserID)
	var i UserMfaTotp
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.SecretEncrypted,
		&i.EnabledAt,
		&i.LastVerifiedStep,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetUserMfaTotpFailures = `-- name: ResetUserMfaTotpFailures :exec
UPDATE user_mfa_totp
SET failed_attempts = 0,
    locked_until = NULL,
    updated_at = now()
WHERE user_id = $1
`

func (q *Queries) ResetUserMfaTotpFailures(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, resetUserMfaTotpFailures, userID)
	return err
}

const upsertUserMfaTotpSecret = `-- name: UpsertUserMfaTotpSecret :one
INSERT INTO user_mfa_totp (user_id, tenant_id, secret_encrypted)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
SET secret_encrypted = EXCLUDED.secret_encrypted,
    enabled_at = NULL,
    last_verified_step = NULL,
    failed_attempts = 0,
    locked_until = NULL,
    updated_at = now()
RETURNING user_id, tenant_id, secret_encrypted, enabled_at, last_verified_step, failed_attempts, locked_until, created_at, updated_at
`

type UpsertUserMfaTotpSecretParams struct {
	UserID          uuid.UUID `json:"user_id"`
	TenantID        uuid.UUID `json:"tenant_id"`
	SecretEncrypted string    `json:"secret_encrypted"`
}

// Starting enrollment replaces whatever unconfirmed secret was there and
// clears the lock, so a stalled attempt never blocks the next one.
func (q *Queries) UpsertUserMfaTotpSecret(ctx context.Context, arg UpsertUserMfaTotpSecretParams) (UserMfaTotp, error) {
	row := q.db.QueryRowContext(ctx, upsertUserMfaTotpSecret, arg.UserID, arg.TenantID, arg.SecretEncrypted)
	var i UserMfaTotp
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.SecretEncrypted,
		&i.EnabledAt,
		&i.LastVerifiedStep,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
