// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbmodels

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AdminAuditLog struct {
	ID                uuid.UUID      `json:"id"`
	ActorUserPublicID string         `json:"actor_user_public_id"`
	ActorRole         string         `json:"actor_role"`
	TenantPublicID    sql.NullString `json:"tenant_public_id"`
	Action            string         `json:"action"`
	TargetType        sql.NullString `json:"target_type"`
	TargetID          sql.NullString `json:"target_id"`
	Outcome           string         `json:"outcome"`
	Reason            sql.NullString `json:"reason"`
	ClientIp          sql.NullString `json:"client_ip"`
	CreatedAt         time.Time      `json:"created_at"`
}

type Creator struct {
	ID          uuid.UUID      `json:"id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	PublicID    string         `json:"public_id"`
	Name        string         `json:"name"`
	ProfileText sql.NullString `json:"profile_text"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Episode struct {
	ID         uuid.UUID `json:"id"`
	SeriesID   uuid.UUID `json:"series_id"`
	PublicID   string    `json:"public_id"`
	Title      string    `json:"title"`
	OrderIndex int32     `json:"order_index"`
	CreatedAt  time.Time `json:"created_at"`
}

type EpisodeImage struct {
	ID              uuid.UUID `json:"id"`
	TenantID        uuid.UUID `json:"tenant_id"`
	EpisodeID       uuid.UUID `json:"episode_id"`
	StorageProvider string    `json:"storage_provider"`
	ObjectKey       string    `json:"object_key"`
	ImageUrl        string    `json:"image_url"`
	ContentType     string    `json:"content_type"`
	FileSizeBytes   int64     `json:"file_size_bytes"`
	DisplayOrder    int32     `json:"display_order"`
	Width           int32     `json:"width"`
	Height          int32     `json:"height"`
	CreatedAt       time.Time `json:"created_at"`
}

type EpisodeListing struct {
	EpisodeID          uuid.UUID     `json:"episode_id"`
	Price              int32         `json:"price"`
	ReadingPeriodHours sql.NullInt32 `json:"reading_period_hours"`
	Status             string        `json:"status"`
	ScheduledAt        sql.NullTime  `json:"scheduled_at"`
	PublishedAt        sql.NullTime  `json:"published_at"`
}

type Label struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	PublicID  string    `json:"public_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type PlatformUserRole struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type Purchase struct {
	ID              uuid.UUID    `json:"id"`
	UserID          uuid.UUID    `json:"user_id"`
	EpisodeID       uuid.UUID    `json:"episode_id"`
	PriceAtPurchase int32        `json:"price_at_purchase"`
	ExpiresAt       sql.NullTime `json:"expires_at"`
	PurchasedAt     time.Time    `json:"purchased_at"`
}

type Series struct {
	ID          uuid.UUID     `json:"id"`
	TenantID    uuid.UUID     `json:"tenant_id"`
	LabelID     uuid.NullUUID `json:"label_id"`
	PublicID    string        `json:"public_id"`
	Title       string        `json:"title"`
	CreatedAt   time.Time     `json:"created_at"`
	IsPublished bool          `json:"is_published"`
	PublishedAt sql.NullTime  `json:"published_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
}

type SeriesCreator struct {
	SeriesID     uuid.UUID `json:"series_id"`
	CreatorID    uuid.UUID `json:"creator_id"`
	Role         string    `json:"role"`
	DisplayOrder int32     `json:"display_order"`
}

type SeriesListing struct {
	SeriesID           uuid.UUID      `json:"series_id"`
	Synopsis           sql.NullString `json:"synopsis"`
	ReadingPeriodHours sql.NullInt32  `json:"reading_period_hours"`
	IsPublished        sql.NullBool   `json:"is_published"`
	PublishedAt        sql.NullTime   `json:"published_at"`
}

type Session struct {
	ID              uuid.UUID     `json:"id"`
	CurrentTenantID uuid.NullUUID `json:"current_tenant_id"`
	UserID          uuid.UUID     `json:"user_id"`
	TokenHash       string        `json:"token_hash"`
	ExpiresAt       time.Time     `json:"expires_at"`
	RevokedAt       sql.NullTime  `json:"revoked_at"`
	CreatedAt       time.Time     `json:"created_at"`
}

type Tenant struct {
	ID                        uuid.UUID      `json:"id"`
	PublicID                  string         `json:"public_id"`
	Domain                    string         `json:"domain"`
	Name                      string         `json:"name"`
	DefaultReadingPeriodHours sql.NullInt32  `json:"default_reading_period_hours"`
	CreatedAt                 time.Time      `json:"created_at"`
	Status                    string         `json:"status"`
	AdminDomain               sql.NullString `json:"admin_domain"`
}

type TenantMemberRole struct {
	ID           uuid.UUID `json:"id"`
	MembershipID uuid.UUID `json:"membership_id"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
}

type TenantMembership struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

type TenantTheme struct {
	TenantID       uuid.UUID      `json:"tenant_id"`
	PrimaryColor   string         `json:"primary_color"`
	SecondaryColor string         `json:"secondary_color"`
	AccentColor    string         `json:"accent_color"`
	LogoUrl        sql.NullString `json:"logo_url"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	PublicID     string    `json:"public_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Name         string    `json:"name"`
	CreatedAt    time.Time `json:"created_at"`
	Status       string    `json:"status"`
}
