// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbmodels

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AuditLog struct {
	ID          uuid.UUID      `json:"id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	ActorUserID uuid.UUID      `json:"actor_user_id"`
	ActorRole   string         `json:"actor_role"`
	Action      string         `json:"action"`
	TargetType  sql.NullString `json:"target_type"`
	TargetID    sql.NullString `json:"target_id"`
	Outcome     string         `json:"outcome"`
	Reason      sql.NullString `json:"reason"`
	ClientIp    sql.NullString `json:"client_ip"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Creator struct {
	ID          uuid.UUID      `json:"id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	PublicID    string         `json:"public_id"`
	Name        string         `json:"name"`
	ProfileText sql.NullString `json:"profile_text"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Episode struct {
	ID         uuid.UUID `json:"id"`
	SeriesID   uuid.UUID `json:"series_id"`
	PublicID   string    `json:"public_id"`
	Title      string    `json:"title"`
	OrderIndex int32     `json:"order_index"`
	CreatedAt  time.Time `json:"created_at"`
}

type EpisodeImage struct {
	ID              uuid.UUID `json:"id"`
	TenantID        uuid.UUID `json:"tenant_id"`
	EpisodeID       uuid.UUID `json:"episode_id"`
	StorageProvider string    `json:"storage_provider"`
	ObjectKey       string    `json:"object_key"`
	ImageUrl        string    `json:"image_url"`
	ContentType     string    `json:"content_type"`
	FileSizeBytes   int64     `json:"file_size_bytes"`
	DisplayOrder    int32     `json:"display_order"`
	Width           int32     `json:"width"`
	Height          int32     `json:"height"`
	CreatedAt       time.Time `json:"created_at"`
}

type EpisodeListing struct {
	EpisodeID          uuid.UUID     `json:"episode_id"`
	Price              int32         `json:"price"`
	ReadingPeriodHours sql.NullInt32 `json:"reading_period_hours"`
	Status             string        `json:"status"`
	ScheduledAt        sql.NullTime  `json:"scheduled_at"`
	PublishedAt        sql.NullTime  `json:"published_at"`
}

type Label struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	PublicID  string    `json:"public_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type PlatformAuditLog struct {
	ID                  uuid.UUID      `json:"id"`
	ActorRole           string         `json:"actor_role"`
	Action              string         `json:"action"`
	TargetType          sql.NullString `json:"target_type"`
	TargetID            sql.NullString `json:"target_id"`
	Outcome             string         `json:"outcome"`
	Reason              sql.NullString `json:"reason"`
	ClientIp            sql.NullString `json:"client_ip"`
	CreatedAt           time.Time      `json:"created_at"`
	ActorPlatformUserID uuid.UUID      `json:"actor_platform_user_id"`
}

type PlatformSession struct {
	ID             uuid.UUID    `json:"id"`
	PlatformUserID uuid.UUID    `json:"platform_user_id"`
	TokenHash      string       `json:"token_hash"`
	ExpiresAt      time.Time    `json:"expires_at"`
	RevokedAt      sql.NullTime `json:"revoked_at"`
	CreatedAt      time.Time    `json:"created_at"`
}

type PlatformSmtpConfig struct {
	Singleton         bool           `json:"singleton"`
	Host              string         `json:"host"`
	Port              int32          `json:"port"`
	Username          string         `json:"username"`
	PasswordEncrypted string         `json:"password_encrypted"`
	Encryption        string         `json:"encryption"`
	FromAddress       string         `json:"from_address"`
	ReplyTo           sql.NullString `json:"reply_to"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type PlatformUser struct {
	ID           uuid.UUID `json:"id"`
	PublicID     string    `json:"public_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Name         string    `json:"name"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
}

type PlatformUserRole struct {
	ID             uuid.UUID `json:"id"`
	Role           string    `json:"role"`
	CreatedAt      time.Time `json:"created_at"`
	PlatformUserID uuid.UUID `json:"platform_user_id"`
}

type Purchase struct {
	ID              uuid.UUID    `json:"id"`
	UserID          uuid.UUID    `json:"user_id"`
	EpisodeID       uuid.UUID    `json:"episode_id"`
	PriceAtPurchase int32        `json:"price_at_purchase"`
	ExpiresAt       sql.NullTime `json:"expires_at"`
	PurchasedAt     time.Time    `json:"purchased_at"`
}

type Series struct {
	ID          uuid.UUID     `json:"id"`
	TenantID    uuid.UUID     `json:"tenant_id"`
	LabelID     uuid.NullUUID `json:"label_id"`
	PublicID    string        `json:"public_id"`
	Title       string        `json:"title"`
	CreatedAt   time.Time     `json:"created_at"`
	IsPublished bool          `json:"is_published"`
	PublishedAt sql.NullTime  `json:"published_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
}

type SeriesCreator struct {
	SeriesID     uuid.UUID `json:"series_id"`
	CreatorID    uuid.UUID `json:"creator_id"`
	Role         string    `json:"role"`
	DisplayOrder int32     `json:"display_order"`
}

type SeriesListing struct {
	SeriesID           uuid.UUID      `json:"series_id"`
	Synopsis           sql.NullString `json:"synopsis"`
	ReadingPeriodHours sql.NullInt32  `json:"reading_period_hours"`
	IsPublished        sql.NullBool   `json:"is_published"`
	PublishedAt        sql.NullTime   `json:"published_at"`
}

type Session struct {
	ID        uuid.UUID    `json:"id"`
	TenantID  uuid.UUID    `json:"tenant_id"`
	UserID    uuid.UUID    `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
	CreatedAt time.Time    `json:"created_at"`
}

type Tenant struct {
	ID                        uuid.UUID      `json:"id"`
	PublicID                  string         `json:"public_id"`
	Domain                    string         `json:"domain"`
	Name                      string         `json:"name"`
	DefaultReadingPeriodHours sql.NullInt32  `json:"default_reading_period_hours"`
	CreatedAt                 time.Time      `json:"created_at"`
	Status                    string         `json:"status"`
	AdminDomain               sql.NullString `json:"admin_domain"`
}

type TenantConfig struct {
	TenantID        uuid.UUID      `json:"tenant_id"`
	CopyrightText   sql.NullString `json:"copyright_text"`
	SiteDescription sql.NullString `json:"site_description"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	SiteTagline     sql.NullString `json:"site_tagline"`
}

type TenantSmtpConfig struct {
	TenantID            uuid.UUID      `json:"tenant_id"`
	SmtpOverrideEnabled bool           `json:"smtp_override_enabled"`
	Host                sql.NullString `json:"host"`
	Port                sql.NullInt32  `json:"port"`
	Username            sql.NullString `json:"username"`
	PasswordEncrypted   sql.NullString `json:"password_encrypted"`
	Encryption          sql.NullString `json:"encryption"`
	FromName            sql.NullString `json:"from_name"`
	FromAddress         sql.NullString `json:"from_address"`
	ReplyTo             sql.NullString `json:"reply_to"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
}

type TenantTheme struct {
	TenantID       uuid.UUID      `json:"tenant_id"`
	PrimaryColor   string         `json:"primary_color"`
	SecondaryColor string         `json:"secondary_color"`
	AccentColor    string         `json:"accent_color"`
	LogoUrl        sql.NullString `json:"logo_url"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type TenantUserRole struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID              uuid.UUID     `json:"id"`
	PublicID        string        `json:"public_id"`
	Email           string        `json:"email"`
	PasswordHash    string        `json:"password_hash"`
	Name            string        `json:"name"`
	CreatedAt       time.Time     `json:"created_at"`
	Status          string        `json:"status"`
	TenantID        uuid.NullUUID `json:"tenant_id"`
	EmailVerifiedAt sql.NullTime  `json:"email_verified_at"`
}

type UserEmailVerificationToken struct {
	ID        uuid.UUID    `json:"id"`
	TenantID  uuid.UUID    `json:"tenant_id"`
	UserID    uuid.UUID    `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	UsedAt    sql.NullTime `json:"used_at"`
	CreatedAt time.Time    `json:"created_at"`
}
