// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package dbmodels

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countUnreadNotificationsForUser = `-- name: CountUnreadNotificationsForUser :one
SELECT COUNT(*)::int AS unread_count
FROM notifications n
WHERE n.tenant_id = $1
    AND n.user_id = $2
    AND NOT EXISTS (
        SELECT 1
        FROM notification_reads nr
        WHERE nr.notification_id = n.id
            AND nr.user_id = $2
    )
`

type CountUnreadNotificationsForUserParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) CountUnreadNotificationsForUser(ctx context.Context, arg CountUnreadNotificationsForUserParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotificationsForUser, arg.TenantID, arg.UserID)
	var unread_count int32
	err := row.Scan(&unread_count)
	return unread_count, err
}

const countUnreadPlatformNotificationsForUser = `-- name: CountUnreadPlatformNotificationsForUser :one
SELECT COUNT(*)::int AS unread_count
FROM platform_notifications n
WHERE n.platform_user_id = $1
    AND NOT EXISTS (
        SELECT 1
        FROM platform_notification_reads nr
        WHERE nr.platform_notification_id = n.id
            AND nr.platform_user_id = $1
    )
`

func (q *Queries) CountUnreadPlatformNotificationsForUser(ctx context.Context, platformUserID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countUnreadPlatformNotificationsForUser, platformUserID)
	var unread_count int32
	err := row.Scan(&unread_count)
	return unread_count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    id,
    tenant_id,
    user_id,
    notification_type,
    subject_key,
    payload
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (user_id, notification_type, subject_key) DO NOTHING
RETURNING id, tenant_id, user_id, notification_type, subject_key, payload, created_at
`

type CreateNotificationParams struct {
	ID               uuid.UUID       `json:"id"`
	TenantID         uuid.UUID       `json:"tenant_id"`
	UserID           uuid.UUID       `json:"user_id"`
	NotificationType string          `json:"notification_type"`
	SubjectKey       string          `json:"subject_key"`
	Payload          json.RawMessage `json:"payload"`
}

// Worker insert. Same recipient / type / subject is a no-op so retries
// do not create a second row. :one returns no rows on conflict.
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.NotificationType,
		arg.SubjectKey,
		arg.Payload,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.NotificationType,
		&i.SubjectKey,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const createPlatformNotification = `-- name: CreatePlatformNotification :one
INSERT INTO platform_notifications (
    id,
    platform_user_id,
    notification_type,
    subject_key,
    payload
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (platform_user_id, notification_type, subject_key) DO NOTHING
RETURNING id, platform_user_id, notification_type, subject_key, payload, created_at
`

type CreatePlatformNotificationParams struct {
	ID               uuid.UUID       `json:"id"`
	PlatformUserID   uuid.UUID       `json:"platform_user_id"`
	NotificationType string          `json:"notification_type"`
	SubjectKey       string          `json:"subject_key"`
	Payload          json.RawMessage `json:"payload"`
}

func (q *Queries) CreatePlatformNotification(ctx context.Context, arg CreatePlatformNotificationParams) (PlatformNotification, error) {
	row := q.db.QueryRowContext(ctx, createPlatformNotification,
		arg.ID,
		arg.PlatformUserID,
		arg.NotificationType,
		arg.SubjectKey,
		arg.Payload,
	)
	var i PlatformNotification
	err := row.Scan(
		&i.ID,
		&i.PlatformUserID,
		&i.NotificationType,
		&i.SubjectKey,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationsForUserAsc = `-- name: ListNotificationsForUserAsc :many
SELECT
    n.id,
    n.tenant_id,
    n.user_id,
    n.notification_type,
    n.subject_key,
    n.payload,
    n.created_at,
    (nr.notification_id IS NOT NULL)::bool AS is_read,
    nr.read_at
FROM notifications n
    LEFT JOIN notification_reads nr ON nr.notification_id = n.id
    AND nr.user_id = $1
WHERE n.tenant_id = $2
    AND n.user_id = $1
    AND (
        $3::uuid IS NULL
        OR (
            $4::boolean
            AND (n.created_at, n.id) >= ($5::timestamptz, $3::uuid)
        )
        OR (
            NOT $4::boolean
            AND (n.created_at, n.id) > ($5::timestamptz, $3::uuid)
        )
    )
ORDER BY n.created_at ASC, n.id ASC
LIMIT $6
`

type ListNotificationsForUserAscParams struct {
	UserID          uuid.UUID     `json:"user_id"`
	TenantID        uuid.UUID     `json:"tenant_id"`
	CursorID        uuid.NullUUID `json:"cursor_id"`
	CursorInclusive bool          `json:"cursor_inclusive"`
	CursorCreatedAt sql.NullTime  `json:"cursor_created_at"`
	Limit           int32         `json:"limit"`
}

type ListNotificationsForUserAscRow struct {
	ID               uuid.UUID       `json:"id"`
	TenantID         uuid.UUID       `json:"tenant_id"`
	UserID           uuid.UUID       `json:"user_id"`
	NotificationType string          `json:"notification_type"`
	SubjectKey       string          `json:"subject_key"`
	Payload          json.RawMessage `json:"payload"`
	CreatedAt        time.Time       `json:"created_at"`
	IsRead           bool            `json:"is_read"`
	ReadAt           sql.NullTime    `json:"read_at"`
}

func (q *Queries) ListNotificationsForUserAsc(ctx context.Context, arg ListNotificationsForUserAscParams) ([]ListNotificationsForUserAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsForUserAsc,
		arg.UserID,
		arg.TenantID,
		arg.CursorID,
		arg.CursorInclusive,
		arg.CursorCreatedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsForUserAscRow
	for rows.Next() {
		var i ListNotificationsForUserAscRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.NotificationType,
			&i.SubjectKey,
			&i.Payload,
			&i.CreatedAt,
			&i.IsRead,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsForUserDesc = `-- name: ListNotificationsForUserDesc :many
SELECT
    n.id,
    n.tenant_id,
    n.user_id,
    n.notification_type,
    n.subject_key,
    n.payload,
    n.created_at,
    (nr.notification_id IS NOT NULL)::bool AS is_read,
    nr.read_at
FROM notifications n
    LEFT JOIN notification_reads nr ON nr.notification_id = n.id
    AND nr.user_id = $1
WHERE n.tenant_id = $2
    AND n.user_id = $1
    AND (
        $3::uuid IS NULL
        OR (
            $4::boolean
            AND (n.created_at, n.id) <= ($5::timestamptz, $3::uuid)
        )
        OR (
            NOT $4::boolean
            AND (n.created_at, n.id) < ($5::timestamptz, $3::uuid)
        )
    )
ORDER BY n.created_at DESC, n.id DESC
LIMIT $6
`

type ListNotificationsForUserDescParams struct {
	UserID          uuid.UUID     `json:"user_id"`
	TenantID        uuid.UUID     `json:"tenant_id"`
	CursorID        uuid.NullUUID `json:"cursor_id"`
	CursorInclusive bool          `json:"cursor_inclusive"`
	CursorCreatedAt sql.NullTime  `json:"cursor_created_at"`
	Limit           int32         `json:"limit"`
}

type ListNotificationsForUserDescRow struct {
	ID               uuid.UUID       `json:"id"`
	TenantID         uuid.UUID       `json:"tenant_id"`
	UserID           uuid.UUID       `json:"user_id"`
	NotificationType string          `json:"notification_type"`
	SubjectKey       string          `json:"subject_key"`
	Payload          json.RawMessage `json:"payload"`
	CreatedAt        time.Time       `json:"created_at"`
	IsRead           bool            `json:"is_read"`
	ReadAt           sql.NullTime    `json:"read_at"`
}

// ListNotifications is (created_at, id) DESC. Forward uses the DESC query;
// backward uses ASC so the index can be scanned in reverse. The handler
// flips ASC rows back into display order. Do not parameterize ORDER BY.
// cursor rules: proto/README.md.
func (q *Queries) ListNotificationsForUserDesc(ctx context.Context, arg ListNotificationsForUserDescParams) ([]ListNotificationsForUserDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsForUserDesc,
		arg.UserID,
		arg.TenantID,
		arg.CursorID,
		arg.CursorInclusive,
		arg.CursorCreatedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsForUserDescRow
	for rows.Next() {
		var i ListNotificationsForUserDescRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.NotificationType,
			&i.SubjectKey,
			&i.Payload,
			&i.CreatedAt,
			&i.IsRead,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformNotificationsForUserAsc = `-- name: ListPlatformNotificationsForUserAsc :many
SELECT
    n.id,
    n.platform_user_id,
    n.notification_type,
    n.subject_key,
    n.payload,
    n.created_at,
    (nr.platform_notification_id IS NOT NULL)::bool AS is_read,
    nr.read_at
FROM platform_notifications n
    LEFT JOIN platform_notification_reads nr ON nr.platform_notification_id = n.id
    AND nr.platform_user_id = $1
WHERE n.platform_user_id = $1
    AND (
        $2::uuid IS NULL
        OR (
            $3::boolean
            AND (n.created_at, n.id) >= ($4::timestamptz, $2::uuid)
        )
        OR (
            NOT $3::boolean
            AND (n.created_at, n.id) > ($4::timestamptz, $2::uuid)
        )
    )
ORDER BY n.created_at ASC, n.id ASC
LIMIT $5
`

type ListPlatformNotificationsForUserAscParams struct {
	PlatformUserID  uuid.UUID     `json:"platform_user_id"`
	CursorID        uuid.NullUUID `json:"cursor_id"`
	CursorInclusive bool          `json:"cursor_inclusive"`
	CursorCreatedAt sql.NullTime  `json:"cursor_created_at"`
	Limit           int32         `json:"limit"`
}

type ListPlatformNotificationsForUserAscRow struct {
	ID               uuid.UUID       `json:"id"`
	PlatformUserID   uuid.UUID       `json:"platform_user_id"`
	NotificationType string          `json:"notification_type"`
	SubjectKey       string          `json:"subject_key"`
	Payload          json.RawMessage `json:"payload"`
	CreatedAt        time.Time       `json:"created_at"`
	IsRead           bool            `json:"is_read"`
	ReadAt           sql.NullTime    `json:"read_at"`
}

func (q *Queries) ListPlatformNotificationsForUserAsc(ctx context.Context, arg ListPlatformNotificationsForUserAscParams) ([]ListPlatformNotificationsForUserAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlatformNotificationsForUserAsc,
		arg.PlatformUserID,
		arg.CursorID,
		arg.CursorInclusive,
		arg.CursorCreatedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlatformNotificationsForUserAscRow
	for rows.Next() {
		var i ListPlatformNotificationsForUserAscRow
		if err := rows.Scan(
			&i.ID,
			&i.PlatformUserID,
			&i.NotificationType,
			&i.SubjectKey,
			&i.Payload,
			&i.CreatedAt,
			&i.IsRead,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformNotificationsForUserDesc = `-- name: ListPlatformNotificationsForUserDesc :many
SELECT
    n.id,
    n.platform_user_id,
    n.notification_type,
    n.subject_key,
    n.payload,
    n.created_at,
    (nr.platform_notification_id IS NOT NULL)::bool AS is_read,
    nr.read_at
FROM platform_notifications n
    LEFT JOIN platform_notification_reads nr ON nr.platform_notification_id = n.id
    AND nr.platform_user_id = $1
WHERE n.platform_user_id = $1
    AND (
        $2::uuid IS NULL
        OR (
            $3::boolean
            AND (n.created_at, n.id) <= ($4::timestamptz, $2::uuid)
        )
        OR (
            NOT $3::boolean
            AND (n.created_at, n.id) < ($4::timestamptz, $2::uuid)
        )
    )
ORDER BY n.created_at DESC, n.id DESC
LIMIT $5
`

type ListPlatformNotificationsForUserDescParams struct {
	PlatformUserID  uuid.UUID     `json:"platform_user_id"`
	CursorID        uuid.NullUUID `json:"cursor_id"`
	CursorInclusive bool          `json:"cursor_inclusive"`
	CursorCreatedAt sql.NullTime  `json:"cursor_created_at"`
	Limit           int32         `json:"limit"`
}

type ListPlatformNotificationsForUserDescRow struct {
	ID               uuid.UUID       `json:"id"`
	PlatformUserID   uuid.UUID       `json:"platform_user_id"`
	NotificationType string          `json:"notification_type"`
	SubjectKey       string          `json:"subject_key"`
	Payload          json.RawMessage `json:"payload"`
	CreatedAt        time.Time       `json:"created_at"`
	IsRead           bool            `json:"is_read"`
	ReadAt           sql.NullTime    `json:"read_at"`
}

func (q *Queries) ListPlatformNotificationsForUserDesc(ctx context.Context, arg ListPlatformNotificationsForUserDescParams) ([]ListPlatformNotificationsForUserDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlatformNotificationsForUserDesc,
		arg.PlatformUserID,
		arg.CursorID,
		arg.CursorInclusive,
		arg.CursorCreatedAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlatformNotificationsForUserDescRow
	for rows.Next() {
		var i ListPlatformNotificationsForUserDescRow
		if err := rows.Scan(
			&i.ID,
			&i.PlatformUserID,
			&i.NotificationType,
			&i.SubjectKey,
			&i.Payload,
			&i.CreatedAt,
			&i.IsRead,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :execrows
INSERT INTO notification_reads (notification_id, user_id, tenant_id, read_at)
SELECT n.id, $1, n.tenant_id, NOW()
FROM notifications n
WHERE n.tenant_id = $2
    AND n.user_id = $1
    AND NOT EXISTS (
        SELECT 1
        FROM notification_reads nr
        WHERE nr.notification_id = n.id
            AND nr.user_id = $1
    )
ON CONFLICT (notification_id, user_id) DO NOTHING
`

type MarkAllNotificationsAsReadParams struct {
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, arg MarkAllNotificationsAsReadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAllNotificationsAsRead, arg.UserID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markAllPlatformNotificationsAsRead = `-- name: MarkAllPlatformNotificationsAsRead :execrows
INSERT INTO platform_notification_reads (platform_notification_id, platform_user_id, read_at)
SELECT n.id, $1, NOW()
FROM platform_notifications n
WHERE n.platform_user_id = $1
    AND NOT EXISTS (
        SELECT 1
        FROM platform_notification_reads nr
        WHERE nr.platform_notification_id = n.id
            AND nr.platform_user_id = $1
    )
ON CONFLICT (platform_notification_id, platform_user_id) DO NOTHING
`

func (q *Queries) MarkAllPlatformNotificationsAsRead(ctx context.Context, platformUserID uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, markAllPlatformNotificationsAsRead, platformUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :one
INSERT INTO notification_reads (notification_id, user_id, tenant_id, read_at)
SELECT n.id, $1, n.tenant_id, NOW()
FROM notifications n
WHERE n.id = $2
    AND n.tenant_id = $3
    AND n.user_id = $1
ON CONFLICT (notification_id, user_id) DO UPDATE
SET read_at = EXCLUDED.read_at
RETURNING notification_id, user_id, tenant_id, read_at
`

type MarkNotificationAsReadParams struct {
	UserID   uuid.UUID `json:"user_id"`
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (NotificationRead, error) {
	row := q.db.QueryRowContext(ctx, markNotificationAsRead, arg.UserID, arg.ID, arg.TenantID)
	var i NotificationRead
	err := row.Scan(
		&i.NotificationID,
		&i.UserID,
		&i.TenantID,
		&i.ReadAt,
	)
	return i, err
}

const markPlatformNotificationAsRead = `-- name: MarkPlatformNotificationAsRead :one
INSERT INTO platform_notification_reads (platform_notification_id, platform_user_id, read_at)
SELECT n.id, $1, NOW()
FROM platform_notifications n
WHERE n.id = $2
    AND n.platform_user_id = $1
ON CONFLICT (platform_notification_id, platform_user_id) DO UPDATE
SET read_at = EXCLUDED.read_at
RETURNING platform_notification_id, platform_user_id, read_at
`

type MarkPlatformNotificationAsReadParams struct {
	PlatformUserID uuid.UUID `json:"platform_user_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) MarkPlatformNotificationAsRead(ctx context.Context, arg MarkPlatformNotificationAsReadParams) (PlatformNotificationRead, error) {
	row := q.db.QueryRowContext(ctx, markPlatformNotificationAsRead, arg.PlatformUserID, arg.ID)
	var i PlatformNotificationRead
	err := row.Scan(&i.PlatformNotificationID, &i.PlatformUserID, &i.ReadAt)
	return i, err
}
