// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: page.sql

package dbmodels

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPage = `-- name: CreatePage :one
INSERT INTO pages (id, tenant_id, slug, title, display_in_footer)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, slug, title, published_version_id, display_in_footer, created_at, updated_at
`

type CreatePageParams struct {
	ID              uuid.UUID `json:"id"`
	TenantID        uuid.UUID `json:"tenant_id"`
	Slug            string    `json:"slug"`
	Title           string    `json:"title"`
	DisplayInFooter bool      `json:"display_in_footer"`
}

// ページを新規作成する
func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (Page, error) {
	row := q.db.QueryRowContext(ctx, createPage,
		arg.ID,
		arg.TenantID,
		arg.Slug,
		arg.Title,
		arg.DisplayInFooter,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Title,
		&i.PublishedVersionID,
		&i.DisplayInFooter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPageVersion = `-- name: CreatePageVersion :one
INSERT INTO page_versions (id, page_id, tenant_id, version_number, content_markdown, author_user_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, page_id, version_number, content_markdown, author_user_id, status, publish_at, created_at, published_at, tenant_id
`

type CreatePageVersionParams struct {
	ID              uuid.UUID     `json:"id"`
	PageID          uuid.UUID     `json:"page_id"`
	TenantID        uuid.UUID     `json:"tenant_id"`
	VersionNumber   int32         `json:"version_number"`
	ContentMarkdown string        `json:"content_markdown"`
	AuthorUserID    uuid.NullUUID `json:"author_user_id"`
}

// ページバージョンを新規作成する
func (q *Queries) CreatePageVersion(ctx context.Context, arg CreatePageVersionParams) (PageVersion, error) {
	row := q.db.QueryRowContext(ctx, createPageVersion,
		arg.ID,
		arg.PageID,
		arg.TenantID,
		arg.VersionNumber,
		arg.ContentMarkdown,
		arg.AuthorUserID,
	)
	var i PageVersion
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.VersionNumber,
		&i.ContentMarkdown,
		&i.AuthorUserID,
		&i.Status,
		&i.PublishAt,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.TenantID,
	)
	return i, err
}

const getMaxPageVersionNumberByPageID = `-- name: GetMaxPageVersionNumberByPageID :one
SELECT COALESCE(MAX(version_number), 0)::int AS max_version
FROM page_versions
WHERE page_id = $1
`

// ページの最大バージョン番号を取得する（次バージョン番号算出用）
func (q *Queries) GetMaxPageVersionNumberByPageID(ctx context.Context, pageID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getMaxPageVersionNumberByPageID, pageID)
	var max_version int32
	err := row.Scan(&max_version)
	return max_version, err
}

const getPageByIDForTenant = `-- name: GetPageByIDForTenant :one
SELECT id, tenant_id, slug, title, published_version_id, display_in_footer, created_at, updated_at FROM pages
WHERE id = $1 AND tenant_id = $2
`

type GetPageByIDForTenantParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// テナントのページをIDで取得する
func (q *Queries) GetPageByIDForTenant(ctx context.Context, arg GetPageByIDForTenantParams) (Page, error) {
	row := q.db.QueryRowContext(ctx, getPageByIDForTenant, arg.ID, arg.TenantID)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Title,
		&i.PublishedVersionID,
		&i.DisplayInFooter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPageVersionByIDForPage = `-- name: GetPageVersionByIDForPage :one
SELECT id, page_id, version_number, content_markdown, author_user_id, status, publish_at, created_at, published_at, tenant_id FROM page_versions
WHERE id = $1 AND page_id = $2
`

type GetPageVersionByIDForPageParams struct {
	ID     uuid.UUID `json:"id"`
	PageID uuid.UUID `json:"page_id"`
}

// ページバージョンをIDで取得する
func (q *Queries) GetPageVersionByIDForPage(ctx context.Context, arg GetPageVersionByIDForPageParams) (PageVersion, error) {
	row := q.db.QueryRowContext(ctx, getPageVersionByIDForPage, arg.ID, arg.PageID)
	var i PageVersion
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.VersionNumber,
		&i.ContentMarkdown,
		&i.AuthorUserID,
		&i.Status,
		&i.PublishAt,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.TenantID,
	)
	return i, err
}

const getPublishedPageBySlugForTenant = `-- name: GetPublishedPageBySlugForTenant :one
SELECT p.id,
	p.tenant_id,
	p.slug,
	p.title,
	p.published_version_id,
	p.display_in_footer,
	p.created_at,
	p.updated_at,
	pv.id AS version_id,
	pv.page_id,
	pv.version_number,
	pv.content_markdown,
	pv.author_user_id,
	pv.status,
	pv.publish_at,
	pv.created_at AS version_created_at,
	pv.published_at
FROM pages p
	JOIN page_versions pv ON pv.id = p.published_version_id
WHERE p.tenant_id = $1
	AND p.slug = $2
	AND pv.status = 'published'
	AND pv.published_at IS NOT NULL
	AND pv.published_at <= NOW()
LIMIT 1
`

type GetPublishedPageBySlugForTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Slug     string    `json:"slug"`
}

type GetPublishedPageBySlugForTenantRow struct {
	ID                 uuid.UUID     `json:"id"`
	TenantID           uuid.UUID     `json:"tenant_id"`
	Slug               string        `json:"slug"`
	Title              string        `json:"title"`
	PublishedVersionID uuid.NullUUID `json:"published_version_id"`
	DisplayInFooter    bool          `json:"display_in_footer"`
	CreatedAt          time.Time     `json:"created_at"`
	UpdatedAt          time.Time     `json:"updated_at"`
	VersionID          uuid.UUID     `json:"version_id"`
	PageID             uuid.UUID     `json:"page_id"`
	VersionNumber      int32         `json:"version_number"`
	ContentMarkdown    string        `json:"content_markdown"`
	AuthorUserID       uuid.NullUUID `json:"author_user_id"`
	Status             string        `json:"status"`
	PublishAt          sql.NullTime  `json:"publish_at"`
	VersionCreatedAt   time.Time     `json:"version_created_at"`
	PublishedAt        sql.NullTime  `json:"published_at"`
}

// テナントの公開中ページをslugで取得する
func (q *Queries) GetPublishedPageBySlugForTenant(ctx context.Context, arg GetPublishedPageBySlugForTenantParams) (GetPublishedPageBySlugForTenantRow, error) {
	row := q.db.QueryRowContext(ctx, getPublishedPageBySlugForTenant, arg.TenantID, arg.Slug)
	var i GetPublishedPageBySlugForTenantRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Title,
		&i.PublishedVersionID,
		&i.DisplayInFooter,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VersionID,
		&i.PageID,
		&i.VersionNumber,
		&i.ContentMarkdown,
		&i.AuthorUserID,
		&i.Status,
		&i.PublishAt,
		&i.VersionCreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const listPageVersionsByPageID = `-- name: ListPageVersionsByPageID :many
SELECT id, page_id, version_number, content_markdown, author_user_id, status, publish_at, created_at, published_at, tenant_id FROM page_versions
WHERE page_id = $1
ORDER BY version_number DESC
`

// ページのバージョン一覧を新しい順に取得する
func (q *Queries) ListPageVersionsByPageID(ctx context.Context, pageID uuid.UUID) ([]PageVersion, error) {
	rows, err := q.db.QueryContext(ctx, listPageVersionsByPageID, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PageVersion
	for rows.Next() {
		var i PageVersion
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.VersionNumber,
			&i.ContentMarkdown,
			&i.AuthorUserID,
			&i.Status,
			&i.PublishAt,
			&i.CreatedAt,
			&i.PublishedAt,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPagesForTenant = `-- name: ListPagesForTenant :many
SELECT id, tenant_id, slug, title, published_version_id, display_in_footer, created_at, updated_at FROM pages
WHERE tenant_id = $1
ORDER BY created_at ASC
`

// テナントのページ一覧を取得する（作成日昇順）
func (q *Queries) ListPagesForTenant(ctx context.Context, tenantID uuid.UUID) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, listPagesForTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Slug,
			&i.Title,
			&i.PublishedVersionID,
			&i.DisplayInFooter,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPagesForTenant = `-- name: ListPublishedPagesForTenant :many
SELECT p.id, p.tenant_id, p.slug, p.title, p.published_version_id, p.display_in_footer, p.created_at, p.updated_at
FROM pages p
	JOIN page_versions pv ON pv.id = p.published_version_id
WHERE p.tenant_id = $1
	AND p.display_in_footer = true
	AND pv.status = 'published'
	AND pv.published_at IS NOT NULL
	AND pv.published_at <= NOW()
ORDER BY p.created_at ASC
`

// テナントの公開中かつフッター表示対象のページ一覧を取得する
func (q *Queries) ListPublishedPagesForTenant(ctx context.Context, tenantID uuid.UUID) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedPagesForTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Slug,
			&i.Title,
			&i.PublishedVersionID,
			&i.DisplayInFooter,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishPageVersion = `-- name: PublishPageVersion :one
UPDATE page_versions
SET status = 'published', published_at = NOW()
WHERE id = $1 AND page_id = $2
RETURNING id, page_id, version_number, content_markdown, author_user_id, status, publish_at, created_at, published_at, tenant_id
`

type PublishPageVersionParams struct {
	ID     uuid.UUID `json:"id"`
	PageID uuid.UUID `json:"page_id"`
}

// ページバージョンを公開状態にする
func (q *Queries) PublishPageVersion(ctx context.Context, arg PublishPageVersionParams) (PageVersion, error) {
	row := q.db.QueryRowContext(ctx, publishPageVersion, arg.ID, arg.PageID)
	var i PageVersion
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.VersionNumber,
		&i.ContentMarkdown,
		&i.AuthorUserID,
		&i.Status,
		&i.PublishAt,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.TenantID,
	)
	return i, err
}

const setPagePublishedVersion = `-- name: SetPagePublishedVersion :one
UPDATE pages
SET published_version_id = $1, updated_at = NOW()
WHERE id = $2 AND tenant_id = $3
RETURNING id, tenant_id, slug, title, published_version_id, display_in_footer, created_at, updated_at
`

type SetPagePublishedVersionParams struct {
	PublishedVersionID uuid.NullUUID `json:"published_version_id"`
	ID                 uuid.UUID     `json:"id"`
	TenantID           uuid.UUID     `json:"tenant_id"`
}

// ページの公開バージョンIDを更新する
func (q *Queries) SetPagePublishedVersion(ctx context.Context, arg SetPagePublishedVersionParams) (Page, error) {
	row := q.db.QueryRowContext(ctx, setPagePublishedVersion, arg.PublishedVersionID, arg.ID, arg.TenantID)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Title,
		&i.PublishedVersionID,
		&i.DisplayInFooter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePage = `-- name: UpdatePage :one
UPDATE pages
SET title = $1,
	display_in_footer = $2,
	updated_at = NOW()
WHERE id = $3 AND tenant_id = $4
RETURNING id, tenant_id, slug, title, published_version_id, display_in_footer, created_at, updated_at
`

type UpdatePageParams struct {
	Title           string    `json:"title"`
	DisplayInFooter bool      `json:"display_in_footer"`
	ID              uuid.UUID `json:"id"`
	TenantID        uuid.UUID `json:"tenant_id"`
}

// ページのタイトルとフッター表示設定を更新する
func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) (Page, error) {
	row := q.db.QueryRowContext(ctx, updatePage,
		arg.Title,
		arg.DisplayInFooter,
		arg.ID,
		arg.TenantID,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Title,
		&i.PublishedVersionID,
		&i.DisplayInFooter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
