// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package dbmodels

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getEnabledTenantPaymentConfigByTenantID = `-- name: GetEnabledTenantPaymentConfigByTenantID :one
SELECT tenant_id, provider, enabled, secret_key_encrypted, webhook_secret_encrypted, secret_key_hint, webhook_secret_hint, created_at, updated_at
FROM tenant_payment_config
WHERE tenant_id = $1
    AND enabled = TRUE
LIMIT 1
`

func (q *Queries) GetEnabledTenantPaymentConfigByTenantID(ctx context.Context, tenantID uuid.UUID) (TenantPaymentConfig, error) {
	row := q.db.QueryRowContext(ctx, getEnabledTenantPaymentConfigByTenantID, tenantID)
	var i TenantPaymentConfig
	err := row.Scan(
		&i.TenantID,
		&i.Provider,
		&i.Enabled,
		&i.SecretKeyEncrypted,
		&i.WebhookSecretEncrypted,
		&i.SecretKeyHint,
		&i.WebhookSecretHint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantPaymentConfigByTenantID = `-- name: GetTenantPaymentConfigByTenantID :one
SELECT tenant_id, provider, enabled, secret_key_encrypted, webhook_secret_encrypted, secret_key_hint, webhook_secret_hint, created_at, updated_at
FROM tenant_payment_config
WHERE tenant_id = $1
LIMIT 1
`

func (q *Queries) GetTenantPaymentConfigByTenantID(ctx context.Context, tenantID uuid.UUID) (TenantPaymentConfig, error) {
	row := q.db.QueryRowContext(ctx, getTenantPaymentConfigByTenantID, tenantID)
	var i TenantPaymentConfig
	err := row.Scan(
		&i.TenantID,
		&i.Provider,
		&i.Enabled,
		&i.SecretKeyEncrypted,
		&i.WebhookSecretEncrypted,
		&i.SecretKeyHint,
		&i.WebhookSecretHint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTenantPaymentConfig = `-- name: UpsertTenantPaymentConfig :one
INSERT INTO tenant_payment_config (
        tenant_id,
        provider,
        enabled,
        secret_key_encrypted,
        webhook_secret_encrypted,
        secret_key_hint,
        webhook_secret_hint,
        updated_at
    )
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW()) ON CONFLICT (tenant_id) DO
UPDATE
SET provider = EXCLUDED.provider,
    enabled = EXCLUDED.enabled,
    secret_key_encrypted = EXCLUDED.secret_key_encrypted,
    webhook_secret_encrypted = EXCLUDED.webhook_secret_encrypted,
    secret_key_hint = EXCLUDED.secret_key_hint,
    webhook_secret_hint = EXCLUDED.webhook_secret_hint,
    updated_at = NOW()
RETURNING tenant_id, provider, enabled, secret_key_encrypted, webhook_secret_encrypted, secret_key_hint, webhook_secret_hint, created_at, updated_at
`

type UpsertTenantPaymentConfigParams struct {
	TenantID               uuid.UUID      `json:"tenant_id"`
	Provider               string         `json:"provider"`
	Enabled                bool           `json:"enabled"`
	SecretKeyEncrypted     sql.NullString `json:"secret_key_encrypted"`
	WebhookSecretEncrypted sql.NullString `json:"webhook_secret_encrypted"`
	SecretKeyHint          sql.NullString `json:"secret_key_hint"`
	WebhookSecretHint      sql.NullString `json:"webhook_secret_hint"`
}

func (q *Queries) UpsertTenantPaymentConfig(ctx context.Context, arg UpsertTenantPaymentConfigParams) (TenantPaymentConfig, error) {
	row := q.db.QueryRowContext(ctx, upsertTenantPaymentConfig,
		arg.TenantID,
		arg.Provider,
		arg.Enabled,
		arg.SecretKeyEncrypted,
		arg.WebhookSecretEncrypted,
		arg.SecretKeyHint,
		arg.WebhookSecretHint,
	)
	var i TenantPaymentConfig
	err := row.Scan(
		&i.TenantID,
		&i.Provider,
		&i.Enabled,
		&i.SecretKeyEncrypted,
		&i.WebhookSecretEncrypted,
		&i.SecretKeyHint,
		&i.WebhookSecretHint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
