// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package dbmodels

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createEpisodeBase = `-- name: CreateEpisodeBase :one
INSERT INTO episodes (
        id,
        series_id,
        public_id,
        title,
        order_index
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING id, series_id, public_id, title, order_index, created_at
`

type CreateEpisodeBaseParams struct {
	ID         uuid.UUID `json:"id"`
	SeriesID   uuid.UUID `json:"series_id"`
	PublicID   string    `json:"public_id"`
	Title      string    `json:"title"`
	OrderIndex int32     `json:"order_index"`
}

// エピソードのBaseレコードを作成する
func (q *Queries) CreateEpisodeBase(ctx context.Context, arg CreateEpisodeBaseParams) (Episode, error) {
	row := q.db.QueryRowContext(ctx, createEpisodeBase,
		arg.ID,
		arg.SeriesID,
		arg.PublicID,
		arg.Title,
		arg.OrderIndex,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.PublicID,
		&i.Title,
		&i.OrderIndex,
		&i.CreatedAt,
	)
	return i, err
}

const createSeriesBase = `-- name: CreateSeriesBase :one
INSERT INTO series (
        id,
        tenant_id,
        label_id,
        public_id,
        title,
        updated_at
    )
VALUES ($1, $2, $3, $4, $5, NOW())
RETURNING id, tenant_id, label_id, public_id, title, created_at, synopsis, reading_period_hours, is_published, published_at, created_by, updated_by, updated_at
`

type CreateSeriesBaseParams struct {
	ID       uuid.UUID     `json:"id"`
	TenantID uuid.UUID     `json:"tenant_id"`
	LabelID  uuid.NullUUID `json:"label_id"`
	PublicID string        `json:"public_id"`
	Title    string        `json:"title"`
}

func (q *Queries) CreateSeriesBase(ctx context.Context, arg CreateSeriesBaseParams) (Series, error) {
	row := q.db.QueryRowContext(ctx, createSeriesBase,
		arg.ID,
		arg.TenantID,
		arg.LabelID,
		arg.PublicID,
		arg.Title,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LabelID,
		&i.PublicID,
		&i.Title,
		&i.CreatedAt,
		&i.Synopsis,
		&i.ReadingPeriodHours,
		&i.IsPublished,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
        id,
        tenant_id,
        user_id,
        token_hash,
        expires_at
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, user_id, token_hash, expires_at, revoked_at, created_at
`

type CreateSessionParams struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEpisodeByPublicIDForTenant = `-- name: GetEpisodeByPublicIDForTenant :one
SELECT e.id,
    e.public_id,
    e.title,
    e.order_index,
    el.price,
    el.reading_period_hours,
    el.status,
    el.scheduled_at,
    el.published_at
FROM episodes e
    JOIN series s ON s.id = e.series_id
    JOIN episode_listings el ON el.episode_id = e.id
WHERE s.tenant_id = $1
    AND e.public_id = $2
LIMIT 1
`

type GetEpisodeByPublicIDForTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	PublicID string    `json:"public_id"`
}

type GetEpisodeByPublicIDForTenantRow struct {
	ID                 uuid.UUID     `json:"id"`
	PublicID           string        `json:"public_id"`
	Title              string        `json:"title"`
	OrderIndex         int32         `json:"order_index"`
	Price              int32         `json:"price"`
	ReadingPeriodHours sql.NullInt32 `json:"reading_period_hours"`
	Status             string        `json:"status"`
	ScheduledAt        sql.NullTime  `json:"scheduled_at"`
	PublishedAt        sql.NullTime  `json:"published_at"`
}

func (q *Queries) GetEpisodeByPublicIDForTenant(ctx context.Context, arg GetEpisodeByPublicIDForTenantParams) (GetEpisodeByPublicIDForTenantRow, error) {
	row := q.db.QueryRowContext(ctx, getEpisodeByPublicIDForTenant, arg.TenantID, arg.PublicID)
	var i GetEpisodeByPublicIDForTenantRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.OrderIndex,
		&i.Price,
		&i.ReadingPeriodHours,
		&i.Status,
		&i.ScheduledAt,
		&i.PublishedAt,
	)
	return i, err
}

const getLabelByPublicIDForTenant = `-- name: GetLabelByPublicIDForTenant :one
SELECT id, tenant_id, public_id, name, created_at
FROM labels
WHERE tenant_id = $1
    AND public_id = $2
LIMIT 1
`

type GetLabelByPublicIDForTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	PublicID string    `json:"public_id"`
}

func (q *Queries) GetLabelByPublicIDForTenant(ctx context.Context, arg GetLabelByPublicIDForTenantParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, getLabelByPublicIDForTenant, arg.TenantID, arg.PublicID)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PublicID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getSeriesByPublicIDForTenant = `-- name: GetSeriesByPublicIDForTenant :one
SELECT s.id,
    s.public_id,
    s.title,
    s.synopsis,
    s.is_published,
    s.published_at
FROM series s
WHERE s.tenant_id = $1
    AND s.public_id = $2
LIMIT 1
`

type GetSeriesByPublicIDForTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	PublicID string    `json:"public_id"`
}

type GetSeriesByPublicIDForTenantRow struct {
	ID          uuid.UUID      `json:"id"`
	PublicID    string         `json:"public_id"`
	Title       string         `json:"title"`
	Synopsis    sql.NullString `json:"synopsis"`
	IsPublished bool           `json:"is_published"`
	PublishedAt sql.NullTime   `json:"published_at"`
}

func (q *Queries) GetSeriesByPublicIDForTenant(ctx context.Context, arg GetSeriesByPublicIDForTenantParams) (GetSeriesByPublicIDForTenantRow, error) {
	row := q.db.QueryRowContext(ctx, getSeriesByPublicIDForTenant, arg.TenantID, arg.PublicID)
	var i GetSeriesByPublicIDForTenantRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.Synopsis,
		&i.IsPublished,
		&i.PublishedAt,
	)
	return i, err
}

const getSeriesDetail = `-- name: GetSeriesDetail :one
SELECT s.id,
    s.public_id,
    s.title,
    l.name AS label_name,
    s.synopsis,
    s.is_published,
    -- 複数のクリエイター情報をJSON配列として1カラムにまとめる
    COALESCE(
        json_agg(
            json_build_object(
                'name',
                c.name,
                'role',
                sc.role
            )
            ORDER BY sc.display_order ASC
        ) FILTER (
            WHERE c.id IS NOT NULL
        ),
        '[]'
    )::jsonb AS creators,
    COALESCE(
        (
            SELECT json_agg(
                    json_build_object(
                        'public_id',
                        e.public_id,
                        'title',
                        e.title,
                        'order_index',
                        e.order_index,
                        'price',
                        el.price,
                        'reading_period_hours',
                        el.reading_period_hours,
                        'status',
                        el.status,
                        'scheduled_at',
                        el.scheduled_at,
                        'published_at',
                        el.published_at
                    )
                    ORDER BY e.order_index ASC
                )
            FROM episodes e
                JOIN episode_listings el ON el.episode_id = e.id
            WHERE e.series_id = s.id
                AND el.status = 'published'
        ),
        '[]'
    )::jsonb AS episodes
FROM series s
    LEFT JOIN labels l ON s.label_id = l.id
    LEFT JOIN series_creators sc ON s.id = sc.series_id
    LEFT JOIN creators c ON sc.creator_id = c.id
WHERE s.public_id = $1
    AND s.tenant_id = $2
    AND s.is_published = true
GROUP BY s.id,
    l.id
`

type GetSeriesDetailParams struct {
	PublicID string    `json:"public_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetSeriesDetailRow struct {
	ID          uuid.UUID       `json:"id"`
	PublicID    string          `json:"public_id"`
	Title       string          `json:"title"`
	LabelName   sql.NullString  `json:"label_name"`
	Synopsis    sql.NullString  `json:"synopsis"`
	IsPublished bool            `json:"is_published"`
	Creators    json.RawMessage `json:"creators"`
	Episodes    json.RawMessage `json:"episodes"`
}

func (q *Queries) GetSeriesDetail(ctx context.Context, arg GetSeriesDetailParams) (GetSeriesDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getSeriesDetail, arg.PublicID, arg.TenantID)
	var i GetSeriesDetailRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.LabelName,
		&i.Synopsis,
		&i.IsPublished,
		&i.Creators,
		&i.Episodes,
	)
	return i, err
}

const getSessionByTokenHashForTenant = `-- name: GetSessionByTokenHashForTenant :one
SELECT id, tenant_id, user_id, token_hash, expires_at, revoked_at, created_at
FROM sessions
WHERE tenant_id = $1
    AND token_hash = $2
LIMIT 1
`

type GetSessionByTokenHashForTenantParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	TokenHash string    `json:"token_hash"`
}

func (q *Queries) GetSessionByTokenHashForTenant(ctx context.Context, arg GetSessionByTokenHashForTenantParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHashForTenant, arg.TenantID, arg.TokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantByDomain = `-- name: GetTenantByDomain :one
SELECT id, public_id, domain, subdomain, name, default_reading_period_hours, created_at
FROM tenants
WHERE domain = $1
    OR subdomain = $1
LIMIT 1
`

// ホスト名からテナントを特定する (Interceptorで使用)
func (q *Queries) GetTenantByDomain(ctx context.Context, domain sql.NullString) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByDomain, domain)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Domain,
		&i.Subdomain,
		&i.Name,
		&i.DefaultReadingPeriodHours,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantByPublicID = `-- name: GetTenantByPublicID :one
SELECT id, public_id, domain, subdomain, name, default_reading_period_hours, created_at
FROM tenants
WHERE public_id = $1
LIMIT 1
`

func (q *Queries) GetTenantByPublicID(ctx context.Context, publicID string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByPublicID, publicID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Domain,
		&i.Subdomain,
		&i.Name,
		&i.DefaultReadingPeriodHours,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantThemeByTenantID = `-- name: GetTenantThemeByTenantID :one
SELECT tenant_id, primary_color, secondary_color, accent_color, logo_url, updated_at
FROM tenant_themes
WHERE tenant_id = $1
`

func (q *Queries) GetTenantThemeByTenantID(ctx context.Context, tenantID uuid.UUID) (TenantTheme, error) {
	row := q.db.QueryRowContext(ctx, getTenantThemeByTenantID, tenantID)
	var i TenantTheme
	err := row.Scan(
		&i.TenantID,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.AccentColor,
		&i.LogoUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailForTenant = `-- name: GetUserByEmailForTenant :one
SELECT id, tenant_id, public_id, email, password_hash, role, name, created_at
FROM users
WHERE tenant_id = $1
    AND email = $2
LIMIT 1
`

type GetUserByEmailForTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Email    string    `json:"email"`
}

func (q *Queries) GetUserByEmailForTenant(ctx context.Context, arg GetUserByEmailForTenantParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailForTenant, arg.TenantID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PublicID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, public_id, email, password_hash, role, name, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PublicID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveSeries = `-- name: ListActiveSeries :many
SELECT s.id,
    s.public_id,
    s.title,
    s.synopsis,
    s.published_at
FROM series s
WHERE s.tenant_id = $1
    AND s.is_published = true
ORDER BY s.published_at DESC
`

type ListActiveSeriesRow struct {
	ID          uuid.UUID      `json:"id"`
	PublicID    string         `json:"public_id"`
	Title       string         `json:"title"`
	Synopsis    sql.NullString `json:"synopsis"`
	PublishedAt sql.NullTime   `json:"published_at"`
}

// 公開中のシリーズ一覧を取得する (テナントIDで絞り込み)
func (q *Queries) ListActiveSeries(ctx context.Context, tenantID uuid.UUID) ([]ListActiveSeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSeries, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSeriesRow
	for rows.Next() {
		var i ListActiveSeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Title,
			&i.Synopsis,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodesReadyToPublish = `-- name: ListEpisodesReadyToPublish :many
SELECT el.episode_id
FROM episode_listings el
WHERE el.status = 'scheduled'
    AND el.scheduled_at IS NOT NULL
    AND el.scheduled_at <= NOW()
`

func (q *Queries) ListEpisodesReadyToPublish(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listEpisodesReadyToPublish)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var episode_id uuid.UUID
		if err := rows.Scan(&episode_id); err != nil {
			return nil, err
		}
		items = append(items, episode_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedEpisodesBySeries = `-- name: ListPublishedEpisodesBySeries :many
SELECT e.id,
    e.series_id,
    e.public_id,
    e.title,
    e.order_index,
    e.created_at,
    el.price,
    el.reading_period_hours,
    el.status,
    el.scheduled_at,
    el.published_at
FROM episodes e
    JOIN series s ON s.id = e.series_id
    JOIN episode_listings el ON e.id = el.episode_id
WHERE s.tenant_id = $1
    AND e.series_id = $2
    AND el.status = 'published'
ORDER BY e.order_index ASC
`

type ListPublishedEpisodesBySeriesParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	SeriesID uuid.UUID `json:"series_id"`
}

type ListPublishedEpisodesBySeriesRow struct {
	ID                 uuid.UUID     `json:"id"`
	SeriesID           uuid.UUID     `json:"series_id"`
	PublicID           string        `json:"public_id"`
	Title              string        `json:"title"`
	OrderIndex         int32         `json:"order_index"`
	CreatedAt          time.Time     `json:"created_at"`
	Price              int32         `json:"price"`
	ReadingPeriodHours sql.NullInt32 `json:"reading_period_hours"`
	Status             string        `json:"status"`
	ScheduledAt        sql.NullTime  `json:"scheduled_at"`
	PublishedAt        sql.NullTime  `json:"published_at"`
}

func (q *Queries) ListPublishedEpisodesBySeries(ctx context.Context, arg ListPublishedEpisodesBySeriesParams) ([]ListPublishedEpisodesBySeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedEpisodesBySeries, arg.TenantID, arg.SeriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedEpisodesBySeriesRow
	for rows.Next() {
		var i ListPublishedEpisodesBySeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.PublicID,
			&i.Title,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.Price,
			&i.ReadingPeriodHours,
			&i.Status,
			&i.ScheduledAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesByTenant = `-- name: ListSeriesByTenant :many
SELECT s.id,
    s.public_id,
    s.title,
    s.synopsis,
    s.is_published,
    s.published_at
FROM series s
WHERE s.tenant_id = $1
ORDER BY s.created_at DESC
LIMIT $2 OFFSET $3
`

type ListSeriesByTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type ListSeriesByTenantRow struct {
	ID          uuid.UUID      `json:"id"`
	PublicID    string         `json:"public_id"`
	Title       string         `json:"title"`
	Synopsis    sql.NullString `json:"synopsis"`
	IsPublished bool           `json:"is_published"`
	PublishedAt sql.NullTime   `json:"published_at"`
}

func (q *Queries) ListSeriesByTenant(ctx context.Context, arg ListSeriesByTenantParams) ([]ListSeriesByTenantRow, error) {
	rows, err := q.db.QueryContext(ctx, listSeriesByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeriesByTenantRow
	for rows.Next() {
		var i ListSeriesByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Title,
			&i.Synopsis,
			&i.IsPublished,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEpisodePublished = `-- name: MarkEpisodePublished :exec
UPDATE episode_listings
SET status = 'published',
    published_at = NOW()
WHERE episode_id = $1
`

func (q *Queries) MarkEpisodePublished(ctx context.Context, episodeID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markEpisodePublished, episodeID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = NOW()
WHERE id = $1
    AND tenant_id = $2
`

type RevokeSessionParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.ExecContext(ctx, revokeSession, arg.ID, arg.TenantID)
	return err
}

const updateEpisodePublishScheduleByPublicIDForTenant = `-- name: UpdateEpisodePublishScheduleByPublicIDForTenant :exec
UPDATE episode_listings el
SET status = CASE
        WHEN $3 IS NULL THEN 'draft'
        ELSE 'scheduled'
    END,
    scheduled_at = $3,
    published_at = CASE
        WHEN $3 IS NULL THEN NULL
        ELSE el.published_at
    END
FROM episodes e
    JOIN series s ON s.id = e.series_id
WHERE el.episode_id = e.id
    AND s.tenant_id = $1
    AND e.public_id = $2
`

type UpdateEpisodePublishScheduleByPublicIDForTenantParams struct {
	TenantID    uuid.UUID    `json:"tenant_id"`
	PublicID    string       `json:"public_id"`
	ScheduledAt sql.NullTime `json:"scheduled_at"`
}

func (q *Queries) UpdateEpisodePublishScheduleByPublicIDForTenant(ctx context.Context, arg UpdateEpisodePublishScheduleByPublicIDForTenantParams) error {
	_, err := q.db.ExecContext(ctx, updateEpisodePublishScheduleByPublicIDForTenant, arg.TenantID, arg.PublicID, arg.ScheduledAt)
	return err
}

const updateSeriesBase = `-- name: UpdateSeriesBase :exec
UPDATE series
SET title = $2,
    label_id = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateSeriesBaseParams struct {
	ID      uuid.UUID     `json:"id"`
	Title   string        `json:"title"`
	LabelID uuid.NullUUID `json:"label_id"`
}

func (q *Queries) UpdateSeriesBase(ctx context.Context, arg UpdateSeriesBaseParams) error {
	_, err := q.db.ExecContext(ctx, updateSeriesBase, arg.ID, arg.Title, arg.LabelID)
	return err
}

const upsertEpisodeListing = `-- name: UpsertEpisodeListing :one
INSERT INTO episode_listings (
        episode_id,
        price,
        reading_period_hours,
        status,
        scheduled_at,
        published_at
    )
VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT (episode_id) DO
UPDATE
SET price = EXCLUDED.price,
    reading_period_hours = EXCLUDED.reading_period_hours,
    status = EXCLUDED.status,
    scheduled_at = EXCLUDED.scheduled_at,
    published_at = EXCLUDED.published_at
RETURNING episode_id, price, reading_period_hours, status, scheduled_at, published_at
`

type UpsertEpisodeListingParams struct {
	EpisodeID          uuid.UUID     `json:"episode_id"`
	Price              int32         `json:"price"`
	ReadingPeriodHours sql.NullInt32 `json:"reading_period_hours"`
	Status             string        `json:"status"`
	ScheduledAt        sql.NullTime  `json:"scheduled_at"`
	PublishedAt        sql.NullTime  `json:"published_at"`
}

func (q *Queries) UpsertEpisodeListing(ctx context.Context, arg UpsertEpisodeListingParams) (EpisodeListing, error) {
	row := q.db.QueryRowContext(ctx, upsertEpisodeListing,
		arg.EpisodeID,
		arg.Price,
		arg.ReadingPeriodHours,
		arg.Status,
		arg.ScheduledAt,
		arg.PublishedAt,
	)
	var i EpisodeListing
	err := row.Scan(
		&i.EpisodeID,
		&i.Price,
		&i.ReadingPeriodHours,
		&i.Status,
		&i.ScheduledAt,
		&i.PublishedAt,
	)
	return i, err
}

const upsertSeriesListing = `-- name: UpsertSeriesListing :one
UPDATE series
SET synopsis = $2,
    reading_period_hours = $3,
    is_published = $4,
    published_at = CASE
        WHEN $4 THEN COALESCE(series.published_at, NOW())
        ELSE NULL
    END,
    updated_at = NOW()
WHERE id = $1
RETURNING id AS series_id,
    synopsis,
    reading_period_hours,
    is_published,
    published_at
`

type UpsertSeriesListingParams struct {
	ID                 uuid.UUID      `json:"id"`
	Synopsis           sql.NullString `json:"synopsis"`
	ReadingPeriodHours sql.NullInt32  `json:"reading_period_hours"`
	IsPublished        bool           `json:"is_published"`
}

type UpsertSeriesListingRow struct {
	SeriesID           uuid.UUID      `json:"series_id"`
	Synopsis           sql.NullString `json:"synopsis"`
	ReadingPeriodHours sql.NullInt32  `json:"reading_period_hours"`
	IsPublished        bool           `json:"is_published"`
	PublishedAt        sql.NullTime   `json:"published_at"`
}

func (q *Queries) UpsertSeriesListing(ctx context.Context, arg UpsertSeriesListingParams) (UpsertSeriesListingRow, error) {
	row := q.db.QueryRowContext(ctx, upsertSeriesListing,
		arg.ID,
		arg.Synopsis,
		arg.ReadingPeriodHours,
		arg.IsPublished,
	)
	var i UpsertSeriesListingRow
	err := row.Scan(
		&i.SeriesID,
		&i.Synopsis,
		&i.ReadingPeriodHours,
		&i.IsPublished,
		&i.PublishedAt,
	)
	return i, err
}

const upsertTenantTheme = `-- name: UpsertTenantTheme :one
INSERT INTO tenant_themes (
        tenant_id,
        primary_color,
        secondary_color,
        accent_color,
        logo_url,
        updated_at
    )
VALUES ($1, $2, $3, $4, $5, NOW()) ON CONFLICT (tenant_id) DO
UPDATE
SET primary_color = EXCLUDED.primary_color,
    secondary_color = EXCLUDED.secondary_color,
    accent_color = EXCLUDED.accent_color,
    logo_url = EXCLUDED.logo_url,
    updated_at = NOW()
RETURNING tenant_id, primary_color, secondary_color, accent_color, logo_url, updated_at
`

type UpsertTenantThemeParams struct {
	TenantID       uuid.UUID      `json:"tenant_id"`
	PrimaryColor   string         `json:"primary_color"`
	SecondaryColor string         `json:"secondary_color"`
	AccentColor    string         `json:"accent_color"`
	LogoUrl        sql.NullString `json:"logo_url"`
}

func (q *Queries) UpsertTenantTheme(ctx context.Context, arg UpsertTenantThemeParams) (TenantTheme, error) {
	row := q.db.QueryRowContext(ctx, upsertTenantTheme,
		arg.TenantID,
		arg.PrimaryColor,
		arg.SecondaryColor,
		arg.AccentColor,
		arg.LogoUrl,
	)
	var i TenantTheme
	err := row.Scan(
		&i.TenantID,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.AccentColor,
		&i.LogoUrl,
		&i.UpdatedAt,
	)
	return i, err
}
