// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package dbmodels

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countActiveTenants = `-- name: CountActiveTenants :one
SELECT COUNT(*)::int
FROM tenants
WHERE status = 'active'
`

func (q *Queries) CountActiveTenants(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, countActiveTenants)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countAllTenants = `-- name: CountAllTenants :one
SELECT COUNT(*)::int
FROM tenants
`

func (q *Queries) CountAllTenants(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, countAllTenants)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countPendingEndUsers = `-- name: CountPendingEndUsers :one
SELECT COUNT(*)::int
FROM users u
WHERE u.status = 'inactive'
    AND NOT EXISTS (
        SELECT 1
        FROM platform_user_roles pur
        WHERE pur.user_id = u.id
    )
`

func (q *Queries) CountPendingEndUsers(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, countPendingEndUsers)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countPlatformUsers = `-- name: CountPlatformUsers :one
SELECT COUNT(*)::int
FROM (
        SELECT DISTINCT user_id
        FROM platform_user_roles
    ) platform_users
`

// プラットフォーム管理ユーザー数を取得する (初期セットアップ判定用)
func (q *Queries) CountPlatformUsers(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, countPlatformUsers)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countSuspendedTenants = `-- name: CountSuspendedTenants :one
SELECT COUNT(*)::int
FROM tenants
WHERE status = 'suspended'
`

func (q *Queries) CountSuspendedTenants(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, countSuspendedTenants)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countTenantMembershipsByUserID = `-- name: CountTenantMembershipsByUserID :one
SELECT COUNT(*)::int
FROM tenant_memberships
WHERE user_id = $1
`

// ユーザーに紐づくテナントメンバーシップ件数を取得
func (q *Queries) CountTenantMembershipsByUserID(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countTenantMembershipsByUserID, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createEpisodeBase = `-- name: CreateEpisodeBase :one
INSERT INTO episodes (
        id,
        series_id,
        public_id,
        title,
        order_index
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING id, series_id, public_id, title, order_index, created_at
`

type CreateEpisodeBaseParams struct {
	ID         uuid.UUID `json:"id"`
	SeriesID   uuid.UUID `json:"series_id"`
	PublicID   string    `json:"public_id"`
	Title      string    `json:"title"`
	OrderIndex int32     `json:"order_index"`
}

// エピソードのBaseレコードを作成する
func (q *Queries) CreateEpisodeBase(ctx context.Context, arg CreateEpisodeBaseParams) (Episode, error) {
	row := q.db.QueryRowContext(ctx, createEpisodeBase,
		arg.ID,
		arg.SeriesID,
		arg.PublicID,
		arg.Title,
		arg.OrderIndex,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.PublicID,
		&i.Title,
		&i.OrderIndex,
		&i.CreatedAt,
	)
	return i, err
}

const createEpisodeImage = `-- name: CreateEpisodeImage :one
INSERT INTO episode_images (
        id,
        tenant_id,
        episode_id,
        storage_provider,
        object_key,
        image_url,
        content_type,
        file_size_bytes,
    display_order,
    width,
    height
    )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, tenant_id, episode_id, storage_provider, object_key, image_url, content_type, file_size_bytes, display_order, width, height, created_at
`

type CreateEpisodeImageParams struct {
	ID              uuid.UUID `json:"id"`
	TenantID        uuid.UUID `json:"tenant_id"`
	EpisodeID       uuid.UUID `json:"episode_id"`
	StorageProvider string    `json:"storage_provider"`
	ObjectKey       string    `json:"object_key"`
	ImageUrl        string    `json:"image_url"`
	ContentType     string    `json:"content_type"`
	FileSizeBytes   int64     `json:"file_size_bytes"`
	DisplayOrder    int32     `json:"display_order"`
	Width           int32     `json:"width"`
	Height          int32     `json:"height"`
}

func (q *Queries) CreateEpisodeImage(ctx context.Context, arg CreateEpisodeImageParams) (EpisodeImage, error) {
	row := q.db.QueryRowContext(ctx, createEpisodeImage,
		arg.ID,
		arg.TenantID,
		arg.EpisodeID,
		arg.StorageProvider,
		arg.ObjectKey,
		arg.ImageUrl,
		arg.ContentType,
		arg.FileSizeBytes,
		arg.DisplayOrder,
		arg.Width,
		arg.Height,
	)
	var i EpisodeImage
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EpisodeID,
		&i.StorageProvider,
		&i.ObjectKey,
		&i.ImageUrl,
		&i.ContentType,
		&i.FileSizeBytes,
		&i.DisplayOrder,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
	)
	return i, err
}

const createPlatformUserRole = `-- name: CreatePlatformUserRole :one
INSERT INTO platform_user_roles (id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, user_id, role, created_at
`

type CreatePlatformUserRoleParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

func (q *Queries) CreatePlatformUserRole(ctx context.Context, arg CreatePlatformUserRoleParams) (PlatformUserRole, error) {
	row := q.db.QueryRowContext(ctx, createPlatformUserRole, arg.ID, arg.UserID, arg.Role)
	var i PlatformUserRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createSeriesBase = `-- name: CreateSeriesBase :one
INSERT INTO series (
        id,
        tenant_id,
        label_id,
        public_id,
        title,
        updated_at
    )
VALUES ($1, $2, $3, $4, $5, NOW())
RETURNING id, tenant_id, label_id, public_id, title, created_at, synopsis, reading_period_hours, is_published, published_at, created_by, updated_by, updated_at
`

type CreateSeriesBaseParams struct {
	ID       uuid.UUID     `json:"id"`
	TenantID uuid.UUID     `json:"tenant_id"`
	LabelID  uuid.NullUUID `json:"label_id"`
	PublicID string        `json:"public_id"`
	Title    string        `json:"title"`
}

func (q *Queries) CreateSeriesBase(ctx context.Context, arg CreateSeriesBaseParams) (Series, error) {
	row := q.db.QueryRowContext(ctx, createSeriesBase,
		arg.ID,
		arg.TenantID,
		arg.LabelID,
		arg.PublicID,
		arg.Title,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LabelID,
		&i.PublicID,
		&i.Title,
		&i.CreatedAt,
		&i.Synopsis,
		&i.ReadingPeriodHours,
		&i.IsPublished,
		&i.PublishedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
        id,
    current_tenant_id,
        user_id,
        token_hash,
        expires_at
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING id, current_tenant_id, user_id, token_hash, expires_at, revoked_at, created_at
`

type CreateSessionParams struct {
	ID              uuid.UUID     `json:"id"`
	CurrentTenantID uuid.NullUUID `json:"current_tenant_id"`
	UserID          uuid.UUID     `json:"user_id"`
	TokenHash       string        `json:"token_hash"`
	ExpiresAt       time.Time     `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.CurrentTenantID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CurrentTenantID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (id, public_id, domain, name, status)
VALUES ($1, $2, $3, $4, 'active')
RETURNING id, public_id, domain, name, default_reading_period_hours, created_at, status
`

type CreateTenantParams struct {
	ID       uuid.UUID `json:"id"`
	PublicID string    `json:"public_id"`
	Domain   string    `json:"domain"`
	Name     string    `json:"name"`
}

// プラットフォーム管理者向けテナント作成
func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, createTenant,
		arg.ID,
		arg.PublicID,
		arg.Domain,
		arg.Name,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Domain,
		&i.Name,
		&i.DefaultReadingPeriodHours,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const createTenantMemberRole = `-- name: CreateTenantMemberRole :one
INSERT INTO tenant_member_roles (id, membership_id, role)
VALUES ($1, $2, $3)
RETURNING id, membership_id, role, created_at
`

type CreateTenantMemberRoleParams struct {
	ID           uuid.UUID `json:"id"`
	MembershipID uuid.UUID `json:"membership_id"`
	Role         string    `json:"role"`
}

func (q *Queries) CreateTenantMemberRole(ctx context.Context, arg CreateTenantMemberRoleParams) (TenantMemberRole, error) {
	row := q.db.QueryRowContext(ctx, createTenantMemberRole, arg.ID, arg.MembershipID, arg.Role)
	var i TenantMemberRole
	err := row.Scan(
		&i.ID,
		&i.MembershipID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createTenantMembership = `-- name: CreateTenantMembership :one
INSERT INTO tenant_memberships (id, user_id, tenant_id, status)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, tenant_id, status, created_at
`

type CreateTenantMembershipParams struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Status   string    `json:"status"`
}

func (q *Queries) CreateTenantMembership(ctx context.Context, arg CreateTenantMembershipParams) (TenantMembership, error) {
	row := q.db.QueryRowContext(ctx, createTenantMembership,
		arg.ID,
		arg.UserID,
		arg.TenantID,
		arg.Status,
	)
	var i TenantMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, public_id, email, password_hash, name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, public_id, email, password_hash, name, created_at, status
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	PublicID     string    `json:"public_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Name         string    `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.PublicID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const deletePlatformUserRolesByUserID = `-- name: DeletePlatformUserRolesByUserID :exec
DELETE FROM platform_user_roles
WHERE user_id = $1
`

func (q *Queries) DeletePlatformUserRolesByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePlatformUserRolesByUserID, userID)
	return err
}

const deleteTenantMemberRolesByMembershipID = `-- name: DeleteTenantMemberRolesByMembershipID :exec
DELETE FROM tenant_member_roles
WHERE membership_id = $1
`

func (q *Queries) DeleteTenantMemberRolesByMembershipID(ctx context.Context, membershipID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTenantMemberRolesByMembershipID, membershipID)
	return err
}

const deleteTenantMembership = `-- name: DeleteTenantMembership :exec
DELETE FROM tenant_memberships
WHERE id = $1
`

func (q *Queries) DeleteTenantMembership(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTenantMembership, id)
	return err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users
WHERE id = $1
`

// ユーザーを物理削除（外部キー制約により関連データも削除）
func (q *Queries) DeleteUserByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserByID, id)
	return err
}

const getEpisodeByPublicIDForTenant = `-- name: GetEpisodeByPublicIDForTenant :one
SELECT e.id,
    e.public_id,
    e.title,
    e.order_index,
    el.price,
    el.reading_period_hours,
    el.status,
    el.scheduled_at,
    el.published_at
FROM episodes e
    JOIN series s ON s.id = e.series_id
    JOIN episode_listings el ON el.episode_id = e.id
WHERE s.tenant_id = $1
    AND e.public_id = $2
LIMIT 1
`

type GetEpisodeByPublicIDForTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	PublicID string    `json:"public_id"`
}

type GetEpisodeByPublicIDForTenantRow struct {
	ID                 uuid.UUID     `json:"id"`
	PublicID           string        `json:"public_id"`
	Title              string        `json:"title"`
	OrderIndex         int32         `json:"order_index"`
	Price              int32         `json:"price"`
	ReadingPeriodHours sql.NullInt32 `json:"reading_period_hours"`
	Status             string        `json:"status"`
	ScheduledAt        sql.NullTime  `json:"scheduled_at"`
	PublishedAt        sql.NullTime  `json:"published_at"`
}

func (q *Queries) GetEpisodeByPublicIDForTenant(ctx context.Context, arg GetEpisodeByPublicIDForTenantParams) (GetEpisodeByPublicIDForTenantRow, error) {
	row := q.db.QueryRowContext(ctx, getEpisodeByPublicIDForTenant, arg.TenantID, arg.PublicID)
	var i GetEpisodeByPublicIDForTenantRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.OrderIndex,
		&i.Price,
		&i.ReadingPeriodHours,
		&i.Status,
		&i.ScheduledAt,
		&i.PublishedAt,
	)
	return i, err
}

const getLabelByPublicIDForTenant = `-- name: GetLabelByPublicIDForTenant :one
SELECT id, tenant_id, public_id, name, created_at
FROM labels
WHERE tenant_id = $1
    AND public_id = $2
LIMIT 1
`

type GetLabelByPublicIDForTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	PublicID string    `json:"public_id"`
}

func (q *Queries) GetLabelByPublicIDForTenant(ctx context.Context, arg GetLabelByPublicIDForTenantParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, getLabelByPublicIDForTenant, arg.TenantID, arg.PublicID)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PublicID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getPlatformOperatorByPublicID = `-- name: GetPlatformOperatorByPublicID :one
SELECT u.id,
    u.public_id,
    u.email,
    u.name,
    COALESCE(
        (
            SELECT pur.role
            FROM platform_user_roles pur
            WHERE pur.user_id = u.id
            ORDER BY CASE
                    WHEN pur.role = 'platform_super_admin' THEN 3
                    WHEN pur.role = 'super-admin' THEN 3
                    WHEN pur.role = 'platform_operator' THEN 2
                    WHEN pur.role = 'platform-operator' THEN 2
                    WHEN pur.role = 'platform_auditor' THEN 1
                    ELSE 0
                END DESC,
                pur.role ASC
            LIMIT 1
        ),
        ''::text
    )::text AS role,
    u.status,
    u.created_at
FROM users u
WHERE u.public_id = $1
    AND EXISTS (
        SELECT 1
        FROM platform_user_roles pur
        WHERE pur.user_id = u.id
    )
LIMIT 1
`

type GetPlatformOperatorByPublicIDRow struct {
	ID        uuid.UUID `json:"id"`
	PublicID  string    `json:"public_id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	Role      string    `json:"role"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetPlatformOperatorByPublicID(ctx context.Context, publicID string) (GetPlatformOperatorByPublicIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPlatformOperatorByPublicID, publicID)
	var i GetPlatformOperatorByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPublishedEpisodeByPublicIDForTenant = `-- name: GetPublishedEpisodeByPublicIDForTenant :one
SELECT e.id,
    e.public_id,
    e.title,
    e.order_index,
    el.price,
    el.reading_period_hours,
    el.status,
    el.scheduled_at,
    el.published_at
FROM episodes e
    JOIN series s ON s.id = e.series_id
    JOIN episode_listings el ON el.episode_id = e.id
WHERE s.tenant_id = $1
    AND e.public_id = $2
    AND s.is_published = true
    AND s.published_at IS NOT NULL
    AND s.published_at <= NOW()
    AND el.status = 'published'
    AND el.published_at IS NOT NULL
    AND el.published_at <= NOW()
LIMIT 1
`

type GetPublishedEpisodeByPublicIDForTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	PublicID string    `json:"public_id"`
}

type GetPublishedEpisodeByPublicIDForTenantRow struct {
	ID                 uuid.UUID     `json:"id"`
	PublicID           string        `json:"public_id"`
	Title              string        `json:"title"`
	OrderIndex         int32         `json:"order_index"`
	Price              int32         `json:"price"`
	ReadingPeriodHours sql.NullInt32 `json:"reading_period_hours"`
	Status             string        `json:"status"`
	ScheduledAt        sql.NullTime  `json:"scheduled_at"`
	PublishedAt        sql.NullTime  `json:"published_at"`
}

func (q *Queries) GetPublishedEpisodeByPublicIDForTenant(ctx context.Context, arg GetPublishedEpisodeByPublicIDForTenantParams) (GetPublishedEpisodeByPublicIDForTenantRow, error) {
	row := q.db.QueryRowContext(ctx, getPublishedEpisodeByPublicIDForTenant, arg.TenantID, arg.PublicID)
	var i GetPublishedEpisodeByPublicIDForTenantRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.OrderIndex,
		&i.Price,
		&i.ReadingPeriodHours,
		&i.Status,
		&i.ScheduledAt,
		&i.PublishedAt,
	)
	return i, err
}

const getSeriesByPublicIDForTenant = `-- name: GetSeriesByPublicIDForTenant :one
SELECT s.id,
    s.public_id,
    s.title,
    s.synopsis,
    s.is_published,
    s.published_at
FROM series s
WHERE s.tenant_id = $1
    AND s.public_id = $2
LIMIT 1
`

type GetSeriesByPublicIDForTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	PublicID string    `json:"public_id"`
}

type GetSeriesByPublicIDForTenantRow struct {
	ID          uuid.UUID      `json:"id"`
	PublicID    string         `json:"public_id"`
	Title       string         `json:"title"`
	Synopsis    sql.NullString `json:"synopsis"`
	IsPublished bool           `json:"is_published"`
	PublishedAt sql.NullTime   `json:"published_at"`
}

func (q *Queries) GetSeriesByPublicIDForTenant(ctx context.Context, arg GetSeriesByPublicIDForTenantParams) (GetSeriesByPublicIDForTenantRow, error) {
	row := q.db.QueryRowContext(ctx, getSeriesByPublicIDForTenant, arg.TenantID, arg.PublicID)
	var i GetSeriesByPublicIDForTenantRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.Synopsis,
		&i.IsPublished,
		&i.PublishedAt,
	)
	return i, err
}

const getSeriesDetail = `-- name: GetSeriesDetail :one
SELECT s.id,
    s.public_id,
    s.title,
    l.name AS label_name,
    s.synopsis,
    s.is_published,
    s.published_at,
    -- 複数のクリエイター情報をJSON配列として1カラムにまとめる
    COALESCE(
        json_agg(
            json_build_object(
                'name',
                c.name,
                'role',
                sc.role
            )
            ORDER BY sc.display_order ASC
        ) FILTER (
            WHERE c.id IS NOT NULL
        ),
        '[]'
    )::jsonb AS creators,
    COALESCE(
        (
            SELECT json_agg(
                    json_build_object(
                        'public_id',
                        e.public_id,
                        'title',
                        e.title,
                        'order_index',
                        e.order_index,
                        'price',
                        el.price,
                        'reading_period_hours',
                        el.reading_period_hours,
                        'status',
                        el.status,
                        'scheduled_at',
                        el.scheduled_at,
                        'published_at',
                        el.published_at
                    )
                    ORDER BY e.order_index ASC
                )
            FROM episodes e
                JOIN episode_listings el ON el.episode_id = e.id
            WHERE e.series_id = s.id
                AND el.status = 'published'
                AND el.published_at IS NOT NULL
                AND el.published_at <= NOW()
        ),
        '[]'
    )::jsonb AS episodes
FROM series s
    LEFT JOIN labels l ON s.label_id = l.id
    LEFT JOIN series_creators sc ON s.id = sc.series_id
    LEFT JOIN creators c ON sc.creator_id = c.id
WHERE s.public_id = $1
    AND s.tenant_id = $2
GROUP BY s.id,
    l.id
`

type GetSeriesDetailParams struct {
	PublicID string    `json:"public_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetSeriesDetailRow struct {
	ID          uuid.UUID       `json:"id"`
	PublicID    string          `json:"public_id"`
	Title       string          `json:"title"`
	LabelName   sql.NullString  `json:"label_name"`
	Synopsis    sql.NullString  `json:"synopsis"`
	IsPublished bool            `json:"is_published"`
	PublishedAt sql.NullTime    `json:"published_at"`
	Creators    json.RawMessage `json:"creators"`
	Episodes    json.RawMessage `json:"episodes"`
}

func (q *Queries) GetSeriesDetail(ctx context.Context, arg GetSeriesDetailParams) (GetSeriesDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getSeriesDetail, arg.PublicID, arg.TenantID)
	var i GetSeriesDetailRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.LabelName,
		&i.Synopsis,
		&i.IsPublished,
		&i.PublishedAt,
		&i.Creators,
		&i.Episodes,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, current_tenant_id, user_id, token_hash, expires_at, revoked_at, created_at
FROM sessions
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CurrentTenantID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByTokenHashForTenant = `-- name: GetSessionByTokenHashForTenant :one
SELECT id, current_tenant_id, user_id, token_hash, expires_at, revoked_at, created_at
FROM sessions
WHERE current_tenant_id = $1
    AND token_hash = $2
LIMIT 1
`

type GetSessionByTokenHashForTenantParams struct {
	CurrentTenantID uuid.NullUUID `json:"current_tenant_id"`
	TokenHash       string        `json:"token_hash"`
}

func (q *Queries) GetSessionByTokenHashForTenant(ctx context.Context, arg GetSessionByTokenHashForTenantParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHashForTenant, arg.CurrentTenantID, arg.TokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CurrentTenantID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantByDomain = `-- name: GetTenantByDomain :one
SELECT id, public_id, domain, name, default_reading_period_hours, created_at, status
FROM tenants
WHERE domain = $1
LIMIT 1
`

// ホスト名からテナントを特定する (Interceptorで使用)
func (q *Queries) GetTenantByDomain(ctx context.Context, domain string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByDomain, domain)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Domain,
		&i.Name,
		&i.DefaultReadingPeriodHours,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const getTenantByPublicID = `-- name: GetTenantByPublicID :one
SELECT id, public_id, domain, name, default_reading_period_hours, created_at, status
FROM tenants
WHERE public_id = $1
LIMIT 1
`

func (q *Queries) GetTenantByPublicID(ctx context.Context, publicID string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByPublicID, publicID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Domain,
		&i.Name,
		&i.DefaultReadingPeriodHours,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const getTenantMembershipByUserAndTenant = `-- name: GetTenantMembershipByUserAndTenant :one
SELECT tm.id, tm.user_id, tm.tenant_id, tm.status, tm.created_at
FROM tenant_memberships tm
WHERE tm.user_id = $1
    AND tm.tenant_id = $2
LIMIT 1
`

type GetTenantMembershipByUserAndTenantParams struct {
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

// ユーザーとテナントIDでメンバーシップを取得する
func (q *Queries) GetTenantMembershipByUserAndTenant(ctx context.Context, arg GetTenantMembershipByUserAndTenantParams) (TenantMembership, error) {
	row := q.db.QueryRowContext(ctx, getTenantMembershipByUserAndTenant, arg.UserID, arg.TenantID)
	var i TenantMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantThemeByTenantID = `-- name: GetTenantThemeByTenantID :one
SELECT tenant_id, primary_color, secondary_color, accent_color, logo_url, updated_at
FROM tenant_themes
WHERE tenant_id = $1
`

func (q *Queries) GetTenantThemeByTenantID(ctx context.Context, tenantID uuid.UUID) (TenantTheme, error) {
	row := q.db.QueryRowContext(ctx, getTenantThemeByTenantID, tenantID)
	var i TenantTheme
	err := row.Scan(
		&i.TenantID,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.AccentColor,
		&i.LogoUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantsByEndUser = `-- name: GetTenantsByEndUser :many
SELECT DISTINCT t.id,
    t.public_id
FROM tenants t
    JOIN tenant_memberships tm ON tm.tenant_id = t.id
WHERE tm.user_id = $1
    AND tm.status = 'active'
ORDER BY t.created_at DESC
`

type GetTenantsByEndUserRow struct {
	ID       uuid.UUID `json:"id"`
	PublicID string    `json:"public_id"`
}

// エンドユーザーが所属するテナント一覧を取得
func (q *Queries) GetTenantsByEndUser(ctx context.Context, userID uuid.UUID) ([]GetTenantsByEndUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getTenantsByEndUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTenantsByEndUserRow
	for rows.Next() {
		var i GetTenantsByEndUserRow
		if err := rows.Scan(&i.ID, &i.PublicID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, public_id, email, password_hash, name, created_at, status
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const getUserByEmailForTenant = `-- name: GetUserByEmailForTenant :one
SELECT u.id, u.public_id, u.email, u.password_hash, u.name, u.created_at, u.status
FROM users u
    JOIN tenant_memberships tm ON tm.user_id = u.id
    AND tm.tenant_id = $1
    AND tm.status = 'active'
WHERE u.email = $2
LIMIT 1
`

type GetUserByEmailForTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Email    string    `json:"email"`
}

func (q *Queries) GetUserByEmailForTenant(ctx context.Context, arg GetUserByEmailForTenantParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailForTenant, arg.TenantID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, public_id, email, password_hash, name, created_at, status
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const getUserByPublicID = `-- name: GetUserByPublicID :one
SELECT u.id,
    u.public_id,
    u.name,
    u.email,
    u.status,
    u.created_at
FROM users u
WHERE u.public_id = $1
LIMIT 1
`

type GetUserByPublicIDRow struct {
	ID        uuid.UUID `json:"id"`
	PublicID  string    `json:"public_id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

// public_idでユーザーを取得
func (q *Queries) GetUserByPublicID(ctx context.Context, publicID string) (GetUserByPublicIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByPublicID, publicID)
	var i GetUserByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveSeries = `-- name: ListActiveSeries :many
SELECT s.id,
    s.public_id,
    s.title,
    s.synopsis,
    s.published_at
FROM series s
WHERE s.tenant_id = $1
    AND s.is_published = true
    AND s.published_at IS NOT NULL
    AND s.published_at <= NOW()
ORDER BY s.published_at DESC
LIMIT $2 OFFSET $3
`

type ListActiveSeriesParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type ListActiveSeriesRow struct {
	ID          uuid.UUID      `json:"id"`
	PublicID    string         `json:"public_id"`
	Title       string         `json:"title"`
	Synopsis    sql.NullString `json:"synopsis"`
	PublishedAt sql.NullTime   `json:"published_at"`
}

// 公開中のシリーズ一覧を取得する (テナントIDで絞り込み)
func (q *Queries) ListActiveSeries(ctx context.Context, arg ListActiveSeriesParams) ([]ListActiveSeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSeries, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSeriesRow
	for rows.Next() {
		var i ListActiveSeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Title,
			&i.Synopsis,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndUsers = `-- name: ListEndUsers :many
SELECT u.id,
    u.public_id,
    u.name,
    u.email,
    u.status,
    u.created_at
FROM users u
WHERE NOT EXISTS (
        SELECT 1
        FROM platform_user_roles pur
        WHERE pur.user_id = u.id
    )
    AND NOT EXISTS (
        SELECT 1
        FROM tenant_memberships tm
        WHERE tm.user_id = u.id
    )
    AND ($1::timestamptz IS NULL OR u.created_at >= $1::timestamptz)
    AND ($2::timestamptz IS NULL OR u.created_at <= $2::timestamptz)
    AND ($3::text = '' OR u.status = $3::text)
ORDER BY u.created_at DESC
LIMIT $5 OFFSET $4
`

type ListEndUsersParams struct {
	CreatedAfter  sql.NullTime   `json:"created_after"`
	CreatedBefore sql.NullTime   `json:"created_before"`
	Status        sql.NullString `json:"status"`
	Offset        int32          `json:"offset"`
	Limit         int32          `json:"limit"`
}

type ListEndUsersRow struct {
	ID        uuid.UUID `json:"id"`
	PublicID  string    `json:"public_id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

// エンドユーザー（platform_user_roles未保持）の一覧取得
func (q *Queries) ListEndUsers(ctx context.Context, arg ListEndUsersParams) ([]ListEndUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listEndUsers,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEndUsersRow
	for rows.Next() {
		var i ListEndUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Name,
			&i.Email,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodeImagesByEpisodeID = `-- name: ListEpisodeImagesByEpisodeID :many
SELECT id, tenant_id, episode_id, storage_provider, object_key, image_url, content_type, file_size_bytes, display_order, width, height, created_at
FROM episode_images
WHERE episode_id = $1
ORDER BY display_order ASC,
    created_at ASC
`

func (q *Queries) ListEpisodeImagesByEpisodeID(ctx context.Context, episodeID uuid.UUID) ([]EpisodeImage, error) {
	rows, err := q.db.QueryContext(ctx, listEpisodeImagesByEpisodeID, episodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EpisodeImage
	for rows.Next() {
		var i EpisodeImage
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EpisodeID,
			&i.StorageProvider,
			&i.ObjectKey,
			&i.ImageUrl,
			&i.ContentType,
			&i.FileSizeBytes,
			&i.DisplayOrder,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodesReadyToPublish = `-- name: ListEpisodesReadyToPublish :many
SELECT el.episode_id
FROM episode_listings el
WHERE el.status = 'scheduled'
    AND el.scheduled_at IS NOT NULL
    AND el.scheduled_at <= NOW()
`

func (q *Queries) ListEpisodesReadyToPublish(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listEpisodesReadyToPublish)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var episode_id uuid.UUID
		if err := rows.Scan(&episode_id); err != nil {
			return nil, err
		}
		items = append(items, episode_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformOperators = `-- name: ListPlatformOperators :many
SELECT u.public_id,
    u.email,
    u.name,
    COALESCE(
        (
            SELECT pur.role
            FROM platform_user_roles pur
            WHERE pur.user_id = u.id
            ORDER BY CASE
                    WHEN pur.role = 'platform_super_admin' THEN 3
                    WHEN pur.role = 'super-admin' THEN 3
                    WHEN pur.role = 'platform_operator' THEN 2
                    WHEN pur.role = 'platform-operator' THEN 2
                    WHEN pur.role = 'platform_auditor' THEN 1
                    ELSE 0
                END DESC,
                pur.role ASC
            LIMIT 1
        ),
        ''::text
    )::text AS role,
    u.status,
    u.created_at
FROM users u
WHERE EXISTS (
        SELECT 1
        FROM platform_user_roles pur
        WHERE pur.user_id = u.id
    )
ORDER BY u.created_at DESC
`

type ListPlatformOperatorsRow struct {
	PublicID  string    `json:"public_id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	Role      string    `json:"role"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListPlatformOperators(ctx context.Context) ([]ListPlatformOperatorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlatformOperators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlatformOperatorsRow
	for rows.Next() {
		var i ListPlatformOperatorsRow
		if err := rows.Scan(
			&i.PublicID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformUserRoles = `-- name: ListPlatformUserRoles :many
SELECT role
FROM platform_user_roles
WHERE user_id = $1
ORDER BY role
`

func (q *Queries) ListPlatformUserRoles(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPlatformUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedEpisodesBySeries = `-- name: ListPublishedEpisodesBySeries :many
SELECT e.id,
    e.series_id,
    e.public_id,
    e.title,
    e.order_index,
    e.created_at,
    el.price,
    el.reading_period_hours,
    el.status,
    el.scheduled_at,
    el.published_at
FROM episodes e
    JOIN series s ON s.id = e.series_id
    JOIN episode_listings el ON e.id = el.episode_id
WHERE s.tenant_id = $1
    AND e.series_id = $2
    AND el.status = 'published'
ORDER BY e.order_index ASC
`

type ListPublishedEpisodesBySeriesParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	SeriesID uuid.UUID `json:"series_id"`
}

type ListPublishedEpisodesBySeriesRow struct {
	ID                 uuid.UUID     `json:"id"`
	SeriesID           uuid.UUID     `json:"series_id"`
	PublicID           string        `json:"public_id"`
	Title              string        `json:"title"`
	OrderIndex         int32         `json:"order_index"`
	CreatedAt          time.Time     `json:"created_at"`
	Price              int32         `json:"price"`
	ReadingPeriodHours sql.NullInt32 `json:"reading_period_hours"`
	Status             string        `json:"status"`
	ScheduledAt        sql.NullTime  `json:"scheduled_at"`
	PublishedAt        sql.NullTime  `json:"published_at"`
}

func (q *Queries) ListPublishedEpisodesBySeries(ctx context.Context, arg ListPublishedEpisodesBySeriesParams) ([]ListPublishedEpisodesBySeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedEpisodesBySeries, arg.TenantID, arg.SeriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedEpisodesBySeriesRow
	for rows.Next() {
		var i ListPublishedEpisodesBySeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.PublicID,
			&i.Title,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.Price,
			&i.ReadingPeriodHours,
			&i.Status,
			&i.ScheduledAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPlatformEvents = `-- name: ListRecentPlatformEvents :many
SELECT event_type,
    action,
    target,
    actor,
    occurred_at
FROM (
        SELECT 'tenant_created'::text AS event_type,
            'Tenant Created'::text AS action,
            t.public_id::text AS target,
            ''::text AS actor,
            t.created_at AS occurred_at
        FROM tenants t
        UNION ALL
        SELECT 'operator_role_granted'::text AS event_type,
            'Operator Role Granted'::text AS action,
            u.public_id::text AS target,
            ''::text AS actor,
            pur.created_at AS occurred_at
        FROM platform_user_roles pur
            JOIN users u ON u.id = pur.user_id
        UNION ALL
        SELECT 'end_user_created'::text AS event_type,
            'End User Created'::text AS action,
            u.public_id::text AS target,
            ''::text AS actor,
            u.created_at AS occurred_at
        FROM users u
        WHERE NOT EXISTS (
                SELECT 1
                FROM platform_user_roles pur
                WHERE pur.user_id = u.id
            )
    ) events
ORDER BY occurred_at DESC
LIMIT $1
`

type ListRecentPlatformEventsRow struct {
	EventType  string    `json:"event_type"`
	Action     string    `json:"action"`
	Target     string    `json:"target"`
	Actor      string    `json:"actor"`
	OccurredAt time.Time `json:"occurred_at"`
}

func (q *Queries) ListRecentPlatformEvents(ctx context.Context, limit int32) ([]ListRecentPlatformEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentPlatformEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentPlatformEventsRow
	for rows.Next() {
		var i ListRecentPlatformEventsRow
		if err := rows.Scan(
			&i.EventType,
			&i.Action,
			&i.Target,
			&i.Actor,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesByTenant = `-- name: ListSeriesByTenant :many
SELECT s.id,
    s.public_id,
    s.title,
    s.synopsis,
    s.is_published,
    s.published_at
FROM series s
WHERE s.tenant_id = $1
ORDER BY s.created_at DESC
LIMIT $2 OFFSET $3
`

type ListSeriesByTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type ListSeriesByTenantRow struct {
	ID          uuid.UUID      `json:"id"`
	PublicID    string         `json:"public_id"`
	Title       string         `json:"title"`
	Synopsis    sql.NullString `json:"synopsis"`
	IsPublished bool           `json:"is_published"`
	PublishedAt sql.NullTime   `json:"published_at"`
}

func (q *Queries) ListSeriesByTenant(ctx context.Context, arg ListSeriesByTenantParams) ([]ListSeriesByTenantRow, error) {
	rows, err := q.db.QueryContext(ctx, listSeriesByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeriesByTenantRow
	for rows.Next() {
		var i ListSeriesByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Title,
			&i.Synopsis,
			&i.IsPublished,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantMemberships = `-- name: ListTenantMemberships :many
SELECT u.id AS user_id,
    u.public_id,
    u.name,
    u.email,
    COALESCE(
        (
            SELECT tmr.role
            FROM tenant_member_roles tmr
            WHERE tmr.membership_id = tm.id
            ORDER BY CASE
                    WHEN tmr.role = 'tenant_admin' THEN 3
                    WHEN tmr.role = 'admin' THEN 3
                    WHEN tmr.role = 'tenant_editor' THEN 2
                    WHEN tmr.role = 'editor' THEN 2
                    WHEN tmr.role = 'tenant_auditor' THEN 1
                    WHEN tmr.role = 'auditor' THEN 1
                    ELSE 0
                END DESC,
                tmr.role ASC
            LIMIT 1
        ),
        ''::text
    )::text AS role,
    tm.status,
    tm.created_at
FROM tenant_memberships tm
    JOIN users u ON u.id = tm.user_id
WHERE tm.tenant_id = $1
ORDER BY tm.created_at DESC
LIMIT $3 OFFSET $2
`

type ListTenantMembershipsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Offset   int32     `json:"offset"`
	Limit    int32     `json:"limit"`
}

type ListTenantMembershipsRow struct {
	UserID    uuid.UUID `json:"user_id"`
	PublicID  string    `json:"public_id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Role      string    `json:"role"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

// テナントに所属するメンバー一覧を取得する
func (q *Queries) ListTenantMemberships(ctx context.Context, arg ListTenantMembershipsParams) ([]ListTenantMembershipsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTenantMemberships, arg.TenantID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTenantMembershipsRow
	for rows.Next() {
		var i ListTenantMembershipsRow
		if err := rows.Scan(
			&i.UserID,
			&i.PublicID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantRolesByUserAndTenant = `-- name: ListTenantRolesByUserAndTenant :many
SELECT tmr.role
FROM tenant_memberships tm
    JOIN tenant_member_roles tmr ON tmr.membership_id = tm.id
WHERE tm.user_id = $1
    AND tm.tenant_id = $2
    AND tm.status = 'active'
ORDER BY tmr.role
`

type ListTenantRolesByUserAndTenantParams struct {
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) ListTenantRolesByUserAndTenant(ctx context.Context, arg ListTenantRolesByUserAndTenantParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTenantRolesByUserAndTenant, arg.UserID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, public_id, domain, name, default_reading_period_hours, created_at, status
FROM tenants
WHERE ($1::text = '' OR name ILIKE '%' || $1::text || '%')
  AND ($2::text = '' OR public_id ILIKE '%' || $2::text || '%')
  AND ($3::text = '' OR status = $3::text)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListTenantsParams struct {
	FilterName     sql.NullString `json:"filter_name"`
	FilterPublicID sql.NullString `json:"filter_public_id"`
	FilterStatus   sql.NullString `json:"filter_status"`
	Offset         int32          `json:"offset"`
	Limit          int32          `json:"limit"`
}

// プラットフォーム管理者向けテナント一覧取得（フィルタ対応）
func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error) {
	rows, err := q.db.QueryContext(ctx, listTenants,
		arg.FilterName,
		arg.FilterPublicID,
		arg.FilterStatus,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Domain,
			&i.Name,
			&i.DefaultReadingPeriodHours,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEpisodePublished = `-- name: MarkEpisodePublished :exec
UPDATE episode_listings
SET status = 'published',
    published_at = NOW()
WHERE episode_id = $1
`

func (q *Queries) MarkEpisodePublished(ctx context.Context, episodeID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markEpisodePublished, episodeID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeSession, id)
	return err
}

const terminateUserSessions = `-- name: TerminateUserSessions :exec
UPDATE sessions
SET revoked_at = NOW()
WHERE user_id = $1
    AND revoked_at IS NULL
`

// ユーザーの全セッションを失効させる
func (q *Queries) TerminateUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, terminateUserSessions, userID)
	return err
}

const updateEpisodePublishScheduleByPublicIDForTenant = `-- name: UpdateEpisodePublishScheduleByPublicIDForTenant :exec
UPDATE episode_listings el
SET status = CASE
        WHEN $3 IS NULL THEN 'draft'
        ELSE 'scheduled'
    END,
    scheduled_at = $3,
    published_at = CASE
        WHEN $3 IS NULL THEN NULL
        ELSE el.published_at
    END
FROM episodes e
    JOIN series s ON s.id = e.series_id
WHERE el.episode_id = e.id
    AND s.tenant_id = $1
    AND e.public_id = $2
`

type UpdateEpisodePublishScheduleByPublicIDForTenantParams struct {
	TenantID    uuid.UUID    `json:"tenant_id"`
	PublicID    string       `json:"public_id"`
	ScheduledAt sql.NullTime `json:"scheduled_at"`
}

func (q *Queries) UpdateEpisodePublishScheduleByPublicIDForTenant(ctx context.Context, arg UpdateEpisodePublishScheduleByPublicIDForTenantParams) error {
	_, err := q.db.ExecContext(ctx, updateEpisodePublishScheduleByPublicIDForTenant, arg.TenantID, arg.PublicID, arg.ScheduledAt)
	return err
}

const updateSeriesBase = `-- name: UpdateSeriesBase :exec
UPDATE series
SET title = $2,
    label_id = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateSeriesBaseParams struct {
	ID      uuid.UUID     `json:"id"`
	Title   string        `json:"title"`
	LabelID uuid.NullUUID `json:"label_id"`
}

func (q *Queries) UpdateSeriesBase(ctx context.Context, arg UpdateSeriesBaseParams) error {
	_, err := q.db.ExecContext(ctx, updateSeriesBase, arg.ID, arg.Title, arg.LabelID)
	return err
}

const updateTenantInfo = `-- name: UpdateTenantInfo :one
UPDATE tenants
SET name = $2, domain = $3
WHERE public_id = $1
RETURNING id, public_id, domain, name, default_reading_period_hours, created_at, status
`

type UpdateTenantInfoParams struct {
	PublicID string `json:"public_id"`
	Name     string `json:"name"`
	Domain   string `json:"domain"`
}

// テナントの名前・ドメインを更新する
func (q *Queries) UpdateTenantInfo(ctx context.Context, arg UpdateTenantInfoParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, updateTenantInfo, arg.PublicID, arg.Name, arg.Domain)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Domain,
		&i.Name,
		&i.DefaultReadingPeriodHours,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const updateTenantStatus = `-- name: UpdateTenantStatus :one
UPDATE tenants
SET status = $2
WHERE public_id = $1
RETURNING id, public_id, domain, name, default_reading_period_hours, created_at, status
`

type UpdateTenantStatusParams struct {
	PublicID string `json:"public_id"`
	Status   string `json:"status"`
}

// テナントの状態 (active / suspended) を更新する
func (q *Queries) UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, updateTenantStatus, arg.PublicID, arg.Status)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Domain,
		&i.Name,
		&i.DefaultReadingPeriodHours,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET status = $2
WHERE public_id = $1
RETURNING id, public_id, email, password_hash, name, created_at, status
`

type UpdateUserStatusParams struct {
	PublicID string `json:"public_id"`
	Status   string `json:"status"`
}

// ユーザーのステータスを更新
func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserStatus, arg.PublicID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const upsertEpisodeListing = `-- name: UpsertEpisodeListing :one
INSERT INTO episode_listings (
        episode_id,
        price,
        reading_period_hours,
        status,
        scheduled_at,
        published_at
    )
VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT (episode_id) DO
UPDATE
SET price = EXCLUDED.price,
    reading_period_hours = EXCLUDED.reading_period_hours,
    status = EXCLUDED.status,
    scheduled_at = EXCLUDED.scheduled_at,
    published_at = EXCLUDED.published_at
RETURNING episode_id, price, reading_period_hours, status, scheduled_at, published_at
`

type UpsertEpisodeListingParams struct {
	EpisodeID          uuid.UUID     `json:"episode_id"`
	Price              int32         `json:"price"`
	ReadingPeriodHours sql.NullInt32 `json:"reading_period_hours"`
	Status             string        `json:"status"`
	ScheduledAt        sql.NullTime  `json:"scheduled_at"`
	PublishedAt        sql.NullTime  `json:"published_at"`
}

func (q *Queries) UpsertEpisodeListing(ctx context.Context, arg UpsertEpisodeListingParams) (EpisodeListing, error) {
	row := q.db.QueryRowContext(ctx, upsertEpisodeListing,
		arg.EpisodeID,
		arg.Price,
		arg.ReadingPeriodHours,
		arg.Status,
		arg.ScheduledAt,
		arg.PublishedAt,
	)
	var i EpisodeListing
	err := row.Scan(
		&i.EpisodeID,
		&i.Price,
		&i.ReadingPeriodHours,
		&i.Status,
		&i.ScheduledAt,
		&i.PublishedAt,
	)
	return i, err
}

const upsertSeriesListing = `-- name: UpsertSeriesListing :one
UPDATE series
SET synopsis = $2,
    reading_period_hours = $3,
    is_published = $4,
    published_at = CASE
        WHEN $4 THEN COALESCE(series.published_at, NOW())
        ELSE NULL
    END,
    updated_at = NOW()
WHERE id = $1
RETURNING id AS series_id,
    synopsis,
    reading_period_hours,
    is_published,
    published_at
`

type UpsertSeriesListingParams struct {
	ID                 uuid.UUID      `json:"id"`
	Synopsis           sql.NullString `json:"synopsis"`
	ReadingPeriodHours sql.NullInt32  `json:"reading_period_hours"`
	IsPublished        bool           `json:"is_published"`
}

type UpsertSeriesListingRow struct {
	SeriesID           uuid.UUID      `json:"series_id"`
	Synopsis           sql.NullString `json:"synopsis"`
	ReadingPeriodHours sql.NullInt32  `json:"reading_period_hours"`
	IsPublished        bool           `json:"is_published"`
	PublishedAt        sql.NullTime   `json:"published_at"`
}

func (q *Queries) UpsertSeriesListing(ctx context.Context, arg UpsertSeriesListingParams) (UpsertSeriesListingRow, error) {
	row := q.db.QueryRowContext(ctx, upsertSeriesListing,
		arg.ID,
		arg.Synopsis,
		arg.ReadingPeriodHours,
		arg.IsPublished,
	)
	var i UpsertSeriesListingRow
	err := row.Scan(
		&i.SeriesID,
		&i.Synopsis,
		&i.ReadingPeriodHours,
		&i.IsPublished,
		&i.PublishedAt,
	)
	return i, err
}

const upsertTenantTheme = `-- name: UpsertTenantTheme :one
INSERT INTO tenant_themes (
        tenant_id,
        primary_color,
        secondary_color,
        accent_color,
        logo_url,
        updated_at
    )
VALUES ($1, $2, $3, $4, $5, NOW()) ON CONFLICT (tenant_id) DO
UPDATE
SET primary_color = EXCLUDED.primary_color,
    secondary_color = EXCLUDED.secondary_color,
    accent_color = EXCLUDED.accent_color,
    logo_url = EXCLUDED.logo_url,
    updated_at = NOW()
RETURNING tenant_id, primary_color, secondary_color, accent_color, logo_url, updated_at
`

type UpsertTenantThemeParams struct {
	TenantID       uuid.UUID      `json:"tenant_id"`
	PrimaryColor   string         `json:"primary_color"`
	SecondaryColor string         `json:"secondary_color"`
	AccentColor    string         `json:"accent_color"`
	LogoUrl        sql.NullString `json:"logo_url"`
}

func (q *Queries) UpsertTenantTheme(ctx context.Context, arg UpsertTenantThemeParams) (TenantTheme, error) {
	row := q.db.QueryRowContext(ctx, upsertTenantTheme,
		arg.TenantID,
		arg.PrimaryColor,
		arg.SecondaryColor,
		arg.AccentColor,
		arg.LogoUrl,
	)
	var i TenantTheme
	err := row.Scan(
		&i.TenantID,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.AccentColor,
		&i.LogoUrl,
		&i.UpdatedAt,
	)
	return i, err
}
