// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbmodels

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountActiveTenants(ctx context.Context) (int32, error)
	CountAllTenants(ctx context.Context) (int32, error)
	CountPendingEndUsers(ctx context.Context) (int32, error)
	// プラットフォーム管理ユーザー数を取得する (初期セットアップ判定用)
	CountPlatformUsers(ctx context.Context) (int32, error)
	CountSuspendedTenants(ctx context.Context) (int32, error)
	// ユーザーに紐づくテナントメンバーシップ件数を取得
	CountTenantMembershipsByUserID(ctx context.Context, userID uuid.UUID) (int32, error)
	// エピソードのBaseレコードを作成する
	CreateEpisodeBase(ctx context.Context, arg CreateEpisodeBaseParams) (Episode, error)
	CreateEpisodeImage(ctx context.Context, arg CreateEpisodeImageParams) (EpisodeImage, error)
	CreatePlatformUserRole(ctx context.Context, arg CreatePlatformUserRoleParams) (PlatformUserRole, error)
	CreateSeriesBase(ctx context.Context, arg CreateSeriesBaseParams) (Series, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// プラットフォーム管理者向けテナント作成
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateTenantMemberRole(ctx context.Context, arg CreateTenantMemberRoleParams) (TenantMemberRole, error)
	CreateTenantMembership(ctx context.Context, arg CreateTenantMembershipParams) (TenantMembership, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePlatformUserRolesByUserID(ctx context.Context, userID uuid.UUID) error
	DeleteTenantMemberRolesByMembershipID(ctx context.Context, membershipID uuid.UUID) error
	DeleteTenantMembership(ctx context.Context, id uuid.UUID) error
	// ユーザーを物理削除（外部キー制約により関連データも削除）
	DeleteUserByID(ctx context.Context, id uuid.UUID) error
	GetEpisodeByPublicIDForTenant(ctx context.Context, arg GetEpisodeByPublicIDForTenantParams) (GetEpisodeByPublicIDForTenantRow, error)
	GetLabelByPublicIDForTenant(ctx context.Context, arg GetLabelByPublicIDForTenantParams) (Label, error)
	GetPlatformOperatorByPublicID(ctx context.Context, publicID string) (GetPlatformOperatorByPublicIDRow, error)
	GetPublishedEpisodeByPublicIDForTenant(ctx context.Context, arg GetPublishedEpisodeByPublicIDForTenantParams) (GetPublishedEpisodeByPublicIDForTenantRow, error)
	GetSeriesByPublicIDForTenant(ctx context.Context, arg GetSeriesByPublicIDForTenantParams) (GetSeriesByPublicIDForTenantRow, error)
	GetSeriesDetail(ctx context.Context, arg GetSeriesDetailParams) (GetSeriesDetailRow, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error)
	GetSessionByTokenHashForTenant(ctx context.Context, arg GetSessionByTokenHashForTenantParams) (Session, error)
	// 候補ホスト名の順序を保ったまま最初に一致したテナントを返す
	GetTenantByDomains(ctx context.Context, domains []string) (Tenant, error)
	GetTenantByPublicID(ctx context.Context, publicID string) (Tenant, error)
	// ユーザーとテナントIDでメンバーシップを取得する
	GetTenantMembershipByUserAndTenant(ctx context.Context, arg GetTenantMembershipByUserAndTenantParams) (TenantMembership, error)
	GetTenantThemeByTenantID(ctx context.Context, tenantID uuid.UUID) (TenantTheme, error)
	// エンドユーザーが所属するテナント一覧を取得
	GetTenantsByEndUser(ctx context.Context, userID uuid.UUID) ([]GetTenantsByEndUserRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByEmailForTenant(ctx context.Context, arg GetUserByEmailForTenantParams) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// public_idでユーザーを取得
	GetUserByPublicID(ctx context.Context, publicID string) (GetUserByPublicIDRow, error)
	// 管理操作監査ログを記録する
	InsertAdminAuditLog(ctx context.Context, arg InsertAdminAuditLogParams) error
	// 公開中のシリーズ一覧を取得する (テナントIDで絞り込み)
	ListActiveSeries(ctx context.Context, arg ListActiveSeriesParams) ([]ListActiveSeriesRow, error)
	// 管理操作監査ログ一覧取得（フィルタ対応）
	ListAdminAuditLogs(ctx context.Context, arg ListAdminAuditLogsParams) ([]AdminAuditLog, error)
	// エンドユーザー（platform_user_roles未保持）の一覧取得
	ListEndUsers(ctx context.Context, arg ListEndUsersParams) ([]ListEndUsersRow, error)
	ListEpisodeImagesByEpisodeID(ctx context.Context, episodeID uuid.UUID) ([]EpisodeImage, error)
	ListEpisodesReadyToPublish(ctx context.Context) ([]uuid.UUID, error)
	ListPlatformOperators(ctx context.Context) ([]ListPlatformOperatorsRow, error)
	ListPlatformUserRoles(ctx context.Context, userID uuid.UUID) ([]string, error)
	ListPublishedEpisodesBySeries(ctx context.Context, arg ListPublishedEpisodesBySeriesParams) ([]ListPublishedEpisodesBySeriesRow, error)
	ListRecentPlatformEvents(ctx context.Context, limit int32) ([]ListRecentPlatformEventsRow, error)
	ListSeriesByTenant(ctx context.Context, arg ListSeriesByTenantParams) ([]ListSeriesByTenantRow, error)
	// テナントに所属するメンバー一覧を取得する
	ListTenantMemberships(ctx context.Context, arg ListTenantMembershipsParams) ([]ListTenantMembershipsRow, error)
	ListTenantRolesByUserAndTenant(ctx context.Context, arg ListTenantRolesByUserAndTenantParams) ([]string, error)
	// プラットフォーム管理者向けテナント一覧取得（フィルタ対応）
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error)
	MarkEpisodePublished(ctx context.Context, episodeID uuid.UUID) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	// ユーザーの全セッションを失効させる
	TerminateUserSessions(ctx context.Context, userID uuid.UUID) error
	UpdateEpisodePublishScheduleByPublicIDForTenant(ctx context.Context, arg UpdateEpisodePublishScheduleByPublicIDForTenantParams) error
	UpdateSeriesBase(ctx context.Context, arg UpdateSeriesBaseParams) error
	// テナントの名前・ドメインを更新する
	UpdateTenantInfo(ctx context.Context, arg UpdateTenantInfoParams) (Tenant, error)
	// テナントの状態 (active / suspended) を更新する
	UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) (Tenant, error)
	// ユーザーのステータスを更新
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error)
	UpsertEpisodeListing(ctx context.Context, arg UpsertEpisodeListingParams) (EpisodeListing, error)
	UpsertSeriesListing(ctx context.Context, arg UpsertSeriesListingParams) (UpsertSeriesListingRow, error)
	UpsertTenantTheme(ctx context.Context, arg UpsertTenantThemeParams) (TenantTheme, error)
}

var _ Querier = (*Queries)(nil)
