// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package dbmodels

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countActiveTenants = `-- name: CountActiveTenants :one
SELECT COUNT(*)::int
FROM tenants
WHERE status = 'active'
`

func (q *Queries) CountActiveTenants(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, countActiveTenants)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countAllTenants = `-- name: CountAllTenants :one
SELECT COUNT(*)::int
FROM tenants
`

func (q *Queries) CountAllTenants(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, countAllTenants)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countDraftEpisodesForTenant = `-- name: CountDraftEpisodesForTenant :one
SELECT COUNT(*)::int AS draft_episode_count
FROM episodes e
    JOIN series s ON s.id = e.series_id
    JOIN episode_listings el ON el.episode_id = e.id
WHERE s.tenant_id = $1
    AND el.status = 'draft'
`

// テナントの下書きエピソード数を取得する（ダッシュボード用）
func (q *Queries) CountDraftEpisodesForTenant(ctx context.Context, tenantID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countDraftEpisodesForTenant, tenantID)
	var draft_episode_count int32
	err := row.Scan(&draft_episode_count)
	return draft_episode_count, err
}

const countPendingEndUsers = `-- name: CountPendingEndUsers :one
SELECT COUNT(*)::int
FROM users u
WHERE u.status = 'inactive'
    AND NOT EXISTS (
        SELECT 1
        FROM tenant_user_roles tur
        WHERE tur.user_id = u.id
    )
`

func (q *Queries) CountPendingEndUsers(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, countPendingEndUsers)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countPlatformUsers = `-- name: CountPlatformUsers :one
SELECT COUNT(*)::int
FROM platform_users
`

// プラットフォーム管理ユーザー数を取得する (初期セットアップ判定用)
func (q *Queries) CountPlatformUsers(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, countPlatformUsers)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countPublishedSeriesForTenant = `-- name: CountPublishedSeriesForTenant :one
SELECT COUNT(*)::int AS published_series_count
FROM series
WHERE tenant_id = $1
    AND is_published = true
`

// テナントの公開中シリーズ数を取得する（ダッシュボード用）
func (q *Queries) CountPublishedSeriesForTenant(ctx context.Context, tenantID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countPublishedSeriesForTenant, tenantID)
	var published_series_count int32
	err := row.Scan(&published_series_count)
	return published_series_count, err
}

const countScheduledEpisodesForTenant = `-- name: CountScheduledEpisodesForTenant :one
SELECT COUNT(*)::int AS scheduled_episode_count
FROM episodes e
    JOIN series s ON s.id = e.series_id
    JOIN episode_listings el ON el.episode_id = e.id
WHERE s.tenant_id = $1
    AND el.status = 'scheduled'
`

// テナントの予約済みエピソード数を取得する（ダッシュボード用）
func (q *Queries) CountScheduledEpisodesForTenant(ctx context.Context, tenantID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countScheduledEpisodesForTenant, tenantID)
	var scheduled_episode_count int32
	err := row.Scan(&scheduled_episode_count)
	return scheduled_episode_count, err
}

const countSuspendedTenants = `-- name: CountSuspendedTenants :one
SELECT COUNT(*)::int
FROM tenants
WHERE status = 'suspended'
`

func (q *Queries) CountSuspendedTenants(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, countSuspendedTenants)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createCreator = `-- name: CreateCreator :one
INSERT INTO creators (
        id,
        tenant_id,
        public_id,
        name,
        profile_text
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, public_id, name, profile_text, created_at
`

type CreateCreatorParams struct {
	ID          uuid.UUID      `json:"id"`
	TenantID    uuid.UUID      `json:"tenant_id"`
	PublicID    string         `json:"public_id"`
	Name        string         `json:"name"`
	ProfileText sql.NullString `json:"profile_text"`
}

func (q *Queries) CreateCreator(ctx context.Context, arg CreateCreatorParams) (Creator, error) {
	row := q.db.QueryRowContext(ctx, createCreator,
		arg.ID,
		arg.TenantID,
		arg.PublicID,
		arg.Name,
		arg.ProfileText,
	)
	var i Creator
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PublicID,
		&i.Name,
		&i.ProfileText,
		&i.CreatedAt,
	)
	return i, err
}

const createEpisodeBase = `-- name: CreateEpisodeBase :one
INSERT INTO episodes (
        id,
        series_id,
        public_id,
        title,
        order_index
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING id, series_id, public_id, title, order_index, created_at
`

type CreateEpisodeBaseParams struct {
	ID         uuid.UUID `json:"id"`
	SeriesID   uuid.UUID `json:"series_id"`
	PublicID   string    `json:"public_id"`
	Title      string    `json:"title"`
	OrderIndex int32     `json:"order_index"`
}

// エピソードのBaseレコードを作成する
func (q *Queries) CreateEpisodeBase(ctx context.Context, arg CreateEpisodeBaseParams) (Episode, error) {
	row := q.db.QueryRowContext(ctx, createEpisodeBase,
		arg.ID,
		arg.SeriesID,
		arg.PublicID,
		arg.Title,
		arg.OrderIndex,
	)
	var i Episode
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.PublicID,
		&i.Title,
		&i.OrderIndex,
		&i.CreatedAt,
	)
	return i, err
}

const createEpisodeImage = `-- name: CreateEpisodeImage :one
INSERT INTO episode_images (
        id,
        tenant_id,
        episode_id,
        storage_provider,
        object_key,
        image_url,
        content_type,
        file_size_bytes,
    display_order,
    width,
    height
    )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, tenant_id, episode_id, storage_provider, object_key, image_url, content_type, file_size_bytes, display_order, width, height, created_at
`

type CreateEpisodeImageParams struct {
	ID              uuid.UUID `json:"id"`
	TenantID        uuid.UUID `json:"tenant_id"`
	EpisodeID       uuid.UUID `json:"episode_id"`
	StorageProvider string    `json:"storage_provider"`
	ObjectKey       string    `json:"object_key"`
	ImageUrl        string    `json:"image_url"`
	ContentType     string    `json:"content_type"`
	FileSizeBytes   int64     `json:"file_size_bytes"`
	DisplayOrder    int32     `json:"display_order"`
	Width           int32     `json:"width"`
	Height          int32     `json:"height"`
}

func (q *Queries) CreateEpisodeImage(ctx context.Context, arg CreateEpisodeImageParams) (EpisodeImage, error) {
	row := q.db.QueryRowContext(ctx, createEpisodeImage,
		arg.ID,
		arg.TenantID,
		arg.EpisodeID,
		arg.StorageProvider,
		arg.ObjectKey,
		arg.ImageUrl,
		arg.ContentType,
		arg.FileSizeBytes,
		arg.DisplayOrder,
		arg.Width,
		arg.Height,
	)
	var i EpisodeImage
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EpisodeID,
		&i.StorageProvider,
		&i.ObjectKey,
		&i.ImageUrl,
		&i.ContentType,
		&i.FileSizeBytes,
		&i.DisplayOrder,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
	)
	return i, err
}

const createLabel = `-- name: CreateLabel :one
INSERT INTO labels (
        id,
        tenant_id,
        public_id,
        name
    )
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, public_id, name, created_at
`

type CreateLabelParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	PublicID string    `json:"public_id"`
	Name     string    `json:"name"`
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, createLabel,
		arg.ID,
		arg.TenantID,
		arg.PublicID,
		arg.Name,
	)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PublicID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createPlatformSession = `-- name: CreatePlatformSession :one
INSERT INTO platform_sessions (
        id,
        platform_user_id,
        token_hash,
        expires_at
    )
VALUES ($1, $2, $3, $4)
RETURNING id, platform_user_id, token_hash, expires_at, revoked_at, created_at
`

type CreatePlatformSessionParams struct {
	ID             uuid.UUID `json:"id"`
	PlatformUserID uuid.UUID `json:"platform_user_id"`
	TokenHash      string    `json:"token_hash"`
	ExpiresAt      time.Time `json:"expires_at"`
}

func (q *Queries) CreatePlatformSession(ctx context.Context, arg CreatePlatformSessionParams) (PlatformSession, error) {
	row := q.db.QueryRowContext(ctx, createPlatformSession,
		arg.ID,
		arg.PlatformUserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i PlatformSession
	err := row.Scan(
		&i.ID,
		&i.PlatformUserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPlatformUser = `-- name: CreatePlatformUser :one
INSERT INTO platform_users (id, public_id, email, password_hash, name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, public_id, email, password_hash, name, status, created_at
`

type CreatePlatformUserParams struct {
	ID           uuid.UUID `json:"id"`
	PublicID     string    `json:"public_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Name         string    `json:"name"`
}

func (q *Queries) CreatePlatformUser(ctx context.Context, arg CreatePlatformUserParams) (PlatformUser, error) {
	row := q.db.QueryRowContext(ctx, createPlatformUser,
		arg.ID,
		arg.PublicID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
	)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createPlatformUserRole = `-- name: CreatePlatformUserRole :one
INSERT INTO platform_user_roles (id, platform_user_id, role)
VALUES ($1, $2, $3)
RETURNING id, role, created_at, platform_user_id
`

type CreatePlatformUserRoleParams struct {
	ID             uuid.UUID `json:"id"`
	PlatformUserID uuid.UUID `json:"platform_user_id"`
	Role           string    `json:"role"`
}

func (q *Queries) CreatePlatformUserRole(ctx context.Context, arg CreatePlatformUserRoleParams) (PlatformUserRole, error) {
	row := q.db.QueryRowContext(ctx, createPlatformUserRole, arg.ID, arg.PlatformUserID, arg.Role)
	var i PlatformUserRole
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.CreatedAt,
		&i.PlatformUserID,
	)
	return i, err
}

const createSeriesBase = `-- name: CreateSeriesBase :one
INSERT INTO series (
        id,
        tenant_id,
        label_id,
        public_id,
        title
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, label_id, public_id, title, created_at, is_published, published_at, updated_at
`

type CreateSeriesBaseParams struct {
	ID       uuid.UUID     `json:"id"`
	TenantID uuid.UUID     `json:"tenant_id"`
	LabelID  uuid.NullUUID `json:"label_id"`
	PublicID string        `json:"public_id"`
	Title    string        `json:"title"`
}

func (q *Queries) CreateSeriesBase(ctx context.Context, arg CreateSeriesBaseParams) (Series, error) {
	row := q.db.QueryRowContext(ctx, createSeriesBase,
		arg.ID,
		arg.TenantID,
		arg.LabelID,
		arg.PublicID,
		arg.Title,
	)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LabelID,
		&i.PublicID,
		&i.Title,
		&i.CreatedAt,
		&i.IsPublished,
		&i.PublishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSeriesCreator = `-- name: CreateSeriesCreator :exec
INSERT INTO series_creators (
        series_id,
        creator_id,
        role,
        display_order
    )
VALUES ($1, $2, $3, $4)
`

type CreateSeriesCreatorParams struct {
	SeriesID     uuid.UUID `json:"series_id"`
	CreatorID    uuid.UUID `json:"creator_id"`
	Role         string    `json:"role"`
	DisplayOrder int32     `json:"display_order"`
}

func (q *Queries) CreateSeriesCreator(ctx context.Context, arg CreateSeriesCreatorParams) error {
	_, err := q.db.ExecContext(ctx, createSeriesCreator,
		arg.SeriesID,
		arg.CreatorID,
		arg.Role,
		arg.DisplayOrder,
	)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
        id,
        tenant_id,
        user_id,
        token_hash,
        expires_at
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, user_id, token_hash, expires_at, revoked_at, created_at
`

type CreateSessionParams struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (id, public_id, domain, admin_domain, name, status)
VALUES ($1, $2, $3, $4, $5, 'active')
RETURNING id, public_id, domain, name, default_reading_period_hours, created_at, status, admin_domain
`

type CreateTenantParams struct {
	ID          uuid.UUID      `json:"id"`
	PublicID    string         `json:"public_id"`
	Domain      string         `json:"domain"`
	AdminDomain sql.NullString `json:"admin_domain"`
	Name        string         `json:"name"`
}

// プラットフォーム管理者向けテナント作成
func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, createTenant,
		arg.ID,
		arg.PublicID,
		arg.Domain,
		arg.AdminDomain,
		arg.Name,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Domain,
		&i.Name,
		&i.DefaultReadingPeriodHours,
		&i.CreatedAt,
		&i.Status,
		&i.AdminDomain,
	)
	return i, err
}

const createTenantConfig = `-- name: CreateTenantConfig :one
INSERT INTO tenant_config (tenant_id, copyright_text, site_description, site_tagline)
VALUES ($1, $2, $3, $4)
RETURNING tenant_id, copyright_text, site_description, created_at, updated_at, site_tagline
`

type CreateTenantConfigParams struct {
	TenantID        uuid.UUID      `json:"tenant_id"`
	CopyrightText   sql.NullString `json:"copyright_text"`
	SiteDescription sql.NullString `json:"site_description"`
	SiteTagline     sql.NullString `json:"site_tagline"`
}

func (q *Queries) CreateTenantConfig(ctx context.Context, arg CreateTenantConfigParams) (TenantConfig, error) {
	row := q.db.QueryRowContext(ctx, createTenantConfig,
		arg.TenantID,
		arg.CopyrightText,
		arg.SiteDescription,
		arg.SiteTagline,
	)
	var i TenantConfig
	err := row.Scan(
		&i.TenantID,
		&i.CopyrightText,
		&i.SiteDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SiteTagline,
	)
	return i, err
}

const createTenantUserRole = `-- name: CreateTenantUserRole :one
INSERT INTO tenant_user_roles (id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, user_id, role, created_at
`

type CreateTenantUserRoleParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

func (q *Queries) CreateTenantUserRole(ctx context.Context, arg CreateTenantUserRoleParams) (TenantUserRole, error) {
	row := q.db.QueryRowContext(ctx, createTenantUserRole, arg.ID, arg.UserID, arg.Role)
	var i TenantUserRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, tenant_id, public_id, email, password_hash, name)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, public_id, email, password_hash, name, created_at, status, tenant_id
`

type CreateUserParams struct {
	ID           uuid.UUID     `json:"id"`
	TenantID     uuid.NullUUID `json:"tenant_id"`
	PublicID     string        `json:"public_id"`
	Email        string        `json:"email"`
	PasswordHash string        `json:"password_hash"`
	Name         string        `json:"name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.TenantID,
		arg.PublicID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.Status,
		&i.TenantID,
	)
	return i, err
}

const deletePlatformUserRolesByPlatformUserID = `-- name: DeletePlatformUserRolesByPlatformUserID :exec
DELETE FROM platform_user_roles
WHERE platform_user_id = $1
`

func (q *Queries) DeletePlatformUserRolesByPlatformUserID(ctx context.Context, platformUserID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePlatformUserRolesByPlatformUserID, platformUserID)
	return err
}

const deleteSeriesCreatorsBySeriesID = `-- name: DeleteSeriesCreatorsBySeriesID :exec
DELETE FROM series_creators
WHERE series_id = $1
`

func (q *Queries) DeleteSeriesCreatorsBySeriesID(ctx context.Context, seriesID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSeriesCreatorsBySeriesID, seriesID)
	return err
}

const deleteTenantUserRolesByUserID = `-- name: DeleteTenantUserRolesByUserID :exec
DELETE FROM tenant_user_roles
WHERE user_id = $1
`

// テナントユーザーのロールをすべて削除する
func (q *Queries) DeleteTenantUserRolesByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTenantUserRolesByUserID, userID)
	return err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users
WHERE id = $1
`

// ユーザーを物理削除（外部キー制約により関連データも削除）
func (q *Queries) DeleteUserByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserByID, id)
	return err
}

const getAdminTenantByDomains = `-- name: GetAdminTenantByDomains :one
SELECT t.id, t.public_id, t.domain, t.name, t.default_reading_period_hours, t.created_at, t.status, t.admin_domain
FROM unnest($1::text[]) WITH ORDINALITY AS candidate(domain, ord)
JOIN tenants t
    ON t.admin_domain = candidate.domain
    OR (
        t.admin_domain IS NULL
        AND candidate.domain = CONCAT('admin.', t.domain)
    )
ORDER BY candidate.ord
LIMIT 1
`

// 候補ホスト名の順序を保ったまま admin_domain、または admin.{domain} フォールバックで一致したテナントを返す
func (q *Queries) GetAdminTenantByDomains(ctx context.Context, domains []string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getAdminTenantByDomains, pq.Array(domains))
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Domain,
		&i.Name,
		&i.DefaultReadingPeriodHours,
		&i.CreatedAt,
		&i.Status,
		&i.AdminDomain,
	)
	return i, err
}

const getCreatorByPublicIDForTenant = `-- name: GetCreatorByPublicIDForTenant :one
SELECT id,
    tenant_id,
    public_id,
    name,
    profile_text,
    created_at
FROM creators
WHERE tenant_id = $1
    AND public_id = $2
LIMIT 1
`

type GetCreatorByPublicIDForTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	PublicID string    `json:"public_id"`
}

func (q *Queries) GetCreatorByPublicIDForTenant(ctx context.Context, arg GetCreatorByPublicIDForTenantParams) (Creator, error) {
	row := q.db.QueryRowContext(ctx, getCreatorByPublicIDForTenant, arg.TenantID, arg.PublicID)
	var i Creator
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PublicID,
		&i.Name,
		&i.ProfileText,
		&i.CreatedAt,
	)
	return i, err
}

const getEpisodeByPublicIDForTenant = `-- name: GetEpisodeByPublicIDForTenant :one
SELECT e.id,
    e.public_id,
    e.title,
    e.order_index,
    el.price,
    el.reading_period_hours,
    el.status,
    el.scheduled_at,
    el.published_at
FROM episodes e
    JOIN series s ON s.id = e.series_id
    JOIN episode_listings el ON el.episode_id = e.id
WHERE s.tenant_id = $1
    AND e.public_id = $2
LIMIT 1
`

type GetEpisodeByPublicIDForTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	PublicID string    `json:"public_id"`
}

type GetEpisodeByPublicIDForTenantRow struct {
	ID                 uuid.UUID     `json:"id"`
	PublicID           string        `json:"public_id"`
	Title              string        `json:"title"`
	OrderIndex         int32         `json:"order_index"`
	Price              int32         `json:"price"`
	ReadingPeriodHours sql.NullInt32 `json:"reading_period_hours"`
	Status             string        `json:"status"`
	ScheduledAt        sql.NullTime  `json:"scheduled_at"`
	PublishedAt        sql.NullTime  `json:"published_at"`
}

func (q *Queries) GetEpisodeByPublicIDForTenant(ctx context.Context, arg GetEpisodeByPublicIDForTenantParams) (GetEpisodeByPublicIDForTenantRow, error) {
	row := q.db.QueryRowContext(ctx, getEpisodeByPublicIDForTenant, arg.TenantID, arg.PublicID)
	var i GetEpisodeByPublicIDForTenantRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.OrderIndex,
		&i.Price,
		&i.ReadingPeriodHours,
		&i.Status,
		&i.ScheduledAt,
		&i.PublishedAt,
	)
	return i, err
}

const getLabelByPublicIDForTenant = `-- name: GetLabelByPublicIDForTenant :one
SELECT id, tenant_id, public_id, name, created_at
FROM labels
WHERE tenant_id = $1
    AND public_id = $2
LIMIT 1
`

type GetLabelByPublicIDForTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	PublicID string    `json:"public_id"`
}

func (q *Queries) GetLabelByPublicIDForTenant(ctx context.Context, arg GetLabelByPublicIDForTenantParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, getLabelByPublicIDForTenant, arg.TenantID, arg.PublicID)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PublicID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getMaxEpisodeImageDisplayOrderByEpisodeID = `-- name: GetMaxEpisodeImageDisplayOrderByEpisodeID :one
SELECT COALESCE(MAX(display_order), 0)::int4 AS max_display_order
FROM episode_images
WHERE episode_id = $1
`

func (q *Queries) GetMaxEpisodeImageDisplayOrderByEpisodeID(ctx context.Context, episodeID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getMaxEpisodeImageDisplayOrderByEpisodeID, episodeID)
	var max_display_order int32
	err := row.Scan(&max_display_order)
	return max_display_order, err
}

const getMaxEpisodeOrderIndexBySeriesForTenant = `-- name: GetMaxEpisodeOrderIndexBySeriesForTenant :one
SELECT COALESCE(MAX(e.order_index), 0)::int4 AS max_order_index
FROM episodes e
    JOIN series s ON s.id = e.series_id
WHERE s.tenant_id = $1
    AND s.public_id = $2
`

type GetMaxEpisodeOrderIndexBySeriesForTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	PublicID string    `json:"public_id"`
}

func (q *Queries) GetMaxEpisodeOrderIndexBySeriesForTenant(ctx context.Context, arg GetMaxEpisodeOrderIndexBySeriesForTenantParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, getMaxEpisodeOrderIndexBySeriesForTenant, arg.TenantID, arg.PublicID)
	var max_order_index int32
	err := row.Scan(&max_order_index)
	return max_order_index, err
}

const getPlatformOperatorByPublicID = `-- name: GetPlatformOperatorByPublicID :one
SELECT pu.id,
    pu.public_id,
    pu.email,
    pu.name,
    COALESCE(
        (
            SELECT pur.role
            FROM platform_user_roles pur
            WHERE pur.platform_user_id = pu.id
            ORDER BY CASE
                    WHEN pur.role = 'platform_super_admin' THEN 3
                    WHEN pur.role = 'platform_operator' THEN 2
                    WHEN pur.role = 'platform_auditor' THEN 1
                    ELSE 0
                END DESC,
                pur.role ASC
            LIMIT 1
        ),
        ''::text
    )::text AS role,
    pu.status,
    pu.created_at
FROM platform_users pu
WHERE pu.public_id = $1
LIMIT 1
`

type GetPlatformOperatorByPublicIDRow struct {
	ID        uuid.UUID `json:"id"`
	PublicID  string    `json:"public_id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	Role      string    `json:"role"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) GetPlatformOperatorByPublicID(ctx context.Context, publicID string) (GetPlatformOperatorByPublicIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPlatformOperatorByPublicID, publicID)
	var i GetPlatformOperatorByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPlatformSessionByTokenHash = `-- name: GetPlatformSessionByTokenHash :one
SELECT id, platform_user_id, token_hash, expires_at, revoked_at, created_at
FROM platform_sessions
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetPlatformSessionByTokenHash(ctx context.Context, tokenHash string) (PlatformSession, error) {
	row := q.db.QueryRowContext(ctx, getPlatformSessionByTokenHash, tokenHash)
	var i PlatformSession
	err := row.Scan(
		&i.ID,
		&i.PlatformUserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPlatformUserByEmail = `-- name: GetPlatformUserByEmail :one
SELECT id, public_id, email, password_hash, name, status, created_at
FROM platform_users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetPlatformUserByEmail(ctx context.Context, email string) (PlatformUser, error) {
	row := q.db.QueryRowContext(ctx, getPlatformUserByEmail, email)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPlatformUserByID = `-- name: GetPlatformUserByID :one
SELECT id, public_id, email, password_hash, name, status, created_at
FROM platform_users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPlatformUserByID(ctx context.Context, id uuid.UUID) (PlatformUser, error) {
	row := q.db.QueryRowContext(ctx, getPlatformUserByID, id)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPublishedEpisodeByPublicIDForTenant = `-- name: GetPublishedEpisodeByPublicIDForTenant :one
SELECT e.id,
    e.public_id,
    e.title,
    e.order_index,
    el.price,
    el.reading_period_hours,
    el.status,
    el.scheduled_at,
    el.published_at,
    s.public_id AS series_public_id,
    s.title AS series_title
FROM episodes e
    JOIN series s ON s.id = e.series_id
    JOIN episode_listings el ON el.episode_id = e.id
WHERE s.tenant_id = $1
    AND e.public_id = $2
    AND s.is_published = true
    AND s.published_at IS NOT NULL
    AND s.published_at <= NOW()
    AND el.status = 'published'
    AND el.published_at IS NOT NULL
    AND el.published_at <= NOW()
LIMIT 1
`

type GetPublishedEpisodeByPublicIDForTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	PublicID string    `json:"public_id"`
}

type GetPublishedEpisodeByPublicIDForTenantRow struct {
	ID                 uuid.UUID     `json:"id"`
	PublicID           string        `json:"public_id"`
	Title              string        `json:"title"`
	OrderIndex         int32         `json:"order_index"`
	Price              int32         `json:"price"`
	ReadingPeriodHours sql.NullInt32 `json:"reading_period_hours"`
	Status             string        `json:"status"`
	ScheduledAt        sql.NullTime  `json:"scheduled_at"`
	PublishedAt        sql.NullTime  `json:"published_at"`
	SeriesPublicID     string        `json:"series_public_id"`
	SeriesTitle        string        `json:"series_title"`
}

func (q *Queries) GetPublishedEpisodeByPublicIDForTenant(ctx context.Context, arg GetPublishedEpisodeByPublicIDForTenantParams) (GetPublishedEpisodeByPublicIDForTenantRow, error) {
	row := q.db.QueryRowContext(ctx, getPublishedEpisodeByPublicIDForTenant, arg.TenantID, arg.PublicID)
	var i GetPublishedEpisodeByPublicIDForTenantRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.OrderIndex,
		&i.Price,
		&i.ReadingPeriodHours,
		&i.Status,
		&i.ScheduledAt,
		&i.PublishedAt,
		&i.SeriesPublicID,
		&i.SeriesTitle,
	)
	return i, err
}

const getSeriesByPublicIDForTenant = `-- name: GetSeriesByPublicIDForTenant :one
SELECT s.id,
    s.public_id,
    s.title,
    l.public_id AS label_public_id,
    l.name AS label_name,
    sl.synopsis,
    sl.reading_period_hours,
    s.is_published,
    s.published_at
FROM series s
    LEFT JOIN labels l ON l.id = s.label_id
    LEFT JOIN series_listings sl ON sl.series_id = s.id
WHERE s.tenant_id = $1
    AND s.public_id = $2
LIMIT 1
`

type GetSeriesByPublicIDForTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	PublicID string    `json:"public_id"`
}

type GetSeriesByPublicIDForTenantRow struct {
	ID                 uuid.UUID      `json:"id"`
	PublicID           string         `json:"public_id"`
	Title              string         `json:"title"`
	LabelPublicID      sql.NullString `json:"label_public_id"`
	LabelName          sql.NullString `json:"label_name"`
	Synopsis           sql.NullString `json:"synopsis"`
	ReadingPeriodHours sql.NullInt32  `json:"reading_period_hours"`
	IsPublished        bool           `json:"is_published"`
	PublishedAt        sql.NullTime   `json:"published_at"`
}

func (q *Queries) GetSeriesByPublicIDForTenant(ctx context.Context, arg GetSeriesByPublicIDForTenantParams) (GetSeriesByPublicIDForTenantRow, error) {
	row := q.db.QueryRowContext(ctx, getSeriesByPublicIDForTenant, arg.TenantID, arg.PublicID)
	var i GetSeriesByPublicIDForTenantRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.LabelPublicID,
		&i.LabelName,
		&i.Synopsis,
		&i.ReadingPeriodHours,
		&i.IsPublished,
		&i.PublishedAt,
	)
	return i, err
}

const getSeriesDetail = `-- name: GetSeriesDetail :one
SELECT s.id,
    s.public_id,
    s.title,
    l.name AS label_name,
    sl.synopsis,
    s.is_published,
    s.published_at,
    -- 複数の著者情報をJSON配列として1カラムにまとめる
    COALESCE(
        json_agg(
            json_build_object(
                    'public_id',
                    c.public_id,
                'name',
                c.name,
                    'role',
                    sc.role,
                    'profile_text',
                    c.profile_text
            )
            ORDER BY sc.display_order ASC
        ) FILTER (
            WHERE c.id IS NOT NULL
        ),
        '[]'
    )::jsonb AS creators,
    COALESCE(
        (
            SELECT json_agg(
                    json_build_object(
                        'public_id',
                        e.public_id,
                        'title',
                        e.title,
                        'order_index',
                        e.order_index,
                        'price',
                        el.price,
                        'reading_period_hours',
                        el.reading_period_hours,
                        'status',
                        el.status,
                        'scheduled_at',
                        el.scheduled_at,
                        'published_at',
                        el.published_at
                    )
                    ORDER BY e.order_index ASC
                )
            FROM episodes e
                JOIN episode_listings el ON el.episode_id = e.id
            WHERE e.series_id = s.id
                AND el.status = 'published'
                AND el.published_at IS NOT NULL
                AND el.published_at <= NOW()
        ),
        '[]'
    )::jsonb AS episodes
FROM series s
    LEFT JOIN series_listings sl ON sl.series_id = s.id
    LEFT JOIN labels l ON s.label_id = l.id
    LEFT JOIN series_creators sc ON s.id = sc.series_id
    LEFT JOIN creators c ON sc.creator_id = c.id
WHERE s.public_id = $1
    AND s.tenant_id = $2
GROUP BY s.id,
    l.id,
    sl.series_id,
    sl.synopsis
`

type GetSeriesDetailParams struct {
	PublicID string    `json:"public_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetSeriesDetailRow struct {
	ID          uuid.UUID       `json:"id"`
	PublicID    string          `json:"public_id"`
	Title       string          `json:"title"`
	LabelName   sql.NullString  `json:"label_name"`
	Synopsis    sql.NullString  `json:"synopsis"`
	IsPublished bool            `json:"is_published"`
	PublishedAt sql.NullTime    `json:"published_at"`
	Creators    json.RawMessage `json:"creators"`
	Episodes    json.RawMessage `json:"episodes"`
}

func (q *Queries) GetSeriesDetail(ctx context.Context, arg GetSeriesDetailParams) (GetSeriesDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getSeriesDetail, arg.PublicID, arg.TenantID)
	var i GetSeriesDetailRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Title,
		&i.LabelName,
		&i.Synopsis,
		&i.IsPublished,
		&i.PublishedAt,
		&i.Creators,
		&i.Episodes,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, tenant_id, user_id, token_hash, expires_at, revoked_at, created_at
FROM sessions
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByTokenHashForTenant = `-- name: GetSessionByTokenHashForTenant :one
SELECT id, tenant_id, user_id, token_hash, expires_at, revoked_at, created_at
FROM sessions
WHERE tenant_id = $1
    AND token_hash = $2
LIMIT 1
`

type GetSessionByTokenHashForTenantParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	TokenHash string    `json:"token_hash"`
}

func (q *Queries) GetSessionByTokenHashForTenant(ctx context.Context, arg GetSessionByTokenHashForTenantParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHashForTenant, arg.TenantID, arg.TokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantByDomains = `-- name: GetTenantByDomains :one
SELECT t.id, t.public_id, t.domain, t.name, t.default_reading_period_hours, t.created_at, t.status, t.admin_domain
FROM unnest($1::text[]) WITH ORDINALITY AS candidate(domain, ord)
JOIN tenants t ON t.domain = candidate.domain
ORDER BY candidate.ord
LIMIT 1
`

// 候補ホスト名の順序を保ったまま最初に一致したテナントを返す
func (q *Queries) GetTenantByDomains(ctx context.Context, domains []string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByDomains, pq.Array(domains))
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Domain,
		&i.Name,
		&i.DefaultReadingPeriodHours,
		&i.CreatedAt,
		&i.Status,
		&i.AdminDomain,
	)
	return i, err
}

const getTenantByPublicID = `-- name: GetTenantByPublicID :one
SELECT id, public_id, domain, name, default_reading_period_hours, created_at, status, admin_domain
FROM tenants
WHERE public_id = $1
LIMIT 1
`

func (q *Queries) GetTenantByPublicID(ctx context.Context, publicID string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByPublicID, publicID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Domain,
		&i.Name,
		&i.DefaultReadingPeriodHours,
		&i.CreatedAt,
		&i.Status,
		&i.AdminDomain,
	)
	return i, err
}

const getTenantByUserID = `-- name: GetTenantByUserID :one
SELECT t.id,
    t.public_id,
    t.created_at
FROM tenants t
    JOIN users u ON u.tenant_id = t.id
WHERE u.id = $1
LIMIT 1
`

type GetTenantByUserIDRow struct {
	ID        uuid.UUID `json:"id"`
	PublicID  string    `json:"public_id"`
	CreatedAt time.Time `json:"created_at"`
}

// ユーザーが所属するテナントを取得
func (q *Queries) GetTenantByUserID(ctx context.Context, id uuid.UUID) (GetTenantByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTenantByUserID, id)
	var i GetTenantByUserIDRow
	err := row.Scan(&i.ID, &i.PublicID, &i.CreatedAt)
	return i, err
}

const getTenantConfigByTenantID = `-- name: GetTenantConfigByTenantID :one
SELECT tenant_id, copyright_text, site_description, created_at, updated_at, site_tagline
FROM tenant_config
WHERE tenant_id = $1
LIMIT 1
`

func (q *Queries) GetTenantConfigByTenantID(ctx context.Context, tenantID uuid.UUID) (TenantConfig, error) {
	row := q.db.QueryRowContext(ctx, getTenantConfigByTenantID, tenantID)
	var i TenantConfig
	err := row.Scan(
		&i.TenantID,
		&i.CopyrightText,
		&i.SiteDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SiteTagline,
	)
	return i, err
}

const getTenantThemeByTenantID = `-- name: GetTenantThemeByTenantID :one
SELECT tenant_id, primary_color, secondary_color, accent_color, logo_url, updated_at
FROM tenant_themes
WHERE tenant_id = $1
`

func (q *Queries) GetTenantThemeByTenantID(ctx context.Context, tenantID uuid.UUID) (TenantTheme, error) {
	row := q.db.QueryRowContext(ctx, getTenantThemeByTenantID, tenantID)
	var i TenantTheme
	err := row.Scan(
		&i.TenantID,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.AccentColor,
		&i.LogoUrl,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailForTenant = `-- name: GetUserByEmailForTenant :one
SELECT id, public_id, email, password_hash, name, created_at, status, tenant_id
FROM users
WHERE tenant_id = $1
    AND email = $2
LIMIT 1
`

type GetUserByEmailForTenantParams struct {
	TenantID uuid.NullUUID `json:"tenant_id"`
	Email    string        `json:"email"`
}

func (q *Queries) GetUserByEmailForTenant(ctx context.Context, arg GetUserByEmailForTenantParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailForTenant, arg.TenantID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.Status,
		&i.TenantID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, public_id, email, password_hash, name, created_at, status, tenant_id
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.Status,
		&i.TenantID,
	)
	return i, err
}

const getUserByPublicID = `-- name: GetUserByPublicID :one
SELECT u.id,
    u.public_id,
    u.name,
    u.email,
    u.status,
    u.tenant_id,
    u.created_at
FROM users u
WHERE u.public_id = $1
LIMIT 1
`

type GetUserByPublicIDRow struct {
	ID        uuid.UUID     `json:"id"`
	PublicID  string        `json:"public_id"`
	Name      string        `json:"name"`
	Email     string        `json:"email"`
	Status    string        `json:"status"`
	TenantID  uuid.NullUUID `json:"tenant_id"`
	CreatedAt time.Time     `json:"created_at"`
}

// public_idでテナントユーザーを取得
func (q *Queries) GetUserByPublicID(ctx context.Context, publicID string) (GetUserByPublicIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByPublicID, publicID)
	var i GetUserByPublicIDRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.TenantID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByPublicIDForTenant = `-- name: GetUserByPublicIDForTenant :one
SELECT u.id,
    u.public_id,
    u.name,
    u.email,
    u.status,
    u.tenant_id,
    u.created_at
FROM users u
WHERE u.tenant_id = $1
    AND u.public_id = $2
LIMIT 1
`

type GetUserByPublicIDForTenantParams struct {
	TenantID uuid.NullUUID `json:"tenant_id"`
	PublicID string        `json:"public_id"`
}

type GetUserByPublicIDForTenantRow struct {
	ID        uuid.UUID     `json:"id"`
	PublicID  string        `json:"public_id"`
	Name      string        `json:"name"`
	Email     string        `json:"email"`
	Status    string        `json:"status"`
	TenantID  uuid.NullUUID `json:"tenant_id"`
	CreatedAt time.Time     `json:"created_at"`
}

// テナントスコープで public_id からユーザーを取得
func (q *Queries) GetUserByPublicIDForTenant(ctx context.Context, arg GetUserByPublicIDForTenantParams) (GetUserByPublicIDForTenantRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByPublicIDForTenant, arg.TenantID, arg.PublicID)
	var i GetUserByPublicIDForTenantRow
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.TenantID,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveSeries = `-- name: ListActiveSeries :many
SELECT s.id,
    s.public_id,
    s.title,
    sl.synopsis,
    s.published_at,
    COALESCE(
        json_agg(
            json_build_object(
                'public_id',
                c.public_id,
                'name',
                c.name,
                'role',
                sc.role,
                'profile_text',
                c.profile_text
            )
            ORDER BY sc.display_order ASC
        ) FILTER (
            WHERE c.id IS NOT NULL
        ),
        '[]'
    )::jsonb AS creators
FROM series s
    LEFT JOIN series_listings sl ON sl.series_id = s.id
    LEFT JOIN series_creators sc ON s.id = sc.series_id
    LEFT JOIN creators c ON sc.creator_id = c.id
WHERE s.tenant_id = $1
    AND s.is_published = true
    AND s.published_at IS NOT NULL
    AND s.published_at <= NOW()
GROUP BY s.id,
    sl.series_id,
    sl.synopsis
ORDER BY s.published_at DESC
LIMIT $2 OFFSET $3
`

type ListActiveSeriesParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type ListActiveSeriesRow struct {
	ID          uuid.UUID       `json:"id"`
	PublicID    string          `json:"public_id"`
	Title       string          `json:"title"`
	Synopsis    sql.NullString  `json:"synopsis"`
	PublishedAt sql.NullTime    `json:"published_at"`
	Creators    json.RawMessage `json:"creators"`
}

// 公開中のシリーズ一覧を取得する (テナントIDで絞り込み)
func (q *Queries) ListActiveSeries(ctx context.Context, arg ListActiveSeriesParams) ([]ListActiveSeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSeries, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSeriesRow
	for rows.Next() {
		var i ListActiveSeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Title,
			&i.Synopsis,
			&i.PublishedAt,
			&i.Creators,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreatorsByPublicIDsForTenant = `-- name: ListCreatorsByPublicIDsForTenant :many
SELECT id,
    tenant_id,
    public_id,
    name,
    profile_text,
    created_at
FROM creators
WHERE tenant_id = $1
    AND public_id = ANY($2::varchar[])
`

type ListCreatorsByPublicIDsForTenantParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	PublicIds []string  `json:"public_ids"`
}

func (q *Queries) ListCreatorsByPublicIDsForTenant(ctx context.Context, arg ListCreatorsByPublicIDsForTenantParams) ([]Creator, error) {
	rows, err := q.db.QueryContext(ctx, listCreatorsByPublicIDsForTenant, arg.TenantID, pq.Array(arg.PublicIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Creator
	for rows.Next() {
		var i Creator
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PublicID,
			&i.Name,
			&i.ProfileText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreatorsByTenant = `-- name: ListCreatorsByTenant :many
SELECT id,
    tenant_id,
    public_id,
    name,
    profile_text,
    created_at
FROM creators
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCreatorsByTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListCreatorsByTenant(ctx context.Context, arg ListCreatorsByTenantParams) ([]Creator, error) {
	rows, err := q.db.QueryContext(ctx, listCreatorsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Creator
	for rows.Next() {
		var i Creator
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PublicID,
			&i.Name,
			&i.ProfileText,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndUsers = `-- name: ListEndUsers :many
SELECT u.id,
    u.public_id,
    u.name,
    u.email,
    u.status,
    u.created_at
FROM users u
WHERE NOT EXISTS (
        SELECT 1
        FROM tenant_user_roles tur
        WHERE tur.user_id = u.id
    )
    AND ($1::timestamptz IS NULL OR u.created_at >= $1::timestamptz)
    AND ($2::timestamptz IS NULL OR u.created_at <= $2::timestamptz)
    AND (
        $3::text IS NULL
        OR $3::text = ''
        OR u.status = $3::text
    )
    AND ($4::text[] IS NULL OR u.public_id = ANY($4::text[]))
ORDER BY u.created_at DESC
LIMIT $6 OFFSET $5
`

type ListEndUsersParams struct {
	CreatedAfter  sql.NullTime   `json:"created_after"`
	CreatedBefore sql.NullTime   `json:"created_before"`
	Status        sql.NullString `json:"status"`
	PublicIds     []string       `json:"public_ids"`
	Offset        int32          `json:"offset"`
	Limit         int32          `json:"limit"`
}

type ListEndUsersRow struct {
	ID        uuid.UUID `json:"id"`
	PublicID  string    `json:"public_id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

// エンドユーザー（tenant_user_roles未保持）の一覧取得
func (q *Queries) ListEndUsers(ctx context.Context, arg ListEndUsersParams) ([]ListEndUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listEndUsers,
		arg.CreatedAfter,
		arg.CreatedBefore,
		arg.Status,
		pq.Array(arg.PublicIds),
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEndUsersRow
	for rows.Next() {
		var i ListEndUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Name,
			&i.Email,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodeImagesByEpisodeID = `-- name: ListEpisodeImagesByEpisodeID :many
SELECT id, tenant_id, episode_id, storage_provider, object_key, image_url, content_type, file_size_bytes, display_order, width, height, created_at
FROM episode_images
WHERE episode_id = $1
ORDER BY display_order ASC,
    created_at ASC
`

func (q *Queries) ListEpisodeImagesByEpisodeID(ctx context.Context, episodeID uuid.UUID) ([]EpisodeImage, error) {
	rows, err := q.db.QueryContext(ctx, listEpisodeImagesByEpisodeID, episodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EpisodeImage
	for rows.Next() {
		var i EpisodeImage
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EpisodeID,
			&i.StorageProvider,
			&i.ObjectKey,
			&i.ImageUrl,
			&i.ContentType,
			&i.FileSizeBytes,
			&i.DisplayOrder,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodeImagesByEpisodePublicIDForTenant = `-- name: ListEpisodeImagesByEpisodePublicIDForTenant :many
SELECT ei.id, ei.tenant_id, ei.episode_id, ei.storage_provider, ei.object_key, ei.image_url, ei.content_type, ei.file_size_bytes, ei.display_order, ei.width, ei.height, ei.created_at
FROM episode_images ei
    JOIN episodes e ON e.id = ei.episode_id
    JOIN series s ON s.id = e.series_id
WHERE s.tenant_id = $1
    AND e.public_id = $2
ORDER BY ei.display_order ASC,
    ei.created_at ASC
`

type ListEpisodeImagesByEpisodePublicIDForTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	PublicID string    `json:"public_id"`
}

func (q *Queries) ListEpisodeImagesByEpisodePublicIDForTenant(ctx context.Context, arg ListEpisodeImagesByEpisodePublicIDForTenantParams) ([]EpisodeImage, error) {
	rows, err := q.db.QueryContext(ctx, listEpisodeImagesByEpisodePublicIDForTenant, arg.TenantID, arg.PublicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EpisodeImage
	for rows.Next() {
		var i EpisodeImage
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EpisodeID,
			&i.StorageProvider,
			&i.ObjectKey,
			&i.ImageUrl,
			&i.ContentType,
			&i.FileSizeBytes,
			&i.DisplayOrder,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodesBySeriesForTenant = `-- name: ListEpisodesBySeriesForTenant :many
SELECT e.id,
    e.public_id,
    e.title,
    e.order_index,
    el.price,
    el.reading_period_hours,
    el.status,
    el.scheduled_at,
    el.published_at
FROM episodes e
    JOIN series s ON s.id = e.series_id
    JOIN episode_listings el ON el.episode_id = e.id
WHERE s.tenant_id = $1
    AND s.public_id = $2
ORDER BY e.order_index ASC,
    e.created_at ASC
`

type ListEpisodesBySeriesForTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	PublicID string    `json:"public_id"`
}

type ListEpisodesBySeriesForTenantRow struct {
	ID                 uuid.UUID     `json:"id"`
	PublicID           string        `json:"public_id"`
	Title              string        `json:"title"`
	OrderIndex         int32         `json:"order_index"`
	Price              int32         `json:"price"`
	ReadingPeriodHours sql.NullInt32 `json:"reading_period_hours"`
	Status             string        `json:"status"`
	ScheduledAt        sql.NullTime  `json:"scheduled_at"`
	PublishedAt        sql.NullTime  `json:"published_at"`
}

func (q *Queries) ListEpisodesBySeriesForTenant(ctx context.Context, arg ListEpisodesBySeriesForTenantParams) ([]ListEpisodesBySeriesForTenantRow, error) {
	rows, err := q.db.QueryContext(ctx, listEpisodesBySeriesForTenant, arg.TenantID, arg.PublicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEpisodesBySeriesForTenantRow
	for rows.Next() {
		var i ListEpisodesBySeriesForTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Title,
			&i.OrderIndex,
			&i.Price,
			&i.ReadingPeriodHours,
			&i.Status,
			&i.ScheduledAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpisodesReadyToPublish = `-- name: ListEpisodesReadyToPublish :many
SELECT el.episode_id
FROM episode_listings el
WHERE el.status = 'scheduled'
    AND el.scheduled_at IS NOT NULL
    AND el.scheduled_at <= NOW()
`

func (q *Queries) ListEpisodesReadyToPublish(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listEpisodesReadyToPublish)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var episode_id uuid.UUID
		if err := rows.Scan(&episode_id); err != nil {
			return nil, err
		}
		items = append(items, episode_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabelsByTenant = `-- name: ListLabelsByTenant :many
SELECT id,
    tenant_id,
    public_id,
    name,
    created_at
FROM labels
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLabelsByTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListLabelsByTenant(ctx context.Context, arg ListLabelsByTenantParams) ([]Label, error) {
	rows, err := q.db.QueryContext(ctx, listLabelsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PublicID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformOperators = `-- name: ListPlatformOperators :many
SELECT pu.public_id,
    pu.email,
    pu.name,
    COALESCE(
        (
            SELECT pur.role
            FROM platform_user_roles pur
            WHERE pur.platform_user_id = pu.id
            ORDER BY CASE
                    WHEN pur.role = 'platform_super_admin' THEN 3
                    WHEN pur.role = 'platform_operator' THEN 2
                    WHEN pur.role = 'platform_auditor' THEN 1
                    ELSE 0
                END DESC,
                pur.role ASC
            LIMIT 1
        ),
        ''::text
    )::text AS role,
    pu.status,
    pu.created_at
FROM platform_users pu
ORDER BY pu.created_at DESC
`

type ListPlatformOperatorsRow struct {
	PublicID  string    `json:"public_id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	Role      string    `json:"role"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListPlatformOperators(ctx context.Context) ([]ListPlatformOperatorsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlatformOperators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlatformOperatorsRow
	for rows.Next() {
		var i ListPlatformOperatorsRow
		if err := rows.Scan(
			&i.PublicID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformUserRoles = `-- name: ListPlatformUserRoles :many
SELECT role
FROM platform_user_roles
WHERE platform_user_id = $1
ORDER BY role
`

func (q *Queries) ListPlatformUserRoles(ctx context.Context, platformUserID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPlatformUserRoles, platformUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedEpisodesBySeries = `-- name: ListPublishedEpisodesBySeries :many
SELECT e.id,
    e.series_id,
    e.public_id,
    e.title,
    e.order_index,
    e.created_at,
    el.price,
    el.reading_period_hours,
    el.status,
    el.scheduled_at,
    el.published_at
FROM episodes e
    JOIN series s ON s.id = e.series_id
    JOIN episode_listings el ON e.id = el.episode_id
WHERE s.tenant_id = $1
    AND e.series_id = $2
    AND el.status = 'published'
ORDER BY e.order_index ASC
`

type ListPublishedEpisodesBySeriesParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	SeriesID uuid.UUID `json:"series_id"`
}

type ListPublishedEpisodesBySeriesRow struct {
	ID                 uuid.UUID     `json:"id"`
	SeriesID           uuid.UUID     `json:"series_id"`
	PublicID           string        `json:"public_id"`
	Title              string        `json:"title"`
	OrderIndex         int32         `json:"order_index"`
	CreatedAt          time.Time     `json:"created_at"`
	Price              int32         `json:"price"`
	ReadingPeriodHours sql.NullInt32 `json:"reading_period_hours"`
	Status             string        `json:"status"`
	ScheduledAt        sql.NullTime  `json:"scheduled_at"`
	PublishedAt        sql.NullTime  `json:"published_at"`
}

func (q *Queries) ListPublishedEpisodesBySeries(ctx context.Context, arg ListPublishedEpisodesBySeriesParams) ([]ListPublishedEpisodesBySeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedEpisodesBySeries, arg.TenantID, arg.SeriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedEpisodesBySeriesRow
	for rows.Next() {
		var i ListPublishedEpisodesBySeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.PublicID,
			&i.Title,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.Price,
			&i.ReadingPeriodHours,
			&i.Status,
			&i.ScheduledAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentEpisodesForDashboard = `-- name: ListRecentEpisodesForDashboard :many
SELECT
    e.public_id AS episode_public_id,
    e.title AS episode_title,
    s.public_id AS series_public_id,
    s.title AS series_title,
    el.status,
    el.scheduled_at
FROM episodes e
    JOIN series s ON s.id = e.series_id
    JOIN episode_listings el ON el.episode_id = e.id
WHERE s.tenant_id = $1
    AND el.status IN ('draft', 'scheduled')
ORDER BY
    CASE WHEN el.status = 'scheduled' THEN 0 ELSE 1 END ASC,
    el.scheduled_at ASC NULLS LAST,
    e.created_at DESC
LIMIT $2
`

type ListRecentEpisodesForDashboardParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
}

type ListRecentEpisodesForDashboardRow struct {
	EpisodePublicID string       `json:"episode_public_id"`
	EpisodeTitle    string       `json:"episode_title"`
	SeriesPublicID  string       `json:"series_public_id"`
	SeriesTitle     string       `json:"series_title"`
	Status          string       `json:"status"`
	ScheduledAt     sql.NullTime `json:"scheduled_at"`
}

// ダッシュボードの公開キュー用：直近の下書き・予約済みエピソードを取得する
func (q *Queries) ListRecentEpisodesForDashboard(ctx context.Context, arg ListRecentEpisodesForDashboardParams) ([]ListRecentEpisodesForDashboardRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentEpisodesForDashboard, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentEpisodesForDashboardRow
	for rows.Next() {
		var i ListRecentEpisodesForDashboardRow
		if err := rows.Scan(
			&i.EpisodePublicID,
			&i.EpisodeTitle,
			&i.SeriesPublicID,
			&i.SeriesTitle,
			&i.Status,
			&i.ScheduledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPlatformEvents = `-- name: ListRecentPlatformEvents :many
SELECT event_type,
    action,
    target,
    actor,
    occurred_at
FROM (
        SELECT 'tenant_created'::text AS event_type,
            'Tenant Created'::text AS action,
            t.public_id::text AS target,
            ''::text AS actor,
            t.created_at AS occurred_at
        FROM tenants t
        UNION ALL
        SELECT 'operator_role_granted'::text AS event_type,
            'Operator Role Granted'::text AS action,
            pu.public_id::text AS target,
            ''::text AS actor,
            pur.created_at AS occurred_at
        FROM platform_user_roles pur
            JOIN platform_users pu ON pu.id = pur.platform_user_id
        UNION ALL
        SELECT 'end_user_created'::text AS event_type,
            'End User Created'::text AS action,
            u.public_id::text AS target,
            ''::text AS actor,
            u.created_at AS occurred_at
        FROM users u
        WHERE NOT EXISTS (
                SELECT 1
                FROM tenant_user_roles tur
                WHERE tur.user_id = u.id
            )
    ) events
ORDER BY occurred_at DESC
LIMIT $1
`

type ListRecentPlatformEventsRow struct {
	EventType  string    `json:"event_type"`
	Action     string    `json:"action"`
	Target     string    `json:"target"`
	Actor      string    `json:"actor"`
	OccurredAt time.Time `json:"occurred_at"`
}

func (q *Queries) ListRecentPlatformEvents(ctx context.Context, limit int32) ([]ListRecentPlatformEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentPlatformEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentPlatformEventsRow
	for rows.Next() {
		var i ListRecentPlatformEventsRow
		if err := rows.Scan(
			&i.EventType,
			&i.Action,
			&i.Target,
			&i.Actor,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesByTenant = `-- name: ListSeriesByTenant :many
SELECT s.id,
    s.public_id,
    s.title,
    l.public_id AS label_public_id,
    l.name AS label_name,
    sl.synopsis,
    sl.reading_period_hours,
    s.is_published,
    s.published_at
FROM series s
    LEFT JOIN labels l ON l.id = s.label_id
    LEFT JOIN series_listings sl ON sl.series_id = s.id
WHERE s.tenant_id = $1
ORDER BY s.created_at DESC
LIMIT $2 OFFSET $3
`

type ListSeriesByTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type ListSeriesByTenantRow struct {
	ID                 uuid.UUID      `json:"id"`
	PublicID           string         `json:"public_id"`
	Title              string         `json:"title"`
	LabelPublicID      sql.NullString `json:"label_public_id"`
	LabelName          sql.NullString `json:"label_name"`
	Synopsis           sql.NullString `json:"synopsis"`
	ReadingPeriodHours sql.NullInt32  `json:"reading_period_hours"`
	IsPublished        bool           `json:"is_published"`
	PublishedAt        sql.NullTime   `json:"published_at"`
}

func (q *Queries) ListSeriesByTenant(ctx context.Context, arg ListSeriesByTenantParams) ([]ListSeriesByTenantRow, error) {
	rows, err := q.db.QueryContext(ctx, listSeriesByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeriesByTenantRow
	for rows.Next() {
		var i ListSeriesByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Title,
			&i.LabelPublicID,
			&i.LabelName,
			&i.Synopsis,
			&i.ReadingPeriodHours,
			&i.IsPublished,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesCreatorsBySeriesIDs = `-- name: ListSeriesCreatorsBySeriesIDs :many
SELECT sc.series_id,
    c.public_id,
    c.name,
    sc.role,
    sc.display_order
FROM series_creators sc
    JOIN creators c ON c.id = sc.creator_id
WHERE sc.series_id = ANY($1::uuid[])
ORDER BY sc.series_id ASC,
    sc.display_order ASC,
    c.created_at ASC
`

type ListSeriesCreatorsBySeriesIDsRow struct {
	SeriesID     uuid.UUID `json:"series_id"`
	PublicID     string    `json:"public_id"`
	Name         string    `json:"name"`
	Role         string    `json:"role"`
	DisplayOrder int32     `json:"display_order"`
}

func (q *Queries) ListSeriesCreatorsBySeriesIDs(ctx context.Context, seriesIds []uuid.UUID) ([]ListSeriesCreatorsBySeriesIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSeriesCreatorsBySeriesIDs, pq.Array(seriesIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeriesCreatorsBySeriesIDsRow
	for rows.Next() {
		var i ListSeriesCreatorsBySeriesIDsRow
		if err := rows.Scan(
			&i.SeriesID,
			&i.PublicID,
			&i.Name,
			&i.Role,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantUserRoles = `-- name: ListTenantUserRoles :many
SELECT role
FROM tenant_user_roles
WHERE user_id = $1
ORDER BY role
`

// テナントユーザーのロール一覧を取得する
func (q *Queries) ListTenantUserRoles(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTenantUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantUsers = `-- name: ListTenantUsers :many
SELECT u.id AS user_id,
    u.public_id,
    u.name,
    u.email,
    COALESCE(
        (
            SELECT tur.role
            FROM tenant_user_roles tur
            WHERE tur.user_id = u.id
            ORDER BY CASE
                    WHEN tur.role = 'tenant_admin' THEN 3
                    WHEN tur.role = 'tenant_editor' THEN 2
                    WHEN tur.role = 'tenant_auditor' THEN 1
                    ELSE 0
                END DESC,
                tur.role ASC
            LIMIT 1
        ),
        ''::text
    )::text AS role,
    u.status,
    u.created_at
FROM users u
WHERE u.tenant_id = $1
    AND EXISTS (
        SELECT 1
        FROM tenant_user_roles tur
        WHERE tur.user_id = u.id
    )
ORDER BY u.created_at DESC
LIMIT $3 OFFSET $2
`

type ListTenantUsersParams struct {
	TenantID uuid.NullUUID `json:"tenant_id"`
	Offset   int32         `json:"offset"`
	Limit    int32         `json:"limit"`
}

type ListTenantUsersRow struct {
	UserID    uuid.UUID `json:"user_id"`
	PublicID  string    `json:"public_id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Role      string    `json:"role"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

// テナントに所属する管理・編集ユーザー一覧を取得する
func (q *Queries) ListTenantUsers(ctx context.Context, arg ListTenantUsersParams) ([]ListTenantUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listTenantUsers, arg.TenantID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTenantUsersRow
	for rows.Next() {
		var i ListTenantUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.PublicID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, public_id, domain, name, default_reading_period_hours, created_at, status, admin_domain
FROM tenants
WHERE ($1::text = '' OR name ILIKE '%' || $1::text || '%')
  AND ($2::text = '' OR public_id ILIKE '%' || $2::text || '%')
  AND ($3::text = '' OR status = $3::text)
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListTenantsParams struct {
	FilterName     sql.NullString `json:"filter_name"`
	FilterPublicID sql.NullString `json:"filter_public_id"`
	FilterStatus   sql.NullString `json:"filter_status"`
	Offset         int32          `json:"offset"`
	Limit          int32          `json:"limit"`
}

// プラットフォーム管理者向けテナント一覧取得（フィルタ対応）
func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error) {
	rows, err := q.db.QueryContext(ctx, listTenants,
		arg.FilterName,
		arg.FilterPublicID,
		arg.FilterStatus,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.Domain,
			&i.Name,
			&i.DefaultReadingPeriodHours,
			&i.CreatedAt,
			&i.Status,
			&i.AdminDomain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEpisodePublished = `-- name: MarkEpisodePublished :exec
UPDATE episode_listings
SET status = 'published',
    published_at = NOW()
WHERE episode_id = $1
`

func (q *Queries) MarkEpisodePublished(ctx context.Context, episodeID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markEpisodePublished, episodeID)
	return err
}

const revokePlatformSession = `-- name: RevokePlatformSession :exec
UPDATE platform_sessions
SET revoked_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokePlatformSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokePlatformSession, id)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = NOW()
WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, revokeSession, id)
	return err
}

const terminatePlatformUserSessions = `-- name: TerminatePlatformUserSessions :exec
UPDATE platform_sessions
SET revoked_at = NOW()
WHERE platform_user_id = $1
    AND revoked_at IS NULL
`

// プラットフォームユーザーの全セッションを失効させる
func (q *Queries) TerminatePlatformUserSessions(ctx context.Context, platformUserID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, terminatePlatformUserSessions, platformUserID)
	return err
}

const terminateUserSessions = `-- name: TerminateUserSessions :exec
UPDATE sessions
SET revoked_at = NOW()
WHERE user_id = $1
    AND revoked_at IS NULL
`

// ユーザーの全セッションを失効させる
func (q *Queries) TerminateUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, terminateUserSessions, userID)
	return err
}

const updateCreator = `-- name: UpdateCreator :exec
UPDATE creators
SET name = $2,
    profile_text = $3
WHERE id = $1
`

type UpdateCreatorParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	ProfileText sql.NullString `json:"profile_text"`
}

func (q *Queries) UpdateCreator(ctx context.Context, arg UpdateCreatorParams) error {
	_, err := q.db.ExecContext(ctx, updateCreator, arg.ID, arg.Name, arg.ProfileText)
	return err
}

const updateEpisodeImageDisplayOrderByIDForEpisode = `-- name: UpdateEpisodeImageDisplayOrderByIDForEpisode :exec
UPDATE episode_images
SET display_order = $3
WHERE id = $1
    AND episode_id = $2
`

type UpdateEpisodeImageDisplayOrderByIDForEpisodeParams struct {
	ID           uuid.UUID `json:"id"`
	EpisodeID    uuid.UUID `json:"episode_id"`
	DisplayOrder int32     `json:"display_order"`
}

func (q *Queries) UpdateEpisodeImageDisplayOrderByIDForEpisode(ctx context.Context, arg UpdateEpisodeImageDisplayOrderByIDForEpisodeParams) error {
	_, err := q.db.ExecContext(ctx, updateEpisodeImageDisplayOrderByIDForEpisode, arg.ID, arg.EpisodeID, arg.DisplayOrder)
	return err
}

const updateEpisodeOrderIndexByPublicIDForTenantAndSeries = `-- name: UpdateEpisodeOrderIndexByPublicIDForTenantAndSeries :exec
UPDATE episodes e
SET order_index = $4
FROM series s
WHERE e.series_id = s.id
    AND s.tenant_id = $1
    AND s.public_id = $2
    AND e.public_id = $3
`

type UpdateEpisodeOrderIndexByPublicIDForTenantAndSeriesParams struct {
	TenantID   uuid.UUID `json:"tenant_id"`
	PublicID   string    `json:"public_id"`
	PublicID_2 string    `json:"public_id_2"`
	OrderIndex int32     `json:"order_index"`
}

func (q *Queries) UpdateEpisodeOrderIndexByPublicIDForTenantAndSeries(ctx context.Context, arg UpdateEpisodeOrderIndexByPublicIDForTenantAndSeriesParams) error {
	_, err := q.db.ExecContext(ctx, updateEpisodeOrderIndexByPublicIDForTenantAndSeries,
		arg.TenantID,
		arg.PublicID,
		arg.PublicID_2,
		arg.OrderIndex,
	)
	return err
}

const updateEpisodePublishScheduleByPublicIDForTenant = `-- name: UpdateEpisodePublishScheduleByPublicIDForTenant :exec
UPDATE episode_listings el
SET status = CASE
        WHEN $3 IS NULL THEN 'draft'
        ELSE 'scheduled'
    END,
    scheduled_at = $3,
    published_at = CASE
        WHEN $3 IS NULL THEN NULL
        ELSE el.published_at
    END
FROM episodes e
    JOIN series s ON s.id = e.series_id
WHERE el.episode_id = e.id
    AND s.tenant_id = $1
    AND e.public_id = $2
`

type UpdateEpisodePublishScheduleByPublicIDForTenantParams struct {
	TenantID    uuid.UUID    `json:"tenant_id"`
	PublicID    string       `json:"public_id"`
	ScheduledAt sql.NullTime `json:"scheduled_at"`
}

func (q *Queries) UpdateEpisodePublishScheduleByPublicIDForTenant(ctx context.Context, arg UpdateEpisodePublishScheduleByPublicIDForTenantParams) error {
	_, err := q.db.ExecContext(ctx, updateEpisodePublishScheduleByPublicIDForTenant, arg.TenantID, arg.PublicID, arg.ScheduledAt)
	return err
}

const updateLabel = `-- name: UpdateLabel :exec
UPDATE labels
SET name = $2
WHERE id = $1
`

type UpdateLabelParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateLabel(ctx context.Context, arg UpdateLabelParams) error {
	_, err := q.db.ExecContext(ctx, updateLabel, arg.ID, arg.Name)
	return err
}

const updatePlatformUserStatus = `-- name: UpdatePlatformUserStatus :one
UPDATE platform_users
SET status = $2
WHERE public_id = $1
RETURNING id, public_id, email, password_hash, name, status, created_at
`

type UpdatePlatformUserStatusParams struct {
	PublicID string `json:"public_id"`
	Status   string `json:"status"`
}

// プラットフォームユーザーのステータスを更新
func (q *Queries) UpdatePlatformUserStatus(ctx context.Context, arg UpdatePlatformUserStatusParams) (PlatformUser, error) {
	row := q.db.QueryRowContext(ctx, updatePlatformUserStatus, arg.PublicID, arg.Status)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateSeriesBase = `-- name: UpdateSeriesBase :exec
UPDATE series
SET title = $2,
    label_id = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateSeriesBaseParams struct {
	ID      uuid.UUID     `json:"id"`
	Title   string        `json:"title"`
	LabelID uuid.NullUUID `json:"label_id"`
}

func (q *Queries) UpdateSeriesBase(ctx context.Context, arg UpdateSeriesBaseParams) error {
	_, err := q.db.ExecContext(ctx, updateSeriesBase, arg.ID, arg.Title, arg.LabelID)
	return err
}

const updateSeriesPublication = `-- name: UpdateSeriesPublication :exec
UPDATE series
SET is_published = $2,
    published_at = CASE
        WHEN $2 THEN COALESCE(published_at, NOW())
        ELSE NULL
    END,
    updated_at = NOW()
WHERE id = $1
`

type UpdateSeriesPublicationParams struct {
	ID          uuid.UUID `json:"id"`
	IsPublished bool      `json:"is_published"`
}

func (q *Queries) UpdateSeriesPublication(ctx context.Context, arg UpdateSeriesPublicationParams) error {
	_, err := q.db.ExecContext(ctx, updateSeriesPublication, arg.ID, arg.IsPublished)
	return err
}

const updateTenantConfig = `-- name: UpdateTenantConfig :one
UPDATE tenant_config
SET copyright_text = $2, site_description = $3, site_tagline = $4, updated_at = NOW()
WHERE tenant_id = $1
RETURNING tenant_id, copyright_text, site_description, created_at, updated_at, site_tagline
`

type UpdateTenantConfigParams struct {
	TenantID        uuid.UUID      `json:"tenant_id"`
	CopyrightText   sql.NullString `json:"copyright_text"`
	SiteDescription sql.NullString `json:"site_description"`
	SiteTagline     sql.NullString `json:"site_tagline"`
}

func (q *Queries) UpdateTenantConfig(ctx context.Context, arg UpdateTenantConfigParams) (TenantConfig, error) {
	row := q.db.QueryRowContext(ctx, updateTenantConfig,
		arg.TenantID,
		arg.CopyrightText,
		arg.SiteDescription,
		arg.SiteTagline,
	)
	var i TenantConfig
	err := row.Scan(
		&i.TenantID,
		&i.CopyrightText,
		&i.SiteDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SiteTagline,
	)
	return i, err
}

const updateTenantInfo = `-- name: UpdateTenantInfo :one
UPDATE tenants
SET name = $1, domain = $2, admin_domain = $3
WHERE public_id = $4
RETURNING id, public_id, domain, name, default_reading_period_hours, created_at, status, admin_domain
`

type UpdateTenantInfoParams struct {
	Name        string         `json:"name"`
	Domain      string         `json:"domain"`
	AdminDomain sql.NullString `json:"admin_domain"`
	PublicID    string         `json:"public_id"`
}

// テナントの名前・ドメインを更新する
func (q *Queries) UpdateTenantInfo(ctx context.Context, arg UpdateTenantInfoParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, updateTenantInfo,
		arg.Name,
		arg.Domain,
		arg.AdminDomain,
		arg.PublicID,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Domain,
		&i.Name,
		&i.DefaultReadingPeriodHours,
		&i.CreatedAt,
		&i.Status,
		&i.AdminDomain,
	)
	return i, err
}

const updateTenantStatus = `-- name: UpdateTenantStatus :one
UPDATE tenants
SET status = $2
WHERE public_id = $1
RETURNING id, public_id, domain, name, default_reading_period_hours, created_at, status, admin_domain
`

type UpdateTenantStatusParams struct {
	PublicID string `json:"public_id"`
	Status   string `json:"status"`
}

// テナントの状態 (active / suspended) を更新する
func (q *Queries) UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, updateTenantStatus, arg.PublicID, arg.Status)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Domain,
		&i.Name,
		&i.DefaultReadingPeriodHours,
		&i.CreatedAt,
		&i.Status,
		&i.AdminDomain,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET status = $2
WHERE public_id = $1
RETURNING id, public_id, email, password_hash, name, created_at, status, tenant_id
`

type UpdateUserStatusParams struct {
	PublicID string `json:"public_id"`
	Status   string `json:"status"`
}

// ユーザーのステータスを更新
func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserStatus, arg.PublicID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.Status,
		&i.TenantID,
	)
	return i, err
}

const upsertEpisodeListing = `-- name: UpsertEpisodeListing :one
INSERT INTO episode_listings (
        episode_id,
        price,
        reading_period_hours,
        status,
        scheduled_at,
        published_at
    )
VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT (episode_id) DO
UPDATE
SET price = EXCLUDED.price,
    reading_period_hours = EXCLUDED.reading_period_hours,
    status = EXCLUDED.status,
    scheduled_at = EXCLUDED.scheduled_at,
    published_at = EXCLUDED.published_at
RETURNING episode_id, price, reading_period_hours, status, scheduled_at, published_at
`

type UpsertEpisodeListingParams struct {
	EpisodeID          uuid.UUID     `json:"episode_id"`
	Price              int32         `json:"price"`
	ReadingPeriodHours sql.NullInt32 `json:"reading_period_hours"`
	Status             string        `json:"status"`
	ScheduledAt        sql.NullTime  `json:"scheduled_at"`
	PublishedAt        sql.NullTime  `json:"published_at"`
}

func (q *Queries) UpsertEpisodeListing(ctx context.Context, arg UpsertEpisodeListingParams) (EpisodeListing, error) {
	row := q.db.QueryRowContext(ctx, upsertEpisodeListing,
		arg.EpisodeID,
		arg.Price,
		arg.ReadingPeriodHours,
		arg.Status,
		arg.ScheduledAt,
		arg.PublishedAt,
	)
	var i EpisodeListing
	err := row.Scan(
		&i.EpisodeID,
		&i.Price,
		&i.ReadingPeriodHours,
		&i.Status,
		&i.ScheduledAt,
		&i.PublishedAt,
	)
	return i, err
}

const upsertSeriesListing = `-- name: UpsertSeriesListing :one
INSERT INTO series_listings (
        series_id,
        synopsis,
        reading_period_hours
    )
VALUES (
        $1,
        $2,
        $3
    ) ON CONFLICT (series_id) DO
UPDATE
SET synopsis = EXCLUDED.synopsis,
    reading_period_hours = EXCLUDED.reading_period_hours
RETURNING series_id, synopsis, reading_period_hours, is_published, published_at
`

type UpsertSeriesListingParams struct {
	SeriesID           uuid.UUID      `json:"series_id"`
	Synopsis           sql.NullString `json:"synopsis"`
	ReadingPeriodHours sql.NullInt32  `json:"reading_period_hours"`
}

func (q *Queries) UpsertSeriesListing(ctx context.Context, arg UpsertSeriesListingParams) (SeriesListing, error) {
	row := q.db.QueryRowContext(ctx, upsertSeriesListing, arg.SeriesID, arg.Synopsis, arg.ReadingPeriodHours)
	var i SeriesListing
	err := row.Scan(
		&i.SeriesID,
		&i.Synopsis,
		&i.ReadingPeriodHours,
		&i.IsPublished,
		&i.PublishedAt,
	)
	return i, err
}

const upsertTenantTheme = `-- name: UpsertTenantTheme :one
INSERT INTO tenant_themes (
        tenant_id,
        primary_color,
        secondary_color,
        accent_color,
        logo_url,
        updated_at
    )
VALUES ($1, $2, $3, $4, $5, NOW()) ON CONFLICT (tenant_id) DO
UPDATE
SET primary_color = EXCLUDED.primary_color,
    secondary_color = EXCLUDED.secondary_color,
    accent_color = EXCLUDED.accent_color,
    logo_url = EXCLUDED.logo_url,
    updated_at = NOW()
RETURNING tenant_id, primary_color, secondary_color, accent_color, logo_url, updated_at
`

type UpsertTenantThemeParams struct {
	TenantID       uuid.UUID      `json:"tenant_id"`
	PrimaryColor   string         `json:"primary_color"`
	SecondaryColor string         `json:"secondary_color"`
	AccentColor    string         `json:"accent_color"`
	LogoUrl        sql.NullString `json:"logo_url"`
}

func (q *Queries) UpsertTenantTheme(ctx context.Context, arg UpsertTenantThemeParams) (TenantTheme, error) {
	row := q.db.QueryRowContext(ctx, upsertTenantTheme,
		arg.TenantID,
		arg.PrimaryColor,
		arg.SecondaryColor,
		arg.AccentColor,
		arg.LogoUrl,
	)
	var i TenantTheme
	err := row.Scan(
		&i.TenantID,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.AccentColor,
		&i.LogoUrl,
		&i.UpdatedAt,
	)
	return i, err
}
