// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbmodels

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountActiveTenants(ctx context.Context) (int32, error)
	CountAllTenants(ctx context.Context) (int32, error)
	// テナントの下書きエピソード数を取得する（ダッシュボード用）
	CountDraftEpisodesForTenant(ctx context.Context, tenantID uuid.UUID) (int32, error)
	CountPendingEndUsers(ctx context.Context) (int32, error)
	// プラットフォーム管理ユーザー数を取得する (初期セットアップ判定用)
	CountPlatformUsers(ctx context.Context) (int32, error)
	// テナントの公開中シリーズ数を取得する（ダッシュボード用）
	CountPublishedSeriesForTenant(ctx context.Context, tenantID uuid.UUID) (int32, error)
	// テナントの予約済みエピソード数を取得する（ダッシュボード用）
	CountScheduledEpisodesForTenant(ctx context.Context, tenantID uuid.UUID) (int32, error)
	CountSuspendedTenants(ctx context.Context) (int32, error)
	CreateCreator(ctx context.Context, arg CreateCreatorParams) (Creator, error)
	// エピソードのBaseレコードを作成する
	CreateEpisodeBase(ctx context.Context, arg CreateEpisodeBaseParams) (Episode, error)
	CreateEpisodeImage(ctx context.Context, arg CreateEpisodeImageParams) (EpisodeImage, error)
	CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error)
	CreatePlatformSession(ctx context.Context, arg CreatePlatformSessionParams) (PlatformSession, error)
	CreatePlatformUser(ctx context.Context, arg CreatePlatformUserParams) (PlatformUser, error)
	CreatePlatformUserRole(ctx context.Context, arg CreatePlatformUserRoleParams) (PlatformUserRole, error)
	CreateSeriesBase(ctx context.Context, arg CreateSeriesBaseParams) (Series, error)
	CreateSeriesCreator(ctx context.Context, arg CreateSeriesCreatorParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// プラットフォーム管理者向けテナント作成
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateTenantUserRole(ctx context.Context, arg CreateTenantUserRoleParams) (TenantUserRole, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePlatformUserRolesByPlatformUserID(ctx context.Context, platformUserID uuid.UUID) error
	DeleteSeriesCreatorsBySeriesID(ctx context.Context, seriesID uuid.UUID) error
	// テナントユーザーのロールをすべて削除する
	DeleteTenantUserRolesByUserID(ctx context.Context, userID uuid.UUID) error
	// ユーザーを物理削除（外部キー制約により関連データも削除）
	DeleteUserByID(ctx context.Context, id uuid.UUID) error
	// 候補ホスト名の順序を保ったまま admin_domain、または admin.{domain} フォールバックで一致したテナントを返す
	GetAdminTenantByDomains(ctx context.Context, domains []string) (Tenant, error)
	GetCreatorByPublicIDForTenant(ctx context.Context, arg GetCreatorByPublicIDForTenantParams) (Creator, error)
	GetEpisodeByPublicIDForTenant(ctx context.Context, arg GetEpisodeByPublicIDForTenantParams) (GetEpisodeByPublicIDForTenantRow, error)
	GetLabelByPublicIDForTenant(ctx context.Context, arg GetLabelByPublicIDForTenantParams) (Label, error)
	GetMaxEpisodeImageDisplayOrderByEpisodeID(ctx context.Context, episodeID uuid.UUID) (int32, error)
	GetMaxEpisodeOrderIndexBySeriesForTenant(ctx context.Context, arg GetMaxEpisodeOrderIndexBySeriesForTenantParams) (int32, error)
	GetPlatformOperatorByPublicID(ctx context.Context, publicID string) (GetPlatformOperatorByPublicIDRow, error)
	GetPlatformSessionByTokenHash(ctx context.Context, tokenHash string) (PlatformSession, error)
	GetPlatformUserByEmail(ctx context.Context, email string) (PlatformUser, error)
	GetPlatformUserByID(ctx context.Context, id uuid.UUID) (PlatformUser, error)
	GetPublishedEpisodeByPublicIDForTenant(ctx context.Context, arg GetPublishedEpisodeByPublicIDForTenantParams) (GetPublishedEpisodeByPublicIDForTenantRow, error)
	GetSeriesByPublicIDForTenant(ctx context.Context, arg GetSeriesByPublicIDForTenantParams) (GetSeriesByPublicIDForTenantRow, error)
	GetSeriesDetail(ctx context.Context, arg GetSeriesDetailParams) (GetSeriesDetailRow, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error)
	GetSessionByTokenHashForTenant(ctx context.Context, arg GetSessionByTokenHashForTenantParams) (Session, error)
	// 候補ホスト名の順序を保ったまま最初に一致したテナントを返す
	GetTenantByDomains(ctx context.Context, domains []string) (Tenant, error)
	GetTenantByPublicID(ctx context.Context, publicID string) (Tenant, error)
	// ユーザーが所属するテナントを取得
	GetTenantByUserID(ctx context.Context, id uuid.UUID) (GetTenantByUserIDRow, error)
	GetTenantThemeByTenantID(ctx context.Context, tenantID uuid.UUID) (TenantTheme, error)
	GetUserByEmailForTenant(ctx context.Context, arg GetUserByEmailForTenantParams) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// public_idでテナントユーザーを取得
	GetUserByPublicID(ctx context.Context, publicID string) (GetUserByPublicIDRow, error)
	// テナントスコープで public_id からユーザーを取得
	GetUserByPublicIDForTenant(ctx context.Context, arg GetUserByPublicIDForTenantParams) (GetUserByPublicIDForTenantRow, error)
	// テナント操作監査ログを記録する
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	// 管理操作監査ログを記録する
	InsertPlatformAuditLog(ctx context.Context, arg InsertPlatformAuditLogParams) error
	// 公開中のシリーズ一覧を取得する (テナントIDで絞り込み)
	ListActiveSeries(ctx context.Context, arg ListActiveSeriesParams) ([]ListActiveSeriesRow, error)
	// テナント操作監査ログ一覧取得（フィルタ・カーソル対応）
	ListAuditLogsByTenant(ctx context.Context, arg ListAuditLogsByTenantParams) ([]ListAuditLogsByTenantRow, error)
	ListCreatorsByPublicIDsForTenant(ctx context.Context, arg ListCreatorsByPublicIDsForTenantParams) ([]Creator, error)
	ListCreatorsByTenant(ctx context.Context, arg ListCreatorsByTenantParams) ([]Creator, error)
	// エンドユーザー（tenant_user_roles未保持）の一覧取得
	ListEndUsers(ctx context.Context, arg ListEndUsersParams) ([]ListEndUsersRow, error)
	ListEpisodeImagesByEpisodeID(ctx context.Context, episodeID uuid.UUID) ([]EpisodeImage, error)
	ListEpisodeImagesByEpisodePublicIDForTenant(ctx context.Context, arg ListEpisodeImagesByEpisodePublicIDForTenantParams) ([]EpisodeImage, error)
	ListEpisodesBySeriesForTenant(ctx context.Context, arg ListEpisodesBySeriesForTenantParams) ([]ListEpisodesBySeriesForTenantRow, error)
	ListEpisodesReadyToPublish(ctx context.Context) ([]uuid.UUID, error)
	ListLabelsByTenant(ctx context.Context, arg ListLabelsByTenantParams) ([]Label, error)
	// 管理操作監査ログ一覧取得（フィルタ対応）
	ListPlatformAuditLogs(ctx context.Context, arg ListPlatformAuditLogsParams) ([]ListPlatformAuditLogsRow, error)
	ListPlatformOperators(ctx context.Context) ([]ListPlatformOperatorsRow, error)
	ListPlatformUserRoles(ctx context.Context, platformUserID uuid.UUID) ([]string, error)
	ListPublishedEpisodesBySeries(ctx context.Context, arg ListPublishedEpisodesBySeriesParams) ([]ListPublishedEpisodesBySeriesRow, error)
	// ダッシュボードの公開キュー用：直近の下書き・予約済みエピソードを取得する
	ListRecentEpisodesForDashboard(ctx context.Context, arg ListRecentEpisodesForDashboardParams) ([]ListRecentEpisodesForDashboardRow, error)
	ListRecentPlatformEvents(ctx context.Context, limit int32) ([]ListRecentPlatformEventsRow, error)
	ListSeriesByTenant(ctx context.Context, arg ListSeriesByTenantParams) ([]ListSeriesByTenantRow, error)
	ListSeriesCreatorsBySeriesIDs(ctx context.Context, seriesIds []uuid.UUID) ([]ListSeriesCreatorsBySeriesIDsRow, error)
	// テナントユーザーのロール一覧を取得する
	ListTenantUserRoles(ctx context.Context, userID uuid.UUID) ([]string, error)
	// テナントに所属する管理・編集ユーザー一覧を取得する
	ListTenantUsers(ctx context.Context, arg ListTenantUsersParams) ([]ListTenantUsersRow, error)
	// プラットフォーム管理者向けテナント一覧取得（フィルタ対応）
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error)
	MarkEpisodePublished(ctx context.Context, episodeID uuid.UUID) error
	RevokePlatformSession(ctx context.Context, id uuid.UUID) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	// プラットフォームユーザーの全セッションを失効させる
	TerminatePlatformUserSessions(ctx context.Context, platformUserID uuid.UUID) error
	// ユーザーの全セッションを失効させる
	TerminateUserSessions(ctx context.Context, userID uuid.UUID) error
	UpdateCreator(ctx context.Context, arg UpdateCreatorParams) error
	UpdateEpisodeImageDisplayOrderByIDForEpisode(ctx context.Context, arg UpdateEpisodeImageDisplayOrderByIDForEpisodeParams) error
	UpdateEpisodeOrderIndexByPublicIDForTenantAndSeries(ctx context.Context, arg UpdateEpisodeOrderIndexByPublicIDForTenantAndSeriesParams) error
	UpdateEpisodePublishScheduleByPublicIDForTenant(ctx context.Context, arg UpdateEpisodePublishScheduleByPublicIDForTenantParams) error
	UpdateLabel(ctx context.Context, arg UpdateLabelParams) error
	// プラットフォームユーザーのステータスを更新
	UpdatePlatformUserStatus(ctx context.Context, arg UpdatePlatformUserStatusParams) (PlatformUser, error)
	UpdateSeriesBase(ctx context.Context, arg UpdateSeriesBaseParams) error
	UpdateSeriesPublication(ctx context.Context, arg UpdateSeriesPublicationParams) error
	// テナントの名前・ドメインを更新する
	UpdateTenantInfo(ctx context.Context, arg UpdateTenantInfoParams) (Tenant, error)
	// テナントの状態 (active / suspended) を更新する
	UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) (Tenant, error)
	// ユーザーのステータスを更新
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error)
	UpsertEpisodeListing(ctx context.Context, arg UpsertEpisodeListingParams) (EpisodeListing, error)
	UpsertSeriesListing(ctx context.Context, arg UpsertSeriesListingParams) (SeriesListing, error)
	UpsertTenantTheme(ctx context.Context, arg UpsertTenantThemeParams) (TenantTheme, error)
}

var _ Querier = (*Queries)(nil)
