// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbmodels

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	BumpPlatformUserCredentialsVersion(ctx context.Context, id uuid.UUID) (PlatformUser, error)
	BumpUserCredentialsVersion(ctx context.Context, id uuid.UUID) (User, error)
	CancelTenantAdminInvitation(ctx context.Context, arg CancelTenantAdminInvitationParams) (TenantAdminInvitation, error)
	CountActiveTenants(ctx context.Context) (int32, error)
	CountAllTenants(ctx context.Context) (int32, error)
	// テナントの下書きエピソード数を取得する（ダッシュボード用）
	CountDraftEpisodesForTenant(ctx context.Context, tenantID uuid.UUID) (int32, error)
	CountPendingEndUsers(ctx context.Context) (int32, error)
	// プラットフォーム管理ユーザー数を取得する (初期セットアップ判定用)
	CountPlatformUsers(ctx context.Context) (int32, error)
	// テナントの公開中シリーズ数を取得する（ダッシュボード用）
	CountPublishedSeriesForTenant(ctx context.Context, tenantID uuid.UUID) (int32, error)
	// テナントの予約済みエピソード数を取得する（ダッシュボード用）
	CountScheduledEpisodesForTenant(ctx context.Context, tenantID uuid.UUID) (int32, error)
	CountSuspendedTenants(ctx context.Context) (int32, error)
	CreateAccessTicket(ctx context.Context, arg CreateAccessTicketParams) (AccessTicket, error)
	CreateCreator(ctx context.Context, arg CreateCreatorParams) (Creator, error)
	CreateCreatorImage(ctx context.Context, arg CreateCreatorImageParams) (CreatorImage, error)
	CreateCreatorImageVariant(ctx context.Context, arg CreateCreatorImageVariantParams) (CreatorImageVariant, error)
	// エピソードのBaseレコードを作成する
	CreateEpisodeBase(ctx context.Context, arg CreateEpisodeBaseParams) (Episode, error)
	CreateEpisodeImage(ctx context.Context, arg CreateEpisodeImageParams) (EpisodeImage, error)
	CreateEpisodeImageVariant(ctx context.Context, arg CreateEpisodeImageVariantParams) (EpisodeImageVariant, error)
	CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error)
	CreateLabelImage(ctx context.Context, arg CreateLabelImageParams) (LabelImage, error)
	CreateLabelImageVariant(ctx context.Context, arg CreateLabelImageVariantParams) (LabelImageVariant, error)
	// 通知を作成
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	// ページを新規作成する
	CreatePage(ctx context.Context, arg CreatePageParams) (Page, error)
	// ページバージョンを新規作成する
	CreatePageVersion(ctx context.Context, arg CreatePageVersionParams) (PageVersion, error)
	CreatePlatformUser(ctx context.Context, arg CreatePlatformUserParams) (PlatformUser, error)
	CreatePlatformUserEmailChangeToken(ctx context.Context, arg CreatePlatformUserEmailChangeTokenParams) (PlatformUserEmailChangeToken, error)
	CreatePlatformUserPasswordResetToken(ctx context.Context, arg CreatePlatformUserPasswordResetTokenParams) (PlatformUserPasswordResetToken, error)
	CreatePlatformUserRole(ctx context.Context, arg CreatePlatformUserRoleParams) (PlatformUserRole, error)
	CreateSeriesBase(ctx context.Context, arg CreateSeriesBaseParams) (Series, error)
	CreateSeriesCreator(ctx context.Context, arg CreateSeriesCreatorParams) error
	CreateSeriesImage(ctx context.Context, arg CreateSeriesImageParams) (SeriesImage, error)
	CreateSeriesImageVariant(ctx context.Context, arg CreateSeriesImageVariantParams) (SeriesImageVariant, error)
	// プラットフォーム管理者向けテナント作成
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateTenantAdminInvitation(ctx context.Context, arg CreateTenantAdminInvitationParams) (TenantAdminInvitation, error)
	CreateTenantConfig(ctx context.Context, arg CreateTenantConfigParams) (TenantConfig, error)
	CreateTenantUserRole(ctx context.Context, arg CreateTenantUserRoleParams) (TenantUserRole, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserEmailChangeToken(ctx context.Context, arg CreateUserEmailChangeTokenParams) (UserEmailChangeToken, error)
	CreateUserEmailVerificationToken(ctx context.Context, arg CreateUserEmailVerificationTokenParams) (UserEmailVerificationToken, error)
	CreateUserPasswordResetToken(ctx context.Context, arg CreateUserPasswordResetTokenParams) (UserPasswordResetToken, error)
	DeletePlatformUserEmailChangeTokensByUserID(ctx context.Context, platformUserID uuid.UUID) error
	DeletePlatformUserPasswordResetTokensByUserID(ctx context.Context, platformUserID uuid.UUID) error
	DeletePlatformUserRolesByPlatformUserID(ctx context.Context, platformUserID uuid.UUID) error
	DeleteSeriesCreatorsBySeriesID(ctx context.Context, seriesID uuid.UUID) error
	// テナントユーザーのロールをすべて削除する
	DeleteTenantUserRolesByUserID(ctx context.Context, userID uuid.UUID) error
	// ユーザーを物理削除（外部キー制約により関連データも削除）
	DeleteUserByID(ctx context.Context, id uuid.UUID) error
	DeleteUserEmailChangeTokensByUserID(ctx context.Context, userID uuid.UUID) error
	DeleteUserPasswordResetTokensByUserID(ctx context.Context, userID uuid.UUID) error
	GetAccessTicketByPublicIDForTenant(ctx context.Context, arg GetAccessTicketByPublicIDForTenantParams) (GetAccessTicketByPublicIDForTenantRow, error)
	GetActiveAccessTicketForUserEpisode(ctx context.Context, arg GetActiveAccessTicketForUserEpisodeParams) (AccessTicket, error)
	// 候補ホスト名の順序を保ったまま admin_domain、または admin.{domain} フォールバックで一致したテナントを返す
	GetAdminTenantByDomains(ctx context.Context, domains []string) (Tenant, error)
	GetCreatorByPublicIDForTenant(ctx context.Context, arg GetCreatorByPublicIDForTenantParams) (GetCreatorByPublicIDForTenantRow, error)
	GetCreatorImageByIDForTenant(ctx context.Context, arg GetCreatorImageByIDForTenantParams) (GetCreatorImageByIDForTenantRow, error)
	GetEpisodeByPublicIDForTenant(ctx context.Context, arg GetEpisodeByPublicIDForTenantParams) (GetEpisodeByPublicIDForTenantRow, error)
	GetEpisodeByPublicIDForTenantAndSeries(ctx context.Context, arg GetEpisodeByPublicIDForTenantAndSeriesParams) (GetEpisodeByPublicIDForTenantAndSeriesRow, error)
	GetEpisodeImageAccessByIDForUser(ctx context.Context, arg GetEpisodeImageAccessByIDForUserParams) (GetEpisodeImageAccessByIDForUserRow, error)
	GetEpisodeImagePublicAccessByIDForTenant(ctx context.Context, arg GetEpisodeImagePublicAccessByIDForTenantParams) (GetEpisodeImagePublicAccessByIDForTenantRow, error)
	GetLabelByPublicIDForTenant(ctx context.Context, arg GetLabelByPublicIDForTenantParams) (GetLabelByPublicIDForTenantRow, error)
	GetLabelImageVariantByTypeAndWidthForTenant(ctx context.Context, arg GetLabelImageVariantByTypeAndWidthForTenantParams) (GetLabelImageVariantByTypeAndWidthForTenantRow, error)
	GetMaxEpisodeImageDisplayOrderByEpisodeID(ctx context.Context, episodeID uuid.UUID) (int32, error)
	GetMaxEpisodeOrderIndexBySeriesForTenant(ctx context.Context, arg GetMaxEpisodeOrderIndexBySeriesForTenantParams) (int32, error)
	// ページの最大バージョン番号を取得する（次バージョン番号算出用）
	GetMaxPageVersionNumberByPageID(ctx context.Context, pageID uuid.UUID) (int32, error)
	// Non-revoked ticket for a user+episode pair (may already be expired).
	// Used for idempotent issue under the unique partial index on non-revoked rows.
	GetNonRevokedAccessTicketForUserEpisode(ctx context.Context, arg GetNonRevokedAccessTicketForUserEpisodeParams) (AccessTicket, error)
	// テナントのページをIDで取得する
	GetPageByIDForTenant(ctx context.Context, arg GetPageByIDForTenantParams) (Page, error)
	// ページバージョンをIDで取得する
	GetPageVersionByIDForPage(ctx context.Context, arg GetPageVersionByIDForPageParams) (PageVersion, error)
	GetPlatformOperatorByPublicID(ctx context.Context, publicID string) (GetPlatformOperatorByPublicIDRow, error)
	GetPlatformSMTPConfig(ctx context.Context) (PlatformSmtpConfig, error)
	GetPlatformUserByEmail(ctx context.Context, email string) (PlatformUser, error)
	GetPlatformUserByID(ctx context.Context, id uuid.UUID) (PlatformUser, error)
	GetPlatformUserByPublicID(ctx context.Context, publicID string) (PlatformUser, error)
	GetPlatformUserEmailChangeTokenByHash(ctx context.Context, currentEmailTokenHash string) (GetPlatformUserEmailChangeTokenByHashRow, error)
	GetPlatformUserPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PlatformUserPasswordResetToken, error)
	GetPublishedEpisodeByPublicIDForTenant(ctx context.Context, arg GetPublishedEpisodeByPublicIDForTenantParams) (GetPublishedEpisodeByPublicIDForTenantRow, error)
	// テナントの公開中ページをslugで取得する
	GetPublishedPageBySlugForTenant(ctx context.Context, arg GetPublishedPageBySlugForTenantParams) (GetPublishedPageBySlugForTenantRow, error)
	GetSeriesByPublicIDForTenant(ctx context.Context, arg GetSeriesByPublicIDForTenantParams) (GetSeriesByPublicIDForTenantRow, error)
	GetSeriesDetail(ctx context.Context, arg GetSeriesDetailParams) (GetSeriesDetailRow, error)
	GetSeriesImageVariantByTypeAndWidthForTenant(ctx context.Context, arg GetSeriesImageVariantByTypeAndWidthForTenantParams) (GetSeriesImageVariantByTypeAndWidthForTenantRow, error)
	GetTenantAdminInvitationByHashForTenant(ctx context.Context, arg GetTenantAdminInvitationByHashForTenantParams) (TenantAdminInvitation, error)
	GetTenantAdminInvitationByIDForTenant(ctx context.Context, arg GetTenantAdminInvitationByIDForTenantParams) (TenantAdminInvitation, error)
	GetTenantAdminInvitationByTenantAndEmail(ctx context.Context, arg GetTenantAdminInvitationByTenantAndEmailParams) (TenantAdminInvitation, error)
	// 候補ホスト名の順序を保ったまま最初に一致したテナントを返す
	GetTenantByDomains(ctx context.Context, domains []string) (Tenant, error)
	GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTenantByPublicID(ctx context.Context, publicID string) (Tenant, error)
	// ユーザーが所属するテナントを取得
	GetTenantByUserID(ctx context.Context, id uuid.UUID) (GetTenantByUserIDRow, error)
	GetTenantConfigByTenantID(ctx context.Context, tenantID uuid.UUID) (TenantConfig, error)
	GetTenantSMTPConfigByTenantID(ctx context.Context, tenantID uuid.UUID) (TenantSmtpConfig, error)
	GetTenantThemeByTenantID(ctx context.Context, id uuid.UUID) (GetTenantThemeByTenantIDRow, error)
	GetUserByEmailForTenant(ctx context.Context, arg GetUserByEmailForTenantParams) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// public_idでテナントユーザーを取得
	GetUserByPublicID(ctx context.Context, publicID string) (GetUserByPublicIDRow, error)
	// テナントスコープで public_id からユーザーを取得
	GetUserByPublicIDForTenant(ctx context.Context, arg GetUserByPublicIDForTenantParams) (GetUserByPublicIDForTenantRow, error)
	GetUserEmailChangeTokenByHashForTenant(ctx context.Context, arg GetUserEmailChangeTokenByHashForTenantParams) (GetUserEmailChangeTokenByHashForTenantRow, error)
	GetUserEmailVerificationTokenByHashForTenant(ctx context.Context, arg GetUserEmailVerificationTokenByHashForTenantParams) (UserEmailVerificationToken, error)
	// ユーザーの通知設定を取得
	GetUserNotificationSettings(ctx context.Context, userID uuid.UUID) (UserNotificationSetting, error)
	GetUserPasswordResetTokenByHashForTenant(ctx context.Context, arg GetUserPasswordResetTokenByHashForTenantParams) (UserPasswordResetToken, error)
	// テナント操作監査ログを記録する
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	// 管理操作監査ログを記録する
	InsertPlatformAuditLog(ctx context.Context, arg InsertPlatformAuditLogParams) error
	ListAccessTicketsForTenant(ctx context.Context, arg ListAccessTicketsForTenantParams) ([]ListAccessTicketsForTenantRow, error)
	// 公開中のシリーズの表示内容を取得する (テナントIDで絞り込み)
	// 並び順は付けない。1 段目が決めた id の順に呼び出し側が並べ直す。
	ListActiveSeriesByIDs(ctx context.Context, arg ListActiveSeriesByIDsParams) ([]ListActiveSeriesByIDsRow, error)
	ListActiveSeriesIDsByPublishedAtAsc(ctx context.Context, arg ListActiveSeriesIDsByPublishedAtAscParams) ([]uuid.UUID, error)
	// 公開シリーズ一覧の cursor ページネーションは 2 段構えになっている。
	//
	// 1 段目がここに並ぶ 4 本のキーセット走査で、1 ページぶんの id だけを決める。
	// 並び替えキーは (published_at, id) か (title, id)。id は UUIDv7 なので、
	// published_at や title が同着でも一意に決まる。ORDER BY を並び順ごとに
	// 固定した別のクエリに分けてあるのは、CASE で分岐させると索引順に読めなく
	// なり、LIMIT の手前で全件ソートが入るため。それぞれ
	// idx_series_tenant_published_at / idx_series_tenant_title をそのまま辿る。
	// 前ページ方向は、並び順を反転した側のクエリを呼んで呼び出し側で並べ直す。
	//
	// 2 段目が ListActiveSeriesByIDs で、決まった id の表示内容だけを組み立てる。
	//
	// cursor の共通仕様は proto/README.md を参照。
	ListActiveSeriesIDsByPublishedAtDesc(ctx context.Context, arg ListActiveSeriesIDsByPublishedAtDescParams) ([]uuid.UUID, error)
	ListActiveSeriesIDsByTitleAsc(ctx context.Context, arg ListActiveSeriesIDsByTitleAscParams) ([]uuid.UUID, error)
	ListActiveSeriesIDsByTitleDesc(ctx context.Context, arg ListActiveSeriesIDsByTitleDescParams) ([]uuid.UUID, error)
	ListAuditLogsByTenantAsc(ctx context.Context, arg ListAuditLogsByTenantAscParams) ([]ListAuditLogsByTenantAscRow, error)
	// ListAuditLogs は (created_at, id) の降順で表示する。
	// 次ページは降順、前ページは昇順のクエリで索引を走査し、前ページだけ
	// handler で表示順へ戻す。ORDER BY をパラメータで分岐させると索引順に
	// 読めないため、走査方向ごとにクエリを分ける。
	// cursor の共通仕様は proto/README.md を参照。
	ListAuditLogsByTenantDesc(ctx context.Context, arg ListAuditLogsByTenantDescParams) ([]ListAuditLogsByTenantDescRow, error)
	ListCreatorsByPublicIDsForTenant(ctx context.Context, arg ListCreatorsByPublicIDsForTenantParams) ([]ListCreatorsByPublicIDsForTenantRow, error)
	ListCreatorsByTenant(ctx context.Context, arg ListCreatorsByTenantParams) ([]ListCreatorsByTenantRow, error)
	// エンドユーザー（tenant_user_roles未保持）の一覧取得
	ListEndUsers(ctx context.Context, arg ListEndUsersParams) ([]ListEndUsersRow, error)
	ListEpisodeImagesByEpisodeID(ctx context.Context, episodeID uuid.UUID) ([]ListEpisodeImagesByEpisodeIDRow, error)
	ListEpisodeImagesByEpisodePublicIDForTenant(ctx context.Context, arg ListEpisodeImagesByEpisodePublicIDForTenantParams) ([]ListEpisodeImagesByEpisodePublicIDForTenantRow, error)
	ListEpisodesBySeriesForTenant(ctx context.Context, arg ListEpisodesBySeriesForTenantParams) ([]ListEpisodesBySeriesForTenantRow, error)
	ListEpisodesReadyToPublish(ctx context.Context) ([]uuid.UUID, error)
	ListEpisodesReadyToPublishWithTenantInfo(ctx context.Context) ([]ListEpisodesReadyToPublishWithTenantInfoRow, error)
	ListLabelImageVariantsByImageIDs(ctx context.Context, imageIds []uuid.UUID) ([]ListLabelImageVariantsByImageIDsRow, error)
	// ListPublishedLabels はまだ offset pagination を使用する。
	ListLabelsByTenant(ctx context.Context, arg ListLabelsByTenantParams) ([]ListLabelsByTenantRow, error)
	ListLabelsByTenantAsc(ctx context.Context, arg ListLabelsByTenantAscParams) ([]ListLabelsByTenantAscRow, error)
	// Admin ListLabels は (created_at, id) の降順で表示する。
	// 次ページは降順、前ページは昇順のクエリで索引を走査し、前ページだけ
	// handler で表示順へ戻す。cursor の共通仕様は proto/README.md を参照。
	ListLabelsByTenantDesc(ctx context.Context, arg ListLabelsByTenantDescParams) ([]ListLabelsByTenantDescRow, error)
	// テナント管理画面向け通知一覧を取得
	ListNotificationsForTenant(ctx context.Context, arg ListNotificationsForTenantParams) ([]ListNotificationsForTenantRow, error)
	// 通知一覧を取得（既読状態付き・前ページ方向）
	ListNotificationsForUserAsc(ctx context.Context, arg ListNotificationsForUserAscParams) ([]ListNotificationsForUserAscRow, error)
	// 公開サイトの ListNotifications は (created_at, id) の降順で表示する。
	// 次ページは降順、前ページは昇順のクエリで索引を走査し、前ページだけ
	// handler で表示順へ戻す。ORDER BY をパラメータで分岐させると索引順に
	// 読めないため、走査方向ごとにクエリを分ける。
	// cursor の共通仕様は proto/README.md を参照。
	// 通知一覧を取得（既読状態付き・次ページ方向）
	ListNotificationsForUserDesc(ctx context.Context, arg ListNotificationsForUserDescParams) ([]ListNotificationsForUserDescRow, error)
	// ページのバージョン一覧を新しい順に取得する
	ListPageVersionsByPageID(ctx context.Context, pageID uuid.UUID) ([]PageVersion, error)
	// テナントのページ一覧を取得する（作成日昇順）
	ListPagesForTenant(ctx context.Context, tenantID uuid.UUID) ([]Page, error)
	// 管理操作監査ログ一覧取得（フィルタ対応）
	ListPlatformAuditLogs(ctx context.Context, arg ListPlatformAuditLogsParams) ([]ListPlatformAuditLogsRow, error)
	ListPlatformOperators(ctx context.Context) ([]ListPlatformOperatorsRow, error)
	ListPlatformUserRoles(ctx context.Context, platformUserID uuid.UUID) ([]string, error)
	ListPublishedEpisodesBySeries(ctx context.Context, arg ListPublishedEpisodesBySeriesParams) ([]ListPublishedEpisodesBySeriesRow, error)
	// テナントの公開中かつフッター表示対象のページ一覧を取得する
	ListPublishedPagesForTenant(ctx context.Context, tenantID uuid.UUID) ([]Page, error)
	// ダッシュボードの公開キュー用：直近の下書き・予約済みエピソードを取得する
	ListRecentEpisodesForDashboard(ctx context.Context, arg ListRecentEpisodesForDashboardParams) ([]ListRecentEpisodesForDashboardRow, error)
	ListRecentPlatformEvents(ctx context.Context, limit int32) ([]ListRecentPlatformEventsRow, error)
	ListSeriesByTenant(ctx context.Context, arg ListSeriesByTenantParams) ([]ListSeriesByTenantRow, error)
	ListSeriesCreatorsBySeriesIDs(ctx context.Context, seriesIds []uuid.UUID) ([]ListSeriesCreatorsBySeriesIDsRow, error)
	ListSeriesImageVariantsByImageIDs(ctx context.Context, imageIds []uuid.UUID) ([]ListSeriesImageVariantsByImageIDsRow, error)
	ListTenantAdminInvitations(ctx context.Context, arg ListTenantAdminInvitationsParams) ([]TenantAdminInvitation, error)
	// テナントユーザーのロール一覧を取得する
	ListTenantUserRoles(ctx context.Context, userID uuid.UUID) ([]string, error)
	// テナントに所属する管理・編集ユーザー一覧を取得する
	ListTenantUsers(ctx context.Context, arg ListTenantUsersParams) ([]ListTenantUsersRow, error)
	// プラットフォーム管理者向けテナント一覧取得（フィルタ対応）
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error)
	// 指定ユーザーの未読通知を一括既読化
	MarkAllNotificationsAsRead(ctx context.Context, arg MarkAllNotificationsAsReadParams) (int64, error)
	MarkEpisodePublished(ctx context.Context, episodeID uuid.UUID) error
	// 指定した通知を既読にする（未読時は新規作成、既読済みなら時刻更新）
	MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (NotificationRead, error)
	MarkPlatformUserEmailChangeCompleted(ctx context.Context, id uuid.UUID) error
	MarkPlatformUserEmailChangeCurrentEmailConfirmed(ctx context.Context, id uuid.UUID) error
	MarkPlatformUserEmailChangeNewEmailConfirmed(ctx context.Context, id uuid.UUID) error
	MarkPlatformUserPasswordResetTokenCompleted(ctx context.Context, id uuid.UUID) error
	MarkTenantAdminInvitationAccepted(ctx context.Context, arg MarkTenantAdminInvitationAcceptedParams) (TenantAdminInvitation, error)
	MarkUserEmailChangeCompleted(ctx context.Context, id uuid.UUID) error
	MarkUserEmailChangeCurrentEmailConfirmed(ctx context.Context, id uuid.UUID) error
	MarkUserEmailChangeNewEmailConfirmed(ctx context.Context, id uuid.UUID) error
	MarkUserEmailVerificationTokenUsed(ctx context.Context, id uuid.UUID) error
	MarkUserPasswordResetTokenCompleted(ctx context.Context, id uuid.UUID) error
	// ページバージョンを公開状態にする
	PublishPageVersion(ctx context.Context, arg PublishPageVersionParams) (PageVersion, error)
	RevokeAccessTicketByPublicIDForTenant(ctx context.Context, arg RevokeAccessTicketByPublicIDForTenantParams) (AccessTicket, error)
	// ページの公開バージョンIDを更新する
	SetPagePublishedVersion(ctx context.Context, arg SetPagePublishedVersionParams) (Page, error)
	UpdateCreator(ctx context.Context, arg UpdateCreatorParams) error
	UpdateEpisodeImageDisplayOrderByIDForEpisode(ctx context.Context, arg UpdateEpisodeImageDisplayOrderByIDForEpisodeParams) error
	UpdateEpisodeOrderIndexByPublicIDForTenantAndSeries(ctx context.Context, arg UpdateEpisodeOrderIndexByPublicIDForTenantAndSeriesParams) error
	UpdateEpisodePublishScheduleByPublicIDForTenant(ctx context.Context, arg UpdateEpisodePublishScheduleByPublicIDForTenantParams) error
	UpdateLabel(ctx context.Context, arg UpdateLabelParams) error
	// ページのタイトルとフッター表示設定を更新する
	// display_in_footer は省略時 (NULL) に既存値を保持する
	UpdatePage(ctx context.Context, arg UpdatePageParams) (Page, error)
	UpdatePlatformUserEmailByID(ctx context.Context, arg UpdatePlatformUserEmailByIDParams) (PlatformUser, error)
	UpdatePlatformUserPasswordHashByID(ctx context.Context, arg UpdatePlatformUserPasswordHashByIDParams) (PlatformUser, error)
	// プラットフォームユーザーのステータスを更新
	UpdatePlatformUserStatus(ctx context.Context, arg UpdatePlatformUserStatusParams) (PlatformUser, error)
	UpdateSeriesBase(ctx context.Context, arg UpdateSeriesBaseParams) error
	UpdateSeriesEyeCatchImageID(ctx context.Context, arg UpdateSeriesEyeCatchImageIDParams) error
	UpdateSeriesPublication(ctx context.Context, arg UpdateSeriesPublicationParams) error
	UpdateTenantAdminInvitationForResend(ctx context.Context, arg UpdateTenantAdminInvitationForResendParams) (TenantAdminInvitation, error)
	UpdateTenantConfig(ctx context.Context, arg UpdateTenantConfigParams) (TenantConfig, error)
	// テナントの名前・ドメインを更新する
	UpdateTenantInfo(ctx context.Context, arg UpdateTenantInfoParams) (Tenant, error)
	// テナントの状態 (active / suspended) を更新する
	UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) (Tenant, error)
	// テナントの表示タイムゾーン (IANA 名) を更新する
	UpdateTenantTimezone(ctx context.Context, arg UpdateTenantTimezoneParams) (Tenant, error)
	// ユーザーのメールアドレスをID指定で更新
	UpdateUserEmailByID(ctx context.Context, arg UpdateUserEmailByIDParams) (User, error)
	// ユーザーのメール確認日時を更新
	UpdateUserEmailVerifiedAtByID(ctx context.Context, arg UpdateUserEmailVerifiedAtByIDParams) (User, error)
	// ユーザーの表示名をID指定で更新
	UpdateUserNameByID(ctx context.Context, arg UpdateUserNameByIDParams) (User, error)
	// ユーザーのパスワードハッシュをID指定で更新
	UpdateUserPasswordHashByID(ctx context.Context, arg UpdateUserPasswordHashByIDParams) (User, error)
	// ユーザーのステータスを更新
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error)
	// ユーザーのステータスをID指定で更新
	UpdateUserStatusByID(ctx context.Context, arg UpdateUserStatusByIDParams) (User, error)
	UpsertEpisodeListing(ctx context.Context, arg UpsertEpisodeListingParams) (EpisodeListing, error)
	UpsertPlatformSMTPConfig(ctx context.Context, arg UpsertPlatformSMTPConfigParams) (PlatformSmtpConfig, error)
	UpsertSeriesListing(ctx context.Context, arg UpsertSeriesListingParams) (SeriesListing, error)
	UpsertTenantSMTPConfig(ctx context.Context, arg UpsertTenantSMTPConfigParams) (TenantSmtpConfig, error)
	UpsertTenantTheme(ctx context.Context, arg UpsertTenantThemeParams) (TenantTheme, error)
	// ユーザーの通知設定を作成または更新
	UpsertUserNotificationSettings(ctx context.Context, arg UpsertUserNotificationSettingsParams) (UserNotificationSetting, error)
	// True when the user may view paid body content for the episode via purchase or active access ticket.
	// Free episodes (price = 0) are evaluated by the caller; this query only covers grants.
	UserHasEpisodeContentAccess(ctx context.Context, arg UserHasEpisodeContentAccessParams) (sql.NullBool, error)
}

var _ Querier = (*Queries)(nil)
