// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: smtp.sql

package dbmodels

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getPlatformSMTPConfig = `-- name: GetPlatformSMTPConfig :one
SELECT singleton, host, port, username, password_encrypted, encryption, from_address, reply_to, created_at, updated_at
FROM platform_smtp_config
WHERE singleton = TRUE
LIMIT 1
`

func (q *Queries) GetPlatformSMTPConfig(ctx context.Context) (PlatformSmtpConfig, error) {
	row := q.db.QueryRowContext(ctx, getPlatformSMTPConfig)
	var i PlatformSmtpConfig
	err := row.Scan(
		&i.Singleton,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.PasswordEncrypted,
		&i.Encryption,
		&i.FromAddress,
		&i.ReplyTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantSMTPConfigByTenantID = `-- name: GetTenantSMTPConfigByTenantID :one
SELECT tenant_id, smtp_override_enabled, host, port, username, password_encrypted, encryption, from_name, from_address, reply_to, created_at, updated_at
FROM tenant_smtp_config
WHERE tenant_id = $1
LIMIT 1
`

func (q *Queries) GetTenantSMTPConfigByTenantID(ctx context.Context, tenantID uuid.UUID) (TenantSmtpConfig, error) {
	row := q.db.QueryRowContext(ctx, getTenantSMTPConfigByTenantID, tenantID)
	var i TenantSmtpConfig
	err := row.Scan(
		&i.TenantID,
		&i.SmtpOverrideEnabled,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.PasswordEncrypted,
		&i.Encryption,
		&i.FromName,
		&i.FromAddress,
		&i.ReplyTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPlatformSMTPConfig = `-- name: UpsertPlatformSMTPConfig :one
INSERT INTO platform_smtp_config (
        singleton,
        host,
        port,
        username,
        password_encrypted,
        encryption,
        from_address,
        reply_to,
        updated_at
    )
VALUES (TRUE, $1, $2, $3, $4, $5, $6, $7, NOW()) ON CONFLICT (singleton) DO
UPDATE
SET host = EXCLUDED.host,
    port = EXCLUDED.port,
    username = EXCLUDED.username,
    password_encrypted = EXCLUDED.password_encrypted,
    encryption = EXCLUDED.encryption,
    from_address = EXCLUDED.from_address,
    reply_to = EXCLUDED.reply_to,
    updated_at = NOW()
RETURNING singleton, host, port, username, password_encrypted, encryption, from_address, reply_to, created_at, updated_at
`

type UpsertPlatformSMTPConfigParams struct {
	Host              string         `json:"host"`
	Port              int32          `json:"port"`
	Username          string         `json:"username"`
	PasswordEncrypted string         `json:"password_encrypted"`
	Encryption        string         `json:"encryption"`
	FromAddress       string         `json:"from_address"`
	ReplyTo           sql.NullString `json:"reply_to"`
}

func (q *Queries) UpsertPlatformSMTPConfig(ctx context.Context, arg UpsertPlatformSMTPConfigParams) (PlatformSmtpConfig, error) {
	row := q.db.QueryRowContext(ctx, upsertPlatformSMTPConfig,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.PasswordEncrypted,
		arg.Encryption,
		arg.FromAddress,
		arg.ReplyTo,
	)
	var i PlatformSmtpConfig
	err := row.Scan(
		&i.Singleton,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.PasswordEncrypted,
		&i.Encryption,
		&i.FromAddress,
		&i.ReplyTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTenantSMTPConfig = `-- name: UpsertTenantSMTPConfig :one
INSERT INTO tenant_smtp_config (
        tenant_id,
        smtp_override_enabled,
        host,
        port,
        username,
        password_encrypted,
        encryption,
        from_name,
        from_address,
        reply_to,
        updated_at
    )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW()) ON CONFLICT (tenant_id) DO
UPDATE
SET smtp_override_enabled = EXCLUDED.smtp_override_enabled,
    host = EXCLUDED.host,
    port = EXCLUDED.port,
    username = EXCLUDED.username,
    password_encrypted = EXCLUDED.password_encrypted,
    encryption = EXCLUDED.encryption,
    from_name = EXCLUDED.from_name,
    from_address = EXCLUDED.from_address,
    reply_to = EXCLUDED.reply_to,
    updated_at = NOW()
RETURNING tenant_id, smtp_override_enabled, host, port, username, password_encrypted, encryption, from_name, from_address, reply_to, created_at, updated_at
`

type UpsertTenantSMTPConfigParams struct {
	TenantID            uuid.UUID      `json:"tenant_id"`
	SmtpOverrideEnabled bool           `json:"smtp_override_enabled"`
	Host                sql.NullString `json:"host"`
	Port                sql.NullInt32  `json:"port"`
	Username            sql.NullString `json:"username"`
	PasswordEncrypted   sql.NullString `json:"password_encrypted"`
	Encryption          sql.NullString `json:"encryption"`
	FromName            sql.NullString `json:"from_name"`
	FromAddress         sql.NullString `json:"from_address"`
	ReplyTo             sql.NullString `json:"reply_to"`
}

func (q *Queries) UpsertTenantSMTPConfig(ctx context.Context, arg UpsertTenantSMTPConfigParams) (TenantSmtpConfig, error) {
	row := q.db.QueryRowContext(ctx, upsertTenantSMTPConfig,
		arg.TenantID,
		arg.SmtpOverrideEnabled,
		arg.Host,
		arg.Port,
		arg.Username,
		arg.PasswordEncrypted,
		arg.Encryption,
		arg.FromName,
		arg.FromAddress,
		arg.ReplyTo,
	)
	var i TenantSmtpConfig
	err := row.Scan(
		&i.TenantID,
		&i.SmtpOverrideEnabled,
		&i.Host,
		&i.Port,
		&i.Username,
		&i.PasswordEncrypted,
		&i.Encryption,
		&i.FromName,
		&i.FromAddress,
		&i.ReplyTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
