import { defineConfig } from "tsdown";

export default defineConfig({
  dts: true,
  entry: [
    "src/index.ts",
    "src/bell-icon.tsx",
    "src/building-icon.tsx",
    "src/chart-icon.tsx",
    "src/check-icon.tsx",
    "src/chevron-down-icon.tsx",
    "src/chevron-left-icon.tsx",
    "src/chevron-right-icon.tsx",
    "src/chevron-up-icon.tsx",
    "src/close-icon.tsx",
    "src/coins-icon.tsx",
    "src/collection-icon.tsx",
    "src/comment-icon.tsx",
    "src/copy-icon.tsx",
    "src/dashboard-icon.tsx",
    "src/file-text-icon.tsx",
    "src/fold-horizontal-icon.tsx",
    "src/grip-vertical-icon.tsx",
    "src/heart-icon.tsx",
    "src/image-icon.tsx",
    "src/language-icon.tsx",
    "src/logout-icon.tsx",
    "src/mail-icon.tsx",
    "src/maximize-icon.tsx",
    "src/megaphone-icon.tsx",
    "src/menu-icon.tsx",
    "src/minimize-icon.tsx",
    "src/pen-line-icon.tsx",
    "src/plus-icon.tsx",
    "src/scroll-text-icon.tsx",
    "src/settings-icon.tsx",
    "src/shapes-icon.tsx",
    "src/share-icon.tsx",
    "src/shield-user-icon.tsx",
    "src/tag-icon.tsx",
    "src/ticket-icon.tsx",
    "src/unfold-horizontal-icon.tsx",
    "src/user-icon.tsx",
    "src/users-icon.tsx",
    "src/wifi-off-icon.tsx",
  ],
  format: "esm",
});
