name: ci

env:
  # renovate: datasource=github-releases depName=sqlc-dev/sqlc versioning=semver-coerced
  SQLC_VERSION: 1.30.0
  # renovate: datasource=github-releases depName=bufbuild/buf versioning=semver-coerced
  BUF_VERSION: 1.66.1

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    name: Check and Build
    runs-on: ubuntu-24.04
    steps:
      - name: Setup / Checkout
        uses: actions/checkout@v4

      - name: Setup / Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.14.0

      - name: Setup / Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.26.1

      - name: Setup / pnpm
        uses: pnpm/action-setup@v4

      - name: Setup / Install sqlc
        uses: sqlc-dev/setup-sqlc@v4
        with:
          sqlc-version: ${{ env.SQLC_VERSION }}

      - name: Setup / Install buf
        uses: bufbuild/buf-action@v1
        with:
          setup_only: true
          version: ${{ env.BUF_VERSION }}

      - name: Dependencies / Install
        run: make setup

      - name: Generate / Code
        run: make gen

      - name: Validate / Lint and Format
        run: pnpm check

      - name: Build / Web
        run: pnpm build

      - name: Build / Server
        run: cd server && go build ./...
